<a href="https://colab.research.google.com/github/DVORA-AZARKOVICH/Narrative-Similarity/blob/main/Narrative_Similarity_Ensamble.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Narrative Similarity: Ensemble Strategy
**SemEval-2026 Task 4: Narrative Similarity**

This notebook implements an **Ensemble** approach to maximize accuracy.
We combine the predictions from our different pipelines (e.g., "Distill-then-Embed" and "Direct Prompting").

**The Logic:**
Different models make different types of errors. By combining them, we can "smooth out" the noise.
**Methods:**
1.  **Soft Voting:** Averaging the confidence scores (or probabilities) from multiple models.
2.  **Hard Voting:** Taking the majority vote (0 or 1) from the models.[link text](https://)

## 1. Setup and Load Predictions
We import pandas and load the result files generated by the previous notebooks.
We ensure all dataframes are sorted by `id` so we can merge them correctly.

In [ ]:
!pip install -q -U google-generativeai openai anthropic

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.1/155.1 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 51.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 388.2/388.2 kB 26.6 MB/s eta 0:00:00

In [ ]:
import pandas as pd
import json
import requests
import time
import re
import random
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm
from google.colab import userdata, drive
from openai import OpenAI
from anthropic import Anthropic

In [ ]:
try:
    drive.mount('/content/drive')
except:
    pass

BASE_PATH = '/content/drive/MyDrive/Narrative Similarity Data/'
DEV_FILE = BASE_PATH + 'SemEval2026-Task_4-dev-v1/dev_track_a.jsonl'
TEST_FILE = BASE_PATH + 'SemEval2026-Task_4-test-v1/test_track_a.jsonl'

df_dev = pd.read_json(DEV_FILE, lines=True)
df_test = pd.read_json(TEST_FILE, lines=True)
print(f"Loaded DataFrame shape: {df_dev.shape}")
print(f"Loaded DataFrame shape: {df_test.shape}")

Mounted at /content/drive
Loaded DataFrame shape: (200, 4)
Loaded DataFrame shape: (400, 3)

In [ ]:
try:
    GOOGLE_KEY = userdata.get('GOOGLE_API_KEY')
    OPENAI_KEY = userdata.get('OPENAI_API_KEY')
    ANTHROPIC_KEY = userdata.get('ANTHROPIC_API_KEY')
except userdata.SecretNotFoundError:
    print("Warning: Some keys are missing in Colab Secrets.")
    GOOGLE_KEY = None
    OPENAI_KEY = None
    ANTHROPIC_KEY = None

openai_client = OpenAI(api_key=OPENAI_KEY) if OPENAI_KEY else None
anthropic_client = Anthropic(api_key=ANTHROPIC_KEY) if ANTHROPIC_KEY else None

print("Clients initialized.")

Clients initialized.

## 2. Correlation Analysis
Before ensembling, we check how much the models agree with each other.
* **High Agreement:** Models are confident (or making the same mistakes).
* **Low Agreement:** The ensemble has a good chance of improving results by picking the "surer" model in ambiguous cases.

In [ ]:
MODEL_GEMINI = "gemini-2.5-flash"
MODEL_GPT = "gpt-4o"
MODEL_CLAUDE = "claude-sonnet-4-5-20250929"

SYS_PROMPT_TEXT = """
You are an expert annotator tasked with identifying narrative similarity between stories.
Your goal is to determine which of two candidate stories (Text A or Text B) is narratively closer to an Anchor story.

### DEFINITIONS OF NARRATIVE SIMILARITY
You must evaluate similarity based ONLY on the following three core aspects:
1. **Abstract Theme**: The defining constellation of problems, central ideas, and core motifs.
2. **Course of Action**: The sequence of events, actions, conflicts, turning points.
3. **Outcomes**: The results of the plot at the end of the text.

### INSTRUCTIONS
1. Analyze the Anchor.
2. Compare Text A to Anchor.
3. Compare Text B to Anchor.
4. Decide which text is narratively closer overall.

### INPUT DATA
**Anchor Text:**
{{INSERT_ANCHOR_TEXT_HERE}}

**Text A:**
{{INSERT_TEXT_A_HERE}}

**Text B:**
{{INSERT_TEXT_B_HERE}}

### OUTPUT FORMAT
Provide your response in valid JSON format:
{
  "reasoning": "Brief explanation.",
  "text_a_is_closer": boolean
}
"""

def clean_json_text(text):
    """מנקה סימני Markdown מתוך תשובת JSON"""
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(json)?", "", text)
        text = re.sub(r"```$", "", text)
    return text.strip()

In [ ]:

def get_gemini_prediction(anchor, text_a, text_b, row_index):
    if not GOOGLE_KEY:
        tqdm.write(f"⚠️ [Row {row_index}] Gemini: Missing Key")
        return None

    url = f"https://generativelanguage.googleapis.com/v1beta/models/{MODEL_GEMINI}:generateContent?key={GOOGLE_KEY}"
    headers = {"Content-Type": "application/json"}
    prompt_filled = f"Anchor:\n{anchor}\n\nText A:\n{text_a}\n\nText B:\n{text_b}"

    payload = {
        "system_instruction": {"parts": [{"text": SYS_PROMPT_TEXT}]},
        "contents": [{"parts": [{"text": prompt_filled}]}],
        "generationConfig": {"response_mime_type": "application/json"}
    }

    tqdm.write(f"🚀 [Row {row_index}] Gemini: Sending request...")

    for attempt in range(3):
        try:
            response = requests.post(url, headers=headers, json=payload, timeout=30)
            if response.status_code == 200:
                res_json = response.json()
                content = res_json['candidates'][0]['content']['parts'][0]['text']

                tqdm.write(f"✅ [Row {row_index}] Gemini Received: {content[:100]}...") # מציג את תחילת התשובה

                parsed = json.loads(clean_json_text(content))
                return parsed.get("text_a_is_closer")
            elif response.status_code in [429, 503]:
                tqdm.write(f"⏳ [Row {row_index}] Gemini: Rate limit (Attempt {attempt+1})")
                time.sleep(2 * (attempt + 1))
                continue
            else:
                tqdm.write(f"❌ [Row {row_index}] Gemini Error: {response.status_code} - {response.text}")
                return None
        except Exception as e:
            tqdm.write(f"❌ [Row {row_index}] Gemini Exception: {str(e)}")
            time.sleep(1)
    return None

def get_gpt_prediction(anchor, text_a, text_b, row_index):
    if not openai_client: return None
    prompt_filled = f"Anchor:\n{anchor}\n\nText A:\n{text_a}\n\nText B:\n{text_b}"

    tqdm.write(f"🚀 [Row {row_index}] GPT: Sending request...")

    try:
        completion = openai_client.chat.completions.create(
            model=MODEL_GPT,
            messages=[
                {"role": "system", "content": SYS_PROMPT_TEXT},
                {"role": "user", "content": prompt_filled}
            ],
            response_format={"type": "json_object"},
            temperature=0.0
        )
        content = completion.choices[0].message.content
        tqdm.write(f"✅ [Row {row_index}] GPT Received: {content[:100]}...")

        parsed = json.loads(content)
        return parsed.get("text_a_is_closer")
    except Exception as e:
        tqdm.write(f"❌ [Row {row_index}] GPT Error: {str(e)}")
        return None

def get_claude_prediction(anchor, text_a, text_b, row_index):
    if not anthropic_client: return None
    prompt_filled = f"Anchor:\n{anchor}\n\nText A:\n{text_a}\n\nText B:\n{text_b}"
    sys_clean = SYS_PROMPT_TEXT.replace("{{INSERT_ANCHOR_TEXT_HERE}}", "").replace("{{INSERT_TEXT_A_HERE}}", "").replace("{{INSERT_TEXT_B_HERE}}", "")

    tqdm.write(f"🚀 [Row {row_index}] Claude: Sending request...")

    try:
        message = anthropic_client.messages.create(
            model=MODEL_CLAUDE,
            max_tokens=1024,
            system=sys_clean,
            messages=[{"role": "user", "content": prompt_filled}]
        )
        content = message.content[0].text
        tqdm.write(f"✅ [Row {row_index}] Claude Received: {content[:100]}...")

        start = content.find('{')
        end = content.rfind('}') + 1
        if start != -1 and end != -1:
            return json.loads(content[start:end]).get("text_a_is_closer")
    except Exception as e:
        tqdm.write(f"❌ [Row {row_index}] Claude Error: {str(e)}")
        return None

In [ ]:

def get_ensemble_prediction(row, index):
    anchor = row['anchor_text']
    text_a = row['text_a']
    text_b = row['text_b']

    v_gemini = get_gemini_prediction(anchor, text_a, text_b, index)
    v_gpt = get_gpt_prediction(anchor, text_a, text_b, index)
    v_claude = get_claude_prediction(anchor, text_a, text_b, index)

    votes = [v for v in [v_gemini, v_gpt, v_claude] if v is not None]

    details = {"gemini": v_gemini, "gpt": v_gpt, "claude": v_claude}

    tqdm.write(f"🏁 [Row {index}] Votes: {details}")

    if not votes:
        return index, False, {**details, "FAILED_ALL": True}

    true_count = sum(1 for v in votes if v is True)
    required = len(votes) / 2
    final_pred = true_count > required

    if len(votes) == 2 and true_count == 1:
        if v_claude is not None: final_pred = v_claude
        elif v_gpt is not None: final_pred = v_gpt
        else: final_pred = v_gemini

    return index, final_pred, details

## 3. Final Evaluation
We evaluate the ensemble's performance against the ground truth.
Usually, this yields a higher F1-score than any single model alone.

In [ ]:
print("--- Starting Robust Ensemble Prediction ---")
rows = df_dev.to_dict('records')
results_map = {}
details_map = {}

with ThreadPoolExecutor(max_workers=4) as executor:
    futures = [executor.submit(get_ensemble_prediction, row, i) for i, row in enumerate(rows)]
    for future in tqdm(as_completed(futures), total=len(rows)):
        idx, res, det = future.result()
        results_map[idx] = res
        details_map[idx] = det

df_dev['prediction'] = [results_map[i] for i in range(len(rows))]
df_dev['votes_detail'] = [str(details_map[i]) for i in range(len(rows))]

print("\n--- Done ---")

--- Starting Robust Ensemble Prediction ---
🚀 [Row 0] Gemini: Sending request...
🚀 [Row 1] Gemini: Sending request...
🚀 [Row 2] Gemini: Sending request...
🚀 [Row 3] Gemini: Sending request...

  0%|          | 0/200 [00:00<?, ?it/s]

✅ [Row 63] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an extramarital affair between two damaged individua...
🏁 [Row 63] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 67] Gemini: Sending request...

  0%|          | 0/200 [00:01<?, ?it/s]

⏳ [Row 67] Gemini: Rate limit (Attempt 1)

  0%|          | 0/200 [00:01<?, ?it/s]

✅ [Row 64] Claude Received: ```json
{
  "reasoning": "Both texts share the core Western/outlaw genre with Text A being significa...
🏁 [Row 64] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 68] Gemini: Sending request...

  0%|          | 0/200 [00:03<?, ?it/s]

⏳ [Row 3] Gemini: Rate limit (Attempt 1)

  0%|          | 0/200 [00:03<?, ?it/s]

⏳ [Row 68] Gemini: Rate limit (Attempt 1)
✅ [Row 65] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Max, a successful man who cheats on his wife during ...
🏁 [Row 65] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 69] Gemini: Sending request...

  0%|          | 0/200 [00:03<?, ?it/s]

⏳ [Row 66] Gemini: Rate limit (Attempt 2)

  0%|          | 0/200 [00:07<?, ?it/s]

✅ [Row 0] Gemini Received: {
  "reasoning": "The Anchor text describes an international organization's mission to combat climat...
🚀 [Row 0] GPT: Sending request...

  0%|          | 0/200 [00:09<?, ?it/s]

✅ [Row 2] Gemini Received: {
  "reasoning": "The Anchor text features a soldier on a mission in a war-torn setting, interacting...
🚀 [Row 2] GPT: Sending request...

  0%|          | 0/200 [00:10<?, ?it/s]

✅ [Row 0] GPT Received: {
  "reasoning": "The Anchor text revolves around the theme of climate change and the future of huma...
🚀 [Row 0] Claude: Sending request...

  0%|          | 0/200 [00:11<?, ?it/s]

⏳ [Row 67] Gemini: Rate limit (Attempt 2)

  0%|          | 0/200 [00:12<?, ?it/s]

⏳ [Row 69] Gemini: Rate limit (Attempt 1)

  0%|          | 0/200 [00:12<?, ?it/s]

✅ [Row 2] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a protagonist who is involved in a war se...
🚀 [Row 2] Claude: Sending request...

  0%|          | 0/200 [00:15<?, ?it/s]

✅ [Row 68] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B depict a ce...
🚀 [Row 68] GPT: Sending request...

  0%|          | 0/200 [00:18<?, ?it/s]

✅ [Row 1] Gemini Received: {
  "reasoning": "The Anchor text features a young man who gets into trouble, faces legal consequenc...
🚀 [Row 1] GPT: Sending request...

  0%|          | 0/200 [00:19<?, ?it/s]

✅ [Row 68] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a central character returning to a communi...
🚀 [Row 68] Claude: Sending request...

  0%|          | 1/200 [00:21<1:09:44, 21.03s/it]

✅ [Row 0] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a future-oriented international organization (Minist...
🏁 [Row 0] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 4] Gemini: Sending request...

  1%|          | 2/200 [00:21<29:04,  8.81s/it]

✅ [Row 2] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a soldier sent on a mission (disarming a bomb) who e...
🏁 [Row 2] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 5] Gemini: Sending request...

  1%|          | 2/200 [00:23<29:04,  8.81s/it]

✅ [Row 3] Gemini Received: {
  "reasoning": "The Anchor text centers on a severe marital conflict arising from a child's disabi...
🚀 [Row 3] GPT: Sending request...

  1%|          | 2/200 [00:23<29:04,  8.81s/it]

✅ [Row 1] GPT Received: {
  "reasoning": "The Anchor story revolves around a young man, Glenn Tyler, who is given a second c...
🚀 [Row 1] Claude: Sending request...

  1%|          | 2/200 [00:24<29:04,  8.81s/it]

✅ [Row 67] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature pro...
🚀 [Row 67] GPT: Sending request...

  1%|          | 2/200 [00:27<29:04,  8.81s/it]

✅ [Row 68] Claude Received: ```json
{
  "reasoning": "The Anchor depicts an aging, overwhelmed figure (Tolstoy) caught between h...
🏁 [Row 68] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 70] Gemini: Sending request...

  1%|          | 2/200 [00:27<29:04,  8.81s/it]

✅ [Row 3] GPT Received: {
  "reasoning": "The Anchor story revolves around a conflict between a mother and her husband regar...
🚀 [Row 3] Claude: Sending request...

  1%|          | 2/200 [00:28<29:04,  8.81s/it]

✅ [Row 66] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a n...
🚀 [Row 66] GPT: Sending request...

  1%|          | 2/200 [00:28<29:04,  8.81s/it]

✅ [Row 4] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature the...
🚀 [Row 4] GPT: Sending request...

  1%|          | 2/200 [00:29<29:04,  8.81s/it]

✅ [Row 69] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A focus on a ...
🚀 [Row 69] GPT: Sending request...

  1%|          | 2/200 [00:31<29:04,  8.81s/it]

✅ [Row 67] GPT Received: {
  "reasoning": "The Anchor story focuses on Max, a former burglar and talented tap dancer, who mus...
🚀 [Row 67] Claude: Sending request...

  1%|          | 2/200 [00:32<29:04,  8.81s/it]

✅ [Row 69] GPT Received: {
  "reasoning": "The Anchor text focuses on the Italian resistance during WWII from the perspective...
🚀 [Row 69] Claude: Sending request...

  1%|          | 2/200 [00:33<29:04,  8.81s/it]

✅ [Row 66] GPT Received: {
  "reasoning": "The Anchor text focuses on Mussolini's final days, his attempt to escape, and his ...
🚀 [Row 66] Claude: Sending request...

  2%|▏         | 3/200 [00:33<34:09, 10.41s/it]

✅ [Row 5] Gemini Received: {
  "reasoning": "The Anchor text features humans in a decisive conflict with alien humanoids, where...
🚀 [Row 5] GPT: Sending request...
✅ [Row 1] Claude Received: ```json
{
  "reasoning": "The Anchor follows a young man (Glenn) falsely suspected of misdeeds while...
🏁 [Row 1] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 6] Gemini: Sending request...

  2%|▏         | 3/200 [00:33<34:09, 10.41s/it]

✅ [Row 4] GPT Received: {
  "reasoning": "The Anchor story involves themes of mental health, family dynamics, and a mysterio...
🚀 [Row 4] Claude: Sending request...

  2%|▏         | 3/200 [00:36<34:09, 10.41s/it]

✅ [Row 70] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B revolve aro...
🚀 [Row 70] GPT: Sending request...

  2%|▏         | 4/200 [00:37<25:08,  7.70s/it]

✅ [Row 3] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a married woman (Barbara) dealing with her husband's...
🏁 [Row 3] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 7] Gemini: Sending request...

  2%|▏         | 4/200 [00:40<25:08,  7.70s/it]

✅ [Row 5] GPT Received: {
  "reasoning": "The Anchor text involves a battle-to-the-death scenario between humans and aliens ...
🚀 [Row 5] Claude: Sending request...

  2%|▏         | 4/200 [00:40<25:08,  7.70s/it]

✅ [Row 67] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on Max, an ex-con dancer who must choose between ...
🏁 [Row 67] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 71] Gemini: Sending request...

  2%|▏         | 4/200 [00:41<25:08,  7.70s/it]

✅ [Row 70] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle, with themes of past relationship...
🚀 [Row 70] Claude: Sending request...
✅ [Row 69] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on women's experiences in the Italian resistance (1943-...
🏁 [Row 69] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 72] Gemini: Sending request...

  2%|▎         | 5/200 [00:42<21:54,  6.74s/it]

✅ [Row 4] Claude Received: ```json
{
  "reasoning": "Text B is narratively closer to the Anchor. Both stories share the core co...
🏁 [Row 4] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 8] Gemini: Sending request...

  2%|▎         | 5/200 [00:42<21:54,  6.74s/it]

✅ [Row 6] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B focus on pr...
🚀 [Row 6] GPT: Sending request...

  2%|▎         | 5/200 [00:43<21:54,  6.74s/it]

✅ [Row 66] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on the final days of Benito Mussolini, a fascist dictat...
🏁 [Row 66] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 73] Gemini: Sending request...

  2%|▎         | 5/200 [00:45<21:54,  6.74s/it]

✅ [Row 6] GPT Received: {
  "reasoning": "The Anchor story revolves around the aspirations of May and August, who are both t...
🚀 [Row 6] Claude: Sending request...

  2%|▎         | 5/200 [00:46<21:54,  6.74s/it]

✅ [Row 7] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 7] GPT: Sending request...

  2%|▎         | 5/200 [00:49<21:54,  6.74s/it]

✅ [Row 70] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories center on a marri...
🏁 [Row 70] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 74] Gemini: Sending request...

  2%|▎         | 5/200 [00:49<21:54,  6.74s/it]

✅ [Row 8] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a n...
🚀 [Row 8] GPT: Sending request...

  3%|▎         | 6/200 [00:50<23:14,  7.19s/it]

✅ [Row 5] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on humans and aliens in a transcendental contest/...
🏁 [Row 5] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 9] Gemini: Sending request...

  3%|▎         | 6/200 [00:50<23:14,  7.19s/it]

⏳ [Row 74] Gemini: Rate limit (Attempt 1)

  3%|▎         | 6/200 [00:51<23:14,  7.19s/it]

✅ [Row 72] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B are set in ...
🚀 [Row 72] GPT: Sending request...

  3%|▎         | 6/200 [00:51<23:14,  7.19s/it]

✅ [Row 7] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve themes of societal reconstruction and the ...
🚀 [Row 7] Claude: Sending request...
✅ [Row 73] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 73] GPT: Sending request...

  3%|▎         | 6/200 [00:53<23:14,  7.19s/it]

⏳ [Row 74] Gemini: Rate limit (Attempt 2)

  4%|▎         | 7/200 [00:54<19:46,  6.15s/it]

✅ [Row 6] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on multiple dreamers in Echo Park: May pursuing acting ...
🏁 [Row 6] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 10] Gemini: Sending request...

  4%|▎         | 7/200 [00:54<19:46,  6.15s/it]

✅ [Row 8] GPT Received: {
  "reasoning": "The Anchor story involves a modern-day city setting with a supernatural threat fro...
🚀 [Row 8] Claude: Sending request...

  4%|▎         | 7/200 [00:55<19:46,  6.15s/it]

✅ [Row 71] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both feature a protagonist in a position of respon...
🚀 [Row 71] GPT: Sending request...

  4%|▎         | 7/200 [00:56<19:46,  6.15s/it]

⏳ [Row 10] Gemini: Rate limit (Attempt 1)
✅ [Row 73] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of crime, betrayal, and familial conflict,...

  4%|▎         | 7/200 [00:56<19:46,  6.15s/it]

🚀 [Row 73] Claude: Sending request...

  4%|▎         | 7/200 [00:56<19:46,  6.15s/it]

✅ [Row 72] GPT Received: {
  "reasoning": "The Anchor story revolves around a teenage girl, Andrea, who uncovers a sinister p...
🚀 [Row 72] Claude: Sending request...

  4%|▎         | 7/200 [00:58<19:46,  6.15s/it]

⏳ [Row 74] Gemini: Rate limit (Attempt 3)

  4%|▎         | 7/200 [00:59<19:46,  6.15s/it]

⏳ [Row 10] Gemini: Rate limit (Attempt 2)

  4%|▎         | 7/200 [00:59<19:46,  6.15s/it]

✅ [Row 71] GPT Received: {
  "reasoning": "The Anchor story revolves around a British diplomat in an African nation dealing w...
🚀 [Row 71] Claude: Sending request...

  4%|▍         | 8/200 [01:00<19:55,  6.22s/it]

✅ [Row 7] Claude Received: ```json
{
  "reasoning": "The Anchor follows Lewis Orne, a government agent who travels to various p...
🏁 [Row 7] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 11] Gemini: Sending request...

  4%|▍         | 9/200 [01:02<15:30,  4.87s/it]

✅ [Row 8] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around vampire hunters (Van Helsing and King) battling...
🏁 [Row 8] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 12] Gemini: Sending request...

  4%|▍         | 9/200 [01:02<15:30,  4.87s/it]

⏳ [Row 11] Gemini: Rate limit (Attempt 1)

  4%|▍         | 9/200 [01:04<15:30,  4.87s/it]

🚀 [Row 74] GPT: Sending request...
✅ [Row 73] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two brothers caught in organized crime, with one wor...
🏁 [Row 73] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 75] Gemini: Sending request...

  4%|▍         | 9/200 [01:06<15:30,  4.87s/it]

✅ [Row 72] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a teenage girl entering a formerly all-male bo...
🏁 [Row 72] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 76] Gemini: Sending request...

  4%|▍         | 9/200 [01:08<15:30,  4.87s/it]

⏳ [Row 9] Gemini: Rate limit (Attempt 1)

  4%|▍         | 9/200 [01:08<15:30,  4.87s/it]

✅ [Row 71] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a British diplomat in a newly independent African na...
🏁 [Row 71] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 77] Gemini: Sending request...

  4%|▍         | 9/200 [01:08<15:30,  4.87s/it]

✅ [Row 74] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of memory, identity, and vengeance, with a...
🚀 [Row 74] Claude: Sending request...

  4%|▍         | 9/200 [01:11<15:30,  4.87s/it]

⏳ [Row 10] Gemini: Rate limit (Attempt 3)

  4%|▍         | 9/200 [01:11<15:30,  4.87s/it]

⏳ [Row 9] Gemini: Rate limit (Attempt 2)

  4%|▍         | 9/200 [01:12<15:30,  4.87s/it]

⏳ [Row 75] Gemini: Rate limit (Attempt 1)

  4%|▍         | 9/200 [01:12<15:30,  4.87s/it]

⏳ [Row 11] Gemini: Rate limit (Attempt 2)

  4%|▍         | 9/200 [01:15<15:30,  4.87s/it]

✅ [Row 12] Gemini Received: {
  "reasoning": "The Anchor text centers on a protagonist seeking revenge for a murder, with a poli...
🚀 [Row 12] GPT: Sending request...

  4%|▍         | 9/200 [01:16<15:30,  4.87s/it]

⏳ [Row 9] Gemini: Rate limit (Attempt 3)
⏳ [Row 76] Gemini: Rate limit (Attempt 1)

  4%|▍         | 9/200 [01:16<15:30,  4.87s/it]

✅ [Row 77] Gemini Received: {
  "reasoning": "The Anchor text focuses on the re-opening of past political and personal wounds, t...
🚀 [Row 77] GPT: Sending request...

  4%|▍         | 9/200 [01:17<15:30,  4.87s/it]

🚀 [Row 10] GPT: Sending request...

  4%|▍         | 9/200 [01:18<15:30,  4.87s/it]

⏳ [Row 11] Gemini: Rate limit (Attempt 3)
⏳ [Row 76] Gemini: Rate limit (Attempt 2)

  4%|▍         | 9/200 [01:18<15:30,  4.87s/it]

✅ [Row 74] Claude Received: ```json
{
  "reasoning": "Both texts involve revenge narratives, but Text B is narratively closer to...
🏁 [Row 74] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 78] Gemini: Sending request...

  4%|▍         | 9/200 [01:19<15:30,  4.87s/it]

⏳ [Row 78] Gemini: Rate limit (Attempt 1)
✅ [Row 12] GPT Received: {
  "reasoning": "The Anchor story involves a revenge plot where the protagonist, Sugar, seeks venge...
🚀 [Row 12] Claude: Sending request...
✅ [Row 10] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve terrorist or anarchist groups planning and...
🚀 [Row 10] Claude: Sending request...

  4%|▍         | 9/200 [01:21<15:30,  4.87s/it]

✅ [Row 77] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of political activism, unresolved past conf...
🚀 [Row 77] Claude: Sending request...

  4%|▍         | 9/200 [01:22<15:30,  4.87s/it]

🚀 [Row 9] GPT: Sending request...

  4%|▍         | 9/200 [01:24<15:30,  4.87s/it]

🚀 [Row 11] GPT: Sending request...

  4%|▍         | 9/200 [01:26<15:30,  4.87s/it]

✅ [Row 9] GPT Received: {
  "reasoning": "The Anchor story revolves around two thieves who are given a chance to reform by w...
🚀 [Row 9] Claude: Sending request...

  5%|▌         | 10/200 [01:28<35:33, 11.23s/it]

✅ [Row 12] Claude Received: ```json
{
  "reasoning": "The Anchor is a revenge narrative driven by supernatural intervention: Sug...
🏁 [Row 12] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 13] Gemini: Sending request...

  5%|▌         | 10/200 [01:28<35:33, 11.23s/it]

✅ [Row 11] GPT Received: {
  "reasoning": "The Anchor story revolves around a family power struggle over inheritance, with a ...
🚀 [Row 11] Claude: Sending request...

  5%|▌         | 10/200 [01:29<35:33, 11.23s/it]

✅ [Row 78] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B describe a ...
🚀 [Row 78] GPT: Sending request...

  6%|▌         | 11/200 [01:30<26:54,  8.54s/it]

✅ [Row 10] Claude Received: ```json
{
  "reasoning": "Both texts involve criminal/violent activities and tragic outcomes, but Te...
🏁 [Row 10] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 14] Gemini: Sending request...

  6%|▌         | 11/200 [01:30<26:54,  8.54s/it]

✅ [Row 76] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B prominently...
🚀 [Row 76] GPT: Sending request...

  6%|▌         | 11/200 [01:31<26:54,  8.54s/it]

⏳ [Row 14] Gemini: Rate limit (Attempt 1)

  6%|▌         | 11/200 [01:32<26:54,  8.54s/it]

✅ [Row 77] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on former student radicals confronting their political ...
🏁 [Row 77] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 79] Gemini: Sending request...

  6%|▌         | 12/200 [01:35<23:22,  7.46s/it]

✅ [Row 9] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two thieves forced to work with troubled youth at a ...
🏁 [Row 9] Votes: {'gemini': None, 'gpt': True, 'claude': False}
🚀 [Row 15] Gemini: Sending request...

  6%|▌         | 12/200 [01:36<23:22,  7.46s/it]

✅ [Row 76] GPT Received: {
  "reasoning": "The Anchor text revolves around a group of friends attending a funeral and dealing...
🚀 [Row 76] Claude: Sending request...

  6%|▌         | 12/200 [01:36<23:22,  7.46s/it]

✅ [Row 78] GPT Received: {
  "reasoning": "The Anchor story revolves around a group known for extreme Truth or Dare videos, w...
🚀 [Row 78] Claude: Sending request...
✅ [Row 13] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A are set in ...
🚀 [Row 13] GPT: Sending request...

  6%|▋         | 13/200 [01:38<19:29,  6.26s/it]

✅ [Row 11] Claude Received: ```json
{
  "reasoning": "The Anchor involves an inheritance struggle over family property, where ne...
🏁 [Row 11] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 16] Gemini: Sending request...

  6%|▋         | 13/200 [01:41<19:29,  6.26s/it]

✅ [Row 13] GPT Received: {
  "reasoning": "The Anchor story and Text A both revolve around characters struggling to find succ...
🚀 [Row 13] Claude: Sending request...

  6%|▋         | 13/200 [01:43<19:29,  6.26s/it]

✅ [Row 14] Gemini Received: {
  "reasoning": "The Anchor text deals with high-stakes political dealings, international relations...
🚀 [Row 14] GPT: Sending request...

  6%|▋         | 13/200 [01:44<19:29,  6.26s/it]

✅ [Row 76] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a group of friends traveling to and attending a fune...
🏁 [Row 76] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 80] Gemini: Sending request...
❌ [Row 75] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

  6%|▋         | 13/200 [01:45<19:29,  6.26s/it]

⏳ [Row 16] Gemini: Rate limit (Attempt 1)

  6%|▋         | 13/200 [01:45<19:29,  6.26s/it]

✅ [Row 78] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a social media group being stalked and terrorized by...
🏁 [Row 78] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 81] Gemini: Sending request...

  6%|▋         | 13/200 [01:46<19:29,  6.26s/it]

✅ [Row 14] GPT Received: {
  "reasoning": "The Anchor text revolves around political intrigue, international relations, and a...
🚀 [Row 14] Claude: Sending request...

  6%|▋         | 13/200 [01:47<19:29,  6.26s/it]

⏳ [Row 80] Gemini: Rate limit (Attempt 1)

  6%|▋         | 13/200 [01:48<19:29,  6.26s/it]

⏳ [Row 16] Gemini: Rate limit (Attempt 2)

  7%|▋         | 14/200 [01:49<23:02,  7.43s/it]

✅ [Row 13] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a struggling young actress navigating Hollywood audi...
🏁 [Row 13] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 17] Gemini: Sending request...

  7%|▋         | 14/200 [01:49<23:02,  7.43s/it]

⏳ [Row 81] Gemini: Rate limit (Attempt 1)

  7%|▋         | 14/200 [01:49<23:02,  7.43s/it]

⏳ [Row 79] Gemini: Rate limit (Attempt 1)

  7%|▋         | 14/200 [01:50<23:02,  7.43s/it]

⏳ [Row 17] Gemini: Rate limit (Attempt 1)

  7%|▋         | 14/200 [01:51<23:02,  7.43s/it]

⏳ [Row 15] Gemini: Rate limit (Attempt 1)

  7%|▋         | 14/200 [01:51<23:02,  7.43s/it]

⏳ [Row 81] Gemini: Rate limit (Attempt 2)

  7%|▋         | 14/200 [01:52<23:02,  7.43s/it]

⏳ [Row 79] Gemini: Rate limit (Attempt 2)

  7%|▋         | 14/200 [01:54<23:02,  7.43s/it]

⏳ [Row 80] Gemini: Rate limit (Attempt 2)

  7%|▋         | 14/200 [01:54<23:02,  7.43s/it]

⏳ [Row 75] Gemini: Rate limit (Attempt 3)

  7%|▋         | 14/200 [01:54<23:02,  7.43s/it]

⏳ [Row 15] Gemini: Rate limit (Attempt 2)

  7%|▋         | 14/200 [01:55<23:02,  7.43s/it]

⏳ [Row 17] Gemini: Rate limit (Attempt 2)

  7%|▋         | 14/200 [01:55<23:02,  7.43s/it]

⏳ [Row 16] Gemini: Rate limit (Attempt 3)

  8%|▊         | 15/200 [01:56<23:15,  7.54s/it]

✅ [Row 14] Claude Received: ```json
{
  "reasoning": "The Anchor involves a sitting U.S. president dealing with an absurd diplom...
🏁 [Row 14] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 18] Gemini: Sending request...

  8%|▊         | 15/200 [01:57<23:15,  7.54s/it]

⏳ [Row 18] Gemini: Rate limit (Attempt 1)

  8%|▊         | 15/200 [02:00<23:15,  7.54s/it]

🚀 [Row 75] GPT: Sending request...

  8%|▊         | 15/200 [02:01<23:15,  7.54s/it]

⏳ [Row 15] Gemini: Rate limit (Attempt 3)
⏳ [Row 80] Gemini: Rate limit (Attempt 3)

  8%|▊         | 15/200 [02:01<23:15,  7.54s/it]

🚀 [Row 16] GPT: Sending request...

  8%|▊         | 15/200 [02:02<23:15,  7.54s/it]

⏳ [Row 79] Gemini: Rate limit (Attempt 3)

  8%|▊         | 15/200 [02:04<23:15,  7.54s/it]

✅ [Row 81] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both stories feature an aging protagonist in a cre...
🚀 [Row 81] GPT: Sending request...

  8%|▊         | 15/200 [02:06<23:15,  7.54s/it]

✅ [Row 16] GPT Received: {
  "reasoning": "The Anchor story involves a parody of a spy narrative with a focus on impersonatio...
🚀 [Row 16] Claude: Sending request...

  8%|▊         | 15/200 [02:07<23:15,  7.54s/it]

🚀 [Row 15] GPT: Sending request...
⏳ [Row 18] Gemini: Rate limit (Attempt 2)
🚀 [Row 80] GPT: Sending request...

  8%|▊         | 15/200 [02:07<23:15,  7.54s/it]

✅ [Row 75] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of infidelity, temptation, and ultimately ...
🚀 [Row 75] Claude: Sending request...

  8%|▊         | 15/200 [02:08<23:15,  7.54s/it]

🚀 [Row 79] GPT: Sending request...

  8%|▊         | 15/200 [02:09<23:15,  7.54s/it]

⏳ [Row 17] Gemini: Rate limit (Attempt 3)

  8%|▊         | 15/200 [02:10<23:15,  7.54s/it]

✅ [Row 81] GPT Received: {
  "reasoning": "The Anchor text focuses on the later life of J. M. W. Turner, highlighting his per...
🚀 [Row 81] Claude: Sending request...

  8%|▊         | 15/200 [02:10<23:15,  7.54s/it]

✅ [Row 80] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist who is unwittingly involved in a crime, fa...
🚀 [Row 80] Claude: Sending request...

  8%|▊         | 15/200 [02:11<23:15,  7.54s/it]

✅ [Row 15] GPT Received: {
  "reasoning": "The Anchor text revolves around a conflict over water rights, with a protagonist w...
🚀 [Row 15] Claude: Sending request...

  8%|▊         | 15/200 [02:12<23:15,  7.54s/it]

✅ [Row 79] GPT Received: {
  "reasoning": "The Anchor story and Text B both revolve around themes of revenge, misunderstandin...
🚀 [Row 79] Claude: Sending request...

  8%|▊         | 16/200 [02:14<32:10, 10.49s/it]

✅ [Row 16] Claude Received: ```json
{
  "reasoning": "The Anchor is about a spy mission involving impersonation and internationa...
🏁 [Row 16] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 19] Gemini: Sending request...

  8%|▊         | 16/200 [02:15<32:10, 10.49s/it]

🚀 [Row 17] GPT: Sending request...

  8%|▊         | 16/200 [02:15<32:10, 10.49s/it]

⏳ [Row 19] Gemini: Rate limit (Attempt 1)

  8%|▊         | 16/200 [02:17<32:10, 10.49s/it]

✅ [Row 75] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a married man (Paul Manning) who is tempted by...
🏁 [Row 75] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 82] Gemini: Sending request...

  8%|▊         | 16/200 [02:18<32:10, 10.49s/it]

✅ [Row 18] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor text due to several key narrative elements. Both th...
🚀 [Row 18] GPT: Sending request...

  8%|▊         | 16/200 [02:19<32:10, 10.49s/it]

✅ [Row 17] GPT Received: {
  "reasoning": "The Anchor story involves themes of martial arts, betrayal, and a mission involvin...
🚀 [Row 17] Claude: Sending request...
⏳ [Row 82] Gemini: Rate limit (Attempt 1)

  8%|▊         | 17/200 [02:19<27:16,  8.94s/it]

✅ [Row 81] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on the final decades of painter J.M.W. Turner's life, d...
🏁 [Row 81] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 83] Gemini: Sending request...
✅ [Row 80] Claude Received: ```json
{
  "reasoning": "Both texts share narrative elements with the Anchor involving criminals, p...
🏁 [Row 80] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 84] Gemini: Sending request...
✅ [Row 15] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Roy Rogers fighting a water company monopoly through...
🏁 [Row 15] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 20] Gemini: Sending request...

  8%|▊         | 17/200 [02:20<27:16,  8.94s/it]

✅ [Row 79] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a woman seeking vengeance for her mother's rape, los...
🏁 [Row 79] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 85] Gemini: Sending request...

  8%|▊         | 17/200 [02:22<27:16,  8.94s/it]

✅ [Row 18] GPT Received: {
  "reasoning": "The Anchor story revolves around a young girl's dreams and subsequent downfall due...
🚀 [Row 18] Claude: Sending request...

  8%|▊         | 17/200 [02:24<27:16,  8.94s/it]

⏳ [Row 20] Gemini: Rate limit (Attempt 1)

  8%|▊         | 17/200 [02:25<27:16,  8.94s/it]

✅ [Row 19] Gemini Received: {
  "reasoning": "The Anchor text focuses on the abstract theme of loyalty and revenge for a dishono...
🚀 [Row 19] GPT: Sending request...

  8%|▊         | 17/200 [02:26<27:16,  8.94s/it]

✅ [Row 84] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a c...
🚀 [Row 84] GPT: Sending request...

  9%|▉         | 18/200 [02:27<25:58,  8.56s/it]

✅ [Row 17] Claude Received: ```json
{
  "reasoning": "Both texts involve martial arts and Asian settings, but Text B is narrativ...
🏁 [Row 17] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 21] Gemini: Sending request...

  9%|▉         | 18/200 [02:29<25:58,  8.56s/it]

✅ [Row 19] GPT Received: {
  "reasoning": "The Anchor story focuses on themes of loyalty, honor, and revenge, with a specific...
🚀 [Row 19] Claude: Sending request...
✅ [Row 83] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 83] GPT: Sending request...

  9%|▉         | 18/200 [02:30<25:58,  8.56s/it]

✅ [Row 84] GPT Received: {
  "reasoning": "The Anchor story involves a law student working as a night watchman who becomes em...
🚀 [Row 84] Claude: Sending request...

  9%|▉         | 18/200 [02:30<25:58,  8.56s/it]

✅ [Row 85] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center on a...
🚀 [Row 85] GPT: Sending request...

  9%|▉         | 18/200 [02:32<25:58,  8.56s/it]

✅ [Row 83] GPT Received: {
  "reasoning": "The Anchor story involves a detective unraveling a complex web of crime involving ...
🚀 [Row 83] Claude: Sending request...

 10%|▉         | 19/200 [02:33<23:44,  7.87s/it]

✅ [Row 18] Claude Received: ```json
{
  "reasoning": "The Anchor follows a tragic arc of an innocent country girl who leaves hom...
🏁 [Row 18] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 22] Gemini: Sending request...

 10%|▉         | 19/200 [02:34<23:44,  7.87s/it]

✅ [Row 85] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve themes of survival in a hostile environme...
🚀 [Row 85] Claude: Sending request...

 10%|█         | 20/200 [02:36<18:53,  6.30s/it]

✅ [Row 19] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on the forty-seven rōnin story, emphasizing the prepara...
🏁 [Row 19] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 23] Gemini: Sending request...

 10%|█         | 20/200 [02:38<18:53,  6.30s/it]

✅ [Row 84] Claude Received: ```json
{
  "reasoning": "Both texts share elements with the Anchor, but Text B is narratively close...
🏁 [Row 84] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 86] Gemini: Sending request...

 10%|█         | 20/200 [02:40<18:53,  6.30s/it]

✅ [Row 21] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 21] GPT: Sending request...

 10%|█         | 20/200 [02:41<18:53,  6.30s/it]

✅ [Row 82] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 82] GPT: Sending request...

 10%|█         | 20/200 [02:41<18:53,  6.30s/it]

✅ [Row 83] Claude Received: ```json
{
  "reasoning": "Both texts involve investigations into criminal conspiracies, but Text B i...
🏁 [Row 83] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 87] Gemini: Sending request...

 10%|█         | 20/200 [02:42<18:53,  6.30s/it]

✅ [Row 85] Claude Received: ```json
{
  "reasoning": "Both texts share survival elements with the Anchor, but Text A is narrativ...
🏁 [Row 85] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 88] Gemini: Sending request...

 10%|█         | 20/200 [02:43<18:53,  6.30s/it]

⏳ [Row 88] Gemini: Rate limit (Attempt 1)
✅ [Row 20] Gemini Received: {
  "reasoning": "The Anchor story's core involves a powerful man needing to identify a specific, hi...
🚀 [Row 20] GPT: Sending request...

 10%|█         | 20/200 [02:43<18:53,  6.30s/it]

✅ [Row 21] GPT Received: {
  "reasoning": "The Anchor text revolves around a conflict between a king and a miller over noise ...
🚀 [Row 21] Claude: Sending request...

 10%|█         | 20/200 [02:43<18:53,  6.30s/it]

✅ [Row 23] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature a spouse return...
🚀 [Row 23] GPT: Sending request...

 10%|█         | 20/200 [02:45<18:53,  6.30s/it]

✅ [Row 82] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of past relationships, unresolved feelings...
🚀 [Row 82] Claude: Sending request...

 10%|█         | 20/200 [02:47<18:53,  6.30s/it]

✅ [Row 20] GPT Received: {
  "reasoning": "The Anchor story involves a group of travelers, one of whom is secretly carrying a...
🚀 [Row 20] Claude: Sending request...

 10%|█         | 20/200 [02:48<18:53,  6.30s/it]

✅ [Row 23] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle and the difficult choice the prot...
🚀 [Row 23] Claude: Sending request...

 10%|█         | 20/200 [02:48<18:53,  6.30s/it]

✅ [Row 86] Gemini Received: {
  "reasoning": "Text B shares a more significant narrative similarity with the Anchor. Both the An...
🚀 [Row 86] GPT: Sending request...

 10%|█         | 21/200 [02:52<27:38,  9.26s/it]

✅ [Row 21] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a conflict between King Frederick II and a stubborn ...
🏁 [Row 21] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 24] Gemini: Sending request...

 10%|█         | 21/200 [02:53<27:38,  9.26s/it]

✅ [Row 82] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic entanglements and characters confronting their...
🏁 [Row 82] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 89] Gemini: Sending request...

 10%|█         | 21/200 [02:55<27:38,  9.26s/it]

✅ [Row 86] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of delusion, idealism, and the power of ima...
🚀 [Row 86] Claude: Sending request...

 10%|█         | 21/200 [02:55<27:38,  9.26s/it]

✅ [Row 88] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a cor...
🚀 [Row 88] GPT: Sending request...

 11%|█         | 22/200 [02:56<22:39,  7.64s/it]

✅ [Row 20] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a mystery involving multiple suspects where a p...
🏁 [Row 20] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 25] Gemini: Sending request...

 11%|█         | 22/200 [02:56<22:39,  7.64s/it]

✅ [Row 87] Gemini Received: {
  "reasoning": "Both the Anchor and Text B feature an outsider who arrives in a town where mysteri...
🚀 [Row 87] GPT: Sending request...

 12%|█▏        | 23/200 [02:57<17:06,  5.80s/it]

✅ [Row 23] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a love triangle created by extraordinary circum...
🏁 [Row 23] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 26] Gemini: Sending request...

 12%|█▏        | 23/200 [02:58<17:06,  5.80s/it]

✅ [Row 88] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a journey into the Sahara desert with a c...
🚀 [Row 88] Claude: Sending request...
✅ [Row 22] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist with a neurological disorder (agnosia) who ...
🚀 [Row 22] GPT: Sending request...

 12%|█▏        | 23/200 [03:00<17:06,  5.80s/it]

✅ [Row 87] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a small town facing a crisis due to a dan...
🚀 [Row 87] Claude: Sending request...

 12%|█▏        | 23/200 [03:04<17:06,  5.80s/it]

✅ [Row 89] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist who is 'Imprisoned' by an external politic...
🚀 [Row 89] GPT: Sending request...

 12%|█▏        | 23/200 [03:04<17:06,  5.80s/it]

✅ [Row 86] Claude Received: ```json
{
  "reasoning": "Both texts involve incarcerated protagonists who face trials or imprisonme...
🏁 [Row 86] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 90] Gemini: Sending request...

 12%|█▏        | 23/200 [03:06<17:06,  5.80s/it]

✅ [Row 25] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 25] GPT: Sending request...
✅ [Row 24] Gemini Received: {
  "reasoning": "The Anchor text describes a plot where a community is threatened by a series of mu...
🚀 [Row 24] GPT: Sending request...

 12%|█▏        | 23/200 [03:06<17:06,  5.80s/it]

✅ [Row 26] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B center...
🚀 [Row 26] GPT: Sending request...

 12%|█▏        | 23/200 [03:07<17:06,  5.80s/it]

✅ [Row 88] Claude Received: ```json
{
  "reasoning": "Both texts share the core structure of the Anchor: an adventurer/archaeolo...
🏁 [Row 88] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 91] Gemini: Sending request...

 12%|█▏        | 23/200 [03:07<17:06,  5.80s/it]

✅ [Row 22] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a female protagonist with a neurological ...
🚀 [Row 22] Claude: Sending request...

 12%|█▏        | 23/200 [03:08<17:06,  5.80s/it]

✅ [Row 89] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of cultural preservation and resistance...
🚀 [Row 89] Claude: Sending request...

 12%|█▏        | 23/200 [03:09<17:06,  5.80s/it]

✅ [Row 87] Claude Received: ```json
{
  "reasoning": "The Anchor is about a mysterious threat (a great white shark) appearing in...
🏁 [Row 87] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 92] Gemini: Sending request...

 12%|█▏        | 23/200 [03:10<17:06,  5.80s/it]

✅ [Row 24] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a protagonist dealing with a crisis in a ...
🚀 [Row 24] Claude: Sending request...

 12%|█▏        | 23/200 [03:11<17:06,  5.80s/it]

✅ [Row 26] GPT Received: {
  "reasoning": "The Anchor text involves a protagonist, Steve, who is on a mission to find his mis...
🚀 [Row 26] Claude: Sending request...

 12%|█▏        | 23/200 [03:11<17:06,  5.80s/it]

✅ [Row 25] GPT Received: {
  "reasoning": "The Anchor text is set in a fantastical version of pre-revolutionary France, invol...
🚀 [Row 25] Claude: Sending request...

 12%|█▏        | 23/200 [03:13<17:06,  5.80s/it]

✅ [Row 90] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 90] GPT: Sending request...

 12%|█▏        | 23/200 [03:15<17:06,  5.80s/it]

✅ [Row 89] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a protagonist imprisoned under Japanese occupation w...
🏁 [Row 89] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 93] Gemini: Sending request...

 12%|█▏        | 23/200 [03:16<17:06,  5.80s/it]

✅ [Row 91] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 91] GPT: Sending request...

 12%|█▏        | 23/200 [03:17<17:06,  5.80s/it]

✅ [Row 90] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of family conflict, identity, and redempti...
🚀 [Row 90] Claude: Sending request...

 12%|█▏        | 24/200 [03:19<30:49, 10.51s/it]

✅ [Row 24] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a group of people in a rural setting who band ...
🏁 [Row 24] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 27] Gemini: Sending request...

 12%|█▎        | 25/200 [03:19<22:01,  7.55s/it]

✅ [Row 26] Claude Received: ```json
{
  "reasoning": "Both texts share spy/espionage thriller elements with the Anchor, but Text...
❌ [Row 26] Claude Error: Expecting ',' delimiter: line 3 column 3 (char 973)
🏁 [Row 26] Votes: {'gemini': False, 'gpt': False, 'claude': None}
🚀 [Row 28] Gemini: Sending request...

 13%|█▎        | 26/200 [03:20<15:47,  5.44s/it]

✅ [Row 22] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on Joana Prats, who has agnosia (a perceptual dis...
🏁 [Row 22] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 29] Gemini: Sending request...

 14%|█▎        | 27/200 [03:22<12:39,  4.39s/it]

✅ [Row 92] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 92] GPT: Sending request...
✅ [Row 25] Claude Received: ```json
{
  "reasoning": "The Anchor centers on the Marquis de Sade imprisoned in pre-revolutionary ...
🏁 [Row 25] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 30] Gemini: Sending request...

 14%|█▎        | 27/200 [03:22<12:39,  4.39s/it]

✅ [Row 91] GPT Received: {
  "reasoning": "The Anchor story revolves around Dr. David Lowell's struggle against a corporation...
🚀 [Row 91] Claude: Sending request...

 14%|█▎        | 27/200 [03:26<12:39,  4.39s/it]

✅ [Row 28] Gemini Received: {
  "reasoning": "The Anchor text focuses on a disabled music band overcoming societal prejudice and...
🚀 [Row 28] GPT: Sending request...
✅ [Row 92] GPT Received: {
  "reasoning": "The Anchor story involves a drifter with a troubled past being drawn into a crimin...
🚀 [Row 92] Claude: Sending request...

 14%|█▎        | 27/200 [03:27<12:39,  4.39s/it]

✅ [Row 93] Gemini Received: {
  "reasoning": "The Anchor text focuses on volunteers in a wartime recreational center, adhering t...
🚀 [Row 93] GPT: Sending request...

 14%|█▎        | 27/200 [03:29<12:39,  4.39s/it]

✅ [Row 90] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a son fleeing his mother's problematic relationship,...
🏁 [Row 90] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 94] Gemini: Sending request...

 14%|█▎        | 27/200 [03:29<12:39,  4.39s/it]

✅ [Row 28] GPT Received: {
  "reasoning": "The Anchor story focuses on overcoming societal stereotypes and challenges related...
🚀 [Row 28] Claude: Sending request...

 14%|█▎        | 27/200 [03:29<12:39,  4.39s/it]

✅ [Row 27] Gemini Received: {
  "reasoning": "The Anchor text describes a student's journey, interspersed with reflections on hi...
🚀 [Row 27] GPT: Sending request...
✅ [Row 30] Gemini Received: {
  "reasoning": "The Anchor text focuses on themes of romantic betrayal, revenge for infidelity, an...
🚀 [Row 30] GPT: Sending request...

 14%|█▎        | 27/200 [03:30<12:39,  4.39s/it]

✅ [Row 29] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text due to several shared core element...
🚀 [Row 29] GPT: Sending request...

 14%|█▎        | 27/200 [03:31<12:39,  4.39s/it]

✅ [Row 93] GPT Received: {
  "reasoning": "The Anchor story and Text B both revolve around a wartime setting and involve mili...
🚀 [Row 93] Claude: Sending request...

 14%|█▎        | 27/200 [03:32<12:39,  4.39s/it]

✅ [Row 91] Claude Received: ```json
{
  "reasoning": "Both texts involve corporate conflicts over inventions/research and sabota...
🏁 [Row 91] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 95] Gemini: Sending request...

 14%|█▎        | 27/200 [03:33<12:39,  4.39s/it]

✅ [Row 27] GPT Received: {
  "reasoning": "The Anchor text is a travel narrative that includes personal encounters, reflectio...
🚀 [Row 27] Claude: Sending request...

 14%|█▎        | 27/200 [03:33<12:39,  4.39s/it]

✅ [Row 29] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve journeys to foreign lands during historica...
🚀 [Row 29] Claude: Sending request...

 14%|█▎        | 27/200 [03:34<12:39,  4.39s/it]

✅ [Row 30] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of betrayal, fidelity, and revenge, with a...
🚀 [Row 30] Claude: Sending request...
✅ [Row 92] Claude Received: ```json
{
  "reasoning": "Both texts share some surface-level similarities with the Anchor (mental h...
🏁 [Row 92] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 96] Gemini: Sending request...

 14%|█▍        | 28/200 [03:38<22:46,  7.95s/it]

✅ [Row 28] Claude Received: ```json
{
  "reasoning": "The Anchor story is about a disabled Zimbabwean woman and her band overcom...
🏁 [Row 28] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 31] Gemini: Sending request...

 14%|█▍        | 28/200 [03:38<22:46,  7.95s/it]

✅ [Row 93] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a wartime entertainment/service setting where volunt...
🏁 [Row 93] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 97] Gemini: Sending request...

 14%|█▍        | 28/200 [03:39<22:46,  7.95s/it]

✅ [Row 94] Gemini Received: {
  "reasoning": "The Anchor text features a bumbling private detective investigating a murder he's ...
🚀 [Row 94] GPT: Sending request...

 14%|█▍        | 29/200 [03:40<17:53,  6.28s/it]

✅ [Row 27] Claude Received: ```json
{
  "reasoning": "The Anchor is a travel account by Heinrich Heine describing his journey as...
🏁 [Row 27] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 32] Gemini: Sending request...

 15%|█▌        | 30/200 [03:41<13:15,  4.68s/it]

✅ [Row 30] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around Angela's romantic betrayal and revenge within a...
🏁 [Row 30] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 33] Gemini: Sending request...

 16%|█▌        | 31/200 [03:42<10:01,  3.56s/it]

✅ [Row 29] Claude Received: ```json
{
  "reasoning": "The Anchor describes a 19th-century merchant who travels from France to Ja...
🏁 [Row 29] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 34] Gemini: Sending request...

 16%|█▌        | 31/200 [03:43<10:01,  3.56s/it]

✅ [Row 95] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 95] GPT: Sending request...

 16%|█▌        | 31/200 [03:43<10:01,  3.56s/it]

✅ [Row 94] GPT Received: {
  "reasoning": "The Anchor story involves a private detective trying to prove his innocence in a m...
🚀 [Row 94] Claude: Sending request...

 16%|█▌        | 31/200 [03:48<10:01,  3.56s/it]

✅ [Row 97] Gemini Received: {
  "reasoning": "The Anchor text focuses on the mid-life existential crisis of Harry Angstrom, high...
🚀 [Row 97] GPT: Sending request...

 16%|█▌        | 31/200 [03:48<10:01,  3.56s/it]

✅ [Row 95] GPT Received: {
  "reasoning": "The Anchor story revolves around a case of mistaken identity and a romantic pursui...
🚀 [Row 95] Claude: Sending request...

 16%|█▌        | 31/200 [03:49<10:01,  3.56s/it]

⏳ [Row 33] Gemini: Rate limit (Attempt 1)

 16%|█▌        | 31/200 [03:51<10:01,  3.56s/it]

✅ [Row 32] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B prominently...
🚀 [Row 32] GPT: Sending request...

 16%|█▌        | 31/200 [03:51<10:01,  3.56s/it]

⏳ [Row 33] Gemini: Rate limit (Attempt 2)

 16%|█▌        | 31/200 [03:52<10:01,  3.56s/it]

✅ [Row 97] GPT Received: {
  "reasoning": "The Anchor text and Text A both explore themes of middle-class life, personal diss...
🚀 [Row 97] Claude: Sending request...

 16%|█▌        | 31/200 [03:52<10:01,  3.56s/it]

✅ [Row 94] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a bumbling private detective (Peckinpaugh) trying to...
🏁 [Row 94] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 98] Gemini: Sending request...

 16%|█▌        | 31/200 [03:54<10:01,  3.56s/it]

✅ [Row 32] GPT Received: {
  "reasoning": "The Anchor story involves a theme of cannibalism and zombies, with a course of act...
🚀 [Row 32] Claude: Sending request...

 16%|█▌        | 31/200 [03:57<10:01,  3.56s/it]

✅ [Row 95] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic mix-ups with class differences, but Text B is ...
🏁 [Row 95] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 99] Gemini: Sending request...

 16%|█▌        | 31/200 [03:58<10:01,  3.56s/it]

✅ [Row 34] Gemini Received: {
  "reasoning": "The Anchor text centers around friends reuniting after a loss (Tomasi's death) to ...
🚀 [Row 34] GPT: Sending request...

 16%|█▌        | 31/200 [04:02<10:01,  3.56s/it]

✅ [Row 97] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a middle-aged man dealing with marital problems, fam...
🏁 [Row 97] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 100] Gemini: Sending request...

 16%|█▌        | 31/200 [04:02<10:01,  3.56s/it]

✅ [Row 34] GPT Received: {
  "reasoning": "The Anchor text revolves around a reunion of friends reflecting on their past expe...
🚀 [Row 34] Claude: Sending request...

 16%|█▌        | 32/200 [04:03<24:24,  8.72s/it]

✅ [Row 32] Claude Received: ```json
{
  "reasoning": "Both texts involve reanimated corpses/zombies and investigations, but Text...
🏁 [Row 32] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 35] Gemini: Sending request...

 16%|█▌        | 32/200 [04:04<24:24,  8.72s/it]

❌ [Row 96] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 16%|█▌        | 32/200 [04:05<24:24,  8.72s/it]

✅ [Row 31] Gemini Received: {
  "reasoning": "The Anchor Text describes the history of the Chinese Communist Party's struggle fo...
🚀 [Row 31] GPT: Sending request...

 16%|█▌        | 32/200 [04:06<24:24,  8.72s/it]

⏳ [Row 98] Gemini: Rate limit (Attempt 1)

 16%|█▌        | 32/200 [04:09<24:24,  8.72s/it]

✅ [Row 31] GPT Received: {
  "reasoning": "The Anchor text focuses on the historical narrative of the Chinese Communist Party...
🚀 [Row 31] Claude: Sending request...

 16%|█▌        | 32/200 [04:10<24:24,  8.72s/it]

✅ [Row 33] Gemini Received: {
  "reasoning": "Both the Anchor and Text A center on the struggles of Vietnam War veterans with po...
🚀 [Row 33] GPT: Sending request...

 16%|█▋        | 33/200 [04:11<23:24,  8.41s/it]

✅ [Row 34] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on four male friends reuniting ten years after high sch...
🏁 [Row 34] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 36] Gemini: Sending request...

 16%|█▋        | 33/200 [04:14<23:24,  8.41s/it]

✅ [Row 33] GPT Received: {
  "reasoning": "The Anchor text and Text A both deal with the aftermath of the Vietnam War and its...
🚀 [Row 33] Claude: Sending request...

 16%|█▋        | 33/200 [04:16<23:24,  8.41s/it]

✅ [Row 100] Gemini Received: {
  "reasoning": "The Anchor text describes Satan influencing and causing major historical conflicts...
🚀 [Row 100] GPT: Sending request...

 17%|█▋        | 34/200 [04:17<21:35,  7.81s/it]

✅ [Row 31] Claude Received: ```json
{
  "reasoning": "The Anchor depicts the Chinese Communist Party's history from 1921-1949, f...
🏁 [Row 31] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 37] Gemini: Sending request...

 17%|█▋        | 34/200 [04:19<21:35,  7.81s/it]

✅ [Row 35] Gemini Received: {
  "reasoning": "The Anchor text presents a narrative where a protagonist's life is actively orches...
🚀 [Row 35] GPT: Sending request...
⏳ [Row 37] Gemini: Rate limit (Attempt 1)

 17%|█▋        | 34/200 [04:19<21:35,  7.81s/it]

✅ [Row 100] GPT Received: {
  "reasoning": "The Anchor story revolves around Satan's mission on Earth, where he influences his...
🚀 [Row 100] Claude: Sending request...

 17%|█▋        | 34/200 [04:21<21:35,  7.81s/it]

✅ [Row 99] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor than Text B. Both the Anchor and Text A...
🚀 [Row 99] GPT: Sending request...

 17%|█▋        | 34/200 [04:21<21:35,  7.81s/it]

✅ [Row 36] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share a cor...
🚀 [Row 36] GPT: Sending request...

 17%|█▋        | 34/200 [04:23<21:35,  7.81s/it]

✅ [Row 35] GPT Received: {
  "reasoning": "The Anchor text presents a narrative that involves a reinterpretation of the life ...
🚀 [Row 35] Claude: Sending request...

 17%|█▋        | 34/200 [04:23<21:35,  7.81s/it]

✅ [Row 98] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A center...
🚀 [Row 98] GPT: Sending request...

 18%|█▊        | 35/200 [04:23<20:11,  7.34s/it]

✅ [Row 33] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a Vietnam veteran (Megs) helping another troubled ve...
🏁 [Row 33] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 38] Gemini: Sending request...

 18%|█▊        | 35/200 [04:24<20:11,  7.34s/it]

✅ [Row 96] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a f...
🚀 [Row 96] GPT: Sending request...

 18%|█▊        | 35/200 [04:25<20:11,  7.34s/it]

✅ [Row 99] GPT Received: {
  "reasoning": "The Anchor story revolves around a couple trying to mend their relationship during...
🚀 [Row 99] Claude: Sending request...

 18%|█▊        | 35/200 [04:27<20:11,  7.34s/it]

✅ [Row 98] GPT Received: {
  "reasoning": "The Anchor story revolves around two couples dealing with infidelity and the resul...
🚀 [Row 98] Claude: Sending request...

 18%|█▊        | 35/200 [04:27<20:11,  7.34s/it]

✅ [Row 36] GPT Received: {
  "reasoning": "The Anchor story revolves around a reporter who makes a mistake in his article and...
🚀 [Row 36] Claude: Sending request...

 18%|█▊        | 35/200 [04:28<20:11,  7.34s/it]

✅ [Row 96] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle, financial struggles, and a retur...
🚀 [Row 96] Claude: Sending request...

 18%|█▊        | 35/200 [04:29<20:11,  7.34s/it]

✅ [Row 100] Claude Received: ```json
{
  "reasoning": "The Anchor is about Satan being banished to Earth and influencing major hi...
🏁 [Row 100] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 101] Gemini: Sending request...

 18%|█▊        | 35/200 [04:31<20:11,  7.34s/it]

⏳ [Row 101] Gemini: Rate limit (Attempt 1)

 18%|█▊        | 36/200 [04:31<20:22,  7.46s/it]

✅ [Row 35] Claude Received: ```json
{
  "reasoning": "The Anchor story is a radical religious reinterpretation involving Jesus a...
🏁 [Row 35] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 39] Gemini: Sending request...

 18%|█▊        | 36/200 [04:34<20:22,  7.46s/it]

✅ [Row 99] Claude Received: ```json
{
  "reasoning": "The Anchor is centered on a couple's troubled relationship that becomes se...
🏁 [Row 99] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 102] Gemini: Sending request...

 18%|█▊        | 36/200 [04:35<20:22,  7.46s/it]

✅ [Row 37] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a h...
🚀 [Row 37] GPT: Sending request...

 18%|█▊        | 36/200 [04:36<20:22,  7.46s/it]

✅ [Row 98] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a double-adultery situation between two couples (Jack/T...
🏁 [Row 98] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 103] Gemini: Sending request...

 18%|█▊        | 37/200 [04:36<18:08,  6.68s/it]

✅ [Row 36] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a reporter who makes an error in his work, is ...
🏁 [Row 36] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 40] Gemini: Sending request...

 18%|█▊        | 37/200 [04:38<18:08,  6.68s/it]

✅ [Row 96] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a love triangle where Lucile oscillates between a we...
🏁 [Row 96] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 104] Gemini: Sending request...

 18%|█▊        | 37/200 [04:40<18:08,  6.68s/it]

✅ [Row 37] GPT Received: {
  "reasoning": "The Anchor story revolves around a closeted gay teenager, Simon, who is navigating...
🚀 [Row 37] Claude: Sending request...

 18%|█▊        | 37/200 [04:40<18:08,  6.68s/it]

✅ [Row 38] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both stories feature a protagonis...
🚀 [Row 38] GPT: Sending request...

 18%|█▊        | 37/200 [04:43<18:08,  6.68s/it]

✅ [Row 101] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a y...
🚀 [Row 101] GPT: Sending request...

 18%|█▊        | 37/200 [04:44<18:08,  6.68s/it]

✅ [Row 38] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a protagonist facing challenges and setba...
🚀 [Row 38] Claude: Sending request...

 18%|█▊        | 37/200 [04:45<18:08,  6.68s/it]

✅ [Row 103] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A depict how ...
🚀 [Row 103] GPT: Sending request...

 18%|█▊        | 37/200 [04:47<18:08,  6.68s/it]

✅ [Row 40] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a s...
🚀 [Row 40] GPT: Sending request...

 18%|█▊        | 37/200 [04:47<18:08,  6.68s/it]

✅ [Row 104] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B revolv...
🚀 [Row 104] GPT: Sending request...

 19%|█▉        | 38/200 [04:49<22:59,  8.52s/it]

✅ [Row 101] GPT Received: {
  "reasoning": "The Anchor story revolves around Agnes, who escapes her father's control and ends ...
🚀 [Row 101] Claude: Sending request...
✅ [Row 37] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Simon, a closeted gay teen who communicates with an ...
🏁 [Row 37] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 41] Gemini: Sending request...

 19%|█▉        | 38/200 [04:50<22:59,  8.52s/it]

✅ [Row 104] GPT Received: {
  "reasoning": "The Anchor story involves a legal conflict between a fishery and a chemical compan...
🚀 [Row 104] Claude: Sending request...

 19%|█▉        | 38/200 [04:51<22:59,  8.52s/it]

✅ [Row 103] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of change, adaptation, and the impact of e...
🚀 [Row 103] Claude: Sending request...

 19%|█▉        | 38/200 [04:51<22:59,  8.52s/it]

✅ [Row 40] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of environmental degradation, mysterious r...
🚀 [Row 40] Claude: Sending request...

 20%|█▉        | 39/200 [04:54<20:02,  7.47s/it]

✅ [Row 38] Claude Received: ```json
{
  "reasoning": "Both texts feature protagonists facing professional setbacks and crises, b...
🏁 [Row 38] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 42] Gemini: Sending request...

 20%|█▉        | 39/200 [04:57<20:02,  7.47s/it]

✅ [Row 39] Gemini Received: {
  "reasoning": "The Anchor story's central conflict revolves around the protagonist, Diane, experi...
🚀 [Row 39] GPT: Sending request...

 20%|█▉        | 39/200 [04:59<20:02,  7.47s/it]

✅ [Row 103] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on families resettled during communist rule in a ...
🏁 [Row 103] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 105] Gemini: Sending request...

 20%|█▉        | 39/200 [05:00<20:02,  7.47s/it]

⏳ [Row 105] Gemini: Rate limit (Attempt 1)
✅ [Row 104] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a legal case involving environmental pollution...
🏁 [Row 104] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 106] Gemini: Sending request...

 20%|██        | 40/200 [05:01<19:21,  7.26s/it]

✅ [Row 40] Claude Received: ```json
{
  "reasoning": "The Anchor involves a woman (Magdalena) who was presumed dead returning fr...
🏁 [Row 40] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 43] Gemini: Sending request...

 20%|██        | 40/200 [05:01<19:21,  7.26s/it]

✅ [Row 101] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on Agnes, a sheltered woman (daughter of a genera...
🏁 [Row 101] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 107] Gemini: Sending request...

 20%|██        | 40/200 [05:01<19:21,  7.26s/it]

✅ [Row 102] Gemini Received: {
  "reasoning": "The Anchor text is defined by its unique structure of 'five simultaneous, loosely ...
🚀 [Row 102] GPT: Sending request...

 20%|██        | 40/200 [05:02<19:21,  7.26s/it]

✅ [Row 42] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A begin with the discovery of a spouse's infidelity....
🚀 [Row 42] GPT: Sending request...
✅ [Row 41] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center arou...
🚀 [Row 41] GPT: Sending request...

 20%|██        | 40/200 [05:02<19:21,  7.26s/it]

✅ [Row 39] GPT Received: {
  "reasoning": "The Anchor story revolves around Diane, a lawyer who, after a divorce, meets Alexa...
🚀 [Row 39] Claude: Sending request...

 20%|██        | 40/200 [05:05<19:21,  7.26s/it]

✅ [Row 41] GPT Received: {
  "reasoning": "The Anchor story revolves around a complex investigation involving organized crime...
🚀 [Row 41] Claude: Sending request...

 20%|██        | 40/200 [05:05<19:21,  7.26s/it]

✅ [Row 102] GPT Received: {
  "reasoning": "The Anchor text features multiple intertwined plot lines with surreal and darkly c...
🚀 [Row 102] Claude: Sending request...
✅ [Row 42] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of infidelity, revenge, and the consequence...
🚀 [Row 42] Claude: Sending request...

 20%|██        | 40/200 [05:07<19:21,  7.26s/it]

✅ [Row 106] Gemini Received: {
  "reasoning": "The Anchor Text explores idealism and disillusionment within the context of Commun...
🚀 [Row 106] GPT: Sending request...

 20%|██        | 40/200 [05:10<19:21,  7.26s/it]

✅ [Row 107] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor's core theme is the devasta...
🚀 [Row 107] GPT: Sending request...

 20%|██        | 41/200 [05:11<21:29,  8.11s/it]

✅ [Row 39] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve romantic encounters and relationship compli...
🏁 [Row 39] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 44] Gemini: Sending request...

 21%|██        | 42/200 [05:11<15:17,  5.81s/it]

✅ [Row 41] Claude Received: ```json
{
  "reasoning": "Text A shares significantly more narrative elements with the Anchor. Both ...
🏁 [Row 41] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 45] Gemini: Sending request...
✅ [Row 43] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share the c...
🚀 [Row 43] GPT: Sending request...

 21%|██        | 42/200 [05:13<15:17,  5.81s/it]

✅ [Row 106] GPT Received: {
  "reasoning": "The Anchor text revolves around the theme of political idealism and disillusionmen...
🚀 [Row 106] Claude: Sending request...

 21%|██        | 42/200 [05:14<15:17,  5.81s/it]

⏳ [Row 45] Gemini: Rate limit (Attempt 1)

 21%|██        | 42/200 [05:15<15:17,  5.81s/it]

✅ [Row 102] Claude Received: ```json
{
  "reasoning": "The Anchor follows multiple disconnected plot lines (a man repeatedly kill...
🏁 [Row 102] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 108] Gemini: Sending request...

 21%|██        | 42/200 [05:16<15:17,  5.81s/it]

✅ [Row 43] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve themes of love and the arts, with charact...
🚀 [Row 43] Claude: Sending request...

 22%|██▏       | 43/200 [05:16<14:37,  5.59s/it]

⏳ [Row 108] Gemini: Rate limit (Attempt 1)
✅ [Row 42] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on marital infidelity, revenge affairs, and a liberal e...
🏁 [Row 42] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 46] Gemini: Sending request...

 22%|██▏       | 43/200 [05:17<14:37,  5.59s/it]

⏳ [Row 44] Gemini: Rate limit (Attempt 1)
✅ [Row 107] GPT Received: {
  "reasoning": "The Anchor text revolves around the theme of war and its impact on personal lives,...
🚀 [Row 107] Claude: Sending request...

 22%|██▏       | 43/200 [05:20<14:37,  5.59s/it]

⏳ [Row 108] Gemini: Rate limit (Attempt 2)

 22%|██▏       | 43/200 [05:21<14:37,  5.59s/it]

✅ [Row 105] Gemini Received: {
  "reasoning": "The Anchor story involves multiple interconnected plots, including a central schem...
🚀 [Row 105] GPT: Sending request...
⏳ [Row 44] Gemini: Rate limit (Attempt 2)

 22%|██▏       | 43/200 [05:21<14:37,  5.59s/it]

⏳ [Row 45] Gemini: Rate limit (Attempt 2)

 22%|██▏       | 43/200 [05:22<14:37,  5.59s/it]

✅ [Row 106] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a Communist worker (Jarda) who must confront the dis...
🏁 [Row 106] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 109] Gemini: Sending request...
⏳ [Row 46] Gemini: Rate limit (Attempt 1)

 22%|██▏       | 43/200 [05:24<14:37,  5.59s/it]

⏳ [Row 109] Gemini: Rate limit (Attempt 1)

 22%|██▏       | 44/200 [05:25<16:51,  6.48s/it]

✅ [Row 43] Claude Received: ```json
{
  "reasoning": "The Anchor follows a story where Leonora, a peasant woman, becomes a famou...
🏁 [Row 43] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 47] Gemini: Sending request...
✅ [Row 107] Claude Received: ```json
{
  "reasoning": "Both texts involve war settings, but Text B is narratively much closer to ...
🏁 [Row 107] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 110] Gemini: Sending request...

 22%|██▏       | 44/200 [05:26<16:51,  6.48s/it]

✅ [Row 105] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, deception, and reconciliation, wi...
🚀 [Row 105] Claude: Sending request...

 22%|██▏       | 44/200 [05:27<16:51,  6.48s/it]

⏳ [Row 108] Gemini: Rate limit (Attempt 3)

 22%|██▏       | 44/200 [05:27<16:51,  6.48s/it]

⏳ [Row 109] Gemini: Rate limit (Attempt 2)

 22%|██▏       | 44/200 [05:27<16:51,  6.48s/it]

⏳ [Row 47] Gemini: Rate limit (Attempt 1)
⏳ [Row 44] Gemini: Rate limit (Attempt 3)

 22%|██▏       | 44/200 [05:28<16:51,  6.48s/it]

⏳ [Row 110] Gemini: Rate limit (Attempt 1)

 22%|██▏       | 44/200 [05:32<16:51,  6.48s/it]

⏳ [Row 47] Gemini: Rate limit (Attempt 2)

 22%|██▏       | 44/200 [05:32<16:51,  6.48s/it]

⏳ [Row 45] Gemini: Rate limit (Attempt 3)

 22%|██▏       | 44/200 [05:32<16:51,  6.48s/it]

⏳ [Row 109] Gemini: Rate limit (Attempt 3)
⏳ [Row 110] Gemini: Rate limit (Attempt 2)

 22%|██▏       | 44/200 [05:33<16:51,  6.48s/it]

🚀 [Row 108] GPT: Sending request...

 22%|██▏       | 44/200 [05:33<16:51,  6.48s/it]

🚀 [Row 44] GPT: Sending request...

 22%|██▏       | 44/200 [05:34<16:51,  6.48s/it]

⏳ [Row 46] Gemini: Rate limit (Attempt 2)

 22%|██▏       | 44/200 [05:35<16:51,  6.48s/it]

✅ [Row 105] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on romantic deception and infiltration with a cle...
🏁 [Row 105] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 111] Gemini: Sending request...

 22%|██▏       | 44/200 [05:36<16:51,  6.48s/it]

⏳ [Row 47] Gemini: Rate limit (Attempt 3)

 22%|██▏       | 44/200 [05:37<16:51,  6.48s/it]

⏳ [Row 111] Gemini: Rate limit (Attempt 1)
⏳ [Row 110] Gemini: Rate limit (Attempt 3)

 22%|██▏       | 44/200 [05:37<16:51,  6.48s/it]

✅ [Row 44] GPT Received: {
  "reasoning": "The Anchor story involves a cruise, a mix-up with a con man, and a fortuitous outc...
🚀 [Row 44] Claude: Sending request...

 22%|██▏       | 44/200 [05:38<16:51,  6.48s/it]

🚀 [Row 45] GPT: Sending request...

 22%|██▏       | 44/200 [05:38<16:51,  6.48s/it]

🚀 [Row 109] GPT: Sending request...

 22%|██▏       | 44/200 [05:41<16:51,  6.48s/it]

✅ [Row 45] GPT Received: {
  "reasoning": "The Anchor text involves an FBI agent infiltrating a counterfeiting operation in P...
🚀 [Row 45] Claude: Sending request...
✅ [Row 108] GPT Received: {
  "reasoning": "The Anchor text revolves around a speechwriter navigating the challenges of workin...
🚀 [Row 108] Claude: Sending request...
✅ [Row 109] GPT Received: {
  "reasoning": "The Anchor story involves retired detectives coming out of retirement to solve a m...
🚀 [Row 109] Claude: Sending request...

 22%|██▏       | 44/200 [05:42<16:51,  6.48s/it]

⏳ [Row 46] Gemini: Rate limit (Attempt 3)
⏳ [Row 111] Gemini: Rate limit (Attempt 2)

 22%|██▏       | 44/200 [05:42<16:51,  6.48s/it]

🚀 [Row 47] GPT: Sending request...

 22%|██▏       | 44/200 [05:43<16:51,  6.48s/it]

🚀 [Row 110] GPT: Sending request...

 22%|██▏       | 44/200 [05:45<16:51,  6.48s/it]

✅ [Row 47] GPT Received: {
  "reasoning": "The Anchor story involves a kidnapping and ransom situation with public involvemen...
🚀 [Row 47] Claude: Sending request...

 22%|██▎       | 45/200 [05:46<28:18, 10.96s/it]

✅ [Row 44] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B share some surface similarities with the Anchor (mi...
🏁 [Row 44] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 48] Gemini: Sending request...

 22%|██▎       | 45/200 [05:48<28:18, 10.96s/it]

🚀 [Row 46] GPT: Sending request...

 23%|██▎       | 46/200 [05:48<21:17,  8.30s/it]

✅ [Row 45] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on an FBI agent infiltrating a counterfeiting operation...
🏁 [Row 45] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 49] Gemini: Sending request...
✅ [Row 110] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist, John Shaft, who is coerced into a mission...
🚀 [Row 110] Claude: Sending request...

 23%|██▎       | 46/200 [05:50<21:17,  8.30s/it]

✅ [Row 109] Claude Received: ```json
{
  "reasoning": "The Anchor centers on retired detectives (Holmes and Watson) investigating...
🏁 [Row 109] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 112] Gemini: Sending request...

 23%|██▎       | 46/200 [05:50<21:17,  8.30s/it]

⏳ [Row 48] Gemini: Rate limit (Attempt 1)

 23%|██▎       | 46/200 [05:51<21:17,  8.30s/it]

⏳ [Row 111] Gemini: Rate limit (Attempt 3)

 23%|██▎       | 46/200 [05:51<21:17,  8.30s/it]

⏳ [Row 112] Gemini: Rate limit (Attempt 1)

 24%|██▎       | 47/200 [05:51<17:12,  6.75s/it]

✅ [Row 47] Claude Received: ```json
{
  "reasoning": "The Anchor involves a kidnapping with ransom demands, media attention, and...
🏁 [Row 47] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 50] Gemini: Sending request...
✅ [Row 108] Claude Received: ```json
{
  "reasoning": "The Anchor follows a young professional (Arthur) entering a prestigious go...
🏁 [Row 108] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 113] Gemini: Sending request...

 24%|██▎       | 47/200 [05:52<17:12,  6.75s/it]

✅ [Row 46] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle involving an affair, resulting in...
🚀 [Row 46] Claude: Sending request...

 24%|██▎       | 47/200 [05:52<17:12,  6.75s/it]

⏳ [Row 113] Gemini: Rate limit (Attempt 1)
⏳ [Row 50] Gemini: Rate limit (Attempt 1)

 24%|██▎       | 47/200 [05:54<17:12,  6.75s/it]

⏳ [Row 49] Gemini: Rate limit (Attempt 1)

 24%|██▎       | 47/200 [05:54<17:12,  6.75s/it]

⏳ [Row 112] Gemini: Rate limit (Attempt 2)

 24%|██▎       | 47/200 [05:55<17:12,  6.75s/it]

⏳ [Row 113] Gemini: Rate limit (Attempt 2)

 24%|██▎       | 47/200 [05:55<17:12,  6.75s/it]

⏳ [Row 48] Gemini: Rate limit (Attempt 2)

 24%|██▎       | 47/200 [05:56<17:12,  6.75s/it]

✅ [Row 110] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around John Shaft being kidnapped/coerced into assumin...
🏁 [Row 110] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 114] Gemini: Sending request...

 24%|██▎       | 47/200 [05:56<17:12,  6.75s/it]

⏳ [Row 50] Gemini: Rate limit (Attempt 2)

 24%|██▎       | 47/200 [05:57<17:12,  6.75s/it]

🚀 [Row 111] GPT: Sending request...

 24%|██▍       | 48/200 [06:00<18:24,  7.27s/it]

⏳ [Row 113] Gemini: Rate limit (Attempt 3)
✅ [Row 46] Claude Received: ```json
{
  "reasoning": "Both texts involve marital infidelity leading to death and dramatic conseq...
🏁 [Row 46] Votes: {'gemini': None, 'gpt': True, 'claude': False}
🚀 [Row 51] Gemini: Sending request...

 24%|██▍       | 48/200 [06:00<18:24,  7.27s/it]

✅ [Row 111] GPT Received: {
  "reasoning": "The Anchor story involves themes of deceit, land expansion, and conflict between s...
🚀 [Row 111] Claude: Sending request...

 24%|██▍       | 48/200 [06:01<18:24,  7.27s/it]

⏳ [Row 48] Gemini: Rate limit (Attempt 3)
⏳ [Row 112] Gemini: Rate limit (Attempt 3)

 24%|██▍       | 48/200 [06:02<18:24,  7.27s/it]

⏳ [Row 50] Gemini: Rate limit (Attempt 3)

 24%|██▍       | 48/200 [06:02<18:24,  7.27s/it]

⏳ [Row 49] Gemini: Rate limit (Attempt 2)

 24%|██▍       | 48/200 [06:03<18:24,  7.27s/it]

⏳ [Row 51] Gemini: Rate limit (Attempt 1)

 24%|██▍       | 48/200 [06:04<18:24,  7.27s/it]

✅ [Row 114] Gemini Received: {
  "reasoning": "The Anchor story features a character (Huey) wrongly accused and on the run, and a...
🚀 [Row 114] GPT: Sending request...

 24%|██▍       | 48/200 [06:06<18:24,  7.27s/it]

🚀 [Row 113] GPT: Sending request...

 24%|██▍       | 48/200 [06:07<18:24,  7.27s/it]

🚀 [Row 48] GPT: Sending request...
🚀 [Row 112] GPT: Sending request...

 24%|██▍       | 48/200 [06:08<18:24,  7.27s/it]

🚀 [Row 50] GPT: Sending request...
✅ [Row 114] GPT Received: {
  "reasoning": "The Anchor story involves a journey with an FBI agent and a former radical, reveal...
🚀 [Row 114] Claude: Sending request...

 24%|██▍       | 48/200 [06:08<18:24,  7.27s/it]

✅ [Row 111] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve conflicts, but only Text B shares the core ...
🏁 [Row 111] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 115] Gemini: Sending request...

 24%|██▍       | 48/200 [06:09<18:24,  7.27s/it]

⏳ [Row 49] Gemini: Rate limit (Attempt 3)
⏳ [Row 115] Gemini: Rate limit (Attempt 1)

 24%|██▍       | 48/200 [06:09<18:24,  7.27s/it]

✅ [Row 113] GPT Received: {
  "reasoning": "The Anchor text revolves around a naval crew's experiences before and during a mis...
🚀 [Row 113] Claude: Sending request...

 24%|██▍       | 48/200 [06:10<18:24,  7.27s/it]

✅ [Row 112] GPT Received: {
  "reasoning": "The Anchor text is set in a science fiction universe with a focus on space explora...
🚀 [Row 112] Claude: Sending request...

 24%|██▍       | 48/200 [06:11<18:24,  7.27s/it]

✅ [Row 50] GPT Received: {
  "reasoning": "The Anchor text is a documentary about the life of John C. Holmes, focusing on his...
🚀 [Row 50] Claude: Sending request...
⏳ [Row 115] Gemini: Rate limit (Attempt 2)

 24%|██▍       | 48/200 [06:12<18:24,  7.27s/it]

✅ [Row 48] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of self-discovery, dissatisfaction with on...
🚀 [Row 48] Claude: Sending request...

 24%|██▍       | 48/200 [06:13<18:24,  7.27s/it]

⏳ [Row 51] Gemini: Rate limit (Attempt 2)

 24%|██▍       | 48/200 [06:14<18:24,  7.27s/it]

🚀 [Row 49] GPT: Sending request...

 24%|██▍       | 48/200 [06:16<18:24,  7.27s/it]

✅ [Row 114] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on an FBI agent transporting a fugitive hippie/radical,...
🏁 [Row 114] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 116] Gemini: Sending request...

 24%|██▍       | 48/200 [06:17<18:24,  7.27s/it]

⏳ [Row 115] Gemini: Rate limit (Attempt 3)

 24%|██▍       | 48/200 [06:18<18:24,  7.27s/it]

✅ [Row 113] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a naval military crew (U-boat) preparing for and exe...
🏁 [Row 113] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 117] Gemini: Sending request...

 24%|██▍       | 48/200 [06:19<18:24,  7.27s/it]

⏳ [Row 117] Gemini: Rate limit (Attempt 1)
✅ [Row 49] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of love, betrayal, and the consequences of ...
🚀 [Row 49] Claude: Sending request...
⏳ [Row 116] Gemini: Rate limit (Attempt 1)
⏳ [Row 51] Gemini: Rate limit (Attempt 3)

 24%|██▍       | 48/200 [06:19<18:24,  7.27s/it]

✅ [Row 112] Claude Received: ```json
{
  "reasoning": "The Anchor describes a Star Trek-based series set on a space station with ...
🏁 [Row 112] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 118] Gemini: Sending request...

 24%|██▍       | 49/200 [06:20<28:02, 11.15s/it]

✅ [Row 48] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a mentorship relationship between a working-class wo...
🏁 [Row 48] Votes: {'gemini': None, 'gpt': True, 'claude': False}
🚀 [Row 52] Gemini: Sending request...

 24%|██▍       | 49/200 [06:21<28:02, 11.15s/it]

⏳ [Row 117] Gemini: Rate limit (Attempt 2)

 24%|██▍       | 49/200 [06:22<28:02, 11.15s/it]

⏳ [Row 116] Gemini: Rate limit (Attempt 2)

 25%|██▌       | 50/200 [06:23<21:29,  8.60s/it]

🚀 [Row 115] GPT: Sending request...
✅ [Row 50] Claude Received: ```json
{
  "reasoning": "The Anchor is a documentary about adult film star John C. Holmes, covering...
🏁 [Row 50] Votes: {'gemini': None, 'gpt': True, 'claude': False}
🚀 [Row 53] Gemini: Sending request...

 25%|██▌       | 50/200 [06:25<21:29,  8.60s/it]

🚀 [Row 51] GPT: Sending request...

 26%|██▌       | 51/200 [06:26<17:06,  6.89s/it]

✅ [Row 49] Claude Received: ```json
{
  "reasoning": "Text A shares the strongest narrative similarity with the Anchor. Both cen...
🏁 [Row 49] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 54] Gemini: Sending request...
✅ [Row 52] Gemini Received: {
  "reasoning": "Text B is closer to the Anchor. Both the Anchor and Text B feature protagonists wh...
🚀 [Row 52] GPT: Sending request...

 26%|██▌       | 51/200 [06:26<17:06,  6.89s/it]

✅ [Row 115] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve undercover agents dealing with espionage a...
🚀 [Row 115] Claude: Sending request...

 26%|██▌       | 51/200 [06:27<17:06,  6.89s/it]

⏳ [Row 54] Gemini: Rate limit (Attempt 1)

 26%|██▌       | 51/200 [06:27<17:06,  6.89s/it]

⏳ [Row 116] Gemini: Rate limit (Attempt 3)

 26%|██▌       | 51/200 [06:28<17:06,  6.89s/it]

✅ [Row 51] GPT Received: {
  "reasoning": "The Anchor story revolves around a woman raising her children in a rural setting, ...
🚀 [Row 51] Claude: Sending request...

 26%|██▌       | 51/200 [06:29<17:06,  6.89s/it]

✅ [Row 118] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist with psychophysical disorders who is insti...
🚀 [Row 118] GPT: Sending request...

 26%|██▌       | 51/200 [06:30<17:06,  6.89s/it]

✅ [Row 52] GPT Received: {
  "reasoning": "The Anchor story revolves around two lazy construction workers who pretend to be r...
🚀 [Row 52] Claude: Sending request...

 26%|██▌       | 51/200 [06:31<17:06,  6.89s/it]

⏳ [Row 54] Gemini: Rate limit (Attempt 2)

 26%|██▌       | 51/200 [06:32<17:06,  6.89s/it]

✅ [Row 118] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve protagonists with mental health issues who...
🚀 [Row 118] Claude: Sending request...

 26%|██▌       | 51/200 [06:33<17:06,  6.89s/it]

🚀 [Row 116] GPT: Sending request...

 26%|██▌       | 51/200 [06:34<17:06,  6.89s/it]

⏳ [Row 117] Gemini: Rate limit (Attempt 3)

 26%|██▌       | 51/200 [06:35<17:06,  6.89s/it]

✅ [Row 115] Claude Received: ```json
{
  "reasoning": "Both texts involve espionage and international intrigue, but Text B is nar...
🏁 [Row 115] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 119] Gemini: Sending request...
⏳ [Row 53] Gemini: Rate limit (Attempt 1)

 26%|██▌       | 51/200 [06:37<17:06,  6.89s/it]

✅ [Row 116] GPT Received: {
  "reasoning": "The Anchor text revolves around a theater director staging a play about Joan of Ar...
🚀 [Row 116] Claude: Sending request...

 26%|██▌       | 52/200 [06:38<20:47,  8.43s/it]

✅ [Row 51] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a mother raising seven children alone in a rural agricu...
🏁 [Row 51] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 55] Gemini: Sending request...

 26%|██▋       | 53/200 [06:38<14:41,  6.00s/it]

✅ [Row 52] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve romantic plots, but Text B is narratively c...
🏁 [Row 52] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 56] Gemini: Sending request...

 26%|██▋       | 53/200 [06:40<14:41,  6.00s/it]

✅ [Row 118] Claude Received: ```json
{
  "reasoning": "The Anchor follows an outsider artist (Ligabue) struggling with mental ill...
🏁 [Row 118] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 120] Gemini: Sending request...
🚀 [Row 117] GPT: Sending request...

 26%|██▋       | 53/200 [06:44<14:41,  6.00s/it]

⏳ [Row 54] Gemini: Rate limit (Attempt 3)

 26%|██▋       | 53/200 [06:44<14:41,  6.00s/it]

✅ [Row 55] Gemini Received: {
  "reasoning": "The Anchor text features a crime involving gold, a period of consequence (prison),...
🚀 [Row 55] GPT: Sending request...
✅ [Row 117] GPT Received: {
  "reasoning": "The Anchor story involves a criminal plot with counterfeit money, a protagonist wh...
🚀 [Row 117] Claude: Sending request...

 26%|██▋       | 53/200 [06:45<14:41,  6.00s/it]

✅ [Row 116] Claude Received: ```json
{
  "reasoning": "Both texts involve theatrical/artistic figures in turbulent political time...
🏁 [Row 116] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 121] Gemini: Sending request...

 26%|██▋       | 53/200 [06:45<14:41,  6.00s/it]

⏳ [Row 53] Gemini: Rate limit (Attempt 2)

 26%|██▋       | 53/200 [06:46<14:41,  6.00s/it]

⏳ [Row 121] Gemini: Rate limit (Attempt 1)

 26%|██▋       | 53/200 [06:47<14:41,  6.00s/it]

✅ [Row 56] Gemini Received: {
  "reasoning": "Text A shares multiple core narrative elements with the Anchor. Both involve a pro...
🚀 [Row 56] GPT: Sending request...

 26%|██▋       | 53/200 [06:48<14:41,  6.00s/it]

✅ [Row 55] GPT Received: {
  "reasoning": "The Anchor story revolves around a train robbery, a hidden stash of gold, and the ...
🚀 [Row 55] Claude: Sending request...

 26%|██▋       | 53/200 [06:48<14:41,  6.00s/it]

⏳ [Row 119] Gemini: Rate limit (Attempt 1)

 26%|██▋       | 53/200 [06:49<14:41,  6.00s/it]

⏳ [Row 121] Gemini: Rate limit (Attempt 2)

 26%|██▋       | 53/200 [06:50<14:41,  6.00s/it]

🚀 [Row 54] GPT: Sending request...

 26%|██▋       | 53/200 [06:50<14:41,  6.00s/it]

⏳ [Row 53] Gemini: Rate limit (Attempt 3)
✅ [Row 56] GPT Received: {
  "reasoning": "The Anchor story involves a sailor returning to his home city, reconnecting with a...
🚀 [Row 56] Claude: Sending request...

✅ [Row 117] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B share some superficial elements with the Anchor (cr...
🏁 [Row 117] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 122] Gemini: Sending request...

 26%|██▋       | 53/200 [06:53<14:41,  6.00s/it]

⏳ [Row 119] Gemini: Rate limit (Attempt 2)

 26%|██▋       | 53/200 [06:54<14:41,  6.00s/it]

✅ [Row 54] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve a protagonist who is on the run and dealin...
🚀 [Row 54] Claude: Sending request...
✅ [Row 120] Gemini Received: {
  "reasoning": "The Anchor text features real-world violence resulting from a profound misundersta...
🚀 [Row 120] GPT: Sending request...

 26%|██▋       | 53/200 [06:55<14:41,  6.00s/it]

⏳ [Row 121] Gemini: Rate limit (Attempt 3)

 27%|██▋       | 54/200 [06:56<23:10,  9.53s/it]

✅ [Row 55] Claude Received: ```json
{
  "reasoning": "Both texts involve criminals and pursuit, but Text B is narratively closer...
🏁 [Row 55] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 57] Gemini: Sending request...

 27%|██▋       | 54/200 [06:56<23:10,  9.53s/it]

🚀 [Row 53] GPT: Sending request...
⏳ [Row 57] Gemini: Rate limit (Attempt 1)

 27%|██▋       | 54/200 [06:58<23:10,  9.53s/it]

⏳ [Row 122] Gemini: Rate limit (Attempt 1)

 27%|██▋       | 54/200 [06:58<23:10,  9.53s/it]

⏳ [Row 119] Gemini: Rate limit (Attempt 3)

 27%|██▋       | 54/200 [06:59<23:10,  9.53s/it]

✅ [Row 120] GPT Received: {
  "reasoning": "The Anchor story revolves around a stunt coordinator who decides to stay in Peru a...
🚀 [Row 120] Claude: Sending request...

 27%|██▋       | 54/200 [06:59<23:10,  9.53s/it]

✅ [Row 53] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve themes of infidelity, unexpected pregnanc...
🚀 [Row 53] Claude: Sending request...

 27%|██▋       | 54/200 [07:00<23:10,  9.53s/it]

⏳ [Row 57] Gemini: Rate limit (Attempt 2)
✅ [Row 56] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve a protagonist returning to their homeland a...

 28%|██▊       | 55/200 [07:00<19:16,  7.98s/it]

🏁 [Row 56] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 58] Gemini: Sending request...

 28%|██▊       | 55/200 [07:00<19:16,  7.98s/it]

❌ [Row 58] Gemini Exception: 'candidates'

 28%|██▊       | 55/200 [07:01<19:16,  7.98s/it]

🚀 [Row 121] GPT: Sending request...

 28%|██▊       | 55/200 [07:02<19:16,  7.98s/it]

❌ [Row 58] Gemini Exception: 'candidates'

 28%|██▊       | 55/200 [07:03<19:16,  7.98s/it]

❌ [Row 58] Gemini Exception: 'candidates'

 28%|██▊       | 56/200 [07:03<15:47,  6.58s/it]

✅ [Row 54] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a linear descent narrative: a man seeks work, faces rej...
🏁 [Row 54] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 59] Gemini: Sending request...

 28%|██▊       | 56/200 [07:04<15:47,  6.58s/it]

🚀 [Row 58] GPT: Sending request...

 28%|██▊       | 56/200 [07:04<15:47,  6.58s/it]

🚀 [Row 119] GPT: Sending request...

 28%|██▊       | 56/200 [07:05<15:47,  6.58s/it]

✅ [Row 121] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, secrets, and revisiting past rela...
🚀 [Row 121] Claude: Sending request...

 28%|██▊       | 56/200 [07:07<15:47,  6.58s/it]

✅ [Row 122] Gemini Received: {
  "reasoning": "The Anchor text describes a sequence of events leading to an attempted invasion (N...
🚀 [Row 122] GPT: Sending request...

 28%|██▊       | 57/200 [07:08<14:02,  5.89s/it]

✅ [Row 53] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic entanglements and pregnancy complications, but...
🏁 [Row 53] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 60] Gemini: Sending request...

 28%|██▊       | 57/200 [07:08<14:02,  5.89s/it]

✅ [Row 58] GPT Received: {
  "reasoning": "The Anchor text revolves around an experiment involving telepathic abilities devel...
🚀 [Row 58] Claude: Sending request...

 28%|██▊       | 57/200 [07:09<14:02,  5.89s/it]

✅ [Row 119] GPT Received: {
  "reasoning": "The Anchor story involves themes of intelligence, terrorism, and bioterrorism, wit...
🚀 [Row 119] Claude: Sending request...
✅ [Row 120] Claude Received: ```json
{
  "reasoning": "The Anchor is about a movie stunt coordinator who witnesses the blurring o...
🏁 [Row 120] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 123] Gemini: Sending request...

 28%|██▊       | 57/200 [07:11<14:02,  5.89s/it]

✅ [Row 122] GPT Received: {
  "reasoning": "The Anchor text focuses on the events leading up to and during the invasion of Nor...
🚀 [Row 122] Claude: Sending request...

 28%|██▊       | 57/200 [07:12<14:02,  5.89s/it]

✅ [Row 121] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a woman who keeps a major secret (not revealing thei...
🏁 [Row 121] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 124] Gemini: Sending request...

 28%|██▊       | 57/200 [07:14<14:02,  5.89s/it]

✅ [Row 59] Gemini Received: {
  "reasoning": "The Anchor story features a young woman seemingly possessed by her serial killer f...
🚀 [Row 59] GPT: Sending request...

 28%|██▊       | 57/200 [07:14<14:02,  5.89s/it]

✅ [Row 57] Gemini Received: {
  "reasoning": "Both the Anchor text and Text B share the core narrative of a protagonist leaving ...
🚀 [Row 57] GPT: Sending request...

 28%|██▊       | 57/200 [07:16<14:02,  5.89s/it]

⏳ [Row 123] Gemini: Rate limit (Attempt 1)

 29%|██▉       | 58/200 [07:18<16:46,  7.09s/it]

✅ [Row 119] Claude Received: ```json
{
  "reasoning": "The Anchor is a spy thriller involving an intelligence agent investigating...
🏁 [Row 119] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 125] Gemini: Sending request...
✅ [Row 58] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an experimental program where volunteers develop tel...
🏁 [Row 58] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 61] Gemini: Sending request...

 29%|██▉       | 58/200 [07:18<16:46,  7.09s/it]

✅ [Row 57] GPT Received: {
  "reasoning": "The Anchor story revolves around Hüseyin, who moves from a village to a big city, ...
🚀 [Row 57] Claude: Sending request...

 29%|██▉       | 58/200 [07:19<16:46,  7.09s/it]

✅ [Row 122] Claude Received: ```json
{
  "reasoning": "The Anchor text describes a sequence of escalating military and political ...
🏁 [Row 122] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 126] Gemini: Sending request...

 29%|██▉       | 58/200 [07:20<16:46,  7.09s/it]

✅ [Row 59] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of inherited violence, psychological posses...
🚀 [Row 59] Claude: Sending request...

 29%|██▉       | 58/200 [07:20<16:46,  7.09s/it]

⏳ [Row 123] Gemini: Rate limit (Attempt 2)

 29%|██▉       | 58/200 [07:24<16:46,  7.09s/it]

✅ [Row 61] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B prominently...
🚀 [Row 61] GPT: Sending request...

 30%|██▉       | 59/200 [07:25<17:11,  7.32s/it]

✅ [Row 57] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve protagonists leaving their home environment...
🏁 [Row 57] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 62] Gemini: Sending request...

 30%|██▉       | 59/200 [07:26<17:11,  7.32s/it]

✅ [Row 125] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature an ...
🚀 [Row 125] GPT: Sending request...

 30%|██▉       | 59/200 [07:26<17:11,  7.32s/it]

✅ [Row 60] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 60] GPT: Sending request...

 30%|██▉       | 59/200 [07:27<17:11,  7.32s/it]

⏳ [Row 123] Gemini: Rate limit (Attempt 3)

 30%|██▉       | 59/200 [07:27<17:11,  7.32s/it]

✅ [Row 61] GPT Received: {
  "reasoning": "The Anchor story involves an expedition team discovering gold, leading to kidnappi...
🚀 [Row 61] Claude: Sending request...

 30%|███       | 60/200 [07:29<14:39,  6.28s/it]

✅ [Row 59] Claude Received: ```json
{
  "reasoning": "The Anchor is about a woman possessed by her serial killer father's spirit...
🏁 [Row 59] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 63] Gemini: Sending request...

 30%|███       | 60/200 [07:30<14:39,  6.28s/it]

⏳ [Row 62] Gemini: Rate limit (Attempt 1)

 30%|███       | 60/200 [07:31<14:39,  6.28s/it]

✅ [Row 126] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor deals with complex romantic...
🚀 [Row 126] GPT: Sending request...
✅ [Row 125] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve isolated communities with genetic mutatio...
🚀 [Row 125] Claude: Sending request...

 30%|███       | 60/200 [07:32<14:39,  6.28s/it]

✅ [Row 60] GPT Received: {
  "reasoning": "The Anchor story revolves around a high school student, Kevin, who gains psychokin...
🚀 [Row 60] Claude: Sending request...

 30%|███       | 60/200 [07:33<14:39,  6.28s/it]

🚀 [Row 123] GPT: Sending request...

 30%|███       | 60/200 [07:34<14:39,  6.28s/it]

✅ [Row 126] GPT Received: {
  "reasoning": "The Anchor story revolves around two brothers in love with the same woman, leading...
🚀 [Row 126] Claude: Sending request...

 30%|███       | 60/200 [07:36<14:39,  6.28s/it]

✅ [Row 123] GPT Received: {
  "reasoning": "The Anchor story and Text A both revolve around characters from working-class back...
🚀 [Row 123] Claude: Sending request...

 30%|███       | 61/200 [07:37<15:17,  6.60s/it]

✅ [Row 61] Claude Received: ```json
{
  "reasoning": "The Anchor centers on villains discovering gold, kidnapping Jane and Boy t...
🏁 [Row 61] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 64] Gemini: Sending request...

 30%|███       | 61/200 [07:40<15:17,  6.60s/it]

✅ [Row 125] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a couple discovering a dark family secret involving ...
🏁 [Row 125] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 127] Gemini: Sending request...

 31%|███       | 62/200 [07:41<13:39,  5.94s/it]

✅ [Row 60] Claude Received: ```json
{
  "reasoning": "The Anchor follows Kevin, an unpopular student who gains supernatural powe...
🏁 [Row 60] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 65] Gemini: Sending request...

 31%|███       | 62/200 [07:42<13:39,  5.94s/it]

❌ [Row 124] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 31%|███       | 62/200 [07:43<13:39,  5.94s/it]

✅ [Row 126] Claude Received: ```json
{
  "reasoning": "The Anchor is fundamentally about a love triangle between two brothers and...
🏁 [Row 126] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 128] Gemini: Sending request...

 31%|███       | 62/200 [07:44<13:39,  5.94s/it]

⏳ [Row 63] Gemini: Rate limit (Attempt 1)
⏳ [Row 128] Gemini: Rate limit (Attempt 1)

 31%|███       | 62/200 [07:47<13:39,  5.94s/it]

⏳ [Row 128] Gemini: Rate limit (Attempt 2)

 31%|███       | 62/200 [07:48<13:39,  5.94s/it]

⏳ [Row 63] Gemini: Rate limit (Attempt 2)

 31%|███       | 62/200 [07:49<13:39,  5.94s/it]

✅ [Row 123] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a teenager (Krimo) who joins a theatrical production...
🏁 [Row 123] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 129] Gemini: Sending request...

 31%|███       | 62/200 [07:49<13:39,  5.94s/it]

✅ [Row 127] Gemini Received: {
  "reasoning": "The Anchor text features a multi-layered narrative of a family summer holiday invo...
🚀 [Row 127] GPT: Sending request...

 31%|███       | 62/200 [07:50<13:39,  5.94s/it]

✅ [Row 64] Gemini Received: {
  "reasoning": "The Anchor story centers on a U.S. Marshal whose sons become involved in a bank ro...
🚀 [Row 64] GPT: Sending request...

 31%|███       | 62/200 [07:53<13:39,  5.94s/it]

✅ [Row 65] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 65] GPT: Sending request...

 31%|███       | 62/200 [07:53<13:39,  5.94s/it]

✅ [Row 127] GPT Received: {
  "reasoning": "The Anchor story revolves around a summer holiday at a family house on the Côte d'...
🚀 [Row 127] Claude: Sending request...
✅ [Row 124] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 124] GPT: Sending request...

 31%|███       | 62/200 [07:53<13:39,  5.94s/it]

✅ [Row 62] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both texts feature a group of friends/...
🚀 [Row 62] GPT: Sending request...

 31%|███       | 62/200 [07:54<13:39,  5.94s/it]

✅ [Row 64] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of crime, family loyalty, and redemption, ...
🚀 [Row 64] Claude: Sending request...

 31%|███       | 62/200 [07:56<13:39,  5.94s/it]

⏳ [Row 128] Gemini: Rate limit (Attempt 3)

 31%|███       | 62/200 [07:58<13:39,  5.94s/it]

✅ [Row 124] GPT Received: {
  "reasoning": "The Anchor story revolves around Rick's search for meaning and a stable relationsh...
🚀 [Row 124] Claude: Sending request...
✅ [Row 62] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a group of individuals coming together to ...
🚀 [Row 62] Claude: Sending request...
✅ [Row 65] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of infidelity, emotional turmoil, and the ...
🚀 [Row 65] Claude: Sending request...

 31%|███       | 62/200 [08:03<13:39,  5.94s/it]

✅ [Row 63] Gemini Received: {
  "reasoning": "The Anchor text describes a desperate and ultimately tragic affair stemming from a...
🚀 [Row 63] GPT: Sending request...
🚀 [Row 128] GPT: Sending request...

 31%|███       | 62/200 [08:04<13:39,  5.94s/it]

✅ [Row 129] Gemini Received: {
  "reasoning": "The Anchor text's core narrative revolves around a love triangle complicated by mi...
🚀 [Row 129] GPT: Sending request...
✅ [Row 127] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a family's summer holiday at an inherited house wher...
🏁 [Row 127] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 130] Gemini: Sending request...

 32%|███▏      | 63/200 [08:04<25:16, 11.07s/it]

✅ [Row 64] Claude Received: ```json
{
  "reasoning": "Both texts involve lawmen pursuing criminals, but Text A is narratively mu...
🏁 [Row 64] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 66] Gemini: Sending request...
⏳ [Row 130] Gemini: Rate limit (Attempt 1)

 32%|███▏      | 63/200 [08:05<25:16, 11.07s/it]

✅ [Row 124] Claude Received: ```json
{
  "reasoning": "Both texts share the anchor's core theme of a young man engaged in small-s...
🏁 [Row 124] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 131] Gemini: Sending request...

 32%|███▏      | 64/200 [08:06<19:00,  8.39s/it]

✅ [Row 65] Claude Received: ```json
{
  "reasoning": "The Anchor is about a man (Max) who has a happy marriage but commits infid...
🏁 [Row 65] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 67] Gemini: Sending request...

 32%|███▎      | 65/200 [08:07<13:22,  5.94s/it]

✅ [Row 62] Claude Received: ```json
{
  "reasoning": "The Anchor is about two friends who lose their jobs and start a music vide...
🏁 [Row 62] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 68] Gemini: Sending request...
✅ [Row 128] GPT Received: {
  "reasoning": "The Anchor story involves a ghost trying to reunite a divorcing couple to gain ent...
🚀 [Row 128] Claude: Sending request...

 32%|███▎      | 65/200 [08:07<13:22,  5.94s/it]

✅ [Row 63] GPT Received: {
  "reasoning": "The Anchor story revolves around a tragic affair between Petulia and Archie, set a...
🚀 [Row 63] Claude: Sending request...

 32%|███▎      | 65/200 [08:08<13:22,  5.94s/it]

✅ [Row 129] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of identity, familial conflict, and romant...
🚀 [Row 129] Claude: Sending request...

 32%|███▎      | 65/200 [08:14<13:22,  5.94s/it]

✅ [Row 131] Gemini Received: {
  "reasoning": "The Anchor text centers on a family defending their land/business from a powerful ...
🚀 [Row 131] GPT: Sending request...

 33%|███▎      | 66/200 [08:16<15:17,  6.85s/it]

✅ [Row 63] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an affair between two people escaping troubled marri...
🏁 [Row 63] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 69] Gemini: Sending request...
✅ [Row 128] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a ghost (Marion) who must perform a good deed on Ear...
🏁 [Row 128] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 132] Gemini: Sending request...

 33%|███▎      | 66/200 [08:16<15:17,  6.85s/it]

✅ [Row 67] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 67] GPT: Sending request...

 33%|███▎      | 66/200 [08:16<15:17,  6.85s/it]

✅ [Row 66] Gemini Received: {
  "reasoning": "The Anchor text describes the flight, capture, and execution of a dictator (Mussol...
🚀 [Row 66] GPT: Sending request...

 33%|███▎      | 66/200 [08:17<15:17,  6.85s/it]

✅ [Row 68] Gemini Received: {
  "reasoning": "Both the Anchor and Text B depict a male protagonist, once prominent (Tolstoy as a...
🚀 [Row 68] GPT: Sending request...

 33%|███▎      | 66/200 [08:17<15:17,  6.85s/it]

✅ [Row 130] Gemini Received: {
  "reasoning": "The Anchor text features protagonists forming an unlikely trio and being pursued b...
🚀 [Row 130] GPT: Sending request...

 33%|███▎      | 66/200 [08:18<15:17,  6.85s/it]

✅ [Row 129] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around twin sisters (one conservative, one bohemian) u...
🏁 [Row 129] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 133] Gemini: Sending request...

 33%|███▎      | 66/200 [08:19<15:17,  6.85s/it]

✅ [Row 131] GPT Received: {
  "reasoning": "The Anchor story involves a family in the winemaking business in conflict with a p...
🚀 [Row 131] Claude: Sending request...

 33%|███▎      | 66/200 [08:21<15:17,  6.85s/it]

✅ [Row 67] GPT Received: {
  "reasoning": "The Anchor story focuses on Max, a former burglar and talented tap dancer, who mus...
🚀 [Row 67] Claude: Sending request...
✅ [Row 66] GPT Received: {
  "reasoning": "The Anchor text focuses on Mussolini's final days, his attempt to escape, and his ...
🚀 [Row 66] Claude: Sending request...

 33%|███▎      | 66/200 [08:21<15:17,  6.85s/it]

✅ [Row 68] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a central character dealing with a moral a...
🚀 [Row 68] Claude: Sending request...

 33%|███▎      | 66/200 [08:21<15:17,  6.85s/it]

✅ [Row 130] GPT Received: {
  "reasoning": "The Anchor story involves genetically engineered creatures, a former soldier, and ...
🚀 [Row 130] Claude: Sending request...

 33%|███▎      | 66/200 [08:25<15:17,  6.85s/it]

✅ [Row 132] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor because both stories feature a woman wh...
🚀 [Row 132] GPT: Sending request...
✅ [Row 69] Gemini Received: {
  "reasoning": "The Anchor text focuses on the Italian resistance from the perspective of communis...
🚀 [Row 69] GPT: Sending request...

 33%|███▎      | 66/200 [08:26<15:17,  6.85s/it]

✅ [Row 131] Claude Received: ```json
{
  "reasoning": "Both texts share Western genre elements with the Anchor, but Text B is nar...
🏁 [Row 131] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 134] Gemini: Sending request...

 33%|███▎      | 66/200 [08:29<15:17,  6.85s/it]

✅ [Row 132] GPT Received: {
  "reasoning": "The Anchor story revolves around a woman, Ivy, who is dissatisfied with her curren...
🚀 [Row 132] Claude: Sending request...

 34%|███▎      | 67/200 [08:29<19:55,  8.99s/it]

✅ [Row 68] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an elderly, celebrated figure (Tolstoy) who is overw...
🏁 [Row 68] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 70] Gemini: Sending request...

 34%|███▎      | 67/200 [08:30<19:55,  8.99s/it]

✅ [Row 69] GPT Received: {
  "reasoning": "The Anchor text focuses on the Italian resistance during WWII from the perspective...
🚀 [Row 69] Claude: Sending request...

 34%|███▎      | 67/200 [08:30<19:55,  8.99s/it]

⏳ [Row 70] Gemini: Rate limit (Attempt 1)

 34%|███▍      | 68/200 [08:31<14:37,  6.65s/it]

✅ [Row 130] Claude Received: ```json
{
  "reasoning": "The Anchor involves genetically engineered creatures escaping from a gover...
🏁 [Row 130] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 135] Gemini: Sending request...
✅ [Row 66] Claude Received: ```json
{
  "reasoning": "The Anchor is about a specific historical figure (Mussolini) at the end of...
🏁 [Row 66] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 71] Gemini: Sending request...

 34%|███▍      | 69/200 [08:32<10:47,  4.94s/it]

✅ [Row 67] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on Max, an ex-convict and talented tap dancer who...
🏁 [Row 67] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 72] Gemini: Sending request...

 34%|███▍      | 69/200 [08:35<10:47,  4.94s/it]

✅ [Row 134] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share the c...
🚀 [Row 134] GPT: Sending request...

 34%|███▍      | 69/200 [08:36<10:47,  4.94s/it]

✅ [Row 132] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic triangles and dark outcomes, but Text A is nar...
🏁 [Row 132] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 136] Gemini: Sending request...

 35%|███▌      | 70/200 [08:38<11:23,  5.25s/it]

✅ [Row 133] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature pro...
🚀 [Row 133] GPT: Sending request...
✅ [Row 69] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on women's emancipation through their participation in ...
🏁 [Row 69] Votes: {'gemini': True, 'gpt': False, 'claude': False}
✅ [Row 71] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both stories feature a male figure in ...
🚀 [Row 73] Gemini: Sending request...
🚀 [Row 71] GPT: Sending request...

 35%|███▌      | 70/200 [08:38<11:23,  5.25s/it]

✅ [Row 134] GPT Received: {
  "reasoning": "The Anchor story involves a mysterious death connected to family secrets and a pas...
🚀 [Row 134] Claude: Sending request...

 35%|███▌      | 70/200 [08:39<11:23,  5.25s/it]

⏳ [Row 135] Gemini: Rate limit (Attempt 1)

 35%|███▌      | 70/200 [08:41<11:23,  5.25s/it]

✅ [Row 133] GPT Received: {
  "reasoning": "The Anchor story involves a law enforcement officer, Inspector Rizzo, who deals wi...
🚀 [Row 133] Claude: Sending request...

 35%|███▌      | 70/200 [08:42<11:23,  5.25s/it]

✅ [Row 71] GPT Received: {
  "reasoning": "The Anchor story revolves around a British diplomat in an African nation dealing w...
🚀 [Row 71] Claude: Sending request...

 35%|███▌      | 70/200 [08:44<11:23,  5.25s/it]

✅ [Row 70] Gemini Received: {
  "reasoning": "Text A is a murder mystery involving missing money and dangerous people, which has...
🚀 [Row 70] GPT: Sending request...

 35%|███▌      | 70/200 [08:46<11:23,  5.25s/it]

✅ [Row 72] Gemini Received: {
  "reasoning": "Both the Anchor and Text B are set in a high school environment where students (an...
🚀 [Row 72] GPT: Sending request...

 35%|███▌      | 70/200 [08:48<11:23,  5.25s/it]

✅ [Row 134] Claude Received: ```json
{
  "reasoning": "Both texts involve a young woman's death and subsequent investigation, but...
🏁 [Row 134] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 137] Gemini: Sending request...
⏳ [Row 135] Gemini: Rate limit (Attempt 2)

 35%|███▌      | 70/200 [08:49<11:23,  5.25s/it]

✅ [Row 70] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle, with a focus on a man's past rel...
🚀 [Row 70] Claude: Sending request...

 36%|███▌      | 71/200 [08:50<16:05,  7.49s/it]

✅ [Row 72] GPT Received: {
  "reasoning": "The Anchor story revolves around a boarding school where students are turned into ...
🚀 [Row 72] Claude: Sending request...
✅ [Row 133] Claude Received: ```json
{
  "reasoning": "The Anchor follows Inspector Rizzo (Flatfoot), a law enforcement officer w...
🏁 [Row 133] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 138] Gemini: Sending request...
✅ [Row 71] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a British diplomat in a newly independent African na...
🏁 [Row 71] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 74] Gemini: Sending request...

 36%|███▌      | 71/200 [08:53<16:05,  7.49s/it]

✅ [Row 73] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature pro...
🚀 [Row 73] GPT: Sending request...

 36%|███▌      | 71/200 [08:56<16:05,  7.49s/it]

⏳ [Row 74] Gemini: Rate limit (Attempt 1)

 36%|███▌      | 71/200 [08:57<16:05,  7.49s/it]

✅ [Row 137] Gemini Received: {
  "reasoning": "The Anchor text centers on an illegal enterprise (baby selling) run by its protago...
🚀 [Row 137] GPT: Sending request...
✅ [Row 73] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of crime, betrayal, and familial conflict,...
🚀 [Row 73] Claude: Sending request...

 36%|███▌      | 72/200 [08:59<16:31,  7.74s/it]

✅ [Row 70] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a man (Ryno) torn between his past lover (La Vellini...
🏁 [Row 70] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 75] Gemini: Sending request...

 36%|███▋      | 73/200 [08:59<11:46,  5.56s/it]

✅ [Row 72] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a teenage girl at a boarding school where facu...
🏁 [Row 72] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 76] Gemini: Sending request...

 36%|███▋      | 73/200 [09:00<11:46,  5.56s/it]

✅ [Row 137] GPT Received: {
  "reasoning": "The Anchor story revolves around illegal activities involving baby trafficking, a ...
🚀 [Row 137] Claude: Sending request...

 37%|███▋      | 74/200 [09:05<12:02,  5.73s/it]

✅ [Row 73] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two brothers caught on opposite sides of organized c...
🏁 [Row 73] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 77] Gemini: Sending request...

 37%|███▋      | 74/200 [09:06<12:02,  5.73s/it]

❌ [Row 136] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 37%|███▋      | 74/200 [09:08<12:02,  5.73s/it]

⏳ [Row 76] Gemini: Rate limit (Attempt 1)

 37%|███▋      | 74/200 [09:09<12:02,  5.73s/it]

✅ [Row 137] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a baby-selling scheme where the criminals take ...
🏁 [Row 137] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 139] Gemini: Sending request...

 37%|███▋      | 74/200 [09:09<12:02,  5.73s/it]

⏳ [Row 138] Gemini: Rate limit (Attempt 1)

 37%|███▋      | 74/200 [09:12<12:02,  5.73s/it]

⏳ [Row 139] Gemini: Rate limit (Attempt 1)

 37%|███▋      | 74/200 [09:12<12:02,  5.73s/it]

⏳ [Row 138] Gemini: Rate limit (Attempt 2)

 37%|███▋      | 74/200 [09:13<12:02,  5.73s/it]

✅ [Row 74] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 74] GPT: Sending request...

 37%|███▋      | 74/200 [09:16<12:02,  5.73s/it]

✅ [Row 77] Gemini Received: {
  "reasoning": "The Anchor text revolves around the re-opening of past political and personal woun...
🚀 [Row 77] GPT: Sending request...

 37%|███▋      | 74/200 [09:18<12:02,  5.73s/it]

✅ [Row 74] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of memory, identity, and vengeance, with a ...
🚀 [Row 74] Claude: Sending request...

 37%|███▋      | 74/200 [09:20<12:02,  5.73s/it]

✅ [Row 75] Gemini Received: {
  "reasoning": "The Anchor text centers on Paul's temptation to commit adultery, learning about it...
🚀 [Row 75] GPT: Sending request...

 37%|███▋      | 74/200 [09:20<12:02,  5.73s/it]

✅ [Row 77] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of political activism, unresolved conflicts...
🚀 [Row 77] Claude: Sending request...

 37%|███▋      | 74/200 [09:22<12:02,  5.73s/it]

❌ [Row 135] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 37%|███▋      | 74/200 [09:23<12:02,  5.73s/it]

🚀 [Row 135] GPT: Sending request...

 37%|███▋      | 74/200 [09:24<12:02,  5.73s/it]

✅ [Row 75] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of infidelity, temptation, and ultimately ...
🚀 [Row 75] Claude: Sending request...

 38%|███▊      | 75/200 [09:27<21:47, 10.46s/it]

✅ [Row 74] Claude Received: ```json
{
  "reasoning": "Both texts involve revenge narratives, but Text B is narratively closer to...
🏁 [Row 74] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 78] Gemini: Sending request...

 38%|███▊      | 75/200 [09:28<21:47, 10.46s/it]

✅ [Row 139] Gemini Received: {
  "reasoning": "The Anchor text describes a simple man who is exploited and then used as a 'puppet...
🚀 [Row 139] GPT: Sending request...

 38%|███▊      | 75/200 [09:29<21:47, 10.46s/it]

✅ [Row 76] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B prominently...
🚀 [Row 76] GPT: Sending request...

 38%|███▊      | 76/200 [09:31<17:35,  8.51s/it]

✅ [Row 77] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a 1960 wedding disrupted by uninvited guests who for...
🏁 [Row 77] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 79] Gemini: Sending request...

 38%|███▊      | 76/200 [09:31<17:35,  8.51s/it]

⏳ [Row 138] Gemini: Rate limit (Attempt 3)
✅ [Row 135] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of breaking societal norms, self-discovery...
🚀 [Row 135] Claude: Sending request...

 38%|███▊      | 77/200 [09:32<13:03,  6.37s/it]

✅ [Row 75] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a man (Paul) who is tempted by adultery after learni...
🏁 [Row 75] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 80] Gemini: Sending request...

 38%|███▊      | 77/200 [09:33<13:03,  6.37s/it]

✅ [Row 139] GPT Received: {
  "reasoning": "The Anchor story involves themes of betrayal, political manipulation, and rebellio...
🚀 [Row 139] Claude: Sending request...

 38%|███▊      | 77/200 [09:34<13:03,  6.37s/it]

✅ [Row 76] GPT Received: {
  "reasoning": "The Anchor text revolves around a group of friends attending a funeral and dealing...
🚀 [Row 76] Claude: Sending request...

 38%|███▊      | 77/200 [09:37<13:03,  6.37s/it]

🚀 [Row 138] GPT: Sending request...

 38%|███▊      | 77/200 [09:37<13:03,  6.37s/it]

❌ [Row 136] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 38%|███▊      | 77/200 [09:40<13:03,  6.37s/it]

✅ [Row 135] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Carmen breaking from her predetermined Romani commun...
🏁 [Row 135] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 140] Gemini: Sending request...

 38%|███▊      | 77/200 [09:41<13:03,  6.37s/it]

✅ [Row 79] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B center...
🚀 [Row 79] GPT: Sending request...

 39%|███▉      | 78/200 [09:41<14:37,  7.19s/it]

✅ [Row 76] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a group of friends traveling to and attending a...
🏁 [Row 76] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 81] Gemini: Sending request...

 39%|███▉      | 78/200 [09:42<14:37,  7.19s/it]

✅ [Row 138] GPT Received: {
  "reasoning": "The Anchor text revolves around Jacques Ménétrier's journey from a humble backgrou...
🚀 [Row 138] Claude: Sending request...

 39%|███▉      | 78/200 [09:42<14:37,  7.19s/it]

✅ [Row 78] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B involve pro...
🚀 [Row 78] GPT: Sending request...

 39%|███▉      | 78/200 [09:43<14:37,  7.19s/it]

✅ [Row 139] Claude Received: ```json
{
  "reasoning": "The Anchor follows a simple man who is wronged, escapes, joins a resistanc...
🏁 [Row 139] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 141] Gemini: Sending request...

 39%|███▉      | 78/200 [09:45<14:37,  7.19s/it]

⏳ [Row 136] Gemini: Rate limit (Attempt 3)

 39%|███▉      | 78/200 [09:45<14:37,  7.19s/it]

✅ [Row 79] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of revenge, misunderstanding, and the cons...
🚀 [Row 79] Claude: Sending request...

 39%|███▉      | 78/200 [09:47<14:37,  7.19s/it]

✅ [Row 78] GPT Received: {
  "reasoning": "The Anchor story revolves around a group known for extreme Truth or Dare videos, w...
🚀 [Row 78] Claude: Sending request...

 39%|███▉      | 78/200 [09:48<14:37,  7.19s/it]

⏳ [Row 141] Gemini: Rate limit (Attempt 1)

 39%|███▉      | 78/200 [09:48<14:37,  7.19s/it]

✅ [Row 140] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center arou...
🚀 [Row 140] GPT: Sending request...

 39%|███▉      | 78/200 [09:51<14:37,  7.19s/it]

🚀 [Row 136] GPT: Sending request...
⏳ [Row 141] Gemini: Rate limit (Attempt 2)

 39%|███▉      | 78/200 [09:52<14:37,  7.19s/it]

✅ [Row 138] Claude Received: ```json
{
  "reasoning": "The Anchor follows Jacques, a spit-turner who is educated by Abbot Jérôme ...
🏁 [Row 138] Votes: {'gemini': None, 'gpt': True, 'claude': False}
🚀 [Row 142] Gemini: Sending request...
✅ [Row 140] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve military and strategic conflicts over con...
🚀 [Row 140] Claude: Sending request...

 39%|███▉      | 78/200 [09:54<14:37,  7.19s/it]

⏳ [Row 142] Gemini: Rate limit (Attempt 1)
✅ [Row 136] GPT Received: {
  "reasoning": "The Anchor story involves a hospital setting, a foreign leader under threat, a kid...
🚀 [Row 136] Claude: Sending request...

 39%|███▉      | 78/200 [09:54<14:37,  7.19s/it]

✅ [Row 81] Gemini Received: {
  "reasoning": "The Anchor text depicts the life of an aging, master painter deeply dedicated to h...
🚀 [Row 81] GPT: Sending request...

 40%|███▉      | 79/200 [09:55<18:50,  9.34s/it]

✅ [Row 79] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a daughter seeking vengeance for her mother's r...
🏁 [Row 79] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 82] Gemini: Sending request...

 40%|███▉      | 79/200 [09:57<18:50,  9.34s/it]

⏳ [Row 142] Gemini: Rate limit (Attempt 2)

 40%|████      | 80/200 [09:57<14:13,  7.11s/it]

✅ [Row 78] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a YouTube group that performs extreme truth-or-dare ...
🏁 [Row 78] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 83] Gemini: Sending request...

 40%|████      | 80/200 [09:58<14:13,  7.11s/it]

⏳ [Row 141] Gemini: Rate limit (Attempt 3)

 40%|████      | 80/200 [09:59<14:13,  7.11s/it]

✅ [Row 81] GPT Received: {
  "reasoning": "The Anchor text focuses on the last years of J. M. W. Turner's life, highlighting ...
🚀 [Row 81] Claude: Sending request...

 40%|████      | 80/200 [09:59<14:13,  7.11s/it]

⏳ [Row 83] Gemini: Rate limit (Attempt 1)

 40%|████      | 80/200 [10:01<14:13,  7.11s/it]

✅ [Row 140] Claude Received: ```json
{
  "reasoning": "The Anchor involves a colonial-era engineering project (flooding the Sahar...
🏁 [Row 140] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 143] Gemini: Sending request...

 40%|████      | 80/200 [10:02<14:13,  7.11s/it]

❌ [Row 80] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)
✅ [Row 136] Claude Received: {
  "reasoning": "The Anchor centers on a male nurse (Hobday) who kidnaps a foreign President from a...
🏁 [Row 136] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 144] Gemini: Sending request...
⏳ [Row 142] Gemini: Rate limit (Attempt 3)

 40%|████      | 80/200 [10:03<14:13,  7.11s/it]

⏳ [Row 144] Gemini: Rate limit (Attempt 1)

 40%|████      | 80/200 [10:04<14:13,  7.11s/it]

🚀 [Row 141] GPT: Sending request...

 40%|████      | 81/200 [10:07<15:28,  7.80s/it]

✅ [Row 81] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on the final decades of painter J.M.W. Turner's life, d...
🏁 [Row 81] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 84] Gemini: Sending request...

 40%|████      | 81/200 [10:08<15:28,  7.80s/it]

🚀 [Row 142] GPT: Sending request...
✅ [Row 141] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of fear of commitment, self-discovery, and...
🚀 [Row 141] Claude: Sending request...

 40%|████      | 81/200 [10:11<15:28,  7.80s/it]

⏳ [Row 143] Gemini: Rate limit (Attempt 1)

 40%|████      | 81/200 [10:12<15:28,  7.80s/it]

✅ [Row 144] Gemini Received: {
  "reasoning": "The Anchor text focuses on a woman's unwavering love for her ex-husband and her st...
🚀 [Row 144] GPT: Sending request...

 40%|████      | 81/200 [10:13<15:28,  7.80s/it]

⏳ [Row 80] Gemini: Rate limit (Attempt 2)
✅ [Row 142] GPT Received: {
  "reasoning": "The Anchor story revolves around Marcel Marx, who has given up his previous ambiti...
🚀 [Row 142] Claude: Sending request...

 40%|████      | 81/200 [10:15<15:28,  7.80s/it]

⏳ [Row 82] Gemini: Rate limit (Attempt 1)

 40%|████      | 81/200 [10:16<15:28,  7.80s/it]

✅ [Row 83] Gemini Received: {
  "reasoning": "Text A shares the abstract theme of a protagonist involved with law enforcement (f...
🚀 [Row 83] GPT: Sending request...
✅ [Row 144] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of unrequited love, family dynamics, and t...
🚀 [Row 144] Claude: Sending request...
✅ [Row 141] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on characters who struggle with emotional commitment an...
🏁 [Row 141] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 145] Gemini: Sending request...

 40%|████      | 81/200 [10:17<15:28,  7.80s/it]

⏳ [Row 145] Gemini: Rate limit (Attempt 1)

 40%|████      | 81/200 [10:19<15:28,  7.80s/it]

✅ [Row 84] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 84] GPT: Sending request...

 40%|████      | 81/200 [10:20<15:28,  7.80s/it]

✅ [Row 83] GPT Received: {
  "reasoning": "The Anchor story involves a detective unraveling a complex web of crime involving ...
🚀 [Row 83] Claude: Sending request...

 40%|████      | 81/200 [10:21<15:28,  7.80s/it]

✅ [Row 143] Gemini Received: {
  "reasoning": "The Anchor text describes a fictional narrative about a protagonist (Blanche) movi...
🚀 [Row 143] GPT: Sending request...

 40%|████      | 81/200 [10:23<15:28,  7.80s/it]

✅ [Row 142] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Marcel, a former writer who has settled into a modes...
🏁 [Row 142] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 146] Gemini: Sending request...

 40%|████      | 81/200 [10:24<15:28,  7.80s/it]

✅ [Row 84] GPT Received: {
  "reasoning": "The Anchor story involves a law student working as a night watchman who becomes em...
🚀 [Row 84] Claude: Sending request...

 40%|████      | 81/200 [10:24<15:28,  7.80s/it]

✅ [Row 144] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Marie-Louise's inability to let go of her ex-husband...
🏁 [Row 144] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 147] Gemini: Sending request...

 40%|████      | 81/200 [10:26<15:28,  7.80s/it]

✅ [Row 145] Gemini Received: {
  "reasoning": "Text B shares a much closer narrative arc with the Anchor text. Both involve chara...
🚀 [Row 145] GPT: Sending request...

 40%|████      | 81/200 [10:27<15:28,  7.80s/it]

✅ [Row 143] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of new beginnings, social interactions, an...
🚀 [Row 143] Claude: Sending request...

 40%|████      | 81/200 [10:28<15:28,  7.80s/it]

✅ [Row 80] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A involve pro...
🚀 [Row 80] GPT: Sending request...

 40%|████      | 81/200 [10:30<15:28,  7.80s/it]

✅ [Row 145] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve characters with a criminal background who...
🚀 [Row 145] Claude: Sending request...

 42%|████▏     | 83/200 [10:31<17:29,  8.97s/it]

✅ [Row 83] Claude Received: ```json
{
  "reasoning": "Both texts involve criminal investigations with deception and danger, but ...
🏁 [Row 83] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 85] Gemini: Sending request...
✅ [Row 84] Claude Received: ```json
{
  "reasoning": "The Anchor follows a law student who takes a night watchman job and become...
🏁 [Row 84] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 86] Gemini: Sending request...

 42%|████▏     | 83/200 [10:34<17:29,  8.97s/it]

✅ [Row 80] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist, Steve, who is unwittingly involved in a c...
🚀 [Row 80] Claude: Sending request...
✅ [Row 147] Gemini Received: {
  "reasoning": "The Anchor text explores the conflict between a man's desire for death due to life...
🚀 [Row 147] GPT: Sending request...

 42%|████▏     | 83/200 [10:35<17:29,  8.97s/it]

✅ [Row 146] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B explore the...
🚀 [Row 146] GPT: Sending request...

 42%|████▏     | 83/200 [10:36<17:29,  8.97s/it]

✅ [Row 143] Claude Received: ```json
{
  "reasoning": "The Anchor is a relationship-focused narrative about Blanche navigating ne...
🏁 [Row 143] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 148] Gemini: Sending request...

 42%|████▏     | 83/200 [10:37<17:29,  8.97s/it]

✅ [Row 145] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on two swindlers who go to prison, then after rel...
🏁 [Row 145] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 149] Gemini: Sending request...

 42%|████▏     | 83/200 [10:38<17:29,  8.97s/it]

✅ [Row 146] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a female protagonist facing societal and ...
🚀 [Row 146] Claude: Sending request...

 42%|████▏     | 83/200 [10:40<17:29,  8.97s/it]

✅ [Row 147] GPT Received: {
  "reasoning": "The Anchor text deals with themes of mortality, the afterlife, and the value of li...
🚀 [Row 147] Claude: Sending request...

 42%|████▏     | 83/200 [10:40<17:29,  8.97s/it]

✅ [Row 82] Gemini Received: {
  "reasoning": "Text A focuses on a man committing murder, assuming a new identity, and escaping h...
🚀 [Row 82] GPT: Sending request...

 42%|████▏     | 83/200 [10:42<17:29,  8.97s/it]

✅ [Row 85] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A describe a ...
🚀 [Row 85] GPT: Sending request...

 42%|████▏     | 83/200 [10:44<17:29,  8.97s/it]

✅ [Row 82] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of past relationships, unresolved feelings...
🚀 [Row 82] Claude: Sending request...

 42%|████▏     | 84/200 [10:45<20:02, 10.36s/it]

✅ [Row 80] Claude Received: ```json
{
  "reasoning": "Both texts share significant narrative elements with the Anchor: an ordina...
🏁 [Row 80] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 87] Gemini: Sending request...
✅ [Row 85] GPT Received: {
  "reasoning": "The Anchor text and Text B share a similar abstract theme of survival in a hostile...
🚀 [Row 85] Claude: Sending request...

 42%|████▏     | 84/200 [10:46<20:02, 10.36s/it]

⏳ [Row 86] Gemini: Rate limit (Attempt 1)

 42%|████▏     | 84/200 [10:48<20:02, 10.36s/it]

✅ [Row 146] Claude Received: ```json
{
  "reasoning": "Both texts involve women facing institutional/societal oppression and pote...
🏁 [Row 146] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 150] Gemini: Sending request...

 42%|████▏     | 84/200 [10:49<20:02, 10.36s/it]

✅ [Row 147] Claude Received: ```json
{
  "reasoning": "Both texts deal with mortality and the leveling nature of death, but Text ...
🏁 [Row 147] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 151] Gemini: Sending request...

 42%|████▏     | 84/200 [10:49<20:02, 10.36s/it]

⏳ [Row 86] Gemini: Rate limit (Attempt 2)

 42%|████▏     | 84/200 [10:50<20:02, 10.36s/it]

✅ [Row 149] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A involv...
🚀 [Row 149] GPT: Sending request...

 42%|████▎     | 85/200 [10:54<18:54,  9.87s/it]

✅ [Row 85] Claude Received: ```json
{
  "reasoning": "Both texts share survival elements with the Anchor, but Text A is narrativ...
🏁 [Row 85] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 88] Gemini: Sending request...

 42%|████▎     | 85/200 [10:54<18:54,  9.87s/it]

✅ [Row 87] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature an ...
🚀 [Row 87] GPT: Sending request...
✅ [Row 149] GPT Received: {
  "reasoning": "The Anchor story and Text A both deal with themes of crime, familial relationships...
🚀 [Row 149] Claude: Sending request...

 43%|████▎     | 86/200 [10:54<13:26,  7.08s/it]

✅ [Row 82] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a powerful woman (Agatha) who returns to her alma ma...
🏁 [Row 82] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 89] Gemini: Sending request...

 43%|████▎     | 86/200 [10:54<13:26,  7.08s/it]

✅ [Row 150] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A deeply expl...
🚀 [Row 150] GPT: Sending request...

 43%|████▎     | 86/200 [10:57<13:26,  7.08s/it]

⏳ [Row 148] Gemini: Rate limit (Attempt 1)

 43%|████▎     | 86/200 [10:57<13:26,  7.08s/it]

✅ [Row 87] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a small town facing a crisis due to an un...
🚀 [Row 87] Claude: Sending request...

 43%|████▎     | 86/200 [10:59<13:26,  7.08s/it]

✅ [Row 150] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of friendship, life, and death, with a foc...
🚀 [Row 150] Claude: Sending request...
✅ [Row 151] Gemini Received: {
  "reasoning": "The Anchor text centers around a 'will-they won't-they' romance, implicitly sugges...
🚀 [Row 151] GPT: Sending request...

 43%|████▎     | 86/200 [11:00<13:26,  7.08s/it]

⏳ [Row 88] Gemini: Rate limit (Attempt 1)

 43%|████▎     | 86/200 [11:02<13:26,  7.08s/it]

⏳ [Row 86] Gemini: Rate limit (Attempt 3)

 43%|████▎     | 86/200 [11:03<13:26,  7.08s/it]

✅ [Row 149] Claude Received: ```json
{
  "reasoning": "The Anchor follows Ben, a reformed criminal forced back into crime, who ap...
🏁 [Row 149] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 152] Gemini: Sending request...
⏳ [Row 89] Gemini: Rate limit (Attempt 1)

 43%|████▎     | 86/200 [11:04<13:26,  7.08s/it]

✅ [Row 151] GPT Received: {
  "reasoning": "The Anchor story revolves around a 'Will-they won't-they' romance between a wealth...
🚀 [Row 151] Claude: Sending request...

 43%|████▎     | 86/200 [11:05<13:26,  7.08s/it]

⏳ [Row 88] Gemini: Rate limit (Attempt 2)

 44%|████▎     | 87/200 [11:06<16:09,  8.58s/it]

✅ [Row 150] Claude Received: ```json
{
  "reasoning": "The Anchor is about five best friends gathering after Marta's death to hon...
🏁 [Row 150] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 153] Gemini: Sending request...
✅ [Row 87] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a shark attack mystery in a desert town, where ...
🏁 [Row 87] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 90] Gemini: Sending request...

 44%|████▎     | 87/200 [11:08<16:09,  8.58s/it]

🚀 [Row 86] GPT: Sending request...

 44%|████▎     | 87/200 [11:10<16:09,  8.58s/it]

⏳ [Row 88] Gemini: Rate limit (Attempt 3)
⏳ [Row 153] Gemini: Rate limit (Attempt 1)

 44%|████▎     | 87/200 [11:11<16:09,  8.58s/it]

✅ [Row 148] Gemini Received: {
  "reasoning": "Text A focuses on a supernatural force and its containment through a physical inte...
🚀 [Row 148] GPT: Sending request...

 44%|████▎     | 87/200 [11:11<16:09,  8.58s/it]

✅ [Row 152] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a pri...
🚀 [Row 152] GPT: Sending request...

 44%|████▎     | 87/200 [11:12<16:09,  8.58s/it]

✅ [Row 151] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a will-they-won't-they romance between Jack (wealthy...
🏁 [Row 151] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 154] Gemini: Sending request...

 44%|████▎     | 87/200 [11:13<16:09,  8.58s/it]

❌ [Row 154] Gemini Exception: 'candidates'

 44%|████▎     | 87/200 [11:14<16:09,  8.58s/it]

❌ [Row 154] Gemini Exception: 'candidates'
⏳ [Row 90] Gemini: Rate limit (Attempt 1)

 44%|████▎     | 87/200 [11:14<16:09,  8.58s/it]

⏳ [Row 153] Gemini: Rate limit (Attempt 2)

 44%|████▎     | 87/200 [11:15<16:09,  8.58s/it]

❌ [Row 154] Gemini Exception: 'candidates'

 44%|████▎     | 87/200 [11:16<16:09,  8.58s/it]

✅ [Row 152] GPT Received: {
  "reasoning": "The Anchor text 'Terra Nostra' is a complex narrative set primarily in the 16th ce...
🚀 [Row 152] Claude: Sending request...

 44%|████▎     | 87/200 [11:16<16:09,  8.58s/it]

✅ [Row 86] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of delusion, idealism, and the power of ima...
🚀 [Row 86] Claude: Sending request...
🚀 [Row 88] GPT: Sending request...

 44%|████▎     | 87/200 [11:16<16:09,  8.58s/it]

🚀 [Row 154] GPT: Sending request...

 44%|████▎     | 87/200 [11:17<16:09,  8.58s/it]

✅ [Row 148] GPT Received: {
  "reasoning": "The Anchor text involves a plot by foreign agents to control a country's resources...
🚀 [Row 148] Claude: Sending request...

 44%|████▎     | 87/200 [11:20<16:09,  8.58s/it]

✅ [Row 88] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a journey into the Sahara desert, with a c...
🚀 [Row 88] Claude: Sending request...
✅ [Row 154] GPT Received: {
  "reasoning": "The Anchor text focuses on Layla's journey from facing Islamophobia in Amsterdam t...
🚀 [Row 154] Claude: Sending request...

 44%|████▎     | 87/200 [11:22<16:09,  8.58s/it]

✅ [Row 89] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A feature a protagonist who is imprisoned or living ...
🚀 [Row 89] GPT: Sending request...

 44%|████▎     | 87/200 [11:24<16:09,  8.58s/it]

✅ [Row 148] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a conspiracy by foreign agents using technology (sub...
🏁 [Row 148] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 155] Gemini: Sending request...

 44%|████▍     | 88/200 [11:25<21:33, 11.54s/it]

✅ [Row 86] Claude Received: ```json
{
  "reasoning": "The Anchor story features an artist/writer (Cervantes) imprisoned and awai...
🏁 [Row 86] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 91] Gemini: Sending request...
✅ [Row 153] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a cor...
🚀 [Row 153] GPT: Sending request...

 44%|████▍     | 88/200 [11:27<21:33, 11.54s/it]

✅ [Row 90] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 90] GPT: Sending request...

 44%|████▍     | 88/200 [11:27<21:33, 11.54s/it]

✅ [Row 89] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of cultural preservation and resistance...
🚀 [Row 89] Claude: Sending request...

 44%|████▍     | 88/200 [11:28<21:33, 11.54s/it]

✅ [Row 152] Claude Received: ```json
{
  "reasoning": "The Anchor (Terra Nostra) is an epic, multi-temporal narrative spanning ce...
🏁 [Row 152] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 156] Gemini: Sending request...

 44%|████▍     | 88/200 [11:29<21:33, 11.54s/it]

✅ [Row 153] GPT Received: {
  "reasoning": "The Anchor story revolves around a murder mystery involving the royal family, with...
🚀 [Row 153] Claude: Sending request...
✅ [Row 154] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a young Muslim woman's journey from experiencing dis...
🏁 [Row 154] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 157] Gemini: Sending request...

 44%|████▍     | 89/200 [11:30<18:02,  9.75s/it]

✅ [Row 88] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an American archaeologist in 1920s Africa seeking a ...
🏁 [Row 88] Votes: {'gemini': None, 'gpt': True, 'claude': False}
🚀 [Row 92] Gemini: Sending request...

 44%|████▍     | 89/200 [11:31<18:02,  9.75s/it]

✅ [Row 90] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of family estrangement, identity, and reco...
🚀 [Row 90] Claude: Sending request...

 45%|████▌     | 90/200 [11:36<15:35,  8.51s/it]

✅ [Row 155] Gemini Received: {
  "reasoning": "The Anchor text describes a controversial film about the life of Jesus, 'This Is M...
🚀 [Row 155] GPT: Sending request...
✅ [Row 91] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 91] GPT: Sending request...
✅ [Row 89] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a Korean man imprisoned under Japanese occupation wh...
🏁 [Row 89] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 93] Gemini: Sending request...

 45%|████▌     | 90/200 [11:38<15:35,  8.51s/it]

✅ [Row 156] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature ant...
🚀 [Row 156] GPT: Sending request...

 45%|████▌     | 90/200 [11:39<15:35,  8.51s/it]

✅ [Row 157] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B revolve aro...
🚀 [Row 157] GPT: Sending request...
✅ [Row 153] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a murder accusation where special mind-reading...
🏁 [Row 153] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 158] Gemini: Sending request...

 45%|████▌     | 90/200 [11:40<15:35,  8.51s/it]

✅ [Row 155] GPT Received: {
  "reasoning": "The Anchor text revolves around a film about Jesus that draws controversy due to i...
🚀 [Row 155] Claude: Sending request...

 46%|████▌     | 91/200 [11:40<13:14,  7.29s/it]

✅ [Row 90] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a son who flees his mother's toxic relationship, bui...
🏁 [Row 90] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 94] Gemini: Sending request...

 46%|████▌     | 91/200 [11:41<13:14,  7.29s/it]

✅ [Row 156] GPT Received: {
  "reasoning": "The Anchor story revolves around fugitives working in a gold mine under a tyrannic...
🚀 [Row 156] Claude: Sending request...

 46%|████▌     | 91/200 [11:42<13:14,  7.29s/it]

✅ [Row 92] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature pro...
🚀 [Row 92] GPT: Sending request...

 46%|████▌     | 91/200 [11:43<13:14,  7.29s/it]

✅ [Row 91] GPT Received: {
  "reasoning": "The Anchor story revolves around Dr. David Lowell's struggle against a corporation...
🚀 [Row 91] Claude: Sending request...

 46%|████▌     | 91/200 [11:43<13:14,  7.29s/it]

✅ [Row 157] GPT Received: {
  "reasoning": "The Anchor story involves a heist theme with thieves planning to steal valuable pa...
🚀 [Row 157] Claude: Sending request...

 46%|████▌     | 91/200 [11:47<13:14,  7.29s/it]

✅ [Row 92] GPT Received: {
  "reasoning": "The Anchor story involves a drifter with a criminal background who becomes involve...
🚀 [Row 92] Claude: Sending request...

 46%|████▌     | 91/200 [11:48<13:14,  7.29s/it]

✅ [Row 93] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text primarily due to the shared wartim...
🚀 [Row 93] GPT: Sending request...

 46%|████▌     | 91/200 [11:50<13:14,  7.29s/it]

✅ [Row 156] Claude Received: ```json
{
  "reasoning": "Both texts involve characters on the run and themes of trust/danger, but T...
🏁 [Row 156] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 159] Gemini: Sending request...
✅ [Row 155] Claude Received: ```json
{
  "reasoning": "The Anchor describes a meta-narrative about a controversial Jesus film, in...
🏁 [Row 155] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 160] Gemini: Sending request...

 46%|████▌     | 92/200 [11:51<14:46,  8.21s/it]

✅ [Row 91] Claude Received: ```json
{
  "reasoning": "Text A shares more narrative elements with the Anchor. Both stories center...
🏁 [Row 91] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 95] Gemini: Sending request...
✅ [Row 158] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor's core narrative revolves a...
🚀 [Row 158] GPT: Sending request...

 46%|████▌     | 92/200 [11:51<14:46,  8.21s/it]

✅ [Row 157] Claude Received: ```json
{
  "reasoning": "The Anchor involves a specific criminal enterprise centered on stolen pain...
🏁 [Row 157] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 161] Gemini: Sending request...

 46%|████▌     | 92/200 [11:51<14:46,  8.21s/it]

✅ [Row 94] Gemini Received: {
  "reasoning": "The Anchor text features a bumbling detective investigating a murder, which leads ...
🚀 [Row 94] GPT: Sending request...

 46%|████▌     | 92/200 [11:54<14:46,  8.21s/it]

✅ [Row 93] GPT Received: {
  "reasoning": "The Anchor story revolves around the Stage Door Canteen, where women volunteers pr...
🚀 [Row 93] Claude: Sending request...

 46%|████▋     | 93/200 [11:55<12:32,  7.04s/it]

✅ [Row 94] GPT Received: {
  "reasoning": "The Anchor story involves a private detective trying to prove his innocence in a m...
🚀 [Row 94] Claude: Sending request...
✅ [Row 92] Claude Received: ```json
{
  "reasoning": "Both texts involve marginalized protagonists entangled with crime, but Tex...
🏁 [Row 92] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 96] Gemini: Sending request...

 46%|████▋     | 93/200 [11:56<12:32,  7.04s/it]

⏳ [Row 96] Gemini: Rate limit (Attempt 1)

 46%|████▋     | 93/200 [11:57<12:32,  7.04s/it]

✅ [Row 158] GPT Received: {
  "reasoning": "The Anchor story revolves around a criminal defense attorney dealing with a high-p...
🚀 [Row 158] Claude: Sending request...
✅ [Row 160] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A involve a p...
🚀 [Row 160] GPT: Sending request...

 47%|████▋     | 94/200 [12:01<11:52,  6.72s/it]

✅ [Row 93] Claude Received: ```json
{
  "reasoning": "The Anchor is set during wartime and centers on female volunteers at a rec...
🏁 [Row 93] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 97] Gemini: Sending request...

 47%|████▋     | 94/200 [12:02<11:52,  6.72s/it]

✅ [Row 160] GPT Received: {
  "reasoning": "The Anchor story involves a biographer who falls in love with the sister of a dece...
🚀 [Row 160] Claude: Sending request...

 48%|████▊     | 95/200 [12:03<09:15,  5.29s/it]

✅ [Row 94] Claude Received: ```json
{
  "reasoning": "The Anchor follows a bumbling private detective investigating his partner'...
🏁 [Row 94] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 98] Gemini: Sending request...

 48%|████▊     | 95/200 [12:05<09:15,  5.29s/it]

✅ [Row 95] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a h...
🚀 [Row 95] GPT: Sending request...

 48%|████▊     | 95/200 [12:06<09:15,  5.29s/it]

✅ [Row 158] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a defense attorney who initially believes his wealth...
🏁 [Row 158] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 162] Gemini: Sending request...

 48%|████▊     | 95/200 [12:06<09:15,  5.29s/it]

✅ [Row 159] Gemini Received: {
  "reasoning": "The Anchor text features a detective investigating a strange domestic dispute, lea...
🚀 [Row 159] GPT: Sending request...

 48%|████▊     | 95/200 [12:09<09:15,  5.29s/it]

✅ [Row 160] Claude Received: ```json
{
  "reasoning": "The Anchor involves a biographer investigating a pilot's death, falling in...
🏁 [Row 160] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 163] Gemini: Sending request...

 48%|████▊     | 95/200 [12:10<09:15,  5.29s/it]

✅ [Row 161] Gemini Received: {
  "reasoning": "Neither Text A nor Text B are narratively very close to the Anchor. However, I mus...
🚀 [Row 161] GPT: Sending request...

 48%|████▊     | 95/200 [12:10<09:15,  5.29s/it]

✅ [Row 95] GPT Received: {
  "reasoning": "The Anchor story revolves around a case of mistaken identity and a romantic pursui...
🚀 [Row 95] Claude: Sending request...

 48%|████▊     | 95/200 [12:11<09:15,  5.29s/it]

✅ [Row 97] Gemini Received: {
  "reasoning": "The Anchor text focuses on a middle-aged man's dissatisfaction despite material we...
🚀 [Row 97] GPT: Sending request...
✅ [Row 159] GPT Received: {
  "reasoning": "The Anchor story involves a detective, Maigret, investigating a potential poisonin...
🚀 [Row 159] Claude: Sending request...

 48%|████▊     | 95/200 [12:15<09:15,  5.29s/it]

✅ [Row 162] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature dia...
🚀 [Row 162] GPT: Sending request...

 48%|████▊     | 95/200 [12:16<09:15,  5.29s/it]

✅ [Row 97] GPT Received: {
  "reasoning": "The Anchor text and Text A both focus on the life of a middle-aged man dealing wit...
🚀 [Row 97] Claude: Sending request...

 48%|████▊     | 95/200 [12:16<09:15,  5.29s/it]

✅ [Row 98] Gemini Received: {
  "reasoning": "The Anchor text centers on mutual infidelity within a circle of friends, a wife's ...
🚀 [Row 98] GPT: Sending request...
✅ [Row 161] GPT Received: {
  "reasoning": "The Anchor story revolves around a quest to recover hidden wealth within chairs, i...
🚀 [Row 161] Claude: Sending request...

 48%|████▊     | 95/200 [12:16<09:15,  5.29s/it]

✅ [Row 163] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature an ...
🚀 [Row 163] GPT: Sending request...

 48%|████▊     | 96/200 [12:17<13:43,  7.92s/it]

✅ [Row 95] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic confusion and mistaken identity elements, but ...
🏁 [Row 95] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 99] Gemini: Sending request...

 48%|████▊     | 96/200 [12:19<13:43,  7.92s/it]

✅ [Row 163] GPT Received: {
  "reasoning": "The Anchor story revolves around a family gathering for a celebration, with initia...
🚀 [Row 163] Claude: Sending request...

 48%|████▊     | 96/200 [12:19<13:43,  7.92s/it]

✅ [Row 159] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Maigret, a detective investigating a potential poiso...
🏁 [Row 159] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 164] Gemini: Sending request...

 48%|████▊     | 96/200 [12:20<13:43,  7.92s/it]

✅ [Row 98] GPT Received: {
  "reasoning": "The Anchor story revolves around two couples dealing with infidelity and the resul...
🚀 [Row 98] Claude: Sending request...

 48%|████▊     | 96/200 [12:21<13:43,  7.92s/it]

✅ [Row 162] GPT Received: {
  "reasoning": "The Anchor story revolves around Pier Ullman seeking revenge for his father's mist...
🚀 [Row 162] Claude: Sending request...

 48%|████▊     | 96/200 [12:24<13:43,  7.92s/it]

✅ [Row 161] Claude Received: ```json
{
  "reasoning": "The Anchor follows a man who inherits thirteen chairs, sells them for trav...
🏁 [Row 161] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 165] Gemini: Sending request...

 48%|████▊     | 97/200 [12:25<13:37,  7.94s/it]

✅ [Row 97] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a middle-aged protagonist dealing with marital probl...
🏁 [Row 97] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 100] Gemini: Sending request...

 48%|████▊     | 97/200 [12:27<13:37,  7.94s/it]

✅ [Row 163] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a family reunion occasioned by Wilhelm's award cerem...
🏁 [Row 163] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 166] Gemini: Sending request...

 48%|████▊     | 97/200 [12:28<13:37,  7.94s/it]

❌ [Row 96] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 48%|████▊     | 97/200 [12:30<13:37,  7.94s/it]

✅ [Row 164] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center on a...
🚀 [Row 164] GPT: Sending request...

 48%|████▊     | 97/200 [12:31<13:37,  7.94s/it]

✅ [Row 99] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text primarily due to similarities in t...
🚀 [Row 99] GPT: Sending request...
✅ [Row 162] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Pier infiltrating his estranged family's diamond bus...
🏁 [Row 162] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 167] Gemini: Sending request...

 49%|████▉     | 98/200 [12:31<12:29,  7.35s/it]

✅ [Row 98] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two married couples (Jack/Terry and Hank/Edith) who ...
🏁 [Row 98] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 101] Gemini: Sending request...

 49%|████▉     | 98/200 [12:33<12:29,  7.35s/it]

✅ [Row 100] Gemini Received: {
  "reasoning": "The Anchor text features Satan, a supernatural being, who is banished and must tem...
🚀 [Row 100] GPT: Sending request...

 49%|████▉     | 98/200 [12:35<12:29,  7.35s/it]

✅ [Row 166] Gemini Received: {
  "reasoning": "The Anchor text features four vignettes, one of which, 'Queen Elena,' focuses on a...
🚀 [Row 166] GPT: Sending request...

 49%|████▉     | 98/200 [12:36<12:29,  7.35s/it]

✅ [Row 99] GPT Received: {
  "reasoning": "The Anchor story revolves around a couple trying to mend their relationship during...
🚀 [Row 99] Claude: Sending request...

 49%|████▉     | 98/200 [12:37<12:29,  7.35s/it]

✅ [Row 164] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of family disillusionment, unfulfilled aspi...
🚀 [Row 164] Claude: Sending request...

 49%|████▉     | 98/200 [12:37<12:29,  7.35s/it]

✅ [Row 165] Gemini Received: {
  "reasoning": "The Anchor text begins with the protagonist, Thomas, being recruited into an \"ill...
🚀 [Row 165] GPT: Sending request...
✅ [Row 100] GPT Received: {
  "reasoning": "The Anchor text revolves around Satan's mission on Earth, where he influences hist...
🚀 [Row 100] Claude: Sending request...

 49%|████▉     | 98/200 [12:39<12:29,  7.35s/it]

✅ [Row 96] Gemini Received: {
  "reasoning": "The Anchor text's core narrative revolves around a woman choosing between passiona...
🚀 [Row 96] GPT: Sending request...

 49%|████▉     | 98/200 [12:41<12:29,  7.35s/it]

✅ [Row 165] GPT Received: {
  "reasoning": "The Anchor story involves a young man who becomes embroiled in a murder mystery af...
🚀 [Row 165] Claude: Sending request...

 49%|████▉     | 98/200 [12:41<12:29,  7.35s/it]

✅ [Row 166] GPT Received: {
  "reasoning": "The Anchor text consists of four vignettes, each dealing with themes of sexual mis...
🚀 [Row 166] Claude: Sending request...

 49%|████▉     | 98/200 [12:43<12:29,  7.35s/it]

✅ [Row 101] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a y...
🚀 [Row 101] GPT: Sending request...

 49%|████▉     | 98/200 [12:44<12:29,  7.35s/it]

✅ [Row 96] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle involving Lucile, Charles, and An...
🚀 [Row 96] Claude: Sending request...

 50%|████▉     | 99/200 [12:45<15:37,  9.28s/it]

✅ [Row 99] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a couple (Lucy and Norman) on vacation who dis...
🏁 [Row 99] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 102] Gemini: Sending request...

 50%|█████     | 100/200 [12:45<11:13,  6.74s/it]

✅ [Row 100] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Satan being exiled to Earth and influencing major hi...
🏁 [Row 100] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 103] Gemini: Sending request...

 50%|█████     | 100/200 [12:48<11:13,  6.74s/it]

✅ [Row 167] Gemini Received: {
  "reasoning": "The Anchor text features a core theme of supernatural retribution for a historical...
🚀 [Row 167] GPT: Sending request...

 50%|█████     | 100/200 [12:48<11:13,  6.74s/it]

✅ [Row 165] Claude Received: ```json
{
  "reasoning": "Both texts involve illicit relationships and murder, but Text B is narrati...
🏁 [Row 165] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 168] Gemini: Sending request...

 50%|█████     | 100/200 [12:49<11:13,  6.74s/it]

✅ [Row 101] GPT Received: {
  "reasoning": "The Anchor story revolves around Agnes, who escapes her father's control and ends ...
🚀 [Row 101] Claude: Sending request...

 50%|█████     | 100/200 [12:50<11:13,  6.74s/it]

✅ [Row 164] Claude Received: ```json
{
  "reasoning": "Both texts share some surface similarities with the Anchor (family dynamic...
🏁 [Row 164] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 169] Gemini: Sending request...

 50%|█████     | 100/200 [12:51<11:13,  6.74s/it]

✅ [Row 166] Claude Received: ```json
{
  "reasoning": "The Anchor is structured as four independent episodic vignettes, each expl...
🏁 [Row 166] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 170] Gemini: Sending request...

 50%|█████     | 101/200 [12:52<10:58,  6.65s/it]

✅ [Row 96] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a love triangle where Lucile moves between two ...
🏁 [Row 96] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 104] Gemini: Sending request...

 50%|█████     | 101/200 [12:52<10:58,  6.65s/it]

✅ [Row 167] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a group of young people encountering a de...
🚀 [Row 167] Claude: Sending request...

 50%|█████     | 101/200 [12:53<10:58,  6.65s/it]

✅ [Row 102] Gemini Received: {
  "reasoning": "The Anchor text describes a film with five simultaneous, loosely linked, and often...
🚀 [Row 102] GPT: Sending request...

 50%|█████     | 101/200 [12:56<10:58,  6.65s/it]

✅ [Row 103] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A describe ho...
🚀 [Row 103] GPT: Sending request...

 50%|█████     | 101/200 [12:57<10:58,  6.65s/it]

✅ [Row 102] GPT Received: {
  "reasoning": "The Anchor text features multiple intertwined plot lines with a mix of surreal and...
🚀 [Row 102] Claude: Sending request...

 50%|█████     | 101/200 [12:58<10:58,  6.65s/it]

✅ [Row 168] Gemini Received: {
  "reasoning": "The Anchor text tells a story of a young woman, Jade, who defies societal expectat...
🚀 [Row 168] GPT: Sending request...

 51%|█████     | 102/200 [12:58<10:48,  6.62s/it]

✅ [Row 101] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on Agnes, a scandalous novel author who flees her...
🏁 [Row 101] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 105] Gemini: Sending request...

 51%|█████     | 102/200 [13:00<10:48,  6.62s/it]

✅ [Row 103] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of change and adaptation in a small commun...
🚀 [Row 103] Claude: Sending request...

 51%|█████     | 102/200 [13:01<10:48,  6.62s/it]

✅ [Row 170] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist who, through an initial personal pursuit, a...
🚀 [Row 170] GPT: Sending request...

 51%|█████     | 102/200 [13:02<10:48,  6.62s/it]

✅ [Row 168] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a community under threat from an external...
🚀 [Row 168] Claude: Sending request...
✅ [Row 104] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share the c...
🚀 [Row 104] GPT: Sending request...

 51%|█████     | 102/200 [13:04<10:48,  6.62s/it]

✅ [Row 167] Claude Received: ```json
{
  "reasoning": "The Anchor follows travelers who stumble into a seemingly normal town that...
🏁 [Row 167] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 171] Gemini: Sending request...

 51%|█████     | 102/200 [13:05<10:48,  6.62s/it]

✅ [Row 170] GPT Received: {
  "reasoning": "The Anchor story involves a young protagonist who inadvertently gets involved in a...
🚀 [Row 170] Claude: Sending request...

 52%|█████▏    | 103/200 [13:06<11:12,  6.94s/it]

✅ [Row 102] Claude Received: ```json
{
  "reasoning": "The Anchor presents multiple intertwined, surreal storylines (a man repeat...
🏁 [Row 102] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 106] Gemini: Sending request...
✅ [Row 104] GPT Received: {
  "reasoning": "The Anchor story involves a legal conflict between a fishery and a chemical compan...
🚀 [Row 104] Claude: Sending request...

 52%|█████▏    | 104/200 [13:09<09:12,  5.75s/it]

✅ [Row 103] Claude Received: ```json
{
  "reasoning": "The Anchor centers on families resettled during communist rule in Albania,...
🏁 [Row 103] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 107] Gemini: Sending request...

 52%|█████▏    | 104/200 [13:10<09:12,  5.75s/it]

✅ [Row 105] Gemini Received: {
  "reasoning": "The Anchor text features a multi-layered plot driven by a core objective (roses), ...
🚀 [Row 105] GPT: Sending request...

 52%|█████▏    | 104/200 [13:11<09:12,  5.75s/it]

✅ [Row 168] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B differ significantly from the Anchor, but Text A sh...
🏁 [Row 168] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 172] Gemini: Sending request...

 52%|█████▏    | 104/200 [13:12<09:12,  5.75s/it]

✅ [Row 170] Claude Received: ```json
{
  "reasoning": "Text A shares significant narrative similarities with the Anchor. Both fea...
🏁 [Row 170] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 173] Gemini: Sending request...

 52%|█████▏    | 104/200 [13:13<09:12,  5.75s/it]

✅ [Row 171] Gemini Received: {
  "reasoning": "Text B shares the core narrative elements with the Anchor text: both feature misch...
🚀 [Row 171] GPT: Sending request...
⏳ [Row 173] Gemini: Rate limit (Attempt 1)

 52%|█████▎    | 105/200 [13:16<09:35,  6.06s/it]

✅ [Row 171] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve young characters who are expelled from sch...
🚀 [Row 171] Claude: Sending request...
✅ [Row 104] Claude Received: ```json
{
  "reasoning": "The Anchor involves legal professionals (lawyer Jackie Lung) hired by a co...
🏁 [Row 104] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 108] Gemini: Sending request...

 52%|█████▎    | 105/200 [13:16<09:35,  6.06s/it]

✅ [Row 105] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, deception, and reconciliation, wi...
🚀 [Row 105] Claude: Sending request...

 52%|█████▎    | 105/200 [13:20<09:35,  6.06s/it]

✅ [Row 107] Gemini Received: {
  "reasoning": "Text A focuses on a woman's quest for justice regarding her husband's incarceratio...
🚀 [Row 107] GPT: Sending request...
✅ [Row 172] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor because both stories revolve around themes of marit...
🚀 [Row 172] GPT: Sending request...
❌ [Row 169] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 52%|█████▎    | 105/200 [13:23<09:35,  6.06s/it]

⏳ [Row 106] Gemini: Rate limit (Attempt 1)
✅ [Row 172] GPT Received: {
  "reasoning": "The Anchor story involves themes of love, betrayal, and revenge within a criminal ...
🚀 [Row 172] Claude: Sending request...

 52%|█████▎    | 105/200 [13:24<09:35,  6.06s/it]

✅ [Row 107] GPT Received: {
  "reasoning": "The Anchor text revolves around the theme of war and its impact on personal lives,...
🚀 [Row 107] Claude: Sending request...

 53%|█████▎    | 106/200 [13:25<10:48,  6.90s/it]

✅ [Row 105] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on multiple characters infiltrating a household u...
🏁 [Row 105] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 109] Gemini: Sending request...

 53%|█████▎    | 106/200 [13:30<10:48,  6.90s/it]

✅ [Row 108] Gemini Received: {
  "reasoning": "The Anchor story describes a professional (speechwriter) navigating a complex, hig...
🚀 [Row 108] GPT: Sending request...

 53%|█████▎    | 106/200 [13:31<10:48,  6.90s/it]

✅ [Row 169] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist, Horacia, who, after experiencing injustic...
🚀 [Row 169] GPT: Sending request...

 53%|█████▎    | 106/200 [13:31<10:48,  6.90s/it]

✅ [Row 171] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve young people in institutional settings, but...
🏁 [Row 171] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 174] Gemini: Sending request...

 54%|█████▎    | 107/200 [13:32<10:49,  6.98s/it]

✅ [Row 107] Claude Received: ```json
{
  "reasoning": "Both texts involve war and personal loss, but Text B is narratively closer...
🏁 [Row 107] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 110] Gemini: Sending request...

 54%|█████▎    | 107/200 [13:32<10:49,  6.98s/it]

✅ [Row 173] Gemini Received: {
  "reasoning": "Text A describes an ongoing investigation by a treasury agent, focusing on the str...
🚀 [Row 173] GPT: Sending request...

 54%|█████▎    | 107/200 [13:34<10:49,  6.98s/it]

✅ [Row 172] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a love triangle involving deception, revenge, a...
🏁 [Row 172] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 175] Gemini: Sending request...
✅ [Row 108] GPT Received: {
  "reasoning": "The Anchor text revolves around a speechwriter navigating the challenges of workin...
🚀 [Row 108] Claude: Sending request...

 54%|█████▎    | 107/200 [13:35<10:49,  6.98s/it]

✅ [Row 109] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both feature a retired protagonist (Sherlock Holme...
🚀 [Row 109] GPT: Sending request...

 54%|█████▎    | 107/200 [13:36<10:49,  6.98s/it]

✅ [Row 173] GPT Received: {
  "reasoning": "The Anchor story revolves around two fishermen dealing with a gangster who extorts...
🚀 [Row 173] Claude: Sending request...

 54%|█████▎    | 107/200 [13:37<10:49,  6.98s/it]

⏳ [Row 106] Gemini: Rate limit (Attempt 2)

 54%|█████▎    | 107/200 [13:37<10:49,  6.98s/it]

✅ [Row 169] GPT Received: {
  "reasoning": "The Anchor story revolves around Horacia Somorostro, who seeks revenge after being...
🚀 [Row 169] Claude: Sending request...

 54%|█████▎    | 107/200 [13:37<10:49,  6.98s/it]

✅ [Row 109] GPT Received: {
  "reasoning": "The Anchor story involves retired detectives coming out of retirement to solve a m...
🚀 [Row 109] Claude: Sending request...

 54%|█████▍    | 108/200 [13:42<12:02,  7.85s/it]

✅ [Row 108] Claude Received: ```json
{
  "reasoning": "The Anchor follows a young professional (Arthur) navigating a demanding, h...
🏁 [Row 108] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 111] Gemini: Sending request...

 55%|█████▍    | 109/200 [13:45<09:38,  6.36s/it]

✅ [Row 109] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a detective (Holmes) coming out of retirement to inv...
🏁 [Row 109] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 112] Gemini: Sending request...

 55%|█████▍    | 109/200 [13:45<09:38,  6.36s/it]

✅ [Row 169] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Horacia Somorostro's story of wrongful imprisonment,...
🏁 [Row 169] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 176] Gemini: Sending request...

 55%|█████▍    | 109/200 [13:45<09:38,  6.36s/it]

✅ [Row 175] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a j...
🚀 [Row 175] GPT: Sending request...
⏳ [Row 176] Gemini: Rate limit (Attempt 1)

 55%|█████▍    | 109/200 [13:46<09:38,  6.36s/it]

✅ [Row 174] Gemini Received: {
  "reasoning": "The Anchor story describes Stella's journey from an unfulfilling life and casual f...
🚀 [Row 174] GPT: Sending request...

 55%|█████▍    | 109/200 [13:46<09:38,  6.36s/it]

✅ [Row 173] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two fishermen victimized by a gangster extorting pro...
🏁 [Row 173] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 177] Gemini: Sending request...

 55%|█████▍    | 109/200 [13:48<09:38,  6.36s/it]

✅ [Row 175] GPT Received: {
  "reasoning": "The Anchor story involves a love triangle, betrayal, and a journey through a harsh...
🚀 [Row 175] Claude: Sending request...

 55%|█████▍    | 109/200 [13:50<09:38,  6.36s/it]

✅ [Row 110] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature ski...
🚀 [Row 110] GPT: Sending request...

 55%|█████▍    | 109/200 [13:50<09:38,  6.36s/it]

✅ [Row 174] GPT Received: {
  "reasoning": "The Anchor story revolves around a woman, Stella, who is trying to find a new begi...
🚀 [Row 174] Claude: Sending request...

 55%|█████▍    | 109/200 [13:53<09:38,  6.36s/it]

✅ [Row 112] Gemini Received: {
  "reasoning": "The Anchor text describes a science fiction series set on a space station, involvi...
🚀 [Row 112] GPT: Sending request...

 55%|█████▍    | 109/200 [13:54<09:38,  6.36s/it]

✅ [Row 111] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center arou...
🚀 [Row 111] GPT: Sending request...
✅ [Row 110] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist, John Shaft, who is coerced into a mission...
🚀 [Row 110] Claude: Sending request...

 55%|█████▍    | 109/200 [13:55<09:38,  6.36s/it]

✅ [Row 176] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a n...
🚀 [Row 176] GPT: Sending request...

 55%|█████▍    | 109/200 [13:56<09:38,  6.36s/it]

✅ [Row 177] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor text. Both the Anchor and Text A describe the life ...
🚀 [Row 177] GPT: Sending request...
✅ [Row 106] Gemini Received: {
  "reasoning": "The Anchor text focuses on a character's idealism and eventual disillusionment wit...
🚀 [Row 106] GPT: Sending request...

 55%|█████▍    | 109/200 [13:56<09:38,  6.36s/it]

✅ [Row 112] GPT Received: {
  "reasoning": "The Anchor text is set in a science fiction universe with a focus on space explora...
🚀 [Row 112] Claude: Sending request...

 55%|█████▍    | 109/200 [13:57<09:38,  6.36s/it]

✅ [Row 111] GPT Received: {
  "reasoning": "The Anchor story involves themes of deceit, land expansion, and conflict between s...
🚀 [Row 111] Claude: Sending request...
✅ [Row 175] Claude Received: ```json
{
  "reasoning": "Both texts share the core Western triangle structure with the Anchor: a pr...
🏁 [Row 175] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 178] Gemini: Sending request...

 55%|█████▍    | 109/200 [13:59<09:38,  6.36s/it]

✅ [Row 176] GPT Received: {
  "reasoning": "The Anchor story revolves around a nun who leaves her convent, influenced by an ev...
🚀 [Row 176] Claude: Sending request...

 55%|█████▍    | 109/200 [13:59<09:38,  6.36s/it]

✅ [Row 106] GPT Received: {
  "reasoning": "The Anchor text revolves around the theme of political idealism and disillusionmen...
🚀 [Row 106] Claude: Sending request...
✅ [Row 174] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a woman (Stella) escaping an empty life marked by a ...
🏁 [Row 174] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 179] Gemini: Sending request...

 55%|█████▍    | 109/200 [14:00<09:38,  6.36s/it]

✅ [Row 177] GPT Received: {
  "reasoning": "The Anchor text is a biographical story about the life and struggles of a composer...
🚀 [Row 177] Claude: Sending request...

 55%|█████▌    | 110/200 [14:03<14:53,  9.93s/it]

✅ [Row 110] Claude Received: ```json
{
  "reasoning": "The Anchor centers on John Shaft being kidnapped/coerced into assuming a f...
🏁 [Row 110] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 113] Gemini: Sending request...

 55%|█████▌    | 110/200 [14:03<14:53,  9.93s/it]

⏳ [Row 178] Gemini: Rate limit (Attempt 1)

 55%|█████▌    | 110/200 [14:04<14:53,  9.93s/it]

⏳ [Row 113] Gemini: Rate limit (Attempt 1)

 56%|█████▌    | 111/200 [14:05<11:19,  7.64s/it]

✅ [Row 111] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a landowner's deceptive scheme to provoke conf...
🏁 [Row 111] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 114] Gemini: Sending request...

 56%|█████▌    | 112/200 [14:06<08:13,  5.60s/it]

✅ [Row 112] Claude Received: ```json
{
  "reasoning": "The Anchor describes a serialized space station drama with ongoing story a...
🏁 [Row 112] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 115] Gemini: Sending request...

 56%|█████▌    | 112/200 [14:07<08:13,  5.60s/it]

✅ [Row 176] Claude Received: ```json
{
  "reasoning": "The Anchor tells the story of a nun who abandons her religious vows to pur...
🏁 [Row 176] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 180] Gemini: Sending request...
✅ [Row 179] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A share ...
🚀 [Row 179] GPT: Sending request...

 56%|█████▌    | 112/200 [14:07<08:13,  5.60s/it]

✅ [Row 177] Claude Received: ```json
{
  "reasoning": "The Anchor tells the biographical story of composer Hector Berlioz, focusi...
🏁 [Row 177] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 181] Gemini: Sending request...

 56%|█████▋    | 113/200 [14:08<06:21,  4.39s/it]

✅ [Row 106] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a devoted Communist worker (Jarda) who faces the gra...
🏁 [Row 106] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 116] Gemini: Sending request...

 56%|█████▋    | 113/200 [14:08<06:21,  4.39s/it]

⏳ [Row 116] Gemini: Rate limit (Attempt 1)

 56%|█████▋    | 113/200 [14:10<06:21,  4.39s/it]

✅ [Row 179] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of revenge, identity swapping, and protect...
🚀 [Row 179] Claude: Sending request...

 56%|█████▋    | 113/200 [14:14<06:21,  4.39s/it]

✅ [Row 115] Gemini Received: {
  "reasoning": "The Anchor text describes an international espionage thriller featuring an America...
🚀 [Row 115] GPT: Sending request...

 56%|█████▋    | 113/200 [14:14<06:21,  4.39s/it]

✅ [Row 114] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor because both feature a protagonist who is an agent ...
🚀 [Row 114] GPT: Sending request...

 56%|█████▋    | 113/200 [14:16<06:21,  4.39s/it]

✅ [Row 178] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a r...
🚀 [Row 178] GPT: Sending request...

 56%|█████▋    | 113/200 [14:17<06:21,  4.39s/it]

✅ [Row 115] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve undercover agents dealing with espionage a...
🚀 [Row 115] Claude: Sending request...
✅ [Row 113] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both texts feature a naval vessel (U-b...
🚀 [Row 113] GPT: Sending request...

 56%|█████▋    | 113/200 [14:17<06:21,  4.39s/it]

✅ [Row 114] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of justice, identity, and reconciliation w...
🚀 [Row 114] Claude: Sending request...

 56%|█████▋    | 113/200 [14:18<06:21,  4.39s/it]

✅ [Row 179] Claude Received: ```json
{
  "reasoning": "Both texts share the Western genre with the Anchor, but Text B is narrativ...
✅ [Row 116] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center arou...
🏁 [Row 179] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 182] Gemini: Sending request...
🚀 [Row 116] GPT: Sending request...

 56%|█████▋    | 113/200 [14:21<06:21,  4.39s/it]

✅ [Row 178] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle involving a dancer, a politician,...
🚀 [Row 178] Claude: Sending request...

 56%|█████▋    | 113/200 [14:21<06:21,  4.39s/it]

✅ [Row 113] GPT Received: {
  "reasoning": "The Anchor text revolves around a U-boat crew's experiences before and during a mi...
🚀 [Row 113] Claude: Sending request...

 56%|█████▋    | 113/200 [14:22<06:21,  4.39s/it]

✅ [Row 181] Gemini Received: {
  "reasoning": "Text A shares significant narrative similarities with the Anchor. Both stories inv...
🚀 [Row 181] GPT: Sending request...

 56%|█████▋    | 113/200 [14:23<06:21,  4.39s/it]

✅ [Row 116] GPT Received: {
  "reasoning": "The Anchor text revolves around the theme of revolutionary art and its impact duri...
🚀 [Row 116] Claude: Sending request...

 57%|█████▋    | 114/200 [14:26<12:21,  8.62s/it]

✅ [Row 115] Claude Received: ```json
{
  "reasoning": "Both texts share spy/espionage themes with the Anchor, but Text B is narra...
🏁 [Row 115] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 117] Gemini: Sending request...

 57%|█████▊    | 115/200 [14:27<08:44,  6.18s/it]

✅ [Row 114] Claude Received: ```json
{
  "reasoning": "The Anchor is fundamentally about an unlikely pairing between a fugitive h...
🏁 [Row 114] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 118] Gemini: Sending request...
✅ [Row 181] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of extraterrestrial life, space exploration...
🚀 [Row 181] Claude: Sending request...

 57%|█████▊    | 115/200 [14:28<08:44,  6.18s/it]

✅ [Row 182] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 182] GPT: Sending request...
✅ [Row 180] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist who resorts to an extreme and illegal act (...
🚀 [Row 180] GPT: Sending request...

 58%|█████▊    | 116/200 [14:28<06:42,  4.79s/it]

✅ [Row 113] Claude Received: ```json
{
  "reasoning": "The Anchor follows a military vessel crew through their shore leave, depar...
🏁 [Row 113] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 119] Gemini: Sending request...

 58%|█████▊    | 116/200 [14:29<06:42,  4.79s/it]

✅ [Row 178] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a love triangle involving class and political d...
🏁 [Row 178] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 183] Gemini: Sending request...

 58%|█████▊    | 117/200 [14:31<05:43,  4.14s/it]

✅ [Row 116] Claude Received: ```json
{
  "reasoning": "Both texts involve theater and historical dramatization, but Text A is nar...
🏁 [Row 116] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 120] Gemini: Sending request...

 58%|█████▊    | 117/200 [14:31<05:43,  4.14s/it]

✅ [Row 182] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a journey with family members who have st...
🚀 [Row 182] Claude: Sending request...

 58%|█████▊    | 117/200 [14:32<05:43,  4.14s/it]

✅ [Row 180] GPT Received: {
  "reasoning": "The Anchor story revolves around a man who kidnaps a woman by mistake and has to d...
🚀 [Row 180] Claude: Sending request...

 58%|█████▊    | 117/200 [14:35<05:43,  4.14s/it]

✅ [Row 181] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on an extraterrestrial narrator recounting Earth'...
🏁 [Row 181] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 184] Gemini: Sending request...

 58%|█████▊    | 117/200 [14:36<05:43,  4.14s/it]

✅ [Row 117] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B revolve aro...
🚀 [Row 117] GPT: Sending request...

 58%|█████▊    | 117/200 [14:37<05:43,  4.14s/it]

✅ [Row 118] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 118] GPT: Sending request...

 58%|█████▊    | 117/200 [14:38<05:43,  4.14s/it]

✅ [Row 183] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A revolve aro...
🚀 [Row 183] GPT: Sending request...

 58%|█████▊    | 117/200 [14:40<05:43,  4.14s/it]

✅ [Row 182] Claude Received: ```json
{
  "reasoning": "Both texts involve ex-prisoners trying to rebuild their lives, but Text B ...
🏁 [Row 182] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 185] Gemini: Sending request...

 58%|█████▊    | 117/200 [14:41<05:43,  4.14s/it]

✅ [Row 118] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve protagonists with mental health issues who...
🚀 [Row 118] Claude: Sending request...

 58%|█████▊    | 117/200 [14:42<05:43,  4.14s/it]

✅ [Row 183] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve imposters who are mistaken for someone th...
🚀 [Row 183] Claude: Sending request...
✅ [Row 117] GPT Received: {
  "reasoning": "The Anchor story involves a criminal plot with counterfeit money, a character who ...
🚀 [Row 117] Claude: Sending request...
✅ [Row 180] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an incompetent kidnapper who accidentally captures t...
🏁 [Row 180] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 186] Gemini: Sending request...

 58%|█████▊    | 117/200 [14:42<05:43,  4.14s/it]

✅ [Row 184] Gemini Received: {
  "reasoning": "Both the Anchor and Text B feature a complex plan that goes awry due to an unexpec...
🚀 [Row 184] GPT: Sending request...

 58%|█████▊    | 117/200 [14:44<05:43,  4.14s/it]

✅ [Row 119] Gemini Received: {
  "reasoning": "Text A focuses on a personal crime, escape, and identity change, which bears no re...
🚀 [Row 119] GPT: Sending request...

 58%|█████▊    | 117/200 [14:46<05:43,  4.14s/it]

✅ [Row 184] GPT Received: {
  "reasoning": "The Anchor story involves a plan to kidnap a child for ransom, but the plan backfi...
🚀 [Row 184] Claude: Sending request...

 58%|█████▊    | 117/200 [14:47<05:43,  4.14s/it]

✅ [Row 120] Gemini Received: {
  "reasoning": "The Anchor text deals with a serious and tragic situation involving real violence ...
🚀 [Row 120] GPT: Sending request...

 58%|█████▊    | 117/200 [14:48<05:43,  4.14s/it]

✅ [Row 119] GPT Received: {
  "reasoning": "The Anchor story involves themes of intelligence, radicalization, and bioterrorism...
🚀 [Row 119] Claude: Sending request...

 59%|█████▉    | 118/200 [14:50<11:38,  8.51s/it]

✅ [Row 118] Claude Received: ```json
{
  "reasoning": "Both texts share elements of individuals overcoming adversity, but Text A ...
❌ [Row 118] Claude Error: Expecting ',' delimiter: line 3 column 3 (char 1116)
🏁 [Row 118] Votes: {'gemini': True, 'gpt': True, 'claude': None}
🚀 [Row 121] Gemini: Sending request...

 60%|█████▉    | 119/200 [14:50<08:26,  6.26s/it]

✅ [Row 120] GPT Received: {
  "reasoning": "The Anchor story revolves around a stunt coordinator who decides to stay in Peru a...
🚀 [Row 120] Claude: Sending request...
✅ [Row 117] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve crime and law enforcement, but Text B is na...
🏁 [Row 117] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 122] Gemini: Sending request...

 60%|█████▉    | 119/200 [14:51<08:26,  6.26s/it]

✅ [Row 183] Claude Received: ```json
{
  "reasoning": "The Anchor involves two rural men randomly cast in a film who, after an ac...
🏁 [Row 183] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 187] Gemini: Sending request...

 60%|█████▉    | 119/200 [14:52<08:26,  6.26s/it]

⏳ [Row 122] Gemini: Rate limit (Attempt 1)

 60%|█████▉    | 119/200 [14:54<08:26,  6.26s/it]

✅ [Row 184] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a kidnapping scheme that backfires when the vic...
🏁 [Row 184] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 188] Gemini: Sending request...

 60%|█████▉    | 119/200 [14:57<08:26,  6.26s/it]

✅ [Row 185] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist driven by desperation to take a secret, mor...
🚀 [Row 185] GPT: Sending request...

 60%|█████▉    | 119/200 [14:59<08:26,  6.26s/it]

✅ [Row 187] Gemini Received: {
  "reasoning": "The Anchor text involves a significant theft (a massive diamond), subsequent dange...
🚀 [Row 187] GPT: Sending request...

 60%|██████    | 120/200 [15:00<09:24,  7.06s/it]

✅ [Row 119] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on an intelligence operative drawn back into service to...
🏁 [Row 119] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 123] Gemini: Sending request...
✅ [Row 120] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a stunt coordinator who witnesses the blurring...
🏁 [Row 120] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 124] Gemini: Sending request...
✅ [Row 186] Gemini Received: {
  "reasoning": "While neither Text A nor Text B capture the specific elements of betrayal by a fri...
🚀 [Row 186] GPT: Sending request...

 60%|██████    | 120/200 [15:00<09:24,  7.06s/it]

✅ [Row 121] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center arou...
🚀 [Row 121] GPT: Sending request...

 60%|██████    | 120/200 [15:02<09:24,  7.06s/it]

✅ [Row 185] GPT Received: {
  "reasoning": "The Anchor story revolves around a struggling novelist, Byron Tiller, who takes a ...
🚀 [Row 185] Claude: Sending request...

 60%|██████    | 120/200 [15:02<09:24,  7.06s/it]

✅ [Row 187] GPT Received: {
  "reasoning": "The Anchor story involves themes of mistaken identity, crime, and a heist involvin...
🚀 [Row 187] Claude: Sending request...
✅ [Row 122] Gemini Received: {
  "reasoning": "The Anchor text describes a military invasion of a country (Norway by Germany), hi...
🚀 [Row 122] GPT: Sending request...

 60%|██████    | 120/200 [15:03<09:24,  7.06s/it]

✅ [Row 121] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, secrets, and revisiting past life...
🚀 [Row 121] Claude: Sending request...

 60%|██████    | 120/200 [15:03<09:24,  7.06s/it]

✅ [Row 188] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 188] GPT: Sending request...

 60%|██████    | 120/200 [15:05<09:24,  7.06s/it]

✅ [Row 122] GPT Received: {
  "reasoning": "The Anchor text focuses on the events leading up to and including the invasion of ...
🚀 [Row 122] Claude: Sending request...

 60%|██████    | 120/200 [15:07<09:24,  7.06s/it]

✅ [Row 188] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist, Paul, who is an immigrant searching for a...
🚀 [Row 188] Claude: Sending request...

 60%|██████    | 120/200 [15:09<09:24,  7.06s/it]

✅ [Row 123] Gemini Received: {
  "reasoning": "The Anchor text focuses on a character's personal struggle with shyness and awkwar...
🚀 [Row 123] GPT: Sending request...

 61%|██████    | 122/200 [15:11<08:17,  6.38s/it]

✅ [Row 121] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a woman who conceals from her former love that they ...
🏁 [Row 121] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 125] Gemini: Sending request...

 61%|██████    | 122/200 [15:12<08:17,  6.38s/it]

✅ [Row 186] GPT Received: {
  "reasoning": "The Anchor text revolves around Merlin's investigation into assassination attempts...
🚀 [Row 186] Claude: Sending request...

 61%|██████    | 122/200 [15:13<08:17,  6.38s/it]

✅ [Row 187] Claude Received: ```json
{
  "reasoning": "The Anchor involves a case of mistaken identity between twins, a stolen di...
🏁 [Row 187] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 189] Gemini: Sending request...
✅ [Row 185] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a struggling novelist who takes a job with an escort...
🏁 [Row 185] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 190] Gemini: Sending request...

 62%|██████▏   | 123/200 [15:13<06:51,  5.34s/it]

✅ [Row 122] Claude Received: ```json
{
  "reasoning": "The Anchor describes a WWII film about the lead-up to and execution of the...
🏁 [Row 122] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 126] Gemini: Sending request...

 62%|██████▏   | 123/200 [15:13<06:51,  5.34s/it]

✅ [Row 123] GPT Received: {
  "reasoning": "The Anchor story revolves around a young man's attempt to win over a girl by parti...
🚀 [Row 123] Claude: Sending request...

 62%|██████▏   | 123/200 [15:14<06:51,  5.34s/it]

✅ [Row 188] Claude Received: ```json
{
  "reasoning": "Text A shares more narrative elements with the Anchor. Both stories center...
🏁 [Row 188] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 191] Gemini: Sending request...

 62%|██████▏   | 123/200 [15:16<06:51,  5.34s/it]

✅ [Row 124] Gemini Received: {
  "reasoning": "The Anchor text describes Rick, a man engaged in small-time hustling, seeking mean...
🚀 [Row 124] GPT: Sending request...

 62%|██████▏   | 123/200 [15:20<06:51,  5.34s/it]

✅ [Row 190] Gemini Received: {
  "reasoning": "The Anchor story centers on the arrival of a mysterious man with amnesia whose pas...
🚀 [Row 190] GPT: Sending request...

 62%|██████▏   | 123/200 [15:21<06:51,  5.34s/it]

✅ [Row 191] Gemini Received: {
  "reasoning": "Text A is closer because both the Anchor and Text A describe groups of people enga...
🚀 [Row 191] GPT: Sending request...
✅ [Row 186] Claude Received: ```json
{
  "reasoning": "The Anchor is about Merlin investigating assassination attempts while deal...
🏁 [Row 186] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 192] Gemini: Sending request...

 62%|██████▏   | 124/200 [15:21<07:42,  6.08s/it]

✅ [Row 123] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a teenager (Krimo) who joins a theatrical rehearsal ...
🏁 [Row 123] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 127] Gemini: Sending request...

 62%|██████▏   | 124/200 [15:21<07:42,  6.08s/it]

✅ [Row 124] GPT Received: {
  "reasoning": "The Anchor story revolves around Rick's search for meaning and a stable relationsh...
🚀 [Row 124] Claude: Sending request...

 62%|██████▏   | 124/200 [15:22<07:42,  6.08s/it]

⏳ [Row 127] Gemini: Rate limit (Attempt 1)

 62%|██████▏   | 124/200 [15:22<07:42,  6.08s/it]

✅ [Row 125] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature an ...
🚀 [Row 125] GPT: Sending request...

 62%|██████▏   | 124/200 [15:23<07:42,  6.08s/it]

✅ [Row 126] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B deal with t...
🚀 [Row 126] GPT: Sending request...

 62%|██████▏   | 124/200 [15:24<07:42,  6.08s/it]

✅ [Row 190] GPT Received: {
  "reasoning": "The Anchor story revolves around a mysterious Englishman who changes the lives of ...
🚀 [Row 190] Claude: Sending request...

 62%|██████▏   | 124/200 [15:24<07:42,  6.08s/it]

✅ [Row 191] GPT Received: {
  "reasoning": "The Anchor story revolves around smuggling, economic struggles, and the consequenc...
🚀 [Row 191] Claude: Sending request...

 62%|██████▏   | 124/200 [15:26<07:42,  6.08s/it]

✅ [Row 125] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve isolated communities with genetic mutatio...
🚀 [Row 125] Claude: Sending request...

 62%|██████▏   | 124/200 [15:27<07:42,  6.08s/it]

✅ [Row 126] GPT Received: {
  "reasoning": "The Anchor story revolves around two brothers who love the same woman and make sac...
🚀 [Row 126] Claude: Sending request...

 62%|██████▏   | 124/200 [15:30<07:42,  6.08s/it]

✅ [Row 190] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a mysterious man being taken into a household o...
🏁 [Row 190] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 193] Gemini: Sending request...

 62%|██████▎   | 125/200 [15:31<09:02,  7.24s/it]

✅ [Row 124] Claude Received: ```json
{
  "reasoning": "Both texts share the core element of a young man engaged in small-scale dr...
🏁 [Row 124] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 128] Gemini: Sending request...
✅ [Row 127] Gemini Received: {
  "reasoning": "Text B is narratively closer. Both the Anchor and Text B revolve around complex ad...
🚀 [Row 127] GPT: Sending request...

 62%|██████▎   | 125/200 [15:32<09:02,  7.24s/it]

✅ [Row 192] Gemini Received: {
  "reasoning": "Both Text A and Text B feature a protagonist who loses their job, similar to the A...
🚀 [Row 192] GPT: Sending request...

 62%|██████▎   | 125/200 [15:33<09:02,  7.24s/it]

✅ [Row 189] Gemini Received: {
  "reasoning": "The Anchor text centers on a teenage girl forming a unique, almost magical bond wi...
🚀 [Row 189] GPT: Sending request...

 62%|██████▎   | 125/200 [15:33<09:02,  7.24s/it]

✅ [Row 191] Claude Received: ```json
{
  "reasoning": "The Anchor is fundamentally about the consequences of illegal cross-border...
🏁 [Row 191] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 194] Gemini: Sending request...

 63%|██████▎   | 126/200 [15:35<07:41,  6.24s/it]

✅ [Row 125] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a couple discovering a dark family secret involving ...
🏁 [Row 125] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 129] Gemini: Sending request...

 63%|██████▎   | 126/200 [15:35<07:41,  6.24s/it]

✅ [Row 127] GPT Received: {
  "reasoning": "The Anchor story revolves around a summer holiday at a family house, exploring the...
🚀 [Row 127] Claude: Sending request...

 64%|██████▎   | 127/200 [15:36<05:48,  4.78s/it]

✅ [Row 126] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a love triangle between two brothers and one woman, ...
🏁 [Row 126] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 130] Gemini: Sending request...

 64%|██████▎   | 127/200 [15:36<05:48,  4.78s/it]

✅ [Row 192] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve protagonists who face significant persona...
🚀 [Row 192] Claude: Sending request...

 64%|██████▎   | 127/200 [15:37<05:48,  4.78s/it]

✅ [Row 189] GPT Received: {
  "reasoning": "The Anchor story 'Windstorm' centers around a teenage girl, Mika, who discovers he...
🚀 [Row 189] Claude: Sending request...

 64%|██████▎   | 127/200 [15:40<05:48,  4.78s/it]

✅ [Row 193] Gemini Received: {
  "reasoning": "Text B shares a much stronger narrative similarity with the Anchor. Both texts hea...
🚀 [Row 193] GPT: Sending request...

 64%|██████▎   | 127/200 [15:42<05:48,  4.78s/it]

✅ [Row 194] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature an ...
🚀 [Row 194] GPT: Sending request...

 64%|██████▍   | 128/200 [15:44<06:46,  5.64s/it]

✅ [Row 127] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a family summer vacation at an inherited house on th...
🏁 [Row 127] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 131] Gemini: Sending request...
✅ [Row 193] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of captivity, intrigue, betrayal, and esca...
🚀 [Row 193] Claude: Sending request...

 64%|██████▍   | 128/200 [15:44<06:46,  5.64s/it]

✅ [Row 128] Gemini Received: {
  "reasoning": "The Anchor text features a ghost who initially contributes to a divorcing couple's...
🚀 [Row 128] GPT: Sending request...

 64%|██████▍   | 128/200 [15:45<06:46,  5.64s/it]

✅ [Row 189] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories share: (1) a magi...
🏁 [Row 189] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 195] Gemini: Sending request...

 64%|██████▍   | 128/200 [15:46<06:46,  5.64s/it]

✅ [Row 192] Claude Received: ```json
{
  "reasoning": "Both texts involve protagonists facing consequences and opposition, but Te...
🏁 [Row 192] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 196] Gemini: Sending request...

 64%|██████▍   | 128/200 [15:47<06:46,  5.64s/it]

✅ [Row 194] GPT Received: {
  "reasoning": "The Anchor text focuses on an artist, Antonio López García, who is grappling with ...
🚀 [Row 194] Claude: Sending request...

 64%|██████▍   | 128/200 [15:49<06:46,  5.64s/it]

✅ [Row 128] GPT Received: {
  "reasoning": "The Anchor story involves a ghost trying to reunite a divorcing couple to gain ent...
🚀 [Row 128] Claude: Sending request...

 64%|██████▍   | 128/200 [15:49<06:46,  5.64s/it]

✅ [Row 129] Gemini Received: {
  "reasoning": "The Anchor text features twin sisters, one leading a conservative life and the oth...
🚀 [Row 129] GPT: Sending request...

 64%|██████▍   | 128/200 [15:50<06:46,  5.64s/it]

✅ [Row 131] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a c...
🚀 [Row 131] GPT: Sending request...

 64%|██████▍   | 128/200 [15:52<06:46,  5.64s/it]

✅ [Row 129] GPT Received: {
  "reasoning": "The Anchor story revolves around twin sisters with contrasting personalities and t...
🚀 [Row 129] Claude: Sending request...

 64%|██████▍   | 128/200 [15:52<06:46,  5.64s/it]

✅ [Row 195] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A explore the...
🚀 [Row 195] GPT: Sending request...

 64%|██████▍   | 128/200 [15:54<06:46,  5.64s/it]

✅ [Row 131] GPT Received: {
  "reasoning": "The Anchor story involves a family in the winemaking business in California in the...
🚀 [Row 131] Claude: Sending request...

 64%|██████▍   | 128/200 [15:55<06:46,  5.64s/it]

✅ [Row 193] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Napoleon's imprisonment and an elaborate escape plot...
🏁 [Row 193] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 197] Gemini: Sending request...

 64%|██████▍   | 128/200 [15:56<06:46,  5.64s/it]

✅ [Row 196] Gemini Received: {
  "reasoning": "Text A focuses on marital jealousy and misunderstanding, leading to reconciliation...
🚀 [Row 196] GPT: Sending request...
✅ [Row 194] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on an aging artist (López) racing against time, weather...
🏁 [Row 194] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 198] Gemini: Sending request...
✅ [Row 195] GPT Received: {
  "reasoning": "The Anchor text focuses on the disintegration of a marriage, the interactions and ...
🚀 [Row 195] Claude: Sending request...

 64%|██████▍   | 128/200 [15:56<06:46,  5.64s/it]

✅ [Row 130] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a s...
🚀 [Row 130] GPT: Sending request...

 64%|██████▍   | 129/200 [15:57<09:17,  7.85s/it]

✅ [Row 128] Claude Received: ```json
{
  "reasoning": "The Anchor involves a ghost (Marion) trying to reunite a divorcing couple ...
🏁 [Row 128] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 132] Gemini: Sending request...

 64%|██████▍   | 129/200 [15:58<09:17,  7.85s/it]

⏳ [Row 198] Gemini: Rate limit (Attempt 1)

 64%|██████▍   | 129/200 [15:58<09:17,  7.85s/it]

✅ [Row 196] GPT Received: {
  "reasoning": "The Anchor story revolves around the challenges and eventual triumph associated wi...
🚀 [Row 196] Claude: Sending request...

 64%|██████▍   | 129/200 [16:01<09:17,  7.85s/it]

✅ [Row 130] GPT Received: {
  "reasoning": "The Anchor story involves genetically engineered creatures, a former soldier, and ...
🚀 [Row 130] Claude: Sending request...

 65%|██████▌   | 130/200 [16:02<08:13,  7.06s/it]

✅ [Row 131] Claude Received: ```json
{
  "reasoning": "Both texts involve revenge/conflict in a Western setting, but Text B is na...
🏁 [Row 131] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 133] Gemini: Sending request...

 66%|██████▌   | 131/200 [16:02<05:47,  5.03s/it]

✅ [Row 129] Claude Received: ```json
{
  "reasoning": "The Anchor centers on twin sisters (one modest, one bohemian) who unknowin...
🏁 [Row 129] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 134] Gemini: Sending request...

 66%|██████▌   | 131/200 [16:04<05:47,  5.03s/it]

✅ [Row 195] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a disintegrating marriage where a husband suddenly anno...
🏁 [Row 195] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 199] Gemini: Sending request...

 66%|██████▌   | 131/200 [16:07<05:47,  5.03s/it]

✅ [Row 196] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a family dealing with financial strain and neighborh...
🏁 [Row 196] Votes: {'gemini': False, 'gpt': True, 'claude': True}

 66%|██████▌   | 131/200 [16:07<05:47,  5.03s/it]

✅ [Row 198] Gemini Received: {
  "reasoning": "The Anchor text describes a documentary that 'depicts the life and work of Tirumal...
🚀 [Row 198] GPT: Sending request...

 66%|██████▌   | 131/200 [16:11<05:47,  5.03s/it]

✅ [Row 198] GPT Received: {
  "reasoning": "The Anchor text is about exploring the life and work of a historical figure, Tirum...
🚀 [Row 198] Claude: Sending request...

 66%|██████▌   | 132/200 [16:12<07:04,  6.24s/it]

✅ [Row 130] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around Travis, a former Delta Force operator who disco...
🏁 [Row 130] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 135] Gemini: Sending request...
✅ [Row 134] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a s...
🚀 [Row 134] GPT: Sending request...

 66%|██████▌   | 132/200 [16:12<07:04,  6.24s/it]

✅ [Row 132] Gemini Received: {
  "reasoning": "The Anchor text features a female protagonist driven by ambition and infidelity, w...
🚀 [Row 132] GPT: Sending request...

 66%|██████▌   | 132/200 [16:14<07:04,  6.24s/it]

✅ [Row 199] Gemini Received: {
  "reasoning": "The Anchor text centers on a political figure whose career and personal life (marr...
🚀 [Row 199] GPT: Sending request...

 66%|██████▌   | 132/200 [16:15<07:04,  6.24s/it]

⏳ [Row 133] Gemini: Rate limit (Attempt 1)

 66%|██████▌   | 132/200 [16:15<07:04,  6.24s/it]

✅ [Row 134] GPT Received: {
  "reasoning": "The Anchor text involves a mysterious death connected to family secrets and a dang...
🚀 [Row 134] Claude: Sending request...

 66%|██████▌   | 132/200 [16:16<07:04,  6.24s/it]

✅ [Row 132] GPT Received: {
  "reasoning": "The Anchor story revolves around a woman, Ivy, who is dissatisfied with her curren...
🚀 [Row 132] Claude: Sending request...

 66%|██████▌   | 132/200 [16:20<07:04,  6.24s/it]

✅ [Row 199] GPT Received: {
  "reasoning": "The Anchor story revolves around a political campaign with themes of blackmail, pe...
🚀 [Row 199] Claude: Sending request...
✅ [Row 198] Claude Received: ```json
{
  "reasoning": "The Anchor is a documentary exploring the life and teachings of yoga pione...
🏁 [Row 198] Votes: {'gemini': False, 'gpt': False, 'claude': False}

 66%|██████▌   | 132/200 [16:22<07:04,  6.24s/it]

✅ [Row 197] Gemini Received: {
  "reasoning": "The Anchor text is a fable explaining the stages of human life by attributing char...
🚀 [Row 197] GPT: Sending request...

 66%|██████▋   | 133/200 [16:23<08:49,  7.90s/it]

✅ [Row 134] Claude Received: ```json
{
  "reasoning": "Both texts involve the death of a young woman and subsequent investigation...
🏁 [Row 134] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 136] Gemini: Sending request...

 67%|██████▋   | 134/200 [16:24<06:25,  5.84s/it]

✅ [Row 132] Claude Received: ```json
{
  "reasoning": "The Anchor involves a woman (Ivy) trapped in marriage who plots to poison ...
🏁 [Row 132] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 137] Gemini: Sending request...

 67%|██████▋   | 134/200 [16:26<06:25,  5.84s/it]

✅ [Row 135] Gemini Received: {
  "reasoning": "The Anchor story centers on a woman breaking free from a pre-destined traditional ...
🚀 [Row 135] GPT: Sending request...

 67%|██████▋   | 134/200 [16:26<06:25,  5.84s/it]

✅ [Row 197] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of the stages of life and how the burde...
🚀 [Row 197] Claude: Sending request...

 67%|██████▋   | 134/200 [16:30<06:25,  5.84s/it]

✅ [Row 199] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a male politician (Blake Pellarin) facing potential ...
🏁 [Row 199] Votes: {'gemini': False, 'gpt': True, 'claude': False}

 67%|██████▋   | 134/200 [16:30<06:25,  5.84s/it]

✅ [Row 135] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of breaking societal norms, self-discovery...
🚀 [Row 135] Claude: Sending request...

 67%|██████▋   | 134/200 [16:33<06:25,  5.84s/it]

✅ [Row 137] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a d...
🚀 [Row 137] GPT: Sending request...

 67%|██████▋   | 134/200 [16:34<06:25,  5.84s/it]

✅ [Row 133] Gemini Received: {
  "reasoning": "While neither text is a strong match, Text B is narratively closer to the Anchor. ...
🚀 [Row 133] GPT: Sending request...

 67%|██████▋   | 134/200 [16:35<06:25,  5.84s/it]

✅ [Row 197] Claude Received: ```json
{
  "reasoning": "The Anchor is an allegorical fable explaining the stages of human life thr...
🏁 [Row 197] Votes: {'gemini': False, 'gpt': False, 'claude': True}

 67%|██████▋   | 134/200 [16:38<06:25,  5.84s/it]

✅ [Row 137] GPT Received: {
  "reasoning": "The Anchor story revolves around illegal activities involving baby trafficking, a ...
🚀 [Row 137] Claude: Sending request...

 67%|██████▋   | 134/200 [16:39<06:25,  5.84s/it]

✅ [Row 136] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B promin...
🚀 [Row 136] GPT: Sending request...

 67%|██████▋   | 134/200 [16:40<06:25,  5.84s/it]

✅ [Row 133] GPT Received: {
  "reasoning": "The Anchor story involves a law enforcement officer, Inspector Rizzo, who is deali...
🚀 [Row 133] Claude: Sending request...

 68%|██████▊   | 135/200 [16:41<09:50,  9.09s/it]

✅ [Row 135] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve women meeting potential romantic partners a...
🏁 [Row 135] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 138] Gemini: Sending request...

 68%|██████▊   | 135/200 [16:43<09:50,  9.09s/it]

✅ [Row 136] GPT Received: {
  "reasoning": "The Anchor story involves a hospital setting, a foreign leader under threat, a kid...
🚀 [Row 136] Claude: Sending request...

 68%|██████▊   | 136/200 [16:44<07:50,  7.36s/it]

✅ [Row 137] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a criminal enterprise involving baby trafficking, wi...
🏁 [Row 137] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 139] Gemini: Sending request...

 68%|██████▊   | 137/200 [16:48<06:40,  6.36s/it]

✅ [Row 133] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Inspector Rizzo (Flatfoot), a law enforcement office...
🏁 [Row 133] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 140] Gemini: Sending request...
✅ [Row 138] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 138] GPT: Sending request...

 69%|██████▉   | 138/200 [16:50<05:13,  5.05s/it]

✅ [Row 136] Claude Received: {
  "reasoning": "The Anchor involves a nurse kidnapping a foreign leader for personal gain while a ...
🏁 [Row 136] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 141] Gemini: Sending request...

 69%|██████▉   | 138/200 [16:53<05:13,  5.05s/it]

✅ [Row 138] GPT Received: {
  "reasoning": "The Anchor text revolves around Jacques Ménétrier's journey from a humble backgrou...
🚀 [Row 138] Claude: Sending request...

 69%|██████▉   | 138/200 [16:55<05:13,  5.05s/it]

✅ [Row 140] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a cor...
🚀 [Row 140] GPT: Sending request...

 69%|██████▉   | 138/200 [16:57<05:13,  5.05s/it]

✅ [Row 139] Gemini Received: {
  "reasoning": "The Anchor story describes a simple man who is exploited, becomes a resistance fig...
🚀 [Row 139] GPT: Sending request...

 69%|██████▉   | 138/200 [17:00<05:13,  5.05s/it]

✅ [Row 140] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve military and strategic conflicts over con...
🚀 [Row 140] Claude: Sending request...

 69%|██████▉   | 138/200 [17:00<05:13,  5.05s/it]

✅ [Row 141] Gemini Received: {
  "reasoning": "The Anchor text is about characters grappling with relationship fears, commitment ...
🚀 [Row 141] GPT: Sending request...

 69%|██████▉   | 138/200 [17:01<05:13,  5.05s/it]

✅ [Row 139] GPT Received: {
  "reasoning": "The Anchor story involves themes of betrayal, political manipulation, and rebellio...
🚀 [Row 139] Claude: Sending request...

 69%|██████▉   | 138/200 [17:04<05:13,  5.05s/it]

✅ [Row 141] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of fear of commitment, self-discovery, and...
🚀 [Row 141] Claude: Sending request...

 70%|██████▉   | 139/200 [17:09<09:13,  9.07s/it]

✅ [Row 140] Claude Received: ```json
{
  "reasoning": "Both texts involve conflict over strategic resources/projects with militar...
🏁 [Row 140] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 142] Gemini: Sending request...

 70%|███████   | 140/200 [17:09<06:28,  6.48s/it]

✅ [Row 139] Claude Received: ```json
{
  "reasoning": "Both texts involve prisoners or captives and military/political intrigue, ...
🏁 [Row 139] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 143] Gemini: Sending request...

 70%|███████   | 141/200 [17:09<04:31,  4.60s/it]

✅ [Row 138] Claude Received: ```json
{
  "reasoning": "The Anchor describes a historical tale set in France about Jacques, a youn...
🏁 [Row 138] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 144] Gemini: Sending request...

 71%|███████   | 142/200 [17:14<04:22,  4.52s/it]

✅ [Row 141] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two friends (Jacks and Peter) who both struggle with...
🏁 [Row 141] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 145] Gemini: Sending request...

 71%|███████   | 142/200 [17:18<04:22,  4.52s/it]

✅ [Row 144] Gemini Received: {
  "reasoning": "The Anchor story is about a woman's inability to let go of her love for an ex-husb...
🚀 [Row 144] GPT: Sending request...

 71%|███████   | 142/200 [17:21<04:22,  4.52s/it]

✅ [Row 145] Gemini Received: {
  "reasoning": "The Anchor text features protagonists with criminal backgrounds, a scientific inve...
🚀 [Row 145] GPT: Sending request...

 71%|███████   | 142/200 [17:23<04:22,  4.52s/it]

✅ [Row 143] Gemini Received: {
  "reasoning": "The Anchor text describes a clear narrative plot with a sequence of events, action...
🚀 [Row 143] GPT: Sending request...
✅ [Row 144] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of unrequited love, family dynamics, and t...
🚀 [Row 144] Claude: Sending request...

 71%|███████   | 142/200 [17:24<04:22,  4.52s/it]

✅ [Row 145] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve characters with a criminal background who...
🚀 [Row 145] Claude: Sending request...

 71%|███████   | 142/200 [17:26<04:22,  4.52s/it]

✅ [Row 143] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of new beginnings, social interactions, an...
🚀 [Row 143] Claude: Sending request...

 72%|███████▏  | 143/200 [17:31<07:52,  8.28s/it]

✅ [Row 144] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Marie-Louise's inability to let go of her ex-husband...
🏁 [Row 144] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 146] Gemini: Sending request...

 72%|███████▏  | 144/200 [17:33<05:54,  6.33s/it]

✅ [Row 145] Claude Received: ```json
{
  "reasoning": "The Anchor story follows two swindlers who go to prison, get released, wor...
🏁 [Row 145] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 147] Gemini: Sending request...

 72%|███████▏  | 144/200 [17:34<05:54,  6.33s/it]

✅ [Row 142] Gemini Received: {
  "reasoning": "Both Text A and Text B are narratively quite distant from the Anchor text. However...
🚀 [Row 142] GPT: Sending request...

 72%|███████▎  | 145/200 [17:36<05:00,  5.47s/it]

✅ [Row 143] Claude Received: ```json
{
  "reasoning": "The Anchor is a romantic comedy/drama about Blanche, who moves to a new pl...
🏁 [Row 143] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 148] Gemini: Sending request...

 72%|███████▎  | 145/200 [17:38<05:00,  5.47s/it]

✅ [Row 142] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of simplicity, unexpected challenges, and ...
🚀 [Row 142] Claude: Sending request...

 72%|███████▎  | 145/200 [17:40<05:00,  5.47s/it]

✅ [Row 147] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B explor...
✅ [Row 146] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A feature a protagonist who is unjustly confined (a ...
🚀 [Row 147] GPT: Sending request...
🚀 [Row 146] GPT: Sending request...

 72%|███████▎  | 145/200 [17:45<05:00,  5.47s/it]

✅ [Row 146] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of forced life choices, suffering due to s...
🚀 [Row 146] Claude: Sending request...

 72%|███████▎  | 145/200 [17:47<05:00,  5.47s/it]

✅ [Row 147] GPT Received: {
  "reasoning": "The Anchor text deals with themes of mortality, the afterlife, and the value of li...
🚀 [Row 147] Claude: Sending request...

 73%|███████▎  | 146/200 [17:48<06:39,  7.40s/it]

✅ [Row 142] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a working-class protagonist (Marcel) who has abandon...
🏁 [Row 142] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 149] Gemini: Sending request...

 74%|███████▎  | 147/200 [17:54<06:08,  6.96s/it]

✅ [Row 146] Claude Received: ```json
{
  "reasoning": "Text A shares narrative elements with the Anchor regarding forced separati...
🏁 [Row 146] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 150] Gemini: Sending request...

 74%|███████▎  | 147/200 [17:56<06:08,  6.96s/it]

⏳ [Row 150] Gemini: Rate limit (Attempt 1)

 74%|███████▍  | 148/200 [17:56<04:51,  5.61s/it]

✅ [Row 147] Claude Received: ```json
{
  "reasoning": "Both texts deal with mortality and life lessons, but Text B is narratively...
🏁 [Row 147] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 151] Gemini: Sending request...

 74%|███████▍  | 148/200 [17:58<04:51,  5.61s/it]

✅ [Row 148] Gemini Received: {
  "reasoning": "The Anchor text describes a covert international plot to control a country through...
🚀 [Row 148] GPT: Sending request...

 74%|███████▍  | 148/200 [17:58<04:51,  5.61s/it]

⏳ [Row 151] Gemini: Rate limit (Attempt 1)

 74%|███████▍  | 148/200 [17:59<04:51,  5.61s/it]

⏳ [Row 149] Gemini: Rate limit (Attempt 1)

 74%|███████▍  | 148/200 [18:02<04:51,  5.61s/it]

✅ [Row 148] GPT Received: {
  "reasoning": "The Anchor text involves a plot by foreign agents to control Brazil's natural reso...
🚀 [Row 148] Claude: Sending request...

 74%|███████▍  | 148/200 [18:05<04:51,  5.61s/it]

✅ [Row 150] Gemini Received: {
  "reasoning": "Text A is significantly closer to the Anchor. Both the Anchor and Text A center ar...
🚀 [Row 150] GPT: Sending request...

 74%|███████▍  | 148/200 [18:09<04:51,  5.61s/it]

✅ [Row 151] Gemini Received: {
  "reasoning": "The Anchor text describes a 'Will-they won't-they romance' between a wealthy man a...
🚀 [Row 151] GPT: Sending request...

 74%|███████▍  | 148/200 [18:11<04:51,  5.61s/it]

✅ [Row 149] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. The Anchor deals with the consequences of a crime,...
🚀 [Row 149] GPT: Sending request...
✅ [Row 150] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of friendship, loss, and reflection on lif...
🚀 [Row 150] Claude: Sending request...

 74%|███████▍  | 149/200 [18:12<07:25,  8.74s/it]

✅ [Row 148] Claude Received: ```json
{
  "reasoning": "The Anchor is about foreign agents using technology (subliminal broadcast ...
🏁 [Row 148] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 152] Gemini: Sending request...

 74%|███████▍  | 149/200 [18:14<07:25,  8.74s/it]

✅ [Row 151] GPT Received: {
  "reasoning": "The Anchor text revolves around a 'Will-they won't-they' romance between a wealthy...
🚀 [Row 151] Claude: Sending request...

 74%|███████▍  | 149/200 [18:19<07:25,  8.74s/it]

✅ [Row 149] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of redemption, second chances, and the con...
🚀 [Row 149] Claude: Sending request...

 75%|███████▌  | 150/200 [18:20<06:58,  8.37s/it]

✅ [Row 150] Claude Received: ```json
{
  "reasoning": "The Anchor is about five friends gathering after their friend Marta's deat...
🏁 [Row 150] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 153] Gemini: Sending request...

 75%|███████▌  | 150/200 [18:20<06:58,  8.37s/it]

✅ [Row 152] Gemini Received: {
  "reasoning": "The Anchor text explicitly states that 'Most of the novel takes place in and aroun...
🚀 [Row 152] GPT: Sending request...

 75%|███████▌  | 150/200 [18:23<06:58,  8.37s/it]

✅ [Row 152] GPT Received: {
  "reasoning": "The Anchor text 'Terra Nostra' is a complex narrative set primarily in the 16th ce...
🚀 [Row 152] Claude: Sending request...

 76%|███████▌  | 151/200 [18:24<05:43,  7.02s/it]

✅ [Row 151] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a will-they-won't-they romance between Jack (wealthy...
🏁 [Row 151] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 154] Gemini: Sending request...

 76%|███████▌  | 151/200 [18:24<05:43,  7.02s/it]

❌ [Row 154] Gemini Exception: 'candidates'

 76%|███████▌  | 151/200 [18:25<05:43,  7.02s/it]

❌ [Row 154] Gemini Exception: 'candidates'

 76%|███████▌  | 151/200 [18:27<05:43,  7.02s/it]

❌ [Row 154] Gemini Exception: 'candidates'

 76%|███████▌  | 151/200 [18:28<05:43,  7.02s/it]

🚀 [Row 154] GPT: Sending request...

 76%|███████▌  | 151/200 [18:29<05:43,  7.02s/it]

✅ [Row 153] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A share a core narrative ...
🚀 [Row 153] GPT: Sending request...

 76%|███████▌  | 152/200 [18:30<05:20,  6.68s/it]

✅ [Row 149] Claude Received: ```json
{
  "reasoning": "The Anchor follows Ben, a reformed criminal forced into a robbery that res...
🏁 [Row 149] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 155] Gemini: Sending request...

 76%|███████▌  | 152/200 [18:33<05:20,  6.68s/it]

✅ [Row 154] GPT Received: {
  "reasoning": "The Anchor text focuses on Layla's journey from facing Islamophobia in Amsterdam t...
🚀 [Row 154] Claude: Sending request...

 76%|███████▋  | 153/200 [18:34<04:41,  5.99s/it]

✅ [Row 152] Claude Received: ```json
{
  "reasoning": "The Anchor (Terra Nostra) is characterized by: (1) a multi-temporal, mysti...
🏁 [Row 152] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 156] Gemini: Sending request...

 76%|███████▋  | 153/200 [18:34<04:41,  5.99s/it]

✅ [Row 153] GPT Received: {
  "reasoning": "The Anchor story revolves around a murder mystery involving the royal family, with...
🚀 [Row 153] Claude: Sending request...

 76%|███████▋  | 153/200 [18:40<04:41,  5.99s/it]

✅ [Row 155] Gemini Received: {
  "reasoning": "The Anchor text centers on a controversial film about Jesus, 'This Is My Blood,' w...
🚀 [Row 155] GPT: Sending request...

 76%|███████▋  | 153/200 [18:40<04:41,  5.99s/it]

✅ [Row 156] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature ser...
🚀 [Row 156] GPT: Sending request...

 77%|███████▋  | 154/200 [18:42<05:02,  6.59s/it]

✅ [Row 154] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a young Muslim woman's radicalization journey—...
🏁 [Row 154] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 157] Gemini: Sending request...

 77%|███████▋  | 154/200 [18:44<05:02,  6.59s/it]

✅ [Row 155] GPT Received: {
  "reasoning": "The Anchor story revolves around a film about Jesus that causes controversy due to...
🚀 [Row 155] Claude: Sending request...
✅ [Row 156] GPT Received: {
  "reasoning": "The Anchor story revolves around fugitives working in a gold mine under a tyrannic...
🚀 [Row 156] Claude: Sending request...

 78%|███████▊  | 155/200 [18:44<03:59,  5.32s/it]

✅ [Row 153] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a wrongly accused prince, Nicodemus, who is sus...
🏁 [Row 153] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 158] Gemini: Sending request...

 78%|███████▊  | 155/200 [18:51<03:59,  5.32s/it]

✅ [Row 157] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a c...
🚀 [Row 157] GPT: Sending request...

 78%|███████▊  | 156/200 [18:51<04:14,  5.78s/it]

✅ [Row 155] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a controversial Jesus film, its actress seeking trut...
🏁 [Row 155] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 159] Gemini: Sending request...

 78%|███████▊  | 157/200 [18:55<03:35,  5.01s/it]

✅ [Row 156] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a dictator-like mine operator who exploits fugitive ...
🏁 [Row 156] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 160] Gemini: Sending request...
✅ [Row 157] GPT Received: {
  "reasoning": "The Anchor story involves a heist plot with thieves planning to steal paintings, a...
🚀 [Row 157] Claude: Sending request...

 78%|███████▊  | 157/200 [18:56<03:35,  5.01s/it]

✅ [Row 158] Gemini Received: {
  "reasoning": "The Anchor story centers on a criminal defense attorney who uncovers a wrongful co...
🚀 [Row 158] GPT: Sending request...

 78%|███████▊  | 157/200 [19:01<03:35,  5.01s/it]

✅ [Row 160] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both stories feature a protagonist who...
🚀 [Row 160] GPT: Sending request...

 79%|███████▉  | 158/200 [19:02<04:02,  5.78s/it]

✅ [Row 157] Claude Received: ```json
{
  "reasoning": "The Anchor centers on stolen paintings, thieves planning a heist, and mult...
🏁 [Row 157] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 161] Gemini: Sending request...

 79%|███████▉  | 158/200 [19:03<04:02,  5.78s/it]

✅ [Row 158] GPT Received: {
  "reasoning": "The Anchor story revolves around a defense attorney dealing with a high-profile ca...
🚀 [Row 158] Claude: Sending request...

 79%|███████▉  | 158/200 [19:05<04:02,  5.78s/it]

✅ [Row 160] GPT Received: {
  "reasoning": "The Anchor story involves a biographer who falls in love with the sister of a dece...
🚀 [Row 160] Claude: Sending request...

 79%|███████▉  | 158/200 [19:06<04:02,  5.78s/it]

✅ [Row 159] Gemini Received: {
  "reasoning": "The Anchor text features a detective (Maigret) investigating a domestic suspicion ...
🚀 [Row 159] GPT: Sending request...

 79%|███████▉  | 158/200 [19:10<04:02,  5.78s/it]

✅ [Row 159] GPT Received: {
  "reasoning": "The Anchor story involves a detective, Maigret, investigating a potential poisonin...
🚀 [Row 159] Claude: Sending request...

 80%|███████▉  | 159/200 [19:12<04:47,  7.00s/it]

✅ [Row 160] Claude Received: ```json
{
  "reasoning": "The Anchor involves a researcher investigating a death (pilot's test fligh...
🏁 [Row 160] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 162] Gemini: Sending request...

 80%|███████▉  | 159/200 [19:13<04:47,  7.00s/it]

✅ [Row 161] Gemini Received: {
  "reasoning": "The Anchor text revolves around a barber discovering hidden money within chairs he...
🚀 [Row 161] GPT: Sending request...

 80%|████████  | 160/200 [19:14<03:43,  5.58s/it]

✅ [Row 158] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a criminal defense attorney who initially believes h...
🏁 [Row 158] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 163] Gemini: Sending request...

 80%|████████  | 160/200 [19:17<03:43,  5.58s/it]

✅ [Row 161] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a protagonist who is on a quest to recove...
🚀 [Row 161] Claude: Sending request...

 80%|████████  | 160/200 [19:20<03:43,  5.58s/it]

✅ [Row 162] Gemini Received: {
  "reasoning": "Text A is narratively closer. Both the Anchor and Text A feature a protagonist who...
🚀 [Row 162] GPT: Sending request...

 80%|████████  | 161/200 [19:21<03:49,  5.89s/it]

✅ [Row 159] Claude Received: ```json
{
  "reasoning": "The Anchor involves a detective (Maigret) receiving a visit from a man who...
🏁 [Row 159] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 164] Gemini: Sending request...

 80%|████████  | 161/200 [19:24<03:49,  5.89s/it]

✅ [Row 162] GPT Received: {
  "reasoning": "The Anchor story revolves around Pier Ullman seeking revenge for his father's mist...
🚀 [Row 162] Claude: Sending request...

 81%|████████  | 162/200 [19:25<03:22,  5.34s/it]

✅ [Row 161] Claude Received: ```json
{
  "reasoning": "The Anchor follows a protagonist who must track down multiple people (the ...
🏁 [Row 161] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 165] Gemini: Sending request...

 81%|████████  | 162/200 [19:27<03:22,  5.34s/it]

⏳ [Row 165] Gemini: Rate limit (Attempt 1)

 81%|████████  | 162/200 [19:27<03:22,  5.34s/it]

✅ [Row 163] Gemini Received: {
  "reasoning": "The Anchor text features an older protagonist who is meant to be honored on a sign...
🚀 [Row 163] GPT: Sending request...

 81%|████████  | 162/200 [19:31<03:22,  5.34s/it]

✅ [Row 163] GPT Received: {
  "reasoning": "The Anchor story revolves around a family gathering for a celebration, with initia...
🚀 [Row 163] Claude: Sending request...

 82%|████████▏ | 163/200 [19:32<03:38,  5.92s/it]

✅ [Row 162] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Pier infiltrating his estranged father's family diam...
🏁 [Row 162] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 166] Gemini: Sending request...

 82%|████████▏ | 163/200 [19:34<03:38,  5.92s/it]

✅ [Row 164] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B explore the...
🚀 [Row 164] GPT: Sending request...

 82%|████████▏ | 163/200 [19:38<03:38,  5.92s/it]

✅ [Row 164] GPT Received: {
  "reasoning": "The Anchor text revolves around a family dynamic, focusing on themes of disillusio...
🚀 [Row 164] Claude: Sending request...

 82%|████████▏ | 164/200 [19:40<03:49,  6.38s/it]

✅ [Row 163] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a family celebration where initial complications (ch...
🏁 [Row 163] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 167] Gemini: Sending request...

 82%|████████▏ | 164/200 [19:41<03:49,  6.38s/it]

✅ [Row 166] Gemini Received: {
  "reasoning": "The Anchor text features four short stories, one of which, 'Queen Elena,' directly...
🚀 [Row 166] GPT: Sending request...

 82%|████████▏ | 164/200 [19:46<03:49,  6.38s/it]

✅ [Row 165] Gemini Received: {
  "reasoning": "The Anchor text features a young man drawn into an illicit love triangle to observ...
🚀 [Row 165] GPT: Sending request...

 82%|████████▏ | 164/200 [19:47<03:49,  6.38s/it]

✅ [Row 166] GPT Received: {
  "reasoning": "The Anchor text consists of four vignettes, each dealing with themes of infidelity...
🚀 [Row 166] Claude: Sending request...

 82%|████████▎ | 165/200 [19:47<03:59,  6.84s/it]

✅ [Row 164] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a family trapped in disappointment and delusion, wit...
🏁 [Row 164] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 168] Gemini: Sending request...

 82%|████████▎ | 165/200 [19:50<03:59,  6.84s/it]

⏳ [Row 168] Gemini: Rate limit (Attempt 1)

 82%|████████▎ | 165/200 [19:55<03:59,  6.84s/it]

✅ [Row 165] GPT Received: {
  "reasoning": "The Anchor story involves a young man who becomes embroiled in a murder mystery af...
🚀 [Row 165] Claude: Sending request...

 83%|████████▎ | 166/200 [19:57<04:17,  7.57s/it]

✅ [Row 166] Claude Received: ```json
{
  "reasoning": "The Anchor consists of four episodic vignettes about sexual misadventures,...
🏁 [Row 166] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 169] Gemini: Sending request...

 83%|████████▎ | 166/200 [19:58<04:17,  7.57s/it]

✅ [Row 168] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a d...
🚀 [Row 168] GPT: Sending request...

 83%|████████▎ | 166/200 [20:01<04:17,  7.57s/it]

✅ [Row 167] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a cor...
🚀 [Row 167] GPT: Sending request...

 83%|████████▎ | 166/200 [20:02<04:17,  7.57s/it]

✅ [Row 168] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a community facing an external threat fro...
🚀 [Row 168] Claude: Sending request...

 84%|████████▎ | 167/200 [20:04<04:10,  7.60s/it]

✅ [Row 165] Claude Received: ```json
{
  "reasoning": "Both texts involve illicit relationships and murder, but Text B is narrati...
🏁 [Row 165] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 170] Gemini: Sending request...

 84%|████████▎ | 167/200 [20:05<04:10,  7.60s/it]

✅ [Row 167] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a group of young people encountering a de...
🚀 [Row 167] Claude: Sending request...

 84%|████████▍ | 168/200 [20:10<03:40,  6.89s/it]

✅ [Row 168] Claude Received: {
  "reasoning": "The Anchor story centers on a Chinese village under Japanese invasion where a head...
🏁 [Row 168] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 171] Gemini: Sending request...

 84%|████████▍ | 168/200 [20:10<03:40,  6.89s/it]

⏳ [Row 171] Gemini: Rate limit (Attempt 1)

 84%|████████▍ | 169/200 [20:13<02:57,  5.71s/it]

✅ [Row 167] Claude Received: ```json
{
  "reasoning": "The Anchor follows a group of travelers who are lured into a trap by a tow...
🏁 [Row 167] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 172] Gemini: Sending request...

 84%|████████▍ | 169/200 [20:14<02:57,  5.71s/it]

✅ [Row 169] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist who, after being wronged by a powerful indi...
🚀 [Row 169] GPT: Sending request...

 84%|████████▍ | 169/200 [20:14<02:57,  5.71s/it]

✅ [Row 170] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature a young protago...
🚀 [Row 170] GPT: Sending request...

 84%|████████▍ | 169/200 [20:15<02:57,  5.71s/it]

⏳ [Row 172] Gemini: Rate limit (Attempt 1)

 84%|████████▍ | 169/200 [20:21<02:57,  5.71s/it]

✅ [Row 170] GPT Received: {
  "reasoning": "The Anchor story involves a young protagonist who inadvertently gets involved in a...
🚀 [Row 170] Claude: Sending request...

 84%|████████▍ | 169/200 [20:21<02:57,  5.71s/it]

✅ [Row 171] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature mis...
🚀 [Row 171] GPT: Sending request...

 84%|████████▍ | 169/200 [20:23<02:57,  5.71s/it]

✅ [Row 169] GPT Received: {
  "reasoning": "The Anchor story revolves around Horacia Somorostro, who seeks revenge after being...
🚀 [Row 169] Claude: Sending request...

 84%|████████▍ | 169/200 [20:25<02:57,  5.71s/it]

✅ [Row 172] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center on t...
🚀 [Row 172] GPT: Sending request...

 84%|████████▍ | 169/200 [20:27<02:57,  5.71s/it]

✅ [Row 171] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve young characters who are expelled from sc...
🚀 [Row 171] Claude: Sending request...

 85%|████████▌ | 170/200 [20:29<04:26,  8.88s/it]

✅ [Row 170] Claude Received: ```json
{
  "reasoning": "The Anchor follows a young protagonist (Dragon) who is avoiding his respon...
🏁 [Row 170] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 173] Gemini: Sending request...

 85%|████████▌ | 170/200 [20:30<04:26,  8.88s/it]

✅ [Row 172] GPT Received: {
  "reasoning": "The Anchor story involves themes of love, betrayal, and revenge within a criminal ...
🚀 [Row 172] Claude: Sending request...

 86%|████████▌ | 171/200 [20:33<03:32,  7.34s/it]

✅ [Row 169] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a wrongfully imprisoned woman who, upon releas...
🏁 [Row 169] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 174] Gemini: Sending request...

 86%|████████▌ | 171/200 [20:33<03:32,  7.34s/it]

⏳ [Row 174] Gemini: Rate limit (Attempt 1)

 86%|████████▌ | 172/200 [20:35<02:43,  5.82s/it]

✅ [Row 171] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve young protagonists in institutional setting...
🏁 [Row 171] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 175] Gemini: Sending request...

 86%|████████▌ | 172/200 [20:37<02:43,  5.82s/it]

⏳ [Row 174] Gemini: Rate limit (Attempt 2)

 86%|████████▌ | 172/200 [20:39<02:43,  5.82s/it]

✅ [Row 173] Gemini Received: {
  "reasoning": "The Anchor text features protagonists (fishermen) who are victims of a criminal (g...
🚀 [Row 173] GPT: Sending request...

 86%|████████▋ | 173/200 [20:41<02:35,  5.75s/it]

✅ [Row 172] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a love triangle involving deception, revenge, and ga...
🏁 [Row 172] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 176] Gemini: Sending request...

 86%|████████▋ | 173/200 [20:44<02:35,  5.75s/it]

✅ [Row 173] GPT Received: {
  "reasoning": "The Anchor story revolves around two fishermen dealing with a gangster who extorts...
🚀 [Row 173] Claude: Sending request...
✅ [Row 175] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a s...
🚀 [Row 175] GPT: Sending request...

 86%|████████▋ | 173/200 [20:47<02:35,  5.75s/it]

⏳ [Row 176] Gemini: Rate limit (Attempt 1)

 86%|████████▋ | 173/200 [20:48<02:35,  5.75s/it]

✅ [Row 175] GPT Received: {
  "reasoning": "The Anchor story involves a love triangle, betrayal, and a journey through a harsh...
🚀 [Row 175] Claude: Sending request...

 86%|████████▋ | 173/200 [20:51<02:35,  5.75s/it]

✅ [Row 174] Gemini Received: {
  "reasoning": "Text A is a crime/mystery thriller involving murder and a police investigation, wh...
🚀 [Row 174] GPT: Sending request...

 87%|████████▋ | 174/200 [20:54<03:28,  8.03s/it]

✅ [Row 173] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two fishermen being extorted by a gangster, one fish...
🏁 [Row 173] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 177] Gemini: Sending request...

 87%|████████▋ | 174/200 [20:56<03:28,  8.03s/it]

✅ [Row 174] GPT Received: {
  "reasoning": "The Anchor story revolves around Stella's empty life in New York, her relationship...
🚀 [Row 174] Claude: Sending request...

 88%|████████▊ | 175/200 [20:57<02:41,  6.47s/it]

✅ [Row 175] Claude Received: ```json
{
  "reasoning": "Both texts involve pursuit in harsh desert/wilderness settings with romant...
🏁 [Row 175] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 178] Gemini: Sending request...

 88%|████████▊ | 175/200 [21:02<02:41,  6.47s/it]

✅ [Row 177] Gemini Received: {
  "reasoning": "Both Text A and Text B are biographical narratives, but Text A shares a more signi...
🚀 [Row 177] GPT: Sending request...

 88%|████████▊ | 176/200 [21:04<02:43,  6.80s/it]

✅ [Row 174] Claude Received: ```json
{
  "reasoning": "The Anchor follows Stella, who lives an empty life with casual relationshi...
🏁 [Row 174] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 179] Gemini: Sending request...

 88%|████████▊ | 176/200 [21:07<02:43,  6.80s/it]

✅ [Row 177] GPT Received: {
  "reasoning": "The Anchor text is a biographical story about the life and artistic struggles of H...
🚀 [Row 177] Claude: Sending request...

 88%|████████▊ | 176/200 [21:07<02:43,  6.80s/it]

✅ [Row 176] Gemini Received: {
  "reasoning": "The Anchor text features a wayward nun, a convent, and themes of religious transgr...
🚀 [Row 176] GPT: Sending request...

 88%|████████▊ | 176/200 [21:13<02:43,  6.80s/it]

✅ [Row 176] GPT Received: {
  "reasoning": "The Anchor story involves a nun who leaves her convent, influenced by an evil mins...
🚀 [Row 176] Claude: Sending request...

 88%|████████▊ | 176/200 [21:14<02:43,  6.80s/it]

✅ [Row 178] Gemini Received: {
  "reasoning": "The Anchor text features a complex love triangle entangled with political influenc...
🚀 [Row 178] GPT: Sending request...

 88%|████████▊ | 177/200 [21:15<03:03,  7.97s/it]

✅ [Row 177] Claude Received: ```json
{
  "reasoning": "The Anchor follows French composer Hector Berlioz through his artistic str...
🏁 [Row 177] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 180] Gemini: Sending request...

 88%|████████▊ | 177/200 [21:16<03:03,  7.97s/it]

✅ [Row 179] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. While Text A shares the core theme of ...
🚀 [Row 179] GPT: Sending request...

 88%|████████▊ | 177/200 [21:18<03:03,  7.97s/it]

✅ [Row 178] GPT Received: {
  "reasoning": "The Anchor text revolves around a love triangle involving a dancer, a politician, ...
🚀 [Row 178] Claude: Sending request...

 88%|████████▊ | 177/200 [21:21<03:03,  7.97s/it]

✅ [Row 179] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of revenge and justice, with a focus on av...
🚀 [Row 179] Claude: Sending request...

 89%|████████▉ | 178/200 [21:23<02:57,  8.06s/it]

✅ [Row 176] Claude Received: ```json
{
  "reasoning": "Both texts involve religious/supernatural themes, but Text A is narrativel...
🏁 [Row 176] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 181] Gemini: Sending request...

 90%|████████▉ | 179/200 [21:25<02:10,  6.20s/it]

✅ [Row 178] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a romantic triangle involving class and political power...
🏁 [Row 178] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 182] Gemini: Sending request...

 90%|█████████ | 180/200 [21:28<01:46,  5.32s/it]

✅ [Row 179] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B are westerns involving revenge/investigation, but T...
🏁 [Row 179] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 183] Gemini: Sending request...

 90%|█████████ | 180/200 [21:34<01:46,  5.32s/it]

✅ [Row 181] Gemini Received: {
  "reasoning": "The Anchor text describes humanity's long-term struggle, involving an alien perspe...
🚀 [Row 181] GPT: Sending request...

 90%|█████████ | 180/200 [21:36<01:46,  5.32s/it]

✅ [Row 183] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A revolve aro...
🚀 [Row 183] GPT: Sending request...

 90%|█████████ | 180/200 [21:39<01:46,  5.32s/it]

✅ [Row 182] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 182] GPT: Sending request...

 90%|█████████ | 180/200 [21:39<01:46,  5.32s/it]

⏳ [Row 180] Gemini: Rate limit (Attempt 1)

 90%|█████████ | 180/200 [21:41<01:46,  5.32s/it]

✅ [Row 181] GPT Received: {
  "reasoning": "The Anchor text revolves around an extraterrestrial's perspective on Earth and a s...
🚀 [Row 181] Claude: Sending request...

 90%|█████████ | 180/200 [21:41<01:46,  5.32s/it]

✅ [Row 183] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve imposters who are mistaken for someone th...
🚀 [Row 183] Claude: Sending request...

 90%|█████████ | 180/200 [21:44<01:46,  5.32s/it]

✅ [Row 182] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a journey with family members who have be...
🚀 [Row 182] Claude: Sending request...

 90%|█████████ | 180/200 [21:45<01:46,  5.32s/it]

⏳ [Row 180] Gemini: Rate limit (Attempt 2)

 90%|█████████ | 181/200 [21:50<03:13, 10.16s/it]

✅ [Row 183] Claude Received: ```json
{
  "reasoning": "The Anchor involves two rural men thrust into film production who must mai...
🏁 [Row 183] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 184] Gemini: Sending request...

 91%|█████████ | 182/200 [21:50<02:09,  7.22s/it]

✅ [Row 181] Claude Received: ```json
{
  "reasoning": "The Anchor is a science fiction narrative about an alien on Earth narratin...
🏁 [Row 181] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 185] Gemini: Sending request...

 92%|█████████▏| 183/200 [21:55<01:50,  6.48s/it]

✅ [Row 182] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a parolee (Will) trying to establish himself as a gu...
🏁 [Row 182] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 186] Gemini: Sending request...

 92%|█████████▏| 183/200 [21:58<01:50,  6.48s/it]

✅ [Row 184] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a m...
🚀 [Row 184] GPT: Sending request...

 92%|█████████▏| 183/200 [22:02<01:50,  6.48s/it]

✅ [Row 185] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 185] GPT: Sending request...

 92%|█████████▏| 183/200 [22:03<01:50,  6.48s/it]

✅ [Row 184] GPT Received: {
  "reasoning": "The Anchor story involves a plan to kidnap a child for ransom, but the plan backfi...
🚀 [Row 184] Claude: Sending request...

 92%|█████████▏| 183/200 [22:04<01:50,  6.48s/it]

✅ [Row 180] Gemini Received: {
  "reasoning": "The Anchor story centers on an individual's decision to commit a crime (kidnapping...
🚀 [Row 180] GPT: Sending request...

 92%|█████████▏| 183/200 [22:09<01:50,  6.48s/it]

✅ [Row 180] GPT Received: {
  "reasoning": "The Anchor story revolves around a man who kidnaps a woman by mistake and has to d...
🚀 [Row 180] Claude: Sending request...

 92%|█████████▏| 183/200 [22:10<01:50,  6.48s/it]

✅ [Row 185] GPT Received: {
  "reasoning": "The Anchor story revolves around a struggling novelist who takes a job at an escor...
🚀 [Row 185] Claude: Sending request...

 92%|█████████▏| 184/200 [22:11<02:27,  9.23s/it]

✅ [Row 184] Claude Received: ```json
{
  "reasoning": "The Anchor involves an elaborate kidnapping scheme by an aging villain tha...
🏁 [Row 184] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 187] Gemini: Sending request...

 92%|█████████▏| 184/200 [22:14<02:27,  9.23s/it]

⏳ [Row 186] Gemini: Rate limit (Attempt 1)

 92%|█████████▎| 185/200 [22:16<02:02,  8.17s/it]

✅ [Row 180] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on an incompetent kidnapper who accidentally captures t...
🏁 [Row 180] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 188] Gemini: Sending request...

 92%|█████████▎| 185/200 [22:19<02:02,  8.17s/it]

⏳ [Row 188] Gemini: Rate limit (Attempt 1)

 93%|█████████▎| 186/200 [22:20<01:34,  6.75s/it]

✅ [Row 185] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a struggling novelist who takes a secret job as an e...
🏁 [Row 185] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 189] Gemini: Sending request...

 93%|█████████▎| 186/200 [22:32<01:34,  6.75s/it]

✅ [Row 189] Gemini Received: {
  "reasoning": "The Anchor story centers on a teenage girl forming a unique, almost magical bond w...
🚀 [Row 189] GPT: Sending request...

 93%|█████████▎| 186/200 [22:32<01:34,  6.75s/it]

✅ [Row 188] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist (Paul) whose active search for a loved one ...
🚀 [Row 188] GPT: Sending request...

 93%|█████████▎| 186/200 [22:39<01:34,  6.75s/it]

✅ [Row 188] GPT Received: {
  "reasoning": "The Anchor story revolves around a Belgian emigrant, Paul, searching for his pen-p...
🚀 [Row 188] Claude: Sending request...
✅ [Row 189] GPT Received: {
  "reasoning": "The Anchor story 'Windstorm' is about a teenage girl, Mika, who discovers her uniq...
🚀 [Row 189] Claude: Sending request...

 93%|█████████▎| 186/200 [22:41<01:34,  6.75s/it]

❌ [Row 187] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 93%|█████████▎| 186/200 [22:41<01:34,  6.75s/it]

✅ [Row 186] Gemini Received: {
  "reasoning": "The Anchor story centers on Merlin, a powerful individual who has created a sentie...
🚀 [Row 186] GPT: Sending request...

 94%|█████████▎| 187/200 [22:48<02:52, 13.28s/it]

✅ [Row 189] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve young protagonists and magical elements, bu...
🏁 [Row 189] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 190] Gemini: Sending request...

 94%|█████████▍| 188/200 [22:49<01:53,  9.48s/it]

✅ [Row 188] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B differ significantly from the Anchor in theme and p...
🏁 [Row 188] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 191] Gemini: Sending request...
⏳ [Row 190] Gemini: Rate limit (Attempt 1)
✅ [Row 186] GPT Received: {
  "reasoning": "The Anchor text revolves around Merlin's investigation into assassination attempts...
🚀 [Row 186] Claude: Sending request...

 94%|█████████▍| 189/200 [22:59<01:47,  9.77s/it]

✅ [Row 191] Gemini Received: {
  "reasoning": "The Anchor text describes brothers operating an illegal smuggling network across a...
🚀 [Row 191] GPT: Sending request...
✅ [Row 186] Claude Received: ```json
{
  "reasoning": "The Anchor involves a protagonist (Merlin) who has been building a powerfu...
🏁 [Row 186] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 192] Gemini: Sending request...

 94%|█████████▍| 189/200 [23:05<01:47,  9.77s/it]

✅ [Row 187] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 187] GPT: Sending request...

 94%|█████████▍| 189/200 [23:06<01:47,  9.77s/it]

✅ [Row 190] Gemini Received: {
  "reasoning": "The Anchor text revolves around a mysterious stranger with amnesia whose presence ...
🚀 [Row 190] GPT: Sending request...

 94%|█████████▍| 189/200 [23:08<01:47,  9.77s/it]

✅ [Row 191] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of smuggling, economic hardship, and the c...
🚀 [Row 191] Claude: Sending request...

 94%|█████████▍| 189/200 [23:09<01:47,  9.77s/it]

✅ [Row 187] GPT Received: {
  "reasoning": "The Anchor text revolves around mistaken identity, theft, and a series of dangerou...
🚀 [Row 187] Claude: Sending request...

 94%|█████████▍| 189/200 [23:12<01:47,  9.77s/it]

✅ [Row 190] GPT Received: {
  "reasoning": "The Anchor story revolves around a mysterious Englishman who changes the lives of ...
🚀 [Row 190] Claude: Sending request...

 94%|█████████▍| 189/200 [23:14<01:47,  9.77s/it]

✅ [Row 192] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 192] GPT: Sending request...

 95%|█████████▌| 190/200 [23:17<02:01, 12.19s/it]

✅ [Row 187] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a case of mistaken identity involving twin sisters, ...
🏁 [Row 187] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 193] Gemini: Sending request...
✅ [Row 191] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on brothers operating across the East/West German...
🏁 [Row 191] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 194] Gemini: Sending request...

 96%|█████████▌| 192/200 [23:19<00:56,  7.12s/it]

✅ [Row 190] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a mysterious stranger (found unconscious on a ...
🏁 [Row 190] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 195] Gemini: Sending request...

 96%|█████████▌| 192/200 [23:20<00:56,  7.12s/it]

✅ [Row 192] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve protagonists who face significant persona...
🚀 [Row 192] Claude: Sending request...

 96%|█████████▌| 192/200 [23:25<00:56,  7.12s/it]

⏳ [Row 193] Gemini: Rate limit (Attempt 1)

 96%|█████████▌| 192/200 [23:26<00:56,  7.12s/it]

✅ [Row 194] Gemini Received: {
  "reasoning": "The Anchor story describes an aging painter's meticulous, then frantic, struggle a...
🚀 [Row 194] GPT: Sending request...

 96%|█████████▋| 193/200 [23:30<00:55,  7.98s/it]

✅ [Row 192] Claude Received: ```json
{
  "reasoning": "The Anchor follows a failing actor who, frustrated with his career and cri...
🏁 [Row 192] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 196] Gemini: Sending request...

 96%|█████████▋| 193/200 [23:31<00:55,  7.98s/it]

✅ [Row 194] GPT Received: {
  "reasoning": "The Anchor text focuses on an artist, Antonio López García, who is dealing with th...
🚀 [Row 194] Claude: Sending request...

 96%|█████████▋| 193/200 [23:36<00:55,  7.98s/it]

⏳ [Row 195] Gemini: Rate limit (Attempt 1)

 96%|█████████▋| 193/200 [23:39<00:55,  7.98s/it]

✅ [Row 193] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor describes a story centered ...
🚀 [Row 193] GPT: Sending request...

 97%|█████████▋| 194/200 [23:40<00:50,  8.37s/it]

✅ [Row 194] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on an aging artist (López) racing against time, weather...
🏁 [Row 194] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 197] Gemini: Sending request...

 97%|█████████▋| 194/200 [23:40<00:50,  8.37s/it]

✅ [Row 196] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 196] GPT: Sending request...
⏳ [Row 195] Gemini: Rate limit (Attempt 2)

 97%|█████████▋| 194/200 [23:41<00:50,  8.37s/it]

⏳ [Row 197] Gemini: Rate limit (Attempt 1)

 97%|█████████▋| 194/200 [23:43<00:50,  8.37s/it]

✅ [Row 193] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of captivity, intrigue, betrayal, and esca...
🚀 [Row 193] Claude: Sending request...

 97%|█████████▋| 194/200 [23:45<00:50,  8.37s/it]

⏳ [Row 195] Gemini: Rate limit (Attempt 3)

 97%|█████████▋| 194/200 [23:46<00:50,  8.37s/it]

✅ [Row 196] GPT Received: {
  "reasoning": "The Anchor story revolves around the challenges and eventual triumph associated wi...
🚀 [Row 196] Claude: Sending request...

 97%|█████████▋| 194/200 [23:51<00:50,  8.37s/it]

🚀 [Row 195] GPT: Sending request...

 98%|█████████▊| 195/200 [23:53<00:48,  9.67s/it]

✅ [Row 193] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on Napoleon's imprisonment and a complex escape p...
🏁 [Row 193] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 198] Gemini: Sending request...

 98%|█████████▊| 196/200 [23:54<00:29,  7.29s/it]

✅ [Row 196] Claude Received: ```json
{
  "reasoning": "Text A shares significant narrative elements with the Anchor: both are Blo...
🏁 [Row 196] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 199] Gemini: Sending request...

 98%|█████████▊| 196/200 [23:56<00:29,  7.29s/it]

✅ [Row 197] Gemini Received: {
  "reasoning": "The Anchor text explains the origin of human life stages, positing that beyond thi...
🚀 [Row 197] GPT: Sending request...
✅ [Row 195] GPT Received: {
  "reasoning": "The Anchor text focuses on the disintegration of a marriage, the interactions and ...
🚀 [Row 195] Claude: Sending request...

 98%|█████████▊| 196/200 [24:02<00:29,  7.29s/it]

✅ [Row 198] Gemini Received: {
  "reasoning": "The Anchor text describes a documentary that 'depicts the life and work' of a hist...
🚀 [Row 198] GPT: Sending request...

 98%|█████████▊| 196/200 [24:03<00:29,  7.29s/it]

✅ [Row 199] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B delve into ...
🚀 [Row 199] GPT: Sending request...

 98%|█████████▊| 196/200 [24:04<00:29,  7.29s/it]

✅ [Row 197] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of the human life cycle and the burdens...
🚀 [Row 197] Claude: Sending request...

 98%|█████████▊| 197/200 [24:05<00:24,  8.29s/it]

✅ [Row 195] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a marriage disintegrating in real-time, with the husban...
🏁 [Row 195] Votes: {'gemini': None, 'gpt': False, 'claude': True}

 98%|█████████▊| 197/200 [24:08<00:24,  8.29s/it]

✅ [Row 198] GPT Received: {
  "reasoning": "The Anchor text focuses on the life and work of Tirumalai Krishnamacharya, explori...
🚀 [Row 198] Claude: Sending request...
✅ [Row 199] GPT Received: {
  "reasoning": "The Anchor story revolves around a political campaign with themes of scandal, blac...
🚀 [Row 199] Claude: Sending request...

 99%|█████████▉| 198/200 [24:13<00:16,  8.26s/it]

✅ [Row 197] Claude Received: ```json
{
  "reasoning": "The Anchor presents a thematic allegory about the stages of human life, wh...
🏁 [Row 197] Votes: {'gemini': True, 'gpt': False, 'claude': True}

100%|██████████| 200/200 [24:15<00:00,  7.28s/it]

✅ [Row 198] Claude Received: ```json
{
  "reasoning": "The Anchor text focuses on a documentary exploring the life and work of yo...
🏁 [Row 198] Votes: {'gemini': False, 'gpt': False, 'claude': False}
✅ [Row 199] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a politician facing blackmail from a former mentor w...
🏁 [Row 199] Votes: {'gemini': False, 'gpt': True, 'claude': False}

--- Done ---

## 3. Final Evaluation
We evaluate the ensemble's performance against the ground truth.
Usually, this yields a higher F1-score than any single model alone.

In [ ]:
if 'text_a_is_closer' in df_dev.columns:
    acc = (df_dev['text_a_is_closer'] == df_dev['prediction']).mean()
    print(f"Final Accuracy: {acc:.4f}")

failed_count = sum(1 for d in details_map.values() if "FAILED_ALL" in d)
print(f"Rows with complete API failure (fallback used): {failed_count}")

import zipfile
from google.colab import files

sub_df = df_dev[['prediction']].rename(columns={'prediction': 'text_a_is_closer'})
sub_df.to_json('track_a.jsonl', orient='records', lines=True)

with zipfile.ZipFile('submission_robust.zip', 'w', zipfile.ZIP_DEFLATED) as z:
    z.write('track_a.jsonl')

print("Created submission_robust.zip")
files.download('submission_robust.zip')

Final Accuracy: 0.7700
Rows with complete API failure (fallback used): 0
Created submission_robust.zip

In [ ]:
import ast

def parse_vote_details(detail_str):
    try:
        return ast.literal_eval(detail_str)
    except:
        return {}

logs_df = df_dev.copy()

votes_expanded = logs_df['votes_detail'].apply(parse_vote_details).apply(pd.Series)

detailed_logs = pd.concat([
    logs_df[['anchor_text', 'text_a_is_closer', 'prediction']],
    votes_expanded
], axis=1)

detailed_logs = detailed_logs.rename(columns={
    'gemini': 'Vote_Gemini',
    'gpt': 'Vote_GPT',
    'claude': 'Vote_Claude',
    'prediction': 'Final_Ensemble_Prediction',
    'text_a_is_closer': 'Ground_Truth'
})

def has_disagreement(row):
    votes = [row['Vote_Gemini'], row['Vote_GPT'], row['Vote_Claude']]
    valid_votes = [v for v in votes if v is not None]
    if not valid_votes: return False
    return len(set(valid_votes)) > 1

disagreements = detailed_logs[detailed_logs.apply(has_disagreement, axis=1)]

print(f"Total rows with disagreement: {len(disagreements)}")
if not disagreements.empty:
    print("\n--- Sample Disagreements ---")
    display(disagreements[['Vote_Gemini', 'Vote_GPT', 'Vote_Claude', 'Final_Ensemble_Prediction', 'Ground_Truth']].head())

log_filename = 'full_model_logs.csv'
detailed_logs.to_csv(log_filename, index=True)

print(f"\nFull logs saved to {log_filename}")
files.download(log_filename)

Total rows with disagreement: 75

--- Sample Disagreements ---

   Vote_Gemini  Vote_GPT Vote_Claude  Final_Ensemble_Prediction  Ground_Truth
1         True      True       False                       True          True
3         True     False       False                      False         False
5         True     False        True                       True         False
9         None      True       False                      False          True
11        None     False        True                       True          True

Full logs saved to full_model_logs.csv

In [ ]:
print("--- Starting Robust Ensemble Prediction ---")
rows = df_test.to_dict('records')
results_map = {}
details_map = {}

with ThreadPoolExecutor(max_workers=4) as executor:
    futures = [executor.submit(get_ensemble_prediction, row, i) for i, row in enumerate(rows)]
    for future in tqdm(as_completed(futures), total=len(rows)):
        idx, res, det = future.result()
        results_map[idx] = res
        details_map[idx] = det

df_test['prediction'] = [results_map[i] for i in range(len(rows))]
df_test['votes_detail'] = [str(details_map[i]) for i in range(len(rows))]

print("\n--- Done ---")

--- Starting Robust Ensemble Prediction ---
🚀 [Row 0] Gemini: Sending request...
🚀 [Row 1] Gemini: Sending request...
🚀 [Row 2] Gemini: Sending request...
🚀 [Row 3] Gemini: Sending request...

  0%|          | 0/400 [00:08<?, ?it/s]

✅ [Row 0] Gemini Received: {
  "reasoning": "Text B shares significant narrative elements with the Anchor. Both are set in a hi...
🚀 [Row 0] GPT: Sending request...

  0%|          | 0/400 [00:09<?, ?it/s]

✅ [Row 2] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a r...
🚀 [Row 2] GPT: Sending request...

  0%|          | 0/400 [00:09<?, ?it/s]

✅ [Row 1] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 1] GPT: Sending request...

  0%|          | 0/400 [00:13<?, ?it/s]

✅ [Row 3] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a m...
🚀 [Row 3] GPT: Sending request...

  0%|          | 0/400 [00:13<?, ?it/s]

✅ [Row 0] GPT Received: {
  "reasoning": "The Anchor story revolves around a bullied student, Leo, who infects his peers wit...
🚀 [Row 0] Claude: Sending request...

  0%|          | 0/400 [00:14<?, ?it/s]

✅ [Row 2] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a prince under a spell or disguise who ul...
🚀 [Row 2] Claude: Sending request...

  0%|          | 0/400 [00:15<?, ?it/s]

✅ [Row 1] GPT Received: {
  "reasoning": "The Anchor story and Text B both focus on a young child dealing with a troubled fa...
🚀 [Row 1] Claude: Sending request...

  0%|          | 0/400 [00:19<?, ?it/s]

✅ [Row 3] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of power, betrayal, and murder within a pol...
🚀 [Row 3] Claude: Sending request...

  0%|          | 1/400 [00:20<2:14:54, 20.29s/it]

✅ [Row 0] Claude Received: ```json
{
  "reasoning": "Text B is narratively closer to the Anchor. Both stories center on a high ...
🏁 [Row 0] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 4] Gemini: Sending request...

  0%|          | 2/400 [00:24<1:13:34, 11.09s/it]

✅ [Row 2] Claude Received: ```json
{
  "reasoning": "Both texts involve transformation and magical elements, but Text B is narr...
🏁 [Row 2] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 5] Gemini: Sending request...

  1%|          | 3/400 [00:29<52:37,  7.95s/it]

✅ [Row 1] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B share narrative elements with the Anchor about trou...
🏁 [Row 1] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 6] Gemini: Sending request...

  1%|          | 4/400 [00:30<34:32,  5.23s/it]

✅ [Row 3] Claude Received: ```json
{
  "reasoning": "Both texts involve seduction and murder plots, but Text A is narratively c...
🏁 [Row 3] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 7] Gemini: Sending request...

  1%|          | 4/400 [00:36<34:32,  5.23s/it]

⏳ [Row 4] Gemini: Rate limit (Attempt 1)

  1%|          | 4/400 [00:44<34:32,  5.23s/it]

✅ [Row 5] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A involve a m...
🚀 [Row 5] GPT: Sending request...

  1%|          | 4/400 [00:47<34:32,  5.23s/it]

✅ [Row 6] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 6] GPT: Sending request...

  1%|          | 4/400 [00:49<34:32,  5.23s/it]

✅ [Row 5] GPT Received: {
  "reasoning": "The Anchor story involves a murder mystery with a central character who is suspect...
🚀 [Row 5] Claude: Sending request...

  1%|          | 4/400 [00:53<34:32,  5.23s/it]

✅ [Row 6] GPT Received: {
  "reasoning": "The Anchor text revolves around Ben Givens, a retired cardiologist who, after bein...
🚀 [Row 6] Claude: Sending request...

  1%|          | 4/400 [00:55<34:32,  5.23s/it]

✅ [Row 4] Gemini Received: {
  "reasoning": "The Anchor text features a young protagonist who undertakes a difficult, selfless ...
🚀 [Row 4] GPT: Sending request...

  1%|▏         | 5/400 [00:58<1:29:13, 13.55s/it]

✅ [Row 5] Claude Received: ```json
{
  "reasoning": "The Anchor story follows a janitor who becomes entangled in a murder inves...
🏁 [Row 5] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 8] Gemini: Sending request...

  1%|▏         | 5/400 [00:58<1:29:13, 13.55s/it]

✅ [Row 7] Gemini Received: {
  "reasoning": "The Anchor story describes a film that uses the pursuit of a lost cat as a vehicle...
🚀 [Row 7] GPT: Sending request...

  1%|▏         | 5/400 [01:01<1:29:13, 13.55s/it]

✅ [Row 4] GPT Received: {
  "reasoning": "The Anchor story revolves around a young boy, Ahmad, who goes on a quest to return...
🚀 [Row 4] Claude: Sending request...

  2%|▏         | 6/400 [01:02<1:08:09, 10.38s/it]

✅ [Row 6] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories center on a prota...
🏁 [Row 6] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 9] Gemini: Sending request...

  2%|▏         | 6/400 [01:06<1:08:09, 10.38s/it]

✅ [Row 7] GPT Received: {
  "reasoning": "The Anchor story focuses on a young woman in Paris who loses her cat, leading to a...
🚀 [Row 7] Claude: Sending request...

  2%|▏         | 6/400 [01:12<1:08:09, 10.38s/it]

✅ [Row 9] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A are set in ...
🚀 [Row 9] GPT: Sending request...

  2%|▏         | 7/400 [01:14<1:10:40, 10.79s/it]

✅ [Row 4] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a young student who accidentally takes his classmate...
🏁 [Row 4] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 10] Gemini: Sending request...

  2%|▏         | 8/400 [01:15<51:23,  7.86s/it]

✅ [Row 7] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a young woman searching for her lost cat in the Bast...
🏁 [Row 7] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 11] Gemini: Sending request...

  2%|▏         | 8/400 [01:18<51:23,  7.86s/it]

✅ [Row 9] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a protagonist seeking justice or revenge ...
🚀 [Row 9] Claude: Sending request...

  2%|▏         | 8/400 [01:22<51:23,  7.86s/it]

✅ [Row 10] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 10] GPT: Sending request...

  2%|▏         | 8/400 [01:24<51:23,  7.86s/it]

✅ [Row 11] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 11] GPT: Sending request...

  2%|▏         | 8/400 [01:27<51:23,  7.86s/it]

✅ [Row 8] Gemini Received: {
  "reasoning": "The Anchor text features a criminal act (bank robbery), a chase/pursuit by law enf...
🚀 [Row 8] GPT: Sending request...

  2%|▏         | 9/400 [01:28<1:01:27,  9.43s/it]

✅ [Row 9] Claude Received: ```json
{
  "reasoning": "The Anchor follows two outlaws who repeatedly switch roles between crimina...
🏁 [Row 9] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 12] Gemini: Sending request...

  2%|▏         | 9/400 [01:30<1:01:27,  9.43s/it]

✅ [Row 10] GPT Received: {
  "reasoning": "The Anchor story involves an FBI agent dealing with a personal crisis involving hi...
🚀 [Row 10] Claude: Sending request...

  2%|▏         | 9/400 [01:31<1:01:27,  9.43s/it]

✅ [Row 11] GPT Received: {
  "reasoning": "The Anchor story revolves around Carmen, who is drawn into a conflict against a di...
🚀 [Row 11] Claude: Sending request...

  2%|▏         | 9/400 [01:33<1:01:27,  9.43s/it]

✅ [Row 8] GPT Received: {
  "reasoning": "The Anchor story revolves around an ex-convict, Lucas, who is inadvertently caught...
🚀 [Row 8] Claude: Sending request...

  2%|▏         | 9/400 [01:43<1:01:27,  9.43s/it]

✅ [Row 12] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 12] GPT: Sending request...

  2%|▎         | 10/400 [01:44<1:13:24, 11.29s/it]

✅ [Row 8] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on an ex-convict unwillingly paired with an incompetent...
🏁 [Row 8] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 13] Gemini: Sending request...

  3%|▎         | 11/400 [01:47<56:48,  8.76s/it]

✅ [Row 10] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an FBI agent whose son is kidnapped by the mafia in ...
🏁 [Row 10] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 14] Gemini: Sending request...

  3%|▎         | 11/400 [01:47<56:48,  8.76s/it]

✅ [Row 12] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve a protagonist moving to a rural area due t...
🚀 [Row 12] Claude: Sending request...

  3%|▎         | 12/400 [01:55<55:10,  8.53s/it]

✅ [Row 13] Gemini Received: {
  "reasoning": "The Anchor text features a famous artist, Benvenuto Cellini, whose artistic talent...
🚀 [Row 13] GPT: Sending request...
✅ [Row 11] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on Carmen, a comfortable housewife who becomes in...
🏁 [Row 11] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 15] Gemini: Sending request...

  3%|▎         | 12/400 [01:57<55:10,  8.53s/it]

✅ [Row 14] Gemini Received: {
  "reasoning": "The Anchor story features a protagonist, Paloma, who plans to commit suicide on he...
🚀 [Row 14] GPT: Sending request...

  3%|▎         | 13/400 [01:58<43:49,  6.79s/it]

✅ [Row 12] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a French professor inheriting property in Canada wit...
🏁 [Row 12] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 16] Gemini: Sending request...

  3%|▎         | 13/400 [02:01<43:49,  6.79s/it]

✅ [Row 14] GPT Received: {
  "reasoning": "The Anchor story revolves around a young girl, Paloma, who is disillusioned with l...
🚀 [Row 14] Claude: Sending request...
✅ [Row 13] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of infidelity, artistic creation, and dece...
🚀 [Row 13] Claude: Sending request...

  4%|▎         | 14/400 [02:12<58:05,  9.03s/it]

✅ [Row 13] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a Renaissance court setting with a duke, duchess, an...
🏁 [Row 13] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 17] Gemini: Sending request...

  4%|▍         | 15/400 [02:13<41:49,  6.52s/it]

✅ [Row 15] Gemini Received: {
  "reasoning": "The Anchor text describes an episodic, non-linear film structured as Federico Fell...
🚀 [Row 15] GPT: Sending request...
✅ [Row 14] Claude Received: ```json
{
  "reasoning": "Both texts involve protagonists contemplating or accepting death, but Text...
🏁 [Row 14] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 18] Gemini: Sending request...

  4%|▍         | 15/400 [02:17<41:49,  6.52s/it]

✅ [Row 16] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist, Larry, who is deeply unsatisfied with his ...
🚀 [Row 16] GPT: Sending request...

  4%|▍         | 15/400 [02:19<41:49,  6.52s/it]

✅ [Row 15] GPT Received: {
  "reasoning": "The Anchor text is a semi-autobiographical film by Federico Fellini that explores ...
🚀 [Row 15] Claude: Sending request...

  4%|▍         | 15/400 [02:21<41:49,  6.52s/it]

✅ [Row 18] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The most significant point of similari...
🚀 [Row 18] GPT: Sending request...

  4%|▍         | 15/400 [02:24<41:49,  6.52s/it]

✅ [Row 16] GPT Received: {
  "reasoning": "The Anchor story revolves around Larry, an expat piano player who is dissatisfied ...
🚀 [Row 16] Claude: Sending request...

  4%|▍         | 15/400 [02:27<41:49,  6.52s/it]

✅ [Row 18] GPT Received: {
  "reasoning": "The Anchor text revolves around a patient in an asylum who claims to have historic...
🚀 [Row 18] Claude: Sending request...

  4%|▍         | 16/400 [02:29<59:58,  9.37s/it]

✅ [Row 15] Claude Received: ```json
{
  "reasoning": "The Anchor is Fellini's episodic, autobiographical depiction of Rome acros...
🏁 [Row 15] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 19] Gemini: Sending request...

  4%|▍         | 16/400 [02:29<59:58,  9.37s/it]

✅ [Row 17] Gemini Received: {
  "reasoning": "The Anchor text focuses on a wilful, disobedient child whose defiance persists eve...
🚀 [Row 17] GPT: Sending request...

  4%|▍         | 16/400 [02:36<59:58,  9.37s/it]

✅ [Row 17] GPT Received: {
  "reasoning": "The Anchor story revolves around a disobedient child who faces divine punishment, ...
🚀 [Row 17] Claude: Sending request...

  4%|▍         | 17/400 [02:36<56:26,  8.84s/it]

✅ [Row 18] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a psychiatric patient who claims to be a historical ...
🏁 [Row 18] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 20] Gemini: Sending request...

  4%|▍         | 17/400 [02:37<56:26,  8.84s/it]

✅ [Row 19] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A feature a protagonist (or protagonists in Anchor) ...
🚀 [Row 19] GPT: Sending request...

  4%|▍         | 18/400 [02:37<40:56,  6.43s/it]

✅ [Row 16] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories center on a prota...
🏁 [Row 16] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 21] Gemini: Sending request...

  4%|▍         | 18/400 [02:43<40:56,  6.43s/it]

✅ [Row 19] GPT Received: {
  "reasoning": "The Anchor text revolves around four women from different backgrounds who come tog...
🚀 [Row 19] Claude: Sending request...

  5%|▍         | 19/400 [02:47<48:17,  7.61s/it]

✅ [Row 17] Claude Received: ```json
{
  "reasoning": "The Anchor is a cautionary tale about a willful child who disobeys her mot...
🏁 [Row 17] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 22] Gemini: Sending request...

  5%|▌         | 20/400 [02:51<40:55,  6.46s/it]

✅ [Row 19] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both share the core abstract t...
🏁 [Row 19] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 23] Gemini: Sending request...

  5%|▌         | 20/400 [02:57<40:55,  6.46s/it]

✅ [Row 20] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature an ex-convict a...
🚀 [Row 20] GPT: Sending request...

  5%|▌         | 20/400 [02:57<40:55,  6.46s/it]

✅ [Row 21] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 21] GPT: Sending request...

  5%|▌         | 20/400 [02:58<40:55,  6.46s/it]

✅ [Row 22] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature pro...
🚀 [Row 22] GPT: Sending request...

  5%|▌         | 20/400 [03:00<40:55,  6.46s/it]

⏳ [Row 23] Gemini: Rate limit (Attempt 1)

  5%|▌         | 20/400 [03:03<40:55,  6.46s/it]

✅ [Row 21] GPT Received: {
  "reasoning": "The Anchor story involves a historical setting with a focus on piracy, a conflict ...
🚀 [Row 21] Claude: Sending request...

  5%|▌         | 20/400 [03:04<40:55,  6.46s/it]

✅ [Row 20] GPT Received: {
  "reasoning": "The Anchor story revolves around a young girl, Jasmin, who seeks to reconnect with...
🚀 [Row 20] Claude: Sending request...

  5%|▌         | 20/400 [03:06<40:55,  6.46s/it]

✅ [Row 22] GPT Received: {
  "reasoning": "The Anchor story revolves around a famous operetta star and an ex-army officer who...
🚀 [Row 22] Claude: Sending request...

  5%|▌         | 20/400 [03:12<40:55,  6.46s/it]

✅ [Row 23] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature the...
🚀 [Row 23] GPT: Sending request...

  5%|▌         | 21/400 [03:14<1:11:40, 11.35s/it]

✅ [Row 21] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a naval captain dispatched to deal with a renegade p...
🏁 [Row 21] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 24] Gemini: Sending request...

  6%|▌         | 22/400 [03:16<53:57,  8.56s/it]

✅ [Row 22] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a love story between an operetta star and an ex-army...
🏁 [Row 22] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 25] Gemini: Sending request...

  6%|▌         | 22/400 [03:16<53:57,  8.56s/it]

❌ [Row 25] Gemini Exception: 'candidates'

  6%|▌         | 22/400 [03:18<53:57,  8.56s/it]

❌ [Row 25] Gemini Exception: 'candidates'

  6%|▌         | 23/400 [03:19<43:15,  6.89s/it]

✅ [Row 20] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on 14-year-old Jasmin who runs away to reconnect with h...
🏁 [Row 20] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 26] Gemini: Sending request...

  6%|▌         | 23/400 [03:19<43:15,  6.89s/it]

✅ [Row 23] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve the release of a dangerous entity (insects...
🚀 [Row 23] Claude: Sending request...

  6%|▌         | 23/400 [03:20<43:15,  6.89s/it]

❌ [Row 25] Gemini Exception: 'candidates'

  6%|▌         | 23/400 [03:21<43:15,  6.89s/it]

🚀 [Row 25] GPT: Sending request...

  6%|▌         | 23/400 [03:22<43:15,  6.89s/it]

⏳ [Row 26] Gemini: Rate limit (Attempt 1)

  6%|▌         | 23/400 [03:24<43:15,  6.89s/it]

✅ [Row 24] Gemini Received: {
  "reasoning": "The Anchor text describes a narrative where a perpetrator commits serious crimes, ...
🚀 [Row 24] GPT: Sending request...

  6%|▌         | 23/400 [03:26<43:15,  6.89s/it]

✅ [Row 25] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a young girl escaping from a controlling ...
🚀 [Row 25] Claude: Sending request...

  6%|▌         | 23/400 [03:26<43:15,  6.89s/it]

⏳ [Row 26] Gemini: Rate limit (Attempt 2)

  6%|▌         | 24/400 [03:28<46:36,  7.44s/it]

✅ [Row 23] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an earthquake releasing unknown insects that create ...
🏁 [Row 23] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 27] Gemini: Sending request...

  6%|▌         | 24/400 [03:31<46:36,  7.44s/it]

✅ [Row 24] GPT Received: {
  "reasoning": "The Anchor text deals with the theme of crime, specifically child molestation by a...
🚀 [Row 24] Claude: Sending request...

  6%|▌         | 24/400 [03:37<46:36,  7.44s/it]

⏳ [Row 27] Gemini: Rate limit (Attempt 1)

  6%|▋         | 25/400 [03:41<56:56,  9.11s/it]

✅ [Row 25] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a young girl (Heather) escaping her hostile stepmoth...
🏁 [Row 25] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 28] Gemini: Sending request...

  6%|▋         | 25/400 [03:41<56:56,  9.11s/it]

⏳ [Row 26] Gemini: Rate limit (Attempt 3)

  6%|▋         | 25/400 [03:47<56:56,  9.11s/it]

🚀 [Row 26] GPT: Sending request...

  6%|▋         | 25/400 [03:50<56:56,  9.11s/it]

✅ [Row 28] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text primarily because both narratives ...
🚀 [Row 28] GPT: Sending request...

  6%|▋         | 25/400 [03:52<56:56,  9.11s/it]

✅ [Row 27] Gemini Received: {
  "reasoning": "The Anchor text describes a city under external military attack with internal plot...
🚀 [Row 27] GPT: Sending request...

  6%|▋         | 25/400 [03:52<56:56,  9.11s/it]

✅ [Row 26] GPT Received: {
  "reasoning": "The Anchor story revolves around a theft motivated by love, leading to a confessio...
🚀 [Row 26] Claude: Sending request...

  6%|▋         | 25/400 [03:59<56:56,  9.11s/it]

✅ [Row 28] GPT Received: {
  "reasoning": "The Anchor text involves themes of identity, deception, and the harsh realities of...
🚀 [Row 28] Claude: Sending request...

  6%|▋         | 25/400 [04:00<56:56,  9.11s/it]

✅ [Row 27] GPT Received: {
  "reasoning": "The Anchor text is set during the Russian Civil War, focusing on a conflict betwee...
🚀 [Row 27] Claude: Sending request...

  6%|▋         | 26/400 [04:08<1:30:49, 14.57s/it]

✅ [Row 26] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a man (Vincenzo) who commits theft (stealing the Mon...
🏁 [Row 26] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 29] Gemini: Sending request...

  6%|▋         | 26/400 [04:09<1:30:49, 14.57s/it]

❌ [Row 29] Gemini Exception: 'candidates'

  7%|▋         | 27/400 [04:09<1:05:42, 10.57s/it]

✅ [Row 28] Claude Received: ```json
{
  "reasoning": "The Anchor text features a dual narrative structure: one part involves ide...
🏁 [Row 28] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 30] Gemini: Sending request...

  7%|▋         | 27/400 [04:10<1:05:42, 10.57s/it]

❌ [Row 29] Gemini Exception: 'candidates'

  7%|▋         | 28/400 [04:11<49:18,  7.95s/it]

✅ [Row 24] Claude Received: ```json
{
  "reasoning": "The Anchor text centers on a documentary exposing a priest's child molesta...
🏁 [Row 24] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 31] Gemini: Sending request...

  7%|▋         | 28/400 [04:12<49:18,  7.95s/it]

❌ [Row 29] Gemini Exception: 'candidates'

  7%|▋         | 28/400 [04:13<49:18,  7.95s/it]

🚀 [Row 29] GPT: Sending request...

  7%|▋         | 29/400 [04:13<38:51,  6.28s/it]

✅ [Row 27] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a military siege of Petrograd where counter-rev...
🏁 [Row 27] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 32] Gemini: Sending request...

  7%|▋         | 29/400 [04:20<38:51,  6.28s/it]

✅ [Row 31] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B descri...
🚀 [Row 31] GPT: Sending request...

  7%|▋         | 29/400 [04:21<38:51,  6.28s/it]

✅ [Row 32] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A center...
🚀 [Row 32] GPT: Sending request...

  7%|▋         | 29/400 [04:21<38:51,  6.28s/it]

✅ [Row 29] GPT Received: {
  "reasoning": "The Anchor story revolves around a woman who becomes an international star singer ...
🚀 [Row 29] Claude: Sending request...

  7%|▋         | 29/400 [04:22<38:51,  6.28s/it]

✅ [Row 30] Gemini Received: {
  "reasoning": "The Anchor text features a child (Christian) discovering a secret about a parent's...
🚀 [Row 30] GPT: Sending request...

  7%|▋         | 29/400 [04:24<38:51,  6.28s/it]

✅ [Row 31] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a rise to fame in the music industry foll...
🚀 [Row 31] Claude: Sending request...

  7%|▋         | 29/400 [04:24<38:51,  6.28s/it]

✅ [Row 32] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve journalists in conflict zones, dealing wit...
🚀 [Row 32] Claude: Sending request...

  7%|▋         | 29/400 [04:25<38:51,  6.28s/it]

✅ [Row 30] GPT Received: {
  "reasoning": "The Anchor story revolves around family dynamics, hidden truths, and the revelatio...
🚀 [Row 30] Claude: Sending request...

  8%|▊         | 30/400 [04:32<1:00:45,  9.85s/it]

✅ [Row 29] Claude Received: ```json
{
  "reasoning": "The Anchor story revolves around a woman confronting a supernatural/cultur...
🏁 [Row 29] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 33] Gemini: Sending request...

  8%|▊         | 31/400 [04:34<47:45,  7.76s/it]

✅ [Row 32] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a journalist covering a war (Georgia 2008), capturin...
🏁 [Row 32] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 34] Gemini: Sending request...

  8%|▊         | 32/400 [04:36<35:54,  5.85s/it]

✅ [Row 31] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on Milli Vanilli's meteoric rise to fame as a pop...
🏁 [Row 31] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 35] Gemini: Sending request...

  8%|▊         | 32/400 [04:38<35:54,  5.85s/it]

⏳ [Row 35] Gemini: Rate limit (Attempt 1)

  8%|▊         | 33/400 [04:40<32:55,  5.38s/it]

✅ [Row 30] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a widow who reunites with her former lover (who is s...
🏁 [Row 30] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 36] Gemini: Sending request...

  8%|▊         | 33/400 [04:43<32:55,  5.38s/it]

✅ [Row 33] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A are set aga...
🚀 [Row 33] GPT: Sending request...

  8%|▊         | 33/400 [04:44<32:55,  5.38s/it]

✅ [Row 34] Gemini Received: {
  "reasoning": "The Anchor text is about children (cousins, then K3 themselves) behaving badly and...
🚀 [Row 34] GPT: Sending request...

  8%|▊         | 33/400 [04:47<32:55,  5.38s/it]

✅ [Row 33] GPT Received: {
  "reasoning": "The Anchor text revolves around the aftermath of the First Punic War, focusing on ...
🚀 [Row 33] Claude: Sending request...

  8%|▊         | 33/400 [04:49<32:55,  5.38s/it]

✅ [Row 34] GPT Received: {
  "reasoning": "The Anchor story involves themes of family dynamics and the challenges of dealing ...
🚀 [Row 34] Claude: Sending request...
✅ [Row 36] Gemini Received: {
  "reasoning": "The Anchor text describes a gang of violent career criminals, led by a cold killer...
🚀 [Row 36] GPT: Sending request...

  8%|▊         | 33/400 [04:50<32:55,  5.38s/it]

✅ [Row 35] Gemini Received: {
  "reasoning": "The Anchor text features protagonists held captive by a mad scientist and forced t...
🚀 [Row 35] GPT: Sending request...

  8%|▊         | 33/400 [04:54<32:55,  5.38s/it]

✅ [Row 36] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve criminals and law enforcement, with a foc...
🚀 [Row 36] Claude: Sending request...

  8%|▊         | 33/400 [04:54<32:55,  5.38s/it]

✅ [Row 35] GPT Received: {
  "reasoning": "The Anchor text involves a mad scientist forcing characters to watch a film, with ...
🚀 [Row 35] Claude: Sending request...

  8%|▊         | 34/400 [04:58<55:25,  9.09s/it]

✅ [Row 33] Claude Received: ```json
{
  "reasoning": "Both texts involve Carthaginian conflicts, but Text A is narratively close...
🏁 [Row 33] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 37] Gemini: Sending request...

  9%|▉         | 35/400 [05:00<42:11,  6.94s/it]

✅ [Row 34] Claude Received: ```json
{
  "reasoning": "The Anchor is about K3 being transformed into 'little Rascals' who must be...
🏁 [Row 34] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 38] Gemini: Sending request...

  9%|▉         | 35/400 [05:00<42:11,  6.94s/it]

⏳ [Row 37] Gemini: Rate limit (Attempt 1)

  9%|▉         | 36/400 [05:04<37:01,  6.10s/it]

✅ [Row 36] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a criminal gang terrorizing multiple states th...
🏁 [Row 36] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 39] Gemini: Sending request...
✅ [Row 35] Claude Received: ```json
{
  "reasoning": "The Anchor is about characters forced to watch and comment on a science fi...
🏁 [Row 35] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 40] Gemini: Sending request...

  9%|▉         | 36/400 [05:12<37:01,  6.10s/it]

✅ [Row 38] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 38] GPT: Sending request...
⏳ [Row 39] Gemini: Rate limit (Attempt 1)

  9%|▉         | 36/400 [05:12<37:01,  6.10s/it]

✅ [Row 37] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B are set in ...
🚀 [Row 37] GPT: Sending request...

  9%|▉         | 36/400 [05:15<37:01,  6.10s/it]

✅ [Row 40] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. The Anchor concludes with the pro...
🚀 [Row 40] GPT: Sending request...

  9%|▉         | 36/400 [05:17<37:01,  6.10s/it]

✅ [Row 38] GPT Received: {
  "reasoning": "The Anchor story involves a circus owner losing his business due to gambling debts...
🚀 [Row 38] Claude: Sending request...
✅ [Row 37] GPT Received: {
  "reasoning": "The Anchor story is set in a boarding school and involves themes of friendship, au...
🚀 [Row 37] Claude: Sending request...

  9%|▉         | 36/400 [05:20<37:01,  6.10s/it]

✅ [Row 40] GPT Received: {
  "reasoning": "The Anchor story involves a mobster caught in gang conflicts, leading to imprisonm...
🚀 [Row 40] Claude: Sending request...

 10%|▉         | 38/400 [05:27<52:16,  8.66s/it]

✅ [Row 38] Claude Received: ```json
{
  "reasoning": "Both texts involve entertainment industry figures facing financial trouble...
🏁 [Row 38] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 41] Gemini: Sending request...

 10%|▉         | 39/400 [05:30<42:36,  7.08s/it]

✅ [Row 37] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a Danish all-boys boarding school with themes of spe...
🏁 [Row 37] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 42] Gemini: Sending request...

 10%|█         | 40/400 [05:31<34:04,  5.68s/it]

✅ [Row 40] Claude Received: ```json
{
  "reasoning": "The Anchor is about a mobster who goes to help a friend, gets caught in ga...
🏁 [Row 40] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 43] Gemini: Sending request...

 10%|█         | 40/400 [05:35<34:04,  5.68s/it]

✅ [Row 41] Gemini Received: {
  "reasoning": "The Anchor text describes a narrative where children actively pursue horse thieves...
🚀 [Row 41] GPT: Sending request...

 10%|█         | 40/400 [05:40<34:04,  5.68s/it]

✅ [Row 43] Gemini Received: {
  "reasoning": "The Anchor story features an initial bureaucratic misunderstanding that forces two...
🚀 [Row 43] GPT: Sending request...

 10%|█         | 40/400 [05:40<34:04,  5.68s/it]

✅ [Row 41] GPT Received: {
  "reasoning": "The Anchor story involves a group of children who suspect strangers of stealing a ...
🚀 [Row 41] Claude: Sending request...

 10%|█         | 40/400 [05:43<34:04,  5.68s/it]

✅ [Row 43] GPT Received: {
  "reasoning": "The Anchor story revolves around mistaken identity, a forced relationship that tur...
🚀 [Row 43] Claude: Sending request...

 10%|█         | 40/400 [05:43<34:04,  5.68s/it]

✅ [Row 42] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a cor...
🚀 [Row 42] GPT: Sending request...

 10%|█         | 40/400 [05:44<34:04,  5.68s/it]

❌ [Row 39] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 10%|█         | 40/400 [05:48<34:04,  5.68s/it]

✅ [Row 42] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve soldiers in a desert setting facing a sig...
🚀 [Row 42] Claude: Sending request...

 10%|█         | 41/400 [05:52<58:16,  9.74s/it]

✅ [Row 41] Claude Received: ```json
{
  "reasoning": "The Anchor is a children's adventure story centered on a group of young fr...
🏁 [Row 41] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 44] Gemini: Sending request...

 10%|█         | 41/400 [05:53<58:16,  9.74s/it]

❌ [Row 44] Gemini Exception: 'candidates'

 10%|█         | 41/400 [05:53<58:16,  9.74s/it]

⏳ [Row 39] Gemini: Rate limit (Attempt 3)

 10%|█         | 41/400 [05:54<58:16,  9.74s/it]

❌ [Row 44] Gemini Exception: 'candidates'

 10%|█         | 41/400 [05:56<58:16,  9.74s/it]

❌ [Row 44] Gemini Exception: 'candidates'

 10%|█         | 41/400 [05:57<58:16,  9.74s/it]

🚀 [Row 44] GPT: Sending request...

 10%|█         | 42/400 [05:58<52:09,  8.74s/it]

✅ [Row 42] Claude Received: ```json
{
  "reasoning": "Both texts share significant narrative elements with the Anchor. However, ...
🏁 [Row 42] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 45] Gemini: Sending request...

 10%|█         | 42/400 [05:59<52:09,  8.74s/it]

🚀 [Row 39] GPT: Sending request...

 10%|█         | 42/400 [06:04<52:09,  8.74s/it]

✅ [Row 44] GPT Received: {
  "reasoning": "The Anchor story revolves around a woman, Dr. Samantha Goodman, whose past actions...
🚀 [Row 44] Claude: Sending request...

 10%|█         | 42/400 [06:06<52:09,  8.74s/it]

✅ [Row 39] GPT Received: {
  "reasoning": "The Anchor story revolves around a play-within-a-play about Joan of Arc, focusing ...
🚀 [Row 39] Claude: Sending request...

 11%|█         | 43/400 [06:06<50:33,  8.50s/it]

✅ [Row 43] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a mistaken marriage/identity mix-up that forces two ...
🏁 [Row 43] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 46] Gemini: Sending request...

 11%|█         | 43/400 [06:08<50:33,  8.50s/it]

✅ [Row 45] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center arou...
🚀 [Row 45] GPT: Sending request...

 11%|█         | 44/400 [06:14<49:05,  8.27s/it]

✅ [Row 44] Claude Received: ```json
{
  "reasoning": "Both texts involve psychological/horror thriller elements, but Text A is n...
🏁 [Row 44] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 47] Gemini: Sending request...

 11%|█         | 44/400 [06:14<49:05,  8.27s/it]

✅ [Row 45] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist, James, who discovers a mysterious broadca...
🚀 [Row 45] Claude: Sending request...

 11%|█         | 44/400 [06:16<49:05,  8.27s/it]

✅ [Row 46] Gemini Received: {
  "reasoning": "The Anchor story is defined by a love triangle set against the backdrop of a major...
🚀 [Row 46] GPT: Sending request...

 11%|█         | 44/400 [06:20<49:05,  8.27s/it]

✅ [Row 46] GPT Received: {
  "reasoning": "The Anchor story is set during a historical conflict, the Khmelnytsky Uprising, an...
🚀 [Row 46] Claude: Sending request...

 11%|█         | 44/400 [06:24<49:05,  8.27s/it]

✅ [Row 47] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a '...
🚀 [Row 47] GPT: Sending request...

 11%|█▏        | 45/400 [06:26<55:24,  9.36s/it]

✅ [Row 45] Claude Received: ```json
{
  "reasoning": "Both texts involve investigations into mysterious disappearances, but Text...
🏁 [Row 45] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 48] Gemini: Sending request...

 12%|█▏        | 46/400 [06:28<43:31,  7.38s/it]

✅ [Row 39] Claude Received: ```json
{
  "reasoning": "The Anchor is fundamentally about meta-theatrical performance: actors stag...
🏁 [Row 39] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 49] Gemini: Sending request...

 12%|█▏        | 46/400 [06:29<43:31,  7.38s/it]

✅ [Row 47] GPT Received: {
  "reasoning": "The Anchor story revolves around Harper, a misfit in her family, who embarks on a ...
🚀 [Row 47] Claude: Sending request...

 12%|█▏        | 46/400 [06:34<43:31,  7.38s/it]

✅ [Row 48] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both texts share the core theme and in...
🚀 [Row 48] GPT: Sending request...

 12%|█▏        | 47/400 [06:36<44:45,  7.61s/it]

✅ [Row 46] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a love triangle between two military rivals (a Polis...
🏁 [Row 46] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 50] Gemini: Sending request...

 12%|█▏        | 47/400 [06:39<44:45,  7.61s/it]

✅ [Row 49] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center arou...
🚀 [Row 49] GPT: Sending request...
✅ [Row 48] GPT Received: {
  "reasoning": "The Anchor story involves a series of murders on trains, with a detective couple i...
🚀 [Row 48] Claude: Sending request...

 12%|█▏        | 48/400 [06:40<38:11,  6.51s/it]

✅ [Row 47] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a bohemian photographer (Connie) who has a transform...
🏁 [Row 47] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 51] Gemini: Sending request...

 12%|█▏        | 48/400 [06:43<38:11,  6.51s/it]

✅ [Row 50] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor because both stories center around the ...
🚀 [Row 50] GPT: Sending request...

 12%|█▏        | 48/400 [06:43<38:11,  6.51s/it]

✅ [Row 49] GPT Received: {
  "reasoning": "The Anchor story is about a quirky adventure in search of lost car keys, which ser...
🚀 [Row 49] Claude: Sending request...

 12%|█▏        | 49/400 [06:47<38:57,  6.66s/it]

✅ [Row 48] Claude Received: ```json
{
  "reasoning": "Both texts involve murder investigations, but Text A is narratively much c...
🏁 [Row 48] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 52] Gemini: Sending request...

 12%|█▏        | 49/400 [06:49<38:57,  6.66s/it]

✅ [Row 50] GPT Received: {
  "reasoning": "The Anchor story involves an expedition to Zanzibar to find a legendary cache of i...
🚀 [Row 50] Claude: Sending request...
⏳ [Row 52] Gemini: Rate limit (Attempt 1)

 12%|█▎        | 50/400 [06:55<40:01,  6.86s/it]

✅ [Row 49] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a deliberately absurdist quest (searching for keys that...
🏁 [Row 49] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 53] Gemini: Sending request...

 12%|█▎        | 50/400 [06:58<40:01,  6.86s/it]

✅ [Row 51] Gemini Received: {
  "reasoning": "The Anchor text features a lonely protagonist whose life is altered by a significa...
🚀 [Row 51] GPT: Sending request...

 12%|█▎        | 50/400 [06:58<40:01,  6.86s/it]

✅ [Row 52] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share a cor...
🚀 [Row 52] GPT: Sending request...

 13%|█▎        | 51/400 [07:00<36:42,  6.31s/it]

✅ [Row 50] Claude Received: ```json
{
  "reasoning": "Both texts involve adventure narratives with searches for missing people o...
🏁 [Row 50] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 54] Gemini: Sending request...

 13%|█▎        | 51/400 [07:02<36:42,  6.31s/it]

✅ [Row 51] GPT Received: {
  "reasoning": "The Anchor story revolves around Claude, a shy and lonely man, who is encouraged b...
🚀 [Row 51] Claude: Sending request...

 13%|█▎        | 51/400 [07:02<36:42,  6.31s/it]

✅ [Row 52] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a group of people in a jungle setting fac...
🚀 [Row 52] Claude: Sending request...

 13%|█▎        | 51/400 [07:07<36:42,  6.31s/it]

✅ [Row 54] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 54] GPT: Sending request...

 13%|█▎        | 51/400 [07:09<36:42,  6.31s/it]

✅ [Row 53] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor than Text A. The Anchor text's central ...
🚀 [Row 53] GPT: Sending request...

 13%|█▎        | 51/400 [07:11<36:42,  6.31s/it]

✅ [Row 54] GPT Received: {
  "reasoning": "The Anchor story involves a couple whose love is tested by supernatural forces, wi...
🚀 [Row 54] Claude: Sending request...

 13%|█▎        | 52/400 [07:13<47:57,  8.27s/it]

✅ [Row 51] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Claude, a shy bachelor who encounters Serge at a mar...
🏁 [Row 51] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 55] Gemini: Sending request...

 13%|█▎        | 53/400 [07:14<36:23,  6.29s/it]

✅ [Row 52] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories share core simila...
🏁 [Row 52] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 56] Gemini: Sending request...

 13%|█▎        | 53/400 [07:15<36:23,  6.29s/it]

✅ [Row 53] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of aging, familial responsibility, and emp...
🚀 [Row 53] Claude: Sending request...

 14%|█▎        | 54/400 [07:20<35:58,  6.24s/it]

✅ [Row 54] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a supernatural test of love/virtue where a dem...
🏁 [Row 54] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 57] Gemini: Sending request...

 14%|█▎        | 54/400 [07:22<35:58,  6.24s/it]

✅ [Row 56] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center on a...
🚀 [Row 56] GPT: Sending request...

 14%|█▍        | 55/400 [07:24<31:45,  5.52s/it]

✅ [Row 53] Claude Received: ```json
{
  "reasoning": "The Anchor story is fundamentally about intergenerational relationships, m...
🏁 [Row 53] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 58] Gemini: Sending request...

 14%|█▍        | 55/400 [07:25<31:45,  5.52s/it]

❌ [Row 58] Gemini Exception: 'candidates'

 14%|█▍        | 55/400 [07:27<31:45,  5.52s/it]

❌ [Row 58] Gemini Exception: 'candidates'

 14%|█▍        | 55/400 [07:28<31:45,  5.52s/it]

✅ [Row 56] GPT Received: {
  "reasoning": "The Anchor story revolves around a mysterious affliction with sexual undertones, l...
🚀 [Row 56] Claude: Sending request...

 14%|█▍        | 55/400 [07:28<31:45,  5.52s/it]

❌ [Row 58] Gemini Exception: 'candidates'

 14%|█▍        | 55/400 [07:29<31:45,  5.52s/it]

✅ [Row 55] Gemini Received: {
  "reasoning": "The Anchor text revolves around a complex romantic entanglement involving infideli...
🚀 [Row 55] GPT: Sending request...

 14%|█▍        | 55/400 [07:29<31:45,  5.52s/it]

🚀 [Row 58] GPT: Sending request...

 14%|█▍        | 55/400 [07:30<31:45,  5.52s/it]

✅ [Row 57] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share the c...
🚀 [Row 57] GPT: Sending request...

 14%|█▍        | 55/400 [07:34<31:45,  5.52s/it]

✅ [Row 58] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve characters moving to Paris and dealing wit...
🚀 [Row 58] Claude: Sending request...

 14%|█▍        | 55/400 [07:34<31:45,  5.52s/it]

✅ [Row 55] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle involving Stéphane, Maxime, and C...
🚀 [Row 55] Claude: Sending request...

 14%|█▍        | 55/400 [07:35<31:45,  5.52s/it]

✅ [Row 57] GPT Received: {
  "reasoning": "The Anchor story involves a murder investigation where a group of friends, led by ...
🚀 [Row 57] Claude: Sending request...

 14%|█▍        | 56/400 [07:39<47:01,  8.20s/it]

✅ [Row 56] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a woman whose sexual dysfunction manifests as a surr...
🏁 [Row 56] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 59] Gemini: Sending request...

 14%|█▍        | 57/400 [07:43<40:41,  7.12s/it]

✅ [Row 55] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a love triangle involving longtime business partners...
🏁 [Row 55] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 60] Gemini: Sending request...

 14%|█▍        | 58/400 [07:45<31:02,  5.45s/it]

✅ [Row 58] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Jessica, a young woman who moves to Paris, struggles...
🏁 [Row 58] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 61] Gemini: Sending request...

 15%|█▍        | 59/400 [07:46<23:21,  4.11s/it]

✅ [Row 57] Claude Received: ```json
{
  "reasoning": "Both texts involve murder investigations where determined individuals purs...
🏁 [Row 57] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 62] Gemini: Sending request...

 15%|█▍        | 59/400 [07:53<23:21,  4.11s/it]

✅ [Row 59] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist saving a heroine from a villain, using adv...
🚀 [Row 59] GPT: Sending request...
✅ [Row 61] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share a cor...
🚀 [Row 61] GPT: Sending request...

 15%|█▍        | 59/400 [07:56<23:21,  4.11s/it]

✅ [Row 62] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 62] GPT: Sending request...

 15%|█▍        | 59/400 [07:57<23:21,  4.11s/it]

✅ [Row 61] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of family estrangement, reconciliation, an...
🚀 [Row 61] Claude: Sending request...

 15%|█▍        | 59/400 [07:58<23:21,  4.11s/it]

✅ [Row 59] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist who uses technology to save the heroine fr...
🚀 [Row 59] Claude: Sending request...

 15%|█▍        | 59/400 [07:59<23:21,  4.11s/it]

✅ [Row 60] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B are set in ...
🚀 [Row 60] GPT: Sending request...

 15%|█▍        | 59/400 [08:00<23:21,  4.11s/it]

✅ [Row 62] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve an orphaned protagonist who is raised by ...
🚀 [Row 62] Claude: Sending request...

 15%|█▍        | 59/400 [08:04<23:21,  4.11s/it]

✅ [Row 60] GPT Received: {
  "reasoning": "The Anchor text focuses on the life of Nostradamus, his struggles with visions, hi...
🚀 [Row 60] Claude: Sending request...

 15%|█▌        | 60/400 [08:05<48:55,  8.63s/it]

✅ [Row 61] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on family disgrace, abandonment, a banking scheme threa...
🏁 [Row 61] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 63] Gemini: Sending request...

 15%|█▌        | 61/400 [08:07<37:25,  6.62s/it]

✅ [Row 59] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a technologically advanced hero who uses futuristic ...
🏁 [Row 59] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 64] Gemini: Sending request...

 16%|█▌        | 62/400 [08:09<29:34,  5.25s/it]

✅ [Row 62] Claude Received: ```json
{
  "reasoning": "The Anchor follows Nikolas, an orphan who is communally raised by village ...
🏁 [Row 62] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 65] Gemini: Sending request...

 16%|█▌        | 62/400 [08:14<29:34,  5.25s/it]

✅ [Row 63] Gemini Received: {
  "reasoning": "The Anchor text focuses on jealousy and the *aversion of violence* (a duel) throug...
🚀 [Row 63] GPT: Sending request...

 16%|█▌        | 62/400 [08:15<29:34,  5.25s/it]

✅ [Row 65] Gemini Received: {
  "reasoning": "The Anchor text describes a film about a teacher and teenagers learning about the ...
🚀 [Row 65] GPT: Sending request...

 16%|█▌        | 63/400 [08:16<32:26,  5.77s/it]

✅ [Row 60] Claude Received: ```json
{
  "reasoning": "The Anchor follows a historical figure (Nostradamus) in 16th-century Franc...
🏁 [Row 60] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 66] Gemini: Sending request...

 16%|█▌        | 63/400 [08:17<32:26,  5.77s/it]

✅ [Row 64] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 64] GPT: Sending request...
⏳ [Row 66] Gemini: Rate limit (Attempt 1)

 16%|█▌        | 63/400 [08:19<32:26,  5.77s/it]

✅ [Row 63] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of jealousy, marital conflict, and the int...
🚀 [Row 63] Claude: Sending request...

 16%|█▌        | 63/400 [08:21<32:26,  5.77s/it]

✅ [Row 65] GPT Received: {
  "reasoning": "The Anchor text and Text A both revolve around the theme of the Holocaust and its ...
🚀 [Row 65] Claude: Sending request...

 16%|█▌        | 63/400 [08:22<32:26,  5.77s/it]

✅ [Row 64] GPT Received: {
  "reasoning": "The Anchor story involves a young man, Tsane, who goes to the city with a mission ...
🚀 [Row 64] Claude: Sending request...

 16%|█▌        | 64/400 [08:29<45:02,  8.04s/it]

✅ [Row 66] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature an ...
🚀 [Row 66] GPT: Sending request...
✅ [Row 63] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a magician who creates a vision to prevent violence ...
🏁 [Row 63] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 67] Gemini: Sending request...

 16%|█▋        | 65/400 [08:30<32:55,  5.90s/it]

✅ [Row 65] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a transformative educational journey where mar...
🏁 [Row 65] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 68] Gemini: Sending request...

 16%|█▋        | 65/400 [08:32<32:55,  5.90s/it]

✅ [Row 66] GPT Received: {
  "reasoning": "The Anchor story involves themes of love, escape, and deception, with a course of ...
🚀 [Row 66] Claude: Sending request...

 16%|█▋        | 66/400 [08:41<41:17,  7.42s/it]

✅ [Row 64] Claude Received: ```json
{
  "reasoning": "Text A shares the most core narrative elements with the Anchor: (1) an eld...
🏁 [Row 64] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 69] Gemini: Sending request...

 17%|█▋        | 67/400 [08:43<32:13,  5.81s/it]

✅ [Row 66] Claude Received: ```json
{
  "reasoning": "The Anchor involves a protagonist (Kashma Baba) who rescues/shelters a wom...
🏁 [Row 66] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 70] Gemini: Sending request...

 17%|█▋        | 67/400 [08:46<32:13,  5.81s/it]

⏳ [Row 67] Gemini: Rate limit (Attempt 1)

 17%|█▋        | 67/400 [08:50<32:13,  5.81s/it]

⏳ [Row 68] Gemini: Rate limit (Attempt 1)

 17%|█▋        | 67/400 [08:54<32:13,  5.81s/it]

✅ [Row 70] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 70] GPT: Sending request...

 17%|█▋        | 67/400 [08:56<32:13,  5.81s/it]

✅ [Row 69] Gemini Received: {
  "reasoning": "The Anchor text begins with a betrayal in Ann's marriage (husband kissing another ...
🚀 [Row 69] GPT: Sending request...

 17%|█▋        | 67/400 [08:58<32:13,  5.81s/it]

⏳ [Row 68] Gemini: Rate limit (Attempt 2)

 17%|█▋        | 67/400 [08:58<32:13,  5.81s/it]

✅ [Row 70] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a central character with an idealistic vis...
🚀 [Row 70] Claude: Sending request...

 17%|█▋        | 67/400 [09:01<32:13,  5.81s/it]

✅ [Row 69] GPT Received: {
  "reasoning": "The Anchor story revolves around Ann, a musician who, after witnessing her husband...
🚀 [Row 69] Claude: Sending request...

 17%|█▋        | 67/400 [09:04<32:13,  5.81s/it]

✅ [Row 67] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a y...
🚀 [Row 67] GPT: Sending request...

 17%|█▋        | 67/400 [09:08<32:13,  5.81s/it]

✅ [Row 67] GPT Received: {
  "reasoning": "The Anchor story and Text B both feature protagonists who face repeated failures i...
🚀 [Row 67] Claude: Sending request...

 17%|█▋        | 68/400 [09:13<1:11:38, 12.95s/it]

✅ [Row 69] Claude Received: ```json
{
  "reasoning": "Both texts involve a married woman whose secure life is disrupted, leading...
🏁 [Row 69] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 71] Gemini: Sending request...

 17%|█▋        | 69/400 [09:20<1:01:57, 11.23s/it]

✅ [Row 67] Claude Received: ```json
{
  "reasoning": "Both texts share the theme of a young man facing repeated failures and try...
🏁 [Row 67] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 72] Gemini: Sending request...

 17%|█▋        | 69/400 [09:20<1:01:57, 11.23s/it]

✅ [Row 71] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A deal with a large-scale...
🚀 [Row 71] GPT: Sending request...

 17%|█▋        | 69/400 [09:23<1:01:57, 11.23s/it]

✅ [Row 68] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center on a...
🚀 [Row 68] GPT: Sending request...

 17%|█▋        | 69/400 [09:24<1:01:57, 11.23s/it]

✅ [Row 71] GPT Received: {
  "reasoning": "The Anchor text and Text B both take place during World War II and involve themes ...
🚀 [Row 71] Claude: Sending request...

 17%|█▋        | 69/400 [09:26<1:01:57, 11.23s/it]

✅ [Row 68] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a character dealing with family secrets an...
🚀 [Row 68] Claude: Sending request...

 17%|█▋        | 69/400 [09:31<1:01:57, 11.23s/it]

✅ [Row 72] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 72] GPT: Sending request...

 17%|█▋        | 69/400 [09:34<1:01:57, 11.23s/it]

✅ [Row 72] GPT Received: {
  "reasoning": "The Anchor story revolves around a group of artists attempting to set up an erotic...
🚀 [Row 72] Claude: Sending request...

 18%|█▊        | 70/400 [09:36<1:09:28, 12.63s/it]

✅ [Row 68] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a daughter discovering her father's secret past love...
🏁 [Row 68] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 73] Gemini: Sending request...

 18%|█▊        | 71/400 [09:40<55:41, 10.16s/it]

✅ [Row 70] Claude Received: ```json
{
  "reasoning": "The Anchor follows Confucius through a long career arc: initial success an...
🏁 [Row 70] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 74] Gemini: Sending request...

 18%|█▊        | 72/400 [09:44<44:28,  8.14s/it]

✅ [Row 72] Claude Received: ```json
{
  "reasoning": "The Anchor involves artists attempting a creative venture (erotic show) th...
🏁 [Row 72] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 75] Gemini: Sending request...
✅ [Row 73] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature mal...
🚀 [Row 73] GPT: Sending request...

 18%|█▊        | 73/400 [09:46<34:15,  6.29s/it]

✅ [Row 71] Claude Received: ```json
{
  "reasoning": "Both texts involve WWII settings with betrayal/enemy elements, but Text B ...
🏁 [Row 71] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 76] Gemini: Sending request...

 18%|█▊        | 73/400 [09:48<34:15,  6.29s/it]

✅ [Row 73] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of obsession, betrayal, and crime, with a ...
🚀 [Row 73] Claude: Sending request...

 18%|█▊        | 73/400 [09:51<34:15,  6.29s/it]

✅ [Row 76] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature a protagonist m...
🚀 [Row 76] GPT: Sending request...

 18%|█▊        | 73/400 [09:55<34:15,  6.29s/it]

✅ [Row 76] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist, Recep, who discovers a project threatenin...
🚀 [Row 76] Claude: Sending request...

 18%|█▊        | 73/400 [09:56<34:15,  6.29s/it]

✅ [Row 74] Gemini Received: {
  "reasoning": "The Anchor text centers on the investigation and recovery of specific stolen items...
🚀 [Row 74] GPT: Sending request...

 18%|█▊        | 74/400 [09:58<43:16,  7.96s/it]

✅ [Row 73] Claude Received: ```json
{
  "reasoning": "The Anchor follows a soldier (Don José) who becomes obsessed with Carmen, ...
🏁 [Row 73] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 77] Gemini: Sending request...

 18%|█▊        | 74/400 [10:01<43:16,  7.96s/it]

✅ [Row 74] GPT Received: {
  "reasoning": "The Anchor story involves a former burglar teaming up with a detective to recover ...
🚀 [Row 74] Claude: Sending request...

 18%|█▊        | 74/400 [10:06<43:16,  7.96s/it]

⏳ [Row 75] Gemini: Rate limit (Attempt 1)

 19%|█▉        | 75/400 [10:06<44:02,  8.13s/it]

✅ [Row 76] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Recep inheriting property in a village, discovering ...
🏁 [Row 76] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 78] Gemini: Sending request...

 19%|█▉        | 75/400 [10:09<44:02,  8.13s/it]

✅ [Row 77] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist living a double life, defying family expec...
🚀 [Row 77] GPT: Sending request...

 19%|█▉        | 76/400 [10:12<40:53,  7.57s/it]

✅ [Row 74] Claude Received: ```json
{
  "reasoning": "Both texts involve crime investigation, but Text A is narratively closer t...
🏁 [Row 74] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 79] Gemini: Sending request...

✅ [Row 77] GPT Received: {
  "reasoning": "The Anchor story revolves around a young woman, Cobra, who is caught between her f...
🚀 [Row 77] Claude: Sending request...
✅ [Row 78] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...

 19%|█▉        | 76/400 [10:15<40:53,  7.57s/it]

🚀 [Row 78] GPT: Sending request...

 19%|█▉        | 76/400 [10:21<40:53,  7.57s/it]

✅ [Row 78] GPT Received: {
  "reasoning": "The Anchor story revolves around Elliott, a young fisherman with a talent for sing...
🚀 [Row 78] Claude: Sending request...

 19%|█▉        | 76/400 [10:23<40:53,  7.57s/it]

✅ [Row 79] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist displaced in time who encounters a technolo...
🚀 [Row 79] GPT: Sending request...

 19%|█▉        | 76/400 [10:27<40:53,  7.57s/it]

✅ [Row 79] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a character experiencing a significant ti...
🚀 [Row 79] Claude: Sending request...

 19%|█▉        | 77/400 [10:31<59:02, 10.97s/it]

✅ [Row 78] Claude Received: ```json
{
  "reasoning": "Both texts share core narrative elements with the Anchor: a talented perfo...
🏁 [Row 78] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 80] Gemini: Sending request...

 20%|█▉        | 78/400 [10:36<48:59,  9.13s/it]

✅ [Row 79] Claude Received: ```json
{
  "reasoning": "The Anchor story focuses on a man who awakens after 108 years to discover ...
🏁 [Row 79] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 81] Gemini: Sending request...

 20%|█▉        | 79/400 [10:37<35:06,  6.56s/it]

✅ [Row 77] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Cobra, a young Muslim woman caught between her tradi...
🏁 [Row 77] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 82] Gemini: Sending request...

 20%|█▉        | 79/400 [10:37<35:06,  6.56s/it]

⏳ [Row 81] Gemini: Rate limit (Attempt 1)

 20%|█▉        | 79/400 [10:37<35:06,  6.56s/it]

✅ [Row 75] Gemini Received: {
  "reasoning": "The Anchor story centers on the protagonist, Gus, creating a distinct romantic per...
🚀 [Row 75] GPT: Sending request...

 20%|█▉        | 79/400 [10:40<35:06,  6.56s/it]

✅ [Row 80] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor follows an unconventional a...
🚀 [Row 80] GPT: Sending request...

 20%|█▉        | 79/400 [10:43<35:06,  6.56s/it]

✅ [Row 75] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of identity, deception, and romance, with ...
🚀 [Row 75] Claude: Sending request...

 20%|█▉        | 79/400 [10:44<35:06,  6.56s/it]

⏳ [Row 82] Gemini: Rate limit (Attempt 1)

 20%|█▉        | 79/400 [10:45<35:06,  6.56s/it]

✅ [Row 80] GPT Received: {
  "reasoning": "The Anchor text follows Quentin Crisp's journey as he moves to New York, becomes a...
🚀 [Row 80] Claude: Sending request...

 20%|█▉        | 79/400 [10:47<35:06,  6.56s/it]

✅ [Row 81] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature a Western setti...
🚀 [Row 81] GPT: Sending request...

 20%|█▉        | 79/400 [10:52<35:06,  6.56s/it]

✅ [Row 81] GPT Received: {
  "reasoning": "The Anchor story involves two characters, Trinity Junior and Bambino, who are boun...
🚀 [Row 81] Claude: Sending request...

 20%|██        | 80/400 [10:52<49:11,  9.22s/it]

✅ [Row 75] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic comedy plots with deception and mistaken ident...
🏁 [Row 75] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 83] Gemini: Sending request...

 20%|██        | 81/400 [10:57<41:46,  7.86s/it]

✅ [Row 80] Claude Received: ```json
{
  "reasoning": "The Anchor follows Quentin Crisp's later-life journey as an established pu...
🏁 [Row 80] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 84] Gemini: Sending request...

 20%|██        | 81/400 [10:58<41:46,  7.86s/it]

⏳ [Row 84] Gemini: Rate limit (Attempt 1)

 20%|██        | 81/400 [11:03<41:46,  7.86s/it]

✅ [Row 82] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a s...
🚀 [Row 82] GPT: Sending request...

 20%|██        | 81/400 [11:05<41:46,  7.86s/it]

✅ [Row 83] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a c...
🚀 [Row 83] GPT: Sending request...

 20%|██        | 81/400 [11:08<41:46,  7.86s/it]

⏳ [Row 84] Gemini: Rate limit (Attempt 2)
✅ [Row 82] GPT Received: {
  "reasoning": "The Anchor text revolves around a historical maritime journey with themes of leade...

 20%|██        | 81/400 [11:08<41:46,  7.86s/it]

🚀 [Row 82] Claude: Sending request...

 20%|██        | 81/400 [11:10<41:46,  7.86s/it]

✅ [Row 83] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of dealing with past trauma, uncovering hi...
🚀 [Row 83] Claude: Sending request...

 20%|██        | 82/400 [11:12<52:36,  9.92s/it]

✅ [Row 81] Claude Received: ```json
{
  "reasoning": "The Anchor is about two sons of famous lawmen (Trinity Junior and Bambino)...
🏁 [Row 81] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 85] Gemini: Sending request...

 21%|██        | 83/400 [11:17<44:34,  8.44s/it]

✅ [Row 82] Claude Received: ```json
{
  "reasoning": "The Anchor involves a naval voyage in 1816 where tension mounts between an...
🏁 [Row 82] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 86] Gemini: Sending request...

 21%|██        | 84/400 [11:20<37:13,  7.07s/it]

✅ [Row 84] Gemini Received: {
  "reasoning": "Text B shares a significant narrative element with the Anchor text: the theme of b...
🚀 [Row 84] GPT: Sending request...
✅ [Row 83] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around Daniel's traumatic past (his sister's murder), ...
🏁 [Row 83] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 87] Gemini: Sending request...

 21%|██        | 84/400 [11:22<37:13,  7.07s/it]

⏳ [Row 87] Gemini: Rate limit (Attempt 1)

 21%|██        | 84/400 [11:24<37:13,  7.07s/it]

⏳ [Row 85] Gemini: Rate limit (Attempt 1)

 21%|██        | 84/400 [11:26<37:13,  7.07s/it]

✅ [Row 84] GPT Received: {
  "reasoning": "The Anchor story revolves around a blind Italian Captain on a journey with his aid...
🚀 [Row 84] Claude: Sending request...

 21%|██        | 84/400 [11:32<37:13,  7.07s/it]

✅ [Row 86] Gemini Received: {
  "reasoning": "The Anchor text describes an initial state of happiness (Cinderella's marriage), f...
🚀 [Row 86] GPT: Sending request...

 21%|██        | 84/400 [11:32<37:13,  7.07s/it]

✅ [Row 87] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a jun...
🚀 [Row 87] GPT: Sending request...

 21%|██        | 84/400 [11:35<37:13,  7.07s/it]

✅ [Row 86] GPT Received: {
  "reasoning": "The Anchor story revolves around Cinderella's life after marriage, her forced depa...
🚀 [Row 86] Claude: Sending request...

 21%|██        | 84/400 [11:36<37:13,  7.07s/it]

✅ [Row 87] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a jungle setting and a central theme of i...
🚀 [Row 87] Claude: Sending request...

 21%|██        | 84/400 [11:37<37:13,  7.07s/it]

✅ [Row 85] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 85] GPT: Sending request...

 21%|██▏       | 85/400 [11:38<54:25, 10.37s/it]

✅ [Row 84] Claude Received: ```json
{
  "reasoning": "Both texts share elements of physical impairment and life-defining relatio...
🏁 [Row 84] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 88] Gemini: Sending request...

 21%|██▏       | 85/400 [11:40<54:25, 10.37s/it]

✅ [Row 85] GPT Received: {
  "reasoning": "The Anchor story involves themes of power struggles, memory loss, and rescue missi...
🚀 [Row 85] Claude: Sending request...

 22%|██▏       | 86/400 [11:45<47:53,  9.15s/it]

✅ [Row 86] Claude Received: ```json
{
  "reasoning": "Both texts involve protagonists who face adversity after finding happiness...
🏁 [Row 86] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 89] Gemini: Sending request...

 22%|██▏       | 87/400 [11:45<33:44,  6.47s/it]

✅ [Row 87] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories share the core ab...
🏁 [Row 87] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 90] Gemini: Sending request...

 22%|██▏       | 88/400 [11:50<31:19,  6.03s/it]

✅ [Row 85] Claude Received: ```json
{
  "reasoning": "Both texts share adventure elements with the Anchor, but Text A is narrati...
🏁 [Row 85] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 91] Gemini: Sending request...

 22%|██▏       | 88/400 [11:53<31:19,  6.03s/it]

✅ [Row 88] Gemini Received: {
  "reasoning": "The Anchor text features a young, struggling couple whose desperate circumstances ...
🚀 [Row 88] GPT: Sending request...

 22%|██▏       | 88/400 [11:57<31:19,  6.03s/it]

✅ [Row 90] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 90] GPT: Sending request...
✅ [Row 88] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of poverty, desperation, and the consequen...
🚀 [Row 88] Claude: Sending request...

 22%|██▏       | 88/400 [11:57<31:19,  6.03s/it]

✅ [Row 89] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a f...
🚀 [Row 89] GPT: Sending request...

 22%|██▏       | 88/400 [12:01<31:19,  6.03s/it]

✅ [Row 90] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of cultural displacement, identity crisis,...
🚀 [Row 90] Claude: Sending request...

 22%|██▏       | 88/400 [12:01<31:19,  6.03s/it]

✅ [Row 89] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist discovering secrets about their partner, w...
🚀 [Row 89] Claude: Sending request...

 22%|██▏       | 88/400 [12:06<31:19,  6.03s/it]

✅ [Row 91] Gemini Received: {
  "reasoning": "Text A shares several core narrative elements with the Anchor text. Both narrative...
🚀 [Row 91] GPT: Sending request...

 22%|██▏       | 89/400 [12:08<50:03,  9.66s/it]

✅ [Row 88] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a young couple facing severe consequences after Brun...
🏁 [Row 88] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 92] Gemini: Sending request...

 22%|██▏       | 89/400 [12:09<50:03,  9.66s/it]

⏳ [Row 92] Gemini: Rate limit (Attempt 1)

 22%|██▎       | 90/400 [12:10<38:24,  7.43s/it]

✅ [Row 90] Claude Received: ```json
{
  "reasoning": "The Anchor follows a young man experiencing cultural displacement after hi...
🏁 [Row 90] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 93] Gemini: Sending request...

 22%|██▎       | 90/400 [12:12<38:24,  7.43s/it]

✅ [Row 91] GPT Received: {
  "reasoning": "The Anchor story revolves around a hidden play written by a professor, the complic...
🚀 [Row 91] Claude: Sending request...

 23%|██▎       | 91/400 [12:17<37:21,  7.26s/it]

✅ [Row 89] Claude Received: ```json
{
  "reasoning": "Both texts share elements with the Anchor, but Text A is narratively close...
🏁 [Row 89] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 94] Gemini: Sending request...

 23%|██▎       | 91/400 [12:18<37:21,  7.26s/it]

⏳ [Row 94] Gemini: Rate limit (Attempt 1)

 23%|██▎       | 91/400 [12:22<37:21,  7.26s/it]

✅ [Row 92] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A deal with t...
🚀 [Row 92] GPT: Sending request...

 23%|██▎       | 91/400 [12:26<37:21,  7.26s/it]

✅ [Row 93] Gemini Received: {
  "reasoning": "The Anchor text is about an adult son who refuses to leave his parents' home, desp...
🚀 [Row 93] GPT: Sending request...

 23%|██▎       | 91/400 [12:29<37:21,  7.26s/it]

✅ [Row 92] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a central character who is a leader or pro...
🚀 [Row 92] Claude: Sending request...

 23%|██▎       | 91/400 [12:32<37:21,  7.26s/it]

✅ [Row 94] Gemini Received: {
  "reasoning": "The Anchor text describes the rise and fall of an artist, including tumultuous rel...
🚀 [Row 94] GPT: Sending request...

 23%|██▎       | 91/400 [12:32<37:21,  7.26s/it]

✅ [Row 93] GPT Received: {
  "reasoning": "The Anchor story revolves around a son, Tanguy, who refuses to leave his parents' ...
🚀 [Row 93] Claude: Sending request...

 23%|██▎       | 91/400 [12:36<37:21,  7.26s/it]

✅ [Row 94] GPT Received: {
  "reasoning": "The Anchor text follows the life of Basquiat, a struggling artist who rises to fam...
🚀 [Row 94] Claude: Sending request...

 23%|██▎       | 92/400 [12:39<59:27, 11.58s/it]

✅ [Row 92] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Queen Njinga's succession story in 17th-century Ango...
🏁 [Row 92] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 95] Gemini: Sending request...

 23%|██▎       | 93/400 [12:41<44:31,  8.70s/it]

✅ [Row 93] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on adult parents trying to push their grown son o...
🏁 [Row 93] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 96] Gemini: Sending request...

 23%|██▎       | 93/400 [12:43<44:31,  8.70s/it]

⏳ [Row 96] Gemini: Rate limit (Attempt 1)

 24%|██▎       | 94/400 [12:47<40:06,  7.86s/it]

✅ [Row 94] Claude Received: ```json
{
  "reasoning": "The Anchor follows a struggling artist (Basquiat) who rises through the Ne...
🏁 [Row 94] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 97] Gemini: Sending request...

 24%|██▎       | 94/400 [12:47<40:06,  7.86s/it]

❌ [Row 97] Gemini Exception: 'candidates'

 24%|██▎       | 94/400 [12:49<40:06,  7.86s/it]

❌ [Row 97] Gemini Exception: 'candidates'

 24%|██▎       | 94/400 [12:51<40:06,  7.86s/it]

❌ [Row 97] Gemini Exception: 'candidates'

 24%|██▎       | 94/400 [12:52<40:06,  7.86s/it]

🚀 [Row 97] GPT: Sending request...

 24%|██▎       | 94/400 [12:54<40:06,  7.86s/it]

✅ [Row 96] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center arou...
🚀 [Row 96] GPT: Sending request...

 24%|██▎       | 94/400 [12:56<40:06,  7.86s/it]

✅ [Row 97] GPT Received: {
  "reasoning": "The Anchor story is about a young woman leaving her past life behind to start anew...
🚀 [Row 97] Claude: Sending request...

 24%|██▎       | 94/400 [12:57<40:06,  7.86s/it]

✅ [Row 95] Gemini Received: {
  "reasoning": "The Anchor text features a character who escapes captivity and subsequently aligns...
🚀 [Row 95] GPT: Sending request...

 24%|██▎       | 94/400 [13:00<40:06,  7.86s/it]

✅ [Row 96] GPT Received: {
  "reasoning": "The Anchor story revolves around the loss of a secret technique, the descent into ...
🚀 [Row 96] Claude: Sending request...

 24%|██▎       | 94/400 [13:00<40:06,  7.86s/it]

✅ [Row 95] GPT Received: {
  "reasoning": "The Anchor story involves themes of liberation, imperialism, and a revolutionary f...
🚀 [Row 95] Claude: Sending request...

 24%|██▍       | 95/400 [13:08<1:00:15, 11.86s/it]

✅ [Row 97] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a woman leaving her past life behind (symbolized by ...
🏁 [Row 97] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 98] Gemini: Sending request...

 24%|██▍       | 96/400 [13:08<42:41,  8.43s/it]

✅ [Row 95] Claude Received: ```json
{
  "reasoning": "The Anchor features a revolutionary/political prisoner who escapes captivi...
🏁 [Row 95] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 99] Gemini: Sending request...

 24%|██▍       | 97/400 [13:13<37:15,  7.38s/it]

✅ [Row 96] Claude Received: ```json
{
  "reasoning": "Text A shares significant narrative similarity with the Anchor. Both cente...
🏁 [Row 96] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 100] Gemini: Sending request...

 24%|██▍       | 97/400 [13:23<37:15,  7.38s/it]

✅ [Row 99] Gemini Received: {
  "reasoning": "The Anchor text centers on the themes of loneliness, redundancy, and feeling like ...
🚀 [Row 99] GPT: Sending request...

 24%|██▍       | 97/400 [13:24<37:15,  7.38s/it]

✅ [Row 100] Gemini Received: {
  "reasoning": "The Anchor text centers on a group of former comrades reuniting to uncover a trait...
🚀 [Row 100] GPT: Sending request...

 24%|██▍       | 97/400 [13:28<37:15,  7.38s/it]

✅ [Row 99] GPT Received: {
  "reasoning": "The Anchor text and Text A both deal with themes of aging, redundancy, and the str...
🚀 [Row 99] Claude: Sending request...

 24%|██▍       | 97/400 [13:28<37:15,  7.38s/it]

✅ [Row 100] GPT Received: {
  "reasoning": "The Anchor story revolves around a group of ex-resistance fighters reuniting to un...
🚀 [Row 100] Claude: Sending request...

 24%|██▍       | 97/400 [13:33<37:15,  7.38s/it]

⏳ [Row 98] Gemini: Rate limit (Attempt 1)

 24%|██▍       | 97/400 [13:36<37:15,  7.38s/it]

⏳ [Row 98] Gemini: Rate limit (Attempt 2)

 24%|██▍       | 98/400 [13:38<1:02:51, 12.49s/it]

✅ [Row 99] Claude Received: ```json
{
  "reasoning": "Both texts deal with aging men facing irrelevance and decline, but Text B ...
🏁 [Row 99] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 101] Gemini: Sending request...

 25%|██▍       | 99/400 [13:40<46:51,  9.34s/it]

✅ [Row 100] Claude Received: {
  "reasoning": "The Anchor story centers on a group of ex-resistance fighters reuniting to unmask ...
🏁 [Row 100] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 102] Gemini: Sending request...

 25%|██▍       | 99/400 [13:43<46:51,  9.34s/it]

⏳ [Row 98] Gemini: Rate limit (Attempt 3)

 25%|██▍       | 99/400 [13:48<46:51,  9.34s/it]

✅ [Row 102] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a cor...
🚀 [Row 102] GPT: Sending request...

 25%|██▍       | 99/400 [13:49<46:51,  9.34s/it]

🚀 [Row 98] GPT: Sending request...

 25%|██▍       | 99/400 [13:52<46:51,  9.34s/it]

✅ [Row 102] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of loyalty, family, and sacrifice, with a ...
🚀 [Row 102] Claude: Sending request...

 25%|██▍       | 99/400 [13:55<46:51,  9.34s/it]

✅ [Row 98] GPT Received: {
  "reasoning": "The Anchor story involves a fictional character coming to life and a quest to retr...
🚀 [Row 98] Claude: Sending request...

 25%|██▌       | 100/400 [14:05<1:10:12, 14.04s/it]

✅ [Row 98] Claude Received: ```json
{
  "reasoning": "Both texts involve protagonists entering fantastical or heightened realiti...
🏁 [Row 98] Votes: {'gemini': None, 'gpt': False, 'claude': True}
🚀 [Row 103] Gemini: Sending request...

 25%|██▌       | 100/400 [14:06<1:10:12, 14.04s/it]

⏳ [Row 103] Gemini: Rate limit (Attempt 1)

 25%|██▌       | 100/400 [14:08<1:10:12, 14.04s/it]

❌ [Row 101] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 25%|██▌       | 100/400 [14:10<1:10:12, 14.04s/it]

⏳ [Row 103] Gemini: Rate limit (Attempt 2)

 25%|██▌       | 101/400 [14:17<1:07:07, 13.47s/it]

✅ [Row 102] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve protagonists entangled with criminal underw...
🏁 [Row 102] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 104] Gemini: Sending request...

 25%|██▌       | 101/400 [14:26<1:07:07, 13.47s/it]

✅ [Row 101] Gemini Received: {
  "reasoning": "The Anchor text describes a controversial figure who rises to political influence ...
🚀 [Row 101] GPT: Sending request...

 25%|██▌       | 101/400 [14:27<1:07:07, 13.47s/it]

✅ [Row 103] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a c...
🚀 [Row 103] GPT: Sending request...

 25%|██▌       | 101/400 [14:32<1:07:07, 13.47s/it]

✅ [Row 103] GPT Received: {
  "reasoning": "The Anchor story revolves around Joey O'Brien, a car salesman dealing with persona...
🚀 [Row 103] Claude: Sending request...

 25%|██▌       | 101/400 [14:33<1:07:07, 13.47s/it]

✅ [Row 101] GPT Received: {
  "reasoning": "The Anchor story revolves around Rasputin's rise to influence through his mystical...
🚀 [Row 101] Claude: Sending request...

 25%|██▌       | 101/400 [14:36<1:07:07, 13.47s/it]

✅ [Row 104] Gemini Received: {
  "reasoning": "The Anchor text features deception (masquerading as a princess), a central murder,...
🚀 [Row 104] GPT: Sending request...

 25%|██▌       | 101/400 [14:40<1:07:07, 13.47s/it]

✅ [Row 104] GPT Received: {
  "reasoning": "The Anchor story involves themes of deception and masquerade, as well as a murder ...
🚀 [Row 104] Claude: Sending request...

 26%|██▌       | 102/400 [14:42<1:24:31, 17.02s/it]

✅ [Row 103] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Joey O'Brien facing multiple personal crises (ex-wif...
🏁 [Row 103] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 105] Gemini: Sending request...

 26%|██▌       | 103/400 [14:46<1:04:09, 12.96s/it]

✅ [Row 101] Claude Received: ```json
{
  "reasoning": "The Anchor follows a man (Rasputin) who gains influence and power through ...
🏁 [Row 101] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 106] Gemini: Sending request...

 26%|██▌       | 104/400 [14:50<51:16, 10.39s/it]

✅ [Row 104] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two entertainers (an actress and a band leader) who ...
🏁 [Row 104] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 107] Gemini: Sending request...

 26%|██▌       | 104/400 [14:51<51:16, 10.39s/it]

✅ [Row 105] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A share a core narrative ...
🚀 [Row 105] GPT: Sending request...

 26%|██▌       | 104/400 [14:56<51:16, 10.39s/it]

✅ [Row 105] GPT Received: {
  "reasoning": "The Anchor story revolves around a legend of a massacre by an escaped psychiatric ...
🚀 [Row 105] Claude: Sending request...

 26%|██▌       | 104/400 [14:58<51:16, 10.39s/it]

✅ [Row 106] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 106] GPT: Sending request...

 26%|██▌       | 104/400 [14:59<51:16, 10.39s/it]

✅ [Row 107] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share a cor...
🚀 [Row 107] GPT: Sending request...

 26%|██▌       | 104/400 [15:01<51:16, 10.39s/it]

✅ [Row 106] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a protagonist who becomes a fugitive due ...
🚀 [Row 106] Claude: Sending request...

 26%|██▌       | 104/400 [15:05<51:16, 10.39s/it]

✅ [Row 107] GPT Received: {
  "reasoning": "The Anchor story revolves around a journalist and her photographer uncovering a mo...
🚀 [Row 107] Claude: Sending request...

 26%|██▋       | 105/400 [15:11<1:07:02, 13.64s/it]

✅ [Row 91] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a professor whose old play is discovered and pe...
🏁 [Row 91] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 108] Gemini: Sending request...

 26%|██▋       | 106/400 [15:13<50:05, 10.22s/it]

✅ [Row 106] Claude Received: ```json
{
  "reasoning": "Both texts involve protagonists who become murder suspects and go on journ...
🏁 [Row 106] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 109] Gemini: Sending request...

 27%|██▋       | 107/400 [15:14<35:58,  7.37s/it]

✅ [Row 107] Claude Received: ```json
{
  "reasoning": "The Anchor follows a journalist investigating a gangster's stolen payroll,...
🏁 [Row 107] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 110] Gemini: Sending request...

 27%|██▋       | 108/400 [15:15<25:50,  5.31s/it]

✅ [Row 105] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a past family massacre at an isolated lake that beco...
🏁 [Row 105] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 111] Gemini: Sending request...

 27%|██▋       | 108/400 [15:19<25:50,  5.31s/it]

✅ [Row 109] Gemini Received: {
  "reasoning": "The Anchor text describes a passionate affair between a young teacher and a jazz m...
🚀 [Row 109] GPT: Sending request...

 27%|██▋       | 108/400 [15:23<25:50,  5.31s/it]

✅ [Row 108] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 108] GPT: Sending request...

 27%|██▋       | 108/400 [15:24<25:50,  5.31s/it]

✅ [Row 109] GPT Received: {
  "reasoning": "The Anchor story revolves around a young woman, Valentine, who is balancing her ca...
🚀 [Row 109] Claude: Sending request...

 27%|██▋       | 108/400 [15:24<25:50,  5.31s/it]

✅ [Row 111] Gemini Received: {
  "reasoning": "The Anchor story centers on an innocent man (Moore) being framed for a crime he di...
🚀 [Row 111] GPT: Sending request...

 27%|██▋       | 108/400 [15:26<25:50,  5.31s/it]

✅ [Row 110] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 110] GPT: Sending request...

 27%|██▋       | 108/400 [15:28<25:50,  5.31s/it]

✅ [Row 108] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of power struggles, rebellion, and love, w...
🚀 [Row 108] Claude: Sending request...

 27%|██▋       | 108/400 [15:28<25:50,  5.31s/it]

✅ [Row 111] GPT Received: {
  "reasoning": "The Anchor story involves a businessman framed for murder in a foreign country, wh...
🚀 [Row 111] Claude: Sending request...

 27%|██▋       | 108/400 [15:30<25:50,  5.31s/it]

✅ [Row 110] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve characters who change their identities or...
🚀 [Row 110] Claude: Sending request...

 27%|██▋       | 109/400 [15:34<46:30,  9.59s/it]

✅ [Row 109] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a passionate romantic affair between two young peopl...
🏁 [Row 109] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 112] Gemini: Sending request...

 28%|██▊       | 110/400 [15:39<39:09,  8.10s/it]

✅ [Row 111] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a businessman framed for murder who, with his lawyer...
🏁 [Row 111] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 113] Gemini: Sending request...

 28%|██▊       | 111/400 [15:39<27:47,  5.77s/it]

✅ [Row 110] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic plots with identity concealment, but Text A is...
🏁 [Row 110] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 114] Gemini: Sending request...

 28%|██▊       | 112/400 [15:40<20:58,  4.37s/it]

⏳ [Row 114] Gemini: Rate limit (Attempt 1)
✅ [Row 108] Claude Received: ```json
{
  "reasoning": "Both texts share significant narrative elements with the Anchor: a despoti...
🏁 [Row 108] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 115] Gemini: Sending request...

 28%|██▊       | 112/400 [15:42<20:58,  4.37s/it]

⏳ [Row 115] Gemini: Rate limit (Attempt 1)

 28%|██▊       | 112/400 [15:43<20:58,  4.37s/it]

✅ [Row 112] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a h...
🚀 [Row 112] GPT: Sending request...

 28%|██▊       | 112/400 [15:46<20:58,  4.37s/it]

⏳ [Row 115] Gemini: Rate limit (Attempt 2)

 28%|██▊       | 112/400 [15:47<20:58,  4.37s/it]

✅ [Row 113] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B explicitly ...
🚀 [Row 113] GPT: Sending request...

 28%|██▊       | 112/400 [15:49<20:58,  4.37s/it]

✅ [Row 112] GPT Received: {
  "reasoning": "The Anchor text involves a quest for the Golden Fleece, a subplot of a trusted lor...
🚀 [Row 112] Claude: Sending request...

 28%|██▊       | 112/400 [15:53<20:58,  4.37s/it]

✅ [Row 113] GPT Received: {
  "reasoning": "The Anchor story revolves around Petey Brown, a lounge singer who returns to her f...
🚀 [Row 113] Claude: Sending request...

 28%|██▊       | 112/400 [15:53<20:58,  4.37s/it]

⏳ [Row 115] Gemini: Rate limit (Attempt 3)

 28%|██▊       | 112/400 [15:54<20:58,  4.37s/it]

✅ [Row 114] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor describes an accidental mee...
🚀 [Row 114] GPT: Sending request...

 28%|██▊       | 113/400 [15:58<40:19,  8.43s/it]

✅ [Row 112] Claude Received: {
  "reasoning": "The Anchor describes Jason's quest for the Golden Fleece with subplots involving t...
🏁 [Row 112] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 116] Gemini: Sending request...
✅ [Row 114] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of estrangement, failed relationships, and...
🚀 [Row 114] Claude: Sending request...

 28%|██▊       | 113/400 [15:59<40:19,  8.43s/it]

🚀 [Row 115] GPT: Sending request...

 28%|██▊       | 114/400 [16:01<31:44,  6.66s/it]

✅ [Row 113] Claude Received: ```json
{
  "reasoning": "Both texts share the core element of a female entertainer protagonist deal...
🏁 [Row 113] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 117] Gemini: Sending request...

 28%|██▊       | 114/400 [16:03<31:44,  6.66s/it]

✅ [Row 115] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve characters living in remote, mountainous a...
🚀 [Row 115] Claude: Sending request...

 29%|██▉       | 115/400 [16:08<33:00,  6.95s/it]

✅ [Row 114] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a brief, chance encounter between estranged spouses whe...
🏁 [Row 114] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 118] Gemini: Sending request...

 29%|██▉       | 116/400 [16:14<30:20,  6.41s/it]

✅ [Row 115] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a family (the Robinsons) facing survival challenges ...
🏁 [Row 115] Votes: {'gemini': None, 'gpt': True, 'claude': True}
🚀 [Row 119] Gemini: Sending request...

 29%|██▉       | 116/400 [16:20<30:20,  6.41s/it]

✅ [Row 118] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B describe a ...
🚀 [Row 118] GPT: Sending request...

 29%|██▉       | 116/400 [16:22<30:20,  6.41s/it]

✅ [Row 117] Gemini Received: {
  "reasoning": "The Anchor text describes a dangerous mission involving a recruited group, a valua...
🚀 [Row 117] GPT: Sending request...

 29%|██▉       | 116/400 [16:22<30:20,  6.41s/it]

✅ [Row 119] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a d...
🚀 [Row 119] GPT: Sending request...

 29%|██▉       | 116/400 [16:23<30:20,  6.41s/it]

✅ [Row 118] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of forbidden love, family expectations, an...
🚀 [Row 118] Claude: Sending request...

 29%|██▉       | 116/400 [16:25<30:20,  6.41s/it]

✅ [Row 119] GPT Received: {
  "reasoning": "The Anchor story involves a private detective investigating a diamond theft, facin...
🚀 [Row 119] Claude: Sending request...

 29%|██▉       | 116/400 [16:26<30:20,  6.41s/it]

✅ [Row 117] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a protagonist working against a larger or...
🚀 [Row 117] Claude: Sending request...

 29%|██▉       | 116/400 [16:28<30:20,  6.41s/it]

❌ [Row 116] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 29%|██▉       | 117/400 [16:31<46:31,  9.86s/it]

✅ [Row 118] Claude Received: ```json
{
  "reasoning": "Both texts involve young men entangled with women in romantic/social situa...
🏁 [Row 118] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 120] Gemini: Sending request...

 30%|██▉       | 118/400 [16:35<36:58,  7.87s/it]

✅ [Row 119] Claude Received: ```json
{
  "reasoning": "Both texts involve investigations into crimes (stolen/fraudulent diamonds ...
🏁 [Row 119] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 121] Gemini: Sending request...

 30%|██▉       | 119/400 [16:35<26:10,  5.59s/it]

✅ [Row 117] Claude Received: ```json
{
  "reasoning": "The Anchor is a Civil War heist story centered on a military mission invol...
🏁 [Row 117] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 122] Gemini: Sending request...

 30%|██▉       | 119/400 [16:48<26:10,  5.59s/it]

✅ [Row 122] Gemini Received: {
  "reasoning": "The Anchor text centers on a protagonist grappling with the unexplained death of a...
🚀 [Row 122] GPT: Sending request...

 30%|██▉       | 119/400 [16:49<26:10,  5.59s/it]

✅ [Row 116] Gemini Received: {
  "reasoning": "The Anchor text features a middle-aged woman whose absolute devotion to Jesus is c...
🚀 [Row 116] GPT: Sending request...

 30%|██▉       | 119/400 [16:50<26:10,  5.59s/it]

✅ [Row 121] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor text is a classic spy narra...
🚀 [Row 121] GPT: Sending request...

 30%|██▉       | 119/400 [16:52<26:10,  5.59s/it]

✅ [Row 122] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of loss, grief, and moving on after the de...
🚀 [Row 122] Claude: Sending request...

 30%|██▉       | 119/400 [16:55<26:10,  5.59s/it]

✅ [Row 121] GPT Received: {
  "reasoning": "The Anchor story involves a retired secret agent, Matt Helm, being coaxed back int...
🚀 [Row 121] Claude: Sending request...

 30%|██▉       | 119/400 [16:55<26:10,  5.59s/it]

✅ [Row 116] GPT Received: {
  "reasoning": "The Anchor text revolves around a woman, Anna Maria, who is deeply religious and f...
🚀 [Row 116] Claude: Sending request...

 30%|██▉       | 119/400 [17:02<26:10,  5.59s/it]

❌ [Row 120] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 30%|███       | 120/400 [17:02<56:43, 12.15s/it]

✅ [Row 122] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a widow (Yumiko) who remarries after her husband's m...
🏁 [Row 122] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 123] Gemini: Sending request...

 30%|███       | 121/400 [17:04<42:00,  9.04s/it]

⏳ [Row 120] Gemini: Rate limit (Attempt 2)
✅ [Row 121] Claude Received: ```json
{
  "reasoning": "The Anchor follows a retired spy (Matt Helm) reluctantly returning to espi...
🏁 [Row 121] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 124] Gemini: Sending request...

 30%|███       | 121/400 [17:06<42:00,  9.04s/it]

⏳ [Row 123] Gemini: Rate limit (Attempt 1)

 30%|███       | 122/400 [17:10<36:51,  7.96s/it]

✅ [Row 116] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Anna Maria, a devout Austrian woman whose unwavering...
🏁 [Row 116] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 125] Gemini: Sending request...

 30%|███       | 122/400 [17:11<36:51,  7.96s/it]

⏳ [Row 125] Gemini: Rate limit (Attempt 1)

 30%|███       | 122/400 [17:13<36:51,  7.96s/it]

✅ [Row 124] Gemini Received: {
  "reasoning": "The Anchor text centers on themes of adoption, confusion regarding parentage withi...
🚀 [Row 124] GPT: Sending request...

 30%|███       | 122/400 [17:18<36:51,  7.96s/it]

✅ [Row 124] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of family, adoption, and reconciliation, w...
🚀 [Row 124] Claude: Sending request...

 30%|███       | 122/400 [17:19<36:51,  7.96s/it]

✅ [Row 123] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share the c...
🚀 [Row 123] GPT: Sending request...

 30%|███       | 122/400 [17:22<36:51,  7.96s/it]

✅ [Row 125] Gemini Received: {
  "reasoning": "The Anchor story centers on a woman's complex romantic choices, particularly her i...
🚀 [Row 125] GPT: Sending request...

 30%|███       | 122/400 [17:25<36:51,  7.96s/it]

✅ [Row 123] GPT Received: {
  "reasoning": "The Anchor story revolves around Alan, a schoolteacher who becomes involved with B...
🚀 [Row 123] Claude: Sending request...

 30%|███       | 122/400 [17:26<36:51,  7.96s/it]

✅ [Row 125] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of romantic relationships complicated by a...
🚀 [Row 125] Claude: Sending request...
✅ [Row 120] Gemini Received: {
  "reasoning": "The Anchor text centers on two individuals (a widower and a widow) dealing with th...
🚀 [Row 120] GPT: Sending request...

 30%|███       | 122/400 [17:31<36:51,  7.96s/it]

✅ [Row 120] GPT Received: {
  "reasoning": "The Anchor story and Text B both focus on older characters dealing with personal r...
🚀 [Row 120] Claude: Sending request...

 31%|███       | 123/400 [17:36<1:02:32, 13.55s/it]

✅ [Row 125] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a 40-year-old woman (Paula) in a relationship ...
🏁 [Row 125] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 126] Gemini: Sending request...

 31%|███       | 124/400 [17:37<44:38,  9.70s/it]

✅ [Row 123] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Alan, a respectable schoolteacher/DJ who falls for B...
🏁 [Row 123] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 127] Gemini: Sending request...

 31%|███▏      | 125/400 [17:43<39:09,  8.54s/it]

✅ [Row 124] Claude Received: {
  "reasoning": "The Anchor centers on a narrative of adoption confusion, class differences, and fa...
🏁 [Row 124] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 128] Gemini: Sending request...

 31%|███▏      | 125/400 [17:44<39:09,  8.54s/it]

✅ [Row 126] Gemini Received: {
  "reasoning": "The Anchor text emphasizes that a small, seemingly innocent action (a playful knoc...
✅ [Row 127] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor than Text A. The Anchor features a prot...
🚀 [Row 126] GPT: Sending request...
🚀 [Row 127] GPT: Sending request...

 31%|███▏      | 125/400 [17:47<39:09,  8.54s/it]

✅ [Row 126] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of small actions leading to significant...
🚀 [Row 126] Claude: Sending request...

 32%|███▏      | 126/400 [17:51<38:03,  8.33s/it]

✅ [Row 120] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two penniless widowed people (Hamo and Nina) in an e...
🏁 [Row 120] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 129] Gemini: Sending request...

 32%|███▏      | 126/400 [17:52<38:03,  8.33s/it]

✅ [Row 127] GPT Received: {
  "reasoning": "The Anchor story involves a humanoid extraterrestrial superhero, Supersonic Man, w...
🚀 [Row 127] Claude: Sending request...

 32%|███▏      | 127/400 [17:56<34:29,  7.58s/it]

✅ [Row 126] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a seemingly innocent action (knocking on a doo...
🏁 [Row 126] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 130] Gemini: Sending request...

 32%|███▏      | 127/400 [17:59<34:29,  7.58s/it]

✅ [Row 128] Gemini Received: {
  "reasoning": "The Anchor text describes a narrative where a detached individual (Ruza) gradually...
✅ [Row 129] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 128] GPT: Sending request...
🚀 [Row 129] GPT: Sending request...

 32%|███▏      | 128/400 [18:02<31:03,  6.85s/it]

✅ [Row 127] Claude Received: ```json
{
  "reasoning": "The Anchor follows a superhero narrative where an extraterrestrial protect...
🏁 [Row 127] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 131] Gemini: Sending request...

 32%|███▏      | 128/400 [18:03<31:03,  6.85s/it]

✅ [Row 129] GPT Received: {
  "reasoning": "The Anchor story involves a journey with a central character determined to reach a...
🚀 [Row 129] Claude: Sending request...

 32%|███▏      | 128/400 [18:05<31:03,  6.85s/it]

✅ [Row 128] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of immigration, detachment from the past, ...
🚀 [Row 128] Claude: Sending request...

 32%|███▏      | 128/400 [18:05<31:03,  6.85s/it]

✅ [Row 130] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center arou...
🚀 [Row 130] GPT: Sending request...

 32%|███▏      | 128/400 [18:09<31:03,  6.85s/it]

⏳ [Row 131] Gemini: Rate limit (Attempt 1)

 32%|███▏      | 128/400 [18:10<31:03,  6.85s/it]

✅ [Row 130] GPT Received: {
  "reasoning": "The Anchor story revolves around a romantic misunderstanding and a public scandal ...
🚀 [Row 130] Claude: Sending request...

 32%|███▏      | 129/400 [18:12<36:07,  8.00s/it]

✅ [Row 129] Claude Received: ```json
{
  "reasoning": "The Anchor involves a journey through Kazakhstan toward a sacred mountain ...
🏁 [Row 129] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 132] Gemini: Sending request...

 32%|███▎      | 130/400 [18:14<27:47,  6.18s/it]

✅ [Row 128] Claude Received: ```json
{
  "reasoning": "The Anchor centers on three immigrant women working in a cafeteria in Zuri...
🏁 [Row 128] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 133] Gemini: Sending request...

 33%|███▎      | 131/400 [18:20<27:31,  6.14s/it]

✅ [Row 130] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a romantic relationship between a bachelor talent ag...
🏁 [Row 130] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 134] Gemini: Sending request...

 33%|███▎      | 131/400 [18:22<27:31,  6.14s/it]

✅ [Row 133] Gemini Received: {
  "reasoning": "The Anchor text describes a young man's struggle against bureaucratic authority (a...
🚀 [Row 133] GPT: Sending request...

 33%|███▎      | 131/400 [18:23<27:31,  6.14s/it]

✅ [Row 132] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text primarily because both narratives ...
🚀 [Row 132] GPT: Sending request...

 33%|███▎      | 131/400 [18:25<27:31,  6.14s/it]

✅ [Row 131] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist's journey of leaving home, pursuing a care...
🚀 [Row 131] GPT: Sending request...

 33%|███▎      | 131/400 [18:26<27:31,  6.14s/it]

✅ [Row 133] GPT Received: {
  "reasoning": "The Anchor text revolves around Emrah's struggle to achieve his dream of becoming ...
🚀 [Row 133] Claude: Sending request...

 33%|███▎      | 131/400 [18:27<27:31,  6.14s/it]

✅ [Row 132] GPT Received: {
  "reasoning": "The Anchor story revolves around a woman, Dona, who escapes a loveless marriage an...
🚀 [Row 132] Claude: Sending request...

 33%|███▎      | 131/400 [18:28<27:31,  6.14s/it]

✅ [Row 131] GPT Received: {
  "reasoning": "The Anchor story revolves around Claude's journey from a small town to Montreal, h...
🚀 [Row 131] Claude: Sending request...

 33%|███▎      | 132/400 [18:36<40:31,  9.07s/it]

✅ [Row 133] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a young filmmaker (Emrah) struggling against bureauc...
🏁 [Row 133] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 135] Gemini: Sending request...

 33%|███▎      | 132/400 [18:37<40:31,  9.07s/it]

✅ [Row 134] Gemini Received: {
  "reasoning": "The Anchor text features an individual (a clerk) who commits a calculated crime (e...
🚀 [Row 134] GPT: Sending request...

 33%|███▎      | 133/400 [18:37<29:58,  6.74s/it]

✅ [Row 132] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve romantic conflicts and sacrifices, but Text...
🏁 [Row 132] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 136] Gemini: Sending request...

 34%|███▎      | 134/400 [18:39<22:43,  5.13s/it]

✅ [Row 131] Claude Received: ```json
{
  "reasoning": "The Anchor follows a protagonist (Claude) who leaves his small town for th...
🏁 [Row 131] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 137] Gemini: Sending request...

 34%|███▎      | 134/400 [18:40<22:43,  5.13s/it]

⏳ [Row 136] Gemini: Rate limit (Attempt 1)

 34%|███▎      | 134/400 [18:41<22:43,  5.13s/it]

✅ [Row 134] GPT Received: {
  "reasoning": "The Anchor story revolves around a bank clerk who steals money and offers to split...
🚀 [Row 134] Claude: Sending request...

 34%|███▍      | 135/400 [18:50<30:40,  6.94s/it]

✅ [Row 134] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a bank employee who steals money with a specif...
🏁 [Row 134] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 138] Gemini: Sending request...

 34%|███▍      | 135/400 [18:52<30:40,  6.94s/it]

✅ [Row 137] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature a forbidden rom...
🚀 [Row 137] GPT: Sending request...
✅ [Row 135] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature pro...
🚀 [Row 135] GPT: Sending request...

 34%|███▍      | 135/400 [18:54<30:40,  6.94s/it]

✅ [Row 136] Gemini Received: {
  "reasoning": "The Anchor story centers on an unjustly imprisoned royal with a legitimate claim t...
🚀 [Row 136] GPT: Sending request...

 34%|███▍      | 135/400 [18:55<30:40,  6.94s/it]

✅ [Row 135] GPT Received: {
  "reasoning": "The Anchor story involves themes of murder, reanimation, and a performance, with a...
🚀 [Row 135] Claude: Sending request...

 34%|███▍      | 135/400 [18:56<30:40,  6.94s/it]

✅ [Row 137] GPT Received: {
  "reasoning": "The Anchor story revolves around a romantic conflict influenced by family disappro...
🚀 [Row 137] Claude: Sending request...

 34%|███▍      | 135/400 [18:58<30:40,  6.94s/it]

✅ [Row 136] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of injustice, imprisonment, and rightful cl...
🚀 [Row 136] Claude: Sending request...

 34%|███▍      | 135/400 [19:00<30:40,  6.94s/it]

✅ [Row 138] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B focus on a ...
🚀 [Row 138] GPT: Sending request...

 34%|███▍      | 136/400 [19:04<39:21,  8.95s/it]

✅ [Row 137] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories feature: (1) a ro...
🏁 [Row 137] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 139] Gemini: Sending request...

 34%|███▍      | 136/400 [19:04<39:21,  8.95s/it]

✅ [Row 138] GPT Received: {
  "reasoning": "The Anchor text and Text B both revolve around the theme of family struggles durin...
🚀 [Row 138] Claude: Sending request...

 34%|███▍      | 137/400 [19:08<33:27,  7.63s/it]

✅ [Row 136] Claude Received: ```json
{
  "reasoning": "The Anchor is about a wrongfully imprisoned royal (the King's twin brother...
🏁 [Row 136] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 140] Gemini: Sending request...

 34%|███▍      | 138/400 [19:12<28:52,  6.61s/it]

✅ [Row 135] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a murdered opera singer who is reanimated by a villa...
🏁 [Row 135] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 141] Gemini: Sending request...

 35%|███▍      | 139/400 [19:16<25:20,  5.83s/it]

✅ [Row 138] Claude Received: ```json
{
  "reasoning": "Both texts share the wartime setting and focus on women struggling to main...
🏁 [Row 138] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 142] Gemini: Sending request...

 35%|███▍      | 139/400 [19:17<25:20,  5.83s/it]

✅ [Row 140] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center on a...
🚀 [Row 140] GPT: Sending request...

 35%|███▍      | 139/400 [19:17<25:20,  5.83s/it]

✅ [Row 139] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share the c...
🚀 [Row 139] GPT: Sending request...

 35%|███▍      | 139/400 [19:19<25:20,  5.83s/it]

✅ [Row 141] Gemini Received: {
  "reasoning": "The Anchor text focuses on a woman's growing fear of commitment and disillusionmen...
🚀 [Row 141] GPT: Sending request...

 35%|███▍      | 139/400 [19:21<25:20,  5.83s/it]

✅ [Row 139] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve characters in Cuba facing political and so...
🚀 [Row 139] Claude: Sending request...

 35%|███▍      | 139/400 [19:22<25:20,  5.83s/it]

✅ [Row 140] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of impotence, social status, and the conse...
🚀 [Row 140] Claude: Sending request...

 35%|███▍      | 139/400 [19:24<25:20,  5.83s/it]

✅ [Row 141] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of marriage, commitment, and infidelity...
🚀 [Row 141] Claude: Sending request...

 35%|███▌      | 140/400 [19:31<36:12,  8.36s/it]

✅ [Row 139] Claude Received: ```json
{
  "reasoning": "The Anchor follows Reinaldo Arenas' life journey in Cuba: his personal/art...
🏁 [Row 139] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 143] Gemini: Sending request...

 35%|███▌      | 141/400 [19:32<27:00,  6.26s/it]

✅ [Row 142] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist, Marianne, whose attempts to rebuild her li...
🚀 [Row 142] GPT: Sending request...
✅ [Row 140] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a businessman who becomes impotent after taking a th...
🏁 [Row 140] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 144] Gemini: Sending request...

 36%|███▌      | 142/400 [19:32<19:09,  4.45s/it]

✅ [Row 141] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a woman's fear of commitment and discovery of multip...
🏁 [Row 141] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 145] Gemini: Sending request...

 36%|███▌      | 142/400 [19:37<19:09,  4.45s/it]

✅ [Row 142] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of crime, redemption, and personal transfo...
🚀 [Row 142] Claude: Sending request...

 36%|███▌      | 142/400 [19:41<19:09,  4.45s/it]

✅ [Row 144] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 144] GPT: Sending request...

 36%|███▌      | 142/400 [19:41<19:09,  4.45s/it]

✅ [Row 143] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a f...
🚀 [Row 143] GPT: Sending request...

 36%|███▌      | 142/400 [19:42<19:09,  4.45s/it]

✅ [Row 145] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 145] GPT: Sending request...

 36%|███▌      | 142/400 [19:45<19:09,  4.45s/it]

✅ [Row 143] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve characters who are trying to improve thei...
🚀 [Row 143] Claude: Sending request...

 36%|███▌      | 142/400 [19:46<19:09,  4.45s/it]

✅ [Row 144] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve characters who believe they are animals (...
🚀 [Row 144] Claude: Sending request...

 36%|███▌      | 142/400 [19:48<19:09,  4.45s/it]

✅ [Row 145] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of murder, justice, and hidden truths in a ...
🚀 [Row 145] Claude: Sending request...

 36%|███▌      | 143/400 [19:48<33:42,  7.87s/it]

✅ [Row 142] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Marianne, a woman whose husband commits suicide afte...
🏁 [Row 142] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 146] Gemini: Sending request...

 36%|███▌      | 144/400 [19:54<31:38,  7.41s/it]

✅ [Row 143] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic complications with financial undertones, but T...
🏁 [Row 143] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 147] Gemini: Sending request...

 36%|███▋      | 145/400 [19:55<22:45,  5.36s/it]

✅ [Row 144] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a historical serial killer (Romasanta) who cla...
🏁 [Row 144] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 148] Gemini: Sending request...

 36%|███▋      | 146/400 [19:59<20:40,  4.89s/it]

✅ [Row 145] Claude Received: ```json
{
  "reasoning": "Both texts share the core element of a corrupt/evil figure being murdered ...
🏁 [Row 145] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 149] Gemini: Sending request...

 36%|███▋      | 146/400 [20:07<20:40,  4.89s/it]

✅ [Row 146] Gemini Received: {
  "reasoning": "The Anchor text describes an aging, isolated man (Celestino) who undertakes a diff...
🚀 [Row 146] GPT: Sending request...

 36%|███▋      | 146/400 [20:09<20:40,  4.89s/it]

✅ [Row 148] Gemini Received: {
  "reasoning": "The Anchor text describes a narrative centered on corruption, manipulation, and th...
🚀 [Row 148] GPT: Sending request...
✅ [Row 149] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A center on a protagonist...
🚀 [Row 149] GPT: Sending request...

 36%|███▋      | 146/400 [20:10<20:40,  4.89s/it]

✅ [Row 147] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a s...
🚀 [Row 147] GPT: Sending request...

 36%|███▋      | 146/400 [20:12<20:40,  4.89s/it]

✅ [Row 146] GPT Received: {
  "reasoning": "The Anchor story revolves around Celestino, a Quechua peasant, dealing with loss a...
🚀 [Row 146] Claude: Sending request...

 36%|███▋      | 146/400 [20:15<20:40,  4.89s/it]

✅ [Row 148] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of corruption, manipulation, and the inters...
🚀 [Row 148] Claude: Sending request...

 36%|███▋      | 146/400 [20:15<20:40,  4.89s/it]

✅ [Row 149] GPT Received: {
  "reasoning": "The Anchor story revolves around Lutz dealing with the sudden reappearance of his ...
🚀 [Row 149] Claude: Sending request...

 36%|███▋      | 146/400 [20:16<20:40,  4.89s/it]

✅ [Row 147] GPT Received: {
  "reasoning": "The Anchor story revolves around a timid boy gaining courage through a supposed ma...
🚀 [Row 147] Claude: Sending request...

 37%|███▋      | 147/400 [20:22<43:17, 10.27s/it]

✅ [Row 146] Claude Received: ```json
{
  "reasoning": "Both texts share some thematic elements with the Anchor, but Text B is nar...
🏁 [Row 146] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 150] Gemini: Sending request...

 37%|███▋      | 148/400 [20:24<32:38,  7.77s/it]

✅ [Row 147] Claude Received: ```json
{
  "reasoning": "Text A shares the core narrative structure with the Anchor: (1) A grandmot...
🏁 [Row 147] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 151] Gemini: Sending request...

 37%|███▋      | 149/400 [20:24<23:30,  5.62s/it]

✅ [Row 149] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a son (Lutz) whose life is disrupted by his problema...
🏁 [Row 149] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 152] Gemini: Sending request...

 38%|███▊      | 150/400 [20:29<22:42,  5.45s/it]

✅ [Row 148] Claude Received: ```json
{
  "reasoning": "The Anchor involves a wealthy woman (Miss Alice) and her associates (lawye...
🏁 [Row 148] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 153] Gemini: Sending request...

 38%|███▊      | 150/400 [20:30<22:42,  5.45s/it]

✅ [Row 150] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 150] GPT: Sending request...

 38%|███▊      | 150/400 [20:34<22:42,  5.45s/it]

✅ [Row 151] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 151] GPT: Sending request...

 38%|███▊      | 150/400 [20:35<22:42,  5.45s/it]

✅ [Row 152] Gemini Received: {
  "reasoning": "The Anchor text describes the profound psychological impact of war, leading to a '...
🚀 [Row 152] GPT: Sending request...

 38%|███▊      | 150/400 [20:36<22:42,  5.45s/it]

✅ [Row 150] GPT Received: {
  "reasoning": "The Anchor story revolves around Sonny Steele's journey to free a mistreated horse...
🚀 [Row 150] Claude: Sending request...

 38%|███▊      | 150/400 [20:39<22:42,  5.45s/it]

✅ [Row 151] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of financial loss, unexpected encounters, ...
🚀 [Row 151] Claude: Sending request...

 38%|███▊      | 150/400 [20:40<22:42,  5.45s/it]

✅ [Row 152] GPT Received: {
  "reasoning": "The Anchor text deals with themes of social upheaval, personal betrayal, and the p...
🚀 [Row 152] Claude: Sending request...

 38%|███▊      | 151/400 [20:46<36:58,  8.91s/it]

✅ [Row 150] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a disillusioned former rodeo champion who absc...
🏁 [Row 150] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 154] Gemini: Sending request...

 38%|███▊      | 152/400 [20:50<30:48,  7.45s/it]

✅ [Row 152] Claude Received: ```json
{
  "reasoning": "The Anchor depicts post-WWI Germany with multiple interconnected character...
🏁 [Row 152] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 155] Gemini: Sending request...

✅ [Row 153] Gemini Received: {
  "reasoning": "The Anchor text describes multiple desperate characters attempting to 'cheat their...
🚀 [Row 153] GPT: Sending request...
✅ [Row 151] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a romantic relationship born from a financial power ...

 38%|███▊      | 153/400 [20:51<22:25,  5.45s/it]

🏁 [Row 151] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 156] Gemini: Sending request...

 38%|███▊      | 153/400 [20:53<22:25,  5.45s/it]

⏳ [Row 156] Gemini: Rate limit (Attempt 1)

 38%|███▊      | 153/400 [20:55<22:25,  5.45s/it]

✅ [Row 153] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve complex scams and cons, with multiple cha...
🚀 [Row 153] Claude: Sending request...

 38%|███▊      | 153/400 [20:56<22:25,  5.45s/it]

✅ [Row 154] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 154] GPT: Sending request...

 38%|███▊      | 153/400 [21:00<22:25,  5.45s/it]

✅ [Row 155] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A depict a pa...
🚀 [Row 155] GPT: Sending request...

 38%|███▊      | 153/400 [21:03<22:25,  5.45s/it]

✅ [Row 154] GPT Received: {
  "reasoning": "The Anchor story is about a boy named Haoyou who, after his father's death, joins ...
🚀 [Row 154] Claude: Sending request...

 38%|███▊      | 153/400 [21:04<22:25,  5.45s/it]

✅ [Row 155] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve illicit affairs that lead to tragic outco...
🚀 [Row 155] Claude: Sending request...

 38%|███▊      | 153/400 [21:04<22:25,  5.45s/it]

✅ [Row 156] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature pro...
🚀 [Row 156] GPT: Sending request...

 38%|███▊      | 154/400 [21:05<32:35,  7.95s/it]

✅ [Row 153] Claude Received: ```json
{
  "reasoning": "The Anchor centers on three separate characters caught in desperate financ...
🏁 [Row 153] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 157] Gemini: Sending request...

 38%|███▊      | 154/400 [21:10<32:35,  7.95s/it]

✅ [Row 156] GPT Received: {
  "reasoning": "The Anchor story revolves around Joe Bonaparte, a young violinist who turns to box...
🚀 [Row 156] Claude: Sending request...

 39%|███▉      | 155/400 [21:12<31:49,  7.80s/it]

✅ [Row 154] Claude Received: {
  "reasoning": "The Anchor revolves around a boy (Haoyou) whose father dies in a kite-related acci...
🏁 [Row 154] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 158] Gemini: Sending request...

 39%|███▉      | 156/400 [21:14<24:53,  6.12s/it]

✅ [Row 155] Claude Received: ```json
{
  "reasoning": "Both texts involve fatal outcomes of passionate affairs, but Text B is nar...
🏁 [Row 155] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 159] Gemini: Sending request...

 39%|███▉      | 156/400 [21:18<24:53,  6.12s/it]

✅ [Row 157] Gemini Received: {
  "reasoning": "The Anchor text centers on a family's desperate struggle to obtain life-saving med...
🚀 [Row 157] GPT: Sending request...

 39%|███▉      | 157/400 [21:21<25:29,  6.29s/it]

✅ [Row 156] Claude Received: ```json
{
  "reasoning": "The Anchor follows a talented young artist (violinist Joe) who abandons hi...
🏁 [Row 156] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 160] Gemini: Sending request...

 39%|███▉      | 157/400 [21:22<25:29,  6.29s/it]

✅ [Row 157] GPT Received: {
  "reasoning": "The Anchor story revolves around a Roma family facing a medical emergency and fina...
🚀 [Row 157] Claude: Sending request...

 39%|███▉      | 157/400 [21:29<25:29,  6.29s/it]

✅ [Row 159] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor's central theme revolves ar...
🚀 [Row 159] GPT: Sending request...

 39%|███▉      | 157/400 [21:31<25:29,  6.29s/it]

✅ [Row 160] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center arou...
🚀 [Row 160] GPT: Sending request...

 40%|███▉      | 158/400 [21:31<29:51,  7.40s/it]

✅ [Row 157] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a Roma family facing a medical emergency (the wife's...
🏁 [Row 157] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 161] Gemini: Sending request...

 40%|███▉      | 158/400 [21:33<29:51,  7.40s/it]

✅ [Row 159] GPT Received: {
  "reasoning": "The Anchor story revolves around Cleo's quest to find a magical watch to turn back...
🚀 [Row 159] Claude: Sending request...

 40%|███▉      | 158/400 [21:34<29:51,  7.40s/it]

⏳ [Row 161] Gemini: Rate limit (Attempt 1)

 40%|███▉      | 158/400 [21:34<29:51,  7.40s/it]

✅ [Row 160] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of infidelity, hidden parentage, and a son...
🚀 [Row 160] Claude: Sending request...

 40%|███▉      | 158/400 [21:40<29:51,  7.40s/it]

✅ [Row 158] Gemini Received: {
  "reasoning": "Both the Anchor and Text A feature a narrative driven by a specific, central event...
🚀 [Row 158] GPT: Sending request...

 40%|███▉      | 159/400 [21:42<33:21,  8.30s/it]

✅ [Row 159] Claude Received: ```json
{
  "reasoning": "Both texts share some surface similarities with the Anchor (Berlin setting...
🏁 [Row 159] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 162] Gemini: Sending request...

 40%|███▉      | 159/400 [21:43<33:21,  8.30s/it]

✅ [Row 161] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A feature a central romantic couple facing significa...
🚀 [Row 161] GPT: Sending request...
✅ [Row 158] GPT Received: {
  "reasoning": "The Anchor story revolves around Ray and Mary Burkett's trip to Wal-Mart, during w...
🚀 [Row 158] Claude: Sending request...

 40%|████      | 160/400 [21:45<27:32,  6.88s/it]

✅ [Row 160] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a dysfunctional marriage involving Francesca, who is...
🏁 [Row 160] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 163] Gemini: Sending request...

 40%|████      | 160/400 [21:48<27:32,  6.88s/it]

⏳ [Row 163] Gemini: Rate limit (Attempt 1)

 40%|████      | 160/400 [21:49<27:32,  6.88s/it]

✅ [Row 161] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of overcoming societal and familial prejud...
🚀 [Row 161] Claude: Sending request...

 40%|████      | 161/400 [21:55<31:15,  7.85s/it]

✅ [Row 158] Claude Received: ```json
{
  "reasoning": "Both texts involve death and family relationships, but Text B is narrative...
🏁 [Row 158] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 164] Gemini: Sending request...

 40%|████      | 161/400 [21:57<31:15,  7.85s/it]

✅ [Row 162] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor features a story involving ...
🚀 [Row 162] GPT: Sending request...
✅ [Row 163] Gemini Received: {
  "reasoning": "The Anchor text describes a narrative centered around a strategic act of deception...
🚀 [Row 163] GPT: Sending request...

 40%|████      | 162/400 [21:58<25:31,  6.43s/it]

✅ [Row 161] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a cross-cultural romance between Ali (Pakistani desc...
🏁 [Row 161] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 165] Gemini: Sending request...

 40%|████      | 162/400 [22:00<25:31,  6.43s/it]

✅ [Row 162] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, betrayal, and escape, with a cour...
🚀 [Row 162] Claude: Sending request...
✅ [Row 163] GPT Received: {
  "reasoning": "The Anchor text involves a strategic deception where soldiers are hidden in sacks ...
🚀 [Row 163] Claude: Sending request...

 40%|████      | 162/400 [22:06<25:31,  6.43s/it]

✅ [Row 164] Gemini Received: {
  "reasoning": "The Anchor text features a husband whose marriage is strained, leading him to seek...
🚀 [Row 164] GPT: Sending request...

 41%|████      | 163/400 [22:09<30:15,  7.66s/it]

✅ [Row 162] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a prison warden's wife who falls in love with an inm...
🏁 [Row 162] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 166] Gemini: Sending request...

 41%|████      | 163/400 [22:10<30:15,  7.66s/it]

⏳ [Row 166] Gemini: Rate limit (Attempt 1)

 41%|████      | 163/400 [22:10<30:15,  7.66s/it]

✅ [Row 165] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 165] GPT: Sending request...

 41%|████      | 163/400 [22:11<30:15,  7.66s/it]

✅ [Row 164] GPT Received: {
  "reasoning": "The Anchor story revolves around a troubled marriage that is revitalized after one...
🚀 [Row 164] Claude: Sending request...

 41%|████      | 164/400 [22:11<23:56,  6.09s/it]

✅ [Row 163] Claude Received: ```json
{
  "reasoning": "The Anchor story is fundamentally about strategic deception in warfare: Dj...
🏁 [Row 163] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 167] Gemini: Sending request...

 41%|████      | 164/400 [22:14<23:56,  6.09s/it]

✅ [Row 165] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve themes of exploration and discovery, with ...
🚀 [Row 165] Claude: Sending request...

 41%|████▏     | 165/400 [22:22<29:21,  7.50s/it]

✅ [Row 164] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a loveless marriage that is revitalized throug...
🏁 [Row 164] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 168] Gemini: Sending request...

 42%|████▏     | 166/400 [22:27<25:41,  6.59s/it]

✅ [Row 165] Claude Received: ```json
{
  "reasoning": "Both texts share some surface similarities with the Anchor (European histo...
🏁 [Row 165] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 169] Gemini: Sending request...

 42%|████▏     | 166/400 [22:28<25:41,  6.59s/it]

✅ [Row 167] Gemini Received: {
  "reasoning": "The Anchor text describes tourists captured by a native tribe in a jungle, leading...
🚀 [Row 167] GPT: Sending request...

 42%|████▏     | 166/400 [22:31<25:41,  6.59s/it]

✅ [Row 168] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A prominently...
🚀 [Row 168] GPT: Sending request...
✅ [Row 167] GPT Received: {
  "reasoning": "The Anchor story involves themes of captivity, survival, and rescue in a jungle se...
🚀 [Row 167] Claude: Sending request...

 42%|████▏     | 166/400 [22:31<25:41,  6.59s/it]

✅ [Row 166] Gemini Received: {
  "reasoning": "Both Text A and Text B are narratively distant from the Anchor text. However, Text...
🚀 [Row 166] GPT: Sending request...

 42%|████▏     | 166/400 [22:34<25:41,  6.59s/it]

✅ [Row 168] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve themes of deception, betrayal, and the pur...
🚀 [Row 168] Claude: Sending request...

 42%|████▏     | 166/400 [22:35<25:41,  6.59s/it]

✅ [Row 166] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of suspicion, misunderstanding, and eventu...
🚀 [Row 166] Claude: Sending request...

 42%|████▏     | 166/400 [22:39<25:41,  6.59s/it]

✅ [Row 169] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a s...
🚀 [Row 169] GPT: Sending request...

 42%|████▏     | 167/400 [22:40<34:03,  8.77s/it]

✅ [Row 167] Claude Received: ```json
{
  "reasoning": "Both texts involve adventure stories with colonial/exploitative contexts, ...
🏁 [Row 167] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 170] Gemini: Sending request...

 42%|████▏     | 167/400 [22:43<34:03,  8.77s/it]

✅ [Row 169] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve a military officer with a history in the V...
🚀 [Row 169] Claude: Sending request...

 42%|████▏     | 168/400 [22:44<27:39,  7.15s/it]

✅ [Row 168] Claude Received: ```json
{
  "reasoning": "The Anchor involves deathbed advice to sons about knavery, parallel storyl...
🏁 [Row 168] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 171] Gemini: Sending request...

 42%|████▏     | 169/400 [22:45<20:10,  5.24s/it]

✅ [Row 166] Claude Received: ```json
{
  "reasoning": "The Anchor is about a husband who suspects his wife of infidelity, hires a...
🏁 [Row 166] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 172] Gemini: Sending request...

 42%|████▏     | 169/400 [22:50<20:10,  5.24s/it]

✅ [Row 170] Gemini Received: {
  "reasoning": "The Anchor text features a complex investigation into serial murders, where the po...
🚀 [Row 170] GPT: Sending request...

 42%|████▏     | 169/400 [22:52<20:10,  5.24s/it]

✅ [Row 171] Gemini Received: {
  "reasoning": "The Anchor text describes a story about two brothers and others who unite to fight...
🚀 [Row 171] GPT: Sending request...

✅ [Row 172] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B promin...
🚀 [Row 172] GPT: Sending request...
✅ [Row 169] Claude Received: ```json
{
  "reasoning": "The Anchor follows Colonel Braddock, a former POW who returns to Vietnam/S...

 42%|████▎     | 170/400 [22:54<24:44,  6.45s/it]

🏁 [Row 169] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 173] Gemini: Sending request...

 42%|████▎     | 170/400 [22:55<24:44,  6.45s/it]

✅ [Row 170] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a serial killer whose actions are eventual...
🚀 [Row 170] Claude: Sending request...

 42%|████▎     | 170/400 [22:56<24:44,  6.45s/it]

✅ [Row 171] GPT Received: {
  "reasoning": "The Anchor story revolves around a conflict involving land developers threatening ...
🚀 [Row 171] Claude: Sending request...

 42%|████▎     | 170/400 [23:00<24:44,  6.45s/it]

✅ [Row 172] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of social mobility, the decline of nobility...
🚀 [Row 172] Claude: Sending request...

 43%|████▎     | 171/400 [23:04<28:58,  7.59s/it]

✅ [Row 170] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around Sherlock Holmes investigating Jack the Ripper m...
🏁 [Row 170] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 174] Gemini: Sending request...

 43%|████▎     | 171/400 [23:06<28:58,  7.59s/it]

✅ [Row 173] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor's central conflict revolves...
🚀 [Row 173] GPT: Sending request...

 43%|████▎     | 172/400 [23:09<26:12,  6.90s/it]

✅ [Row 171] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a conflict between preserving Native American ...
🏁 [Row 171] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 175] Gemini: Sending request...

 43%|████▎     | 172/400 [23:10<26:12,  6.90s/it]

✅ [Row 173] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of ownership and control over a valuabl...
🚀 [Row 173] Claude: Sending request...

 43%|████▎     | 173/400 [23:12<21:24,  5.66s/it]

✅ [Row 172] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Anton's journey from apprentice to successful mercha...
🏁 [Row 172] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 176] Gemini: Sending request...

 43%|████▎     | 173/400 [23:18<21:24,  5.66s/it]

✅ [Row 174] Gemini Received: {
  "reasoning": "Text B shares the core narrative elements with the Anchor text: a group of struggl...
🚀 [Row 174] GPT: Sending request...
✅ [Row 175] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A share ...
🚀 [Row 175] GPT: Sending request...

 44%|████▎     | 174/400 [23:19<22:47,  6.05s/it]

✅ [Row 173] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an inherited private island territory, succession af...
🏁 [Row 173] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 177] Gemini: Sending request...
✅ [Row 176] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B center...
🚀 [Row 176] GPT: Sending request...

 44%|████▎     | 174/400 [23:22<22:47,  6.05s/it]

✅ [Row 174] GPT Received: {
  "reasoning": "The Anchor story involves a detective agency infiltrating a smuggling operation by...
🚀 [Row 174] Claude: Sending request...
✅ [Row 175] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of class interaction, love across social bo...
🚀 [Row 175] Claude: Sending request...

 44%|████▎     | 174/400 [23:24<22:47,  6.05s/it]

✅ [Row 176] GPT Received: {
  "reasoning": "The Anchor story revolves around a child, Asia, who is found abandoned and taken i...
🚀 [Row 176] Claude: Sending request...

 44%|████▍     | 175/400 [23:30<28:40,  7.65s/it]

✅ [Row 174] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve undercover operations to infiltrate crimina...
🏁 [Row 174] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 178] Gemini: Sending request...

 44%|████▍     | 176/400 [23:31<20:28,  5.48s/it]

✅ [Row 175] Claude Received: ```json
{
  "reasoning": "Text A shares significant narrative similarities with the Anchor. Both sto...
🏁 [Row 175] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 179] Gemini: Sending request...

 44%|████▍     | 176/400 [23:37<20:28,  5.48s/it]

✅ [Row 177] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a c...
🚀 [Row 177] GPT: Sending request...

 44%|████▍     | 177/400 [23:39<23:03,  6.20s/it]

✅ [Row 176] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an abandoned child (Asia) temporarily taken in by ci...
🏁 [Row 176] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 180] Gemini: Sending request...

 44%|████▍     | 177/400 [23:40<23:03,  6.20s/it]

✅ [Row 177] GPT Received: {
  "reasoning": "The Anchor story involves a former detective protecting a woman accused of murder,...
🚀 [Row 177] Claude: Sending request...

 44%|████▍     | 177/400 [23:42<23:03,  6.20s/it]

✅ [Row 178] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a f...
🚀 [Row 178] GPT: Sending request...

 44%|████▍     | 177/400 [23:46<23:03,  6.20s/it]

✅ [Row 178] GPT Received: {
  "reasoning": "The Anchor text revolves around Lady Hamilton's relationships and her influence on...
🚀 [Row 178] Claude: Sending request...

 44%|████▍     | 177/400 [23:48<23:03,  6.20s/it]

✅ [Row 180] Gemini Received: {
  "reasoning": "The Anchor text focuses on a criminal subculture with a clear leader, a succession...
🚀 [Row 180] GPT: Sending request...

 44%|████▍     | 178/400 [23:50<28:32,  7.71s/it]

✅ [Row 177] Claude Received: ```json
{
  "reasoning": "The Anchor follows a clear crime investigation/protection narrative: a det...
🏁 [Row 177] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 181] Gemini: Sending request...

 44%|████▍     | 178/400 [23:52<28:32,  7.71s/it]

✅ [Row 180] GPT Received: {
  "reasoning": "The Anchor story revolves around a reluctant leader, Dave, who is thrust into a po...
🚀 [Row 180] Claude: Sending request...
✅ [Row 179] Gemini Received: {
  "reasoning": "The Anchor story describes how ordinary individuals (Otto and Anna) are politicize...
🚀 [Row 179] GPT: Sending request...

 44%|████▍     | 178/400 [23:56<28:32,  7.71s/it]

✅ [Row 181] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share the a...
🚀 [Row 181] GPT: Sending request...

 44%|████▍     | 178/400 [23:57<28:32,  7.71s/it]

✅ [Row 179] GPT Received: {
  "reasoning": "The Anchor story is about Otto and Anna Quangel, who become politicized after pers...
🚀 [Row 179] Claude: Sending request...

 44%|████▍     | 178/400 [24:00<28:32,  7.71s/it]

✅ [Row 181] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve St. Peter and the theme of admission to H...
🚀 [Row 181] Claude: Sending request...

 45%|████▍     | 179/400 [24:03<33:53,  9.20s/it]

✅ [Row 180] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on leadership succession within a criminal Gypsy clan, ...
🏁 [Row 180] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 182] Gemini: Sending request...

 45%|████▌     | 180/400 [24:05<26:37,  7.26s/it]

✅ [Row 178] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic entanglements and historical settings, but Tex...
🏁 [Row 178] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 183] Gemini: Sending request...

 45%|████▌     | 181/400 [24:07<20:39,  5.66s/it]

✅ [Row 179] Claude Received: ```json
{
  "reasoning": "Both texts are set during WWII and deal with resistance against Nazi oppre...
🏁 [Row 179] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 184] Gemini: Sending request...

 46%|████▌     | 182/400 [24:12<19:21,  5.33s/it]

✅ [Row 181] Claude Received: ```json
{
  "reasoning": "The Anchor is about St. Peter letting someone into Heaven against God's or...
🏁 [Row 181] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 185] Gemini: Sending request...

 46%|████▌     | 182/400 [24:13<19:21,  5.33s/it]

✅ [Row 183] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A involve a p...
🚀 [Row 183] GPT: Sending request...

 46%|████▌     | 182/400 [24:14<19:21,  5.33s/it]

✅ [Row 182] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A involv...
🚀 [Row 182] GPT: Sending request...

 46%|████▌     | 182/400 [24:18<19:21,  5.33s/it]

✅ [Row 183] GPT Received: {
  "reasoning": "The Anchor story revolves around a family with unique skills in taekwondo, facing ...
🚀 [Row 183] Claude: Sending request...

 46%|████▌     | 182/400 [24:19<19:21,  5.33s/it]

✅ [Row 182] GPT Received: {
  "reasoning": "The Anchor story involves a modern setting with supernatural elements, focusing on...
🚀 [Row 182] Claude: Sending request...

 46%|████▌     | 182/400 [24:22<19:21,  5.33s/it]

✅ [Row 185] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a r...
🚀 [Row 185] GPT: Sending request...

 46%|████▌     | 182/400 [24:23<19:21,  5.33s/it]

✅ [Row 184] Gemini Received: {
  "reasoning": "The Anchor story is about a convicted murderer finding redemption, purpose, and lo...
🚀 [Row 184] GPT: Sending request...

 46%|████▌     | 182/400 [24:27<19:21,  5.33s/it]

✅ [Row 185] GPT Received: {
  "reasoning": "The Anchor story involves themes of disguise, espionage, and romance set against a...
🚀 [Row 185] Claude: Sending request...

 46%|████▌     | 182/400 [24:29<19:21,  5.33s/it]

✅ [Row 184] GPT Received: {
  "reasoning": "The Anchor story revolves around a convicted murderer, Colin, who finds redemption...
🚀 [Row 184] Claude: Sending request...

 46%|████▌     | 183/400 [24:30<33:02,  9.14s/it]

✅ [Row 183] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve protagonists who interfere with criminal ga...
🏁 [Row 183] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 186] Gemini: Sending request...

 46%|████▌     | 184/400 [24:30<23:33,  6.55s/it]

✅ [Row 182] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a modern couple (Tid Mak and Nak) purchasing a haunt...
🏁 [Row 182] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 187] Gemini: Sending request...

 46%|████▋     | 185/400 [24:38<24:03,  6.71s/it]

✅ [Row 185] Claude Received: ```json
{
  "reasoning": "The Anchor involves a protagonist (Paul) hiding behind enemy lines in an o...
🏁 [Row 185] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 188] Gemini: Sending request...

 46%|████▋     | 186/400 [24:40<19:39,  5.51s/it]

✅ [Row 184] Claude Received: ```json
{
  "reasoning": "The Anchor is about a convicted murderer (Colin) who discovers gardening i...
🏁 [Row 184] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 189] Gemini: Sending request...

 46%|████▋     | 186/400 [24:42<19:39,  5.51s/it]

✅ [Row 186] Gemini Received: {
  "reasoning": "The Anchor text describes an experienced con man, Mordecai, befriending and formin...
🚀 [Row 186] GPT: Sending request...

 46%|████▋     | 186/400 [24:47<19:39,  5.51s/it]

✅ [Row 186] GPT Received: {
  "reasoning": "The Anchor story revolves around a con artist, Mordecai, who teams up with a young...
🚀 [Row 186] Claude: Sending request...

 46%|████▋     | 186/400 [24:50<19:39,  5.51s/it]

✅ [Row 189] Gemini Received: {
  "reasoning": "The Anchor text features a clear conflict against authority (Mars vs. Jupiter), le...
🚀 [Row 189] GPT: Sending request...

 46%|████▋     | 186/400 [24:55<19:39,  5.51s/it]

✅ [Row 187] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center on t...
🚀 [Row 187] GPT: Sending request...

 46%|████▋     | 186/400 [24:56<19:39,  5.51s/it]

✅ [Row 188] Gemini Received: {
  "reasoning": "The Anchor text centers on a private investigator forming an unexpected bond and p...
🚀 [Row 188] GPT: Sending request...

 46%|████▋     | 186/400 [24:58<19:39,  5.51s/it]

✅ [Row 189] GPT Received: {
  "reasoning": "The Anchor story involves a conflict between gods, with Mars and Venus attempting ...
🚀 [Row 189] Claude: Sending request...

 47%|████▋     | 187/400 [24:59<33:16,  9.37s/it]

✅ [Row 187] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, marriage, and fidelity, with a co...
🚀 [Row 187] Claude: Sending request...
✅ [Row 186] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a seasoned con artist (Mordecai) who befriends and t...
🏁 [Row 186] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 190] Gemini: Sending request...

 47%|████▋     | 187/400 [25:02<33:16,  9.37s/it]

✅ [Row 188] GPT Received: {
  "reasoning": "The Anchor story revolves around a private investigator, V.I. Warshawski, who is d...
🚀 [Row 188] Claude: Sending request...

 47%|████▋     | 187/400 [25:06<33:16,  9.37s/it]

✅ [Row 190] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B share ...
🚀 [Row 190] GPT: Sending request...

 47%|████▋     | 188/400 [25:08<33:16,  9.42s/it]

✅ [Row 189] Claude Received: ```json
{
  "reasoning": "The Anchor is a mythological tale involving gods (Jupiter, Mars, Venus, Vu...
🏁 [Row 189] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 191] Gemini: Sending request...

 47%|████▋     | 188/400 [25:09<33:16,  9.42s/it]

❌ [Row 191] Gemini Exception: 'candidates'

 47%|████▋     | 188/400 [25:10<33:16,  9.42s/it]

✅ [Row 190] GPT Received: {
  "reasoning": "The Anchor text revolves around three men on death row, each with a backstory invo...
🚀 [Row 190] Claude: Sending request...

 47%|████▋     | 188/400 [25:11<33:16,  9.42s/it]

❌ [Row 191] Gemini Exception: 'candidates'

 47%|████▋     | 189/400 [25:11<26:06,  7.42s/it]

✅ [Row 187] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a married woman (Maggie) who achieves domestic happi...
🏁 [Row 187] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 192] Gemini: Sending request...

 47%|████▋     | 189/400 [25:12<26:06,  7.42s/it]

❌ [Row 191] Gemini Exception: 'candidates'

 47%|████▋     | 189/400 [25:13<26:06,  7.42s/it]

🚀 [Row 191] GPT: Sending request...

 48%|████▊     | 190/400 [25:14<21:00,  6.00s/it]

✅ [Row 188] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a private investigator who befriends a victim's daug...
🏁 [Row 188] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 193] Gemini: Sending request...

 48%|████▊     | 190/400 [25:17<21:00,  6.00s/it]

✅ [Row 191] GPT Received: {
  "reasoning": "The Anchor story revolves around a family with complex relationships, secrets, and...
🚀 [Row 191] Claude: Sending request...

 48%|████▊     | 191/400 [25:19<20:04,  5.76s/it]

✅ [Row 190] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around three death row inmates, a custodian attempting...
🏁 [Row 190] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 194] Gemini: Sending request...

 48%|████▊     | 192/400 [25:28<23:03,  6.65s/it]

✅ [Row 191] Claude Received: ```json
{
  "reasoning": "Both texts share elements of suspected wrongdoing, romantic entanglements,...
🏁 [Row 191] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 195] Gemini: Sending request...

 48%|████▊     | 192/400 [25:29<23:03,  6.65s/it]

✅ [Row 193] Gemini Received: {
  "reasoning": "The Anchor text is a descriptive snapshot of diverse inhabitants in an apartment b...
🚀 [Row 193] GPT: Sending request...

 48%|████▊     | 192/400 [25:32<23:03,  6.65s/it]

✅ [Row 194] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor because both share the setting of a 'ra...
🚀 [Row 194] GPT: Sending request...

 48%|████▊     | 192/400 [25:33<23:03,  6.65s/it]

✅ [Row 193] GPT Received: {
  "reasoning": "The Anchor text revolves around the theme of community and interconnected lives wi...
🚀 [Row 193] Claude: Sending request...

 48%|████▊     | 192/400 [25:34<23:03,  6.65s/it]

✅ [Row 192] Gemini Received: {
  "reasoning": "The Anchor story centers on a young wife discovering her husband's secret identity...
🚀 [Row 192] GPT: Sending request...

 48%|████▊     | 192/400 [25:36<23:03,  6.65s/it]

✅ [Row 194] GPT Received: {
  "reasoning": "The Anchor story revolves around a radio station, a mentor-mentee relationship, an...
🚀 [Row 194] Claude: Sending request...

 48%|████▊     | 192/400 [25:37<23:03,  6.65s/it]

✅ [Row 195] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist, Sosa, involved in a corrupt legal system (...
🚀 [Row 195] GPT: Sending request...

 48%|████▊     | 192/400 [25:38<23:03,  6.65s/it]

✅ [Row 192] GPT Received: {
  "reasoning": "The Anchor story revolves around a romantic relationship that is disrupted by a sh...
🚀 [Row 192] Claude: Sending request...

 48%|████▊     | 192/400 [25:41<23:03,  6.65s/it]

✅ [Row 195] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of redemption, corruption, and romance, wi...
🚀 [Row 195] Claude: Sending request...

 48%|████▊     | 193/400 [25:46<34:46, 10.08s/it]

✅ [Row 194] Claude Received: ```json
{
  "reasoning": "Text B is narratively closer to the Anchor. Both stories center on romanti...
🏁 [Row 194] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 196] Gemini: Sending request...

 48%|████▊     | 194/400 [25:47<25:49,  7.52s/it]

✅ [Row 192] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a woman who discovers her husband harbors a dar...
🏁 [Row 192] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 197] Gemini: Sending request...

 49%|████▉     | 195/400 [25:53<24:27,  7.16s/it]

✅ [Row 195] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a disgraced lawyer working in a morally gray p...
🏁 [Row 195] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 198] Gemini: Sending request...

 49%|████▉     | 195/400 [25:54<24:27,  7.16s/it]

✅ [Row 197] Gemini Received: {
  "reasoning": "The Anchor text centers around a conflict involving a tobacco plantation and busin...
🚀 [Row 197] GPT: Sending request...

 49%|████▉     | 195/400 [25:55<24:27,  7.16s/it]

⏳ [Row 198] Gemini: Rate limit (Attempt 1)
✅ [Row 196] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share a cor...
🚀 [Row 196] GPT: Sending request...

 49%|████▉     | 195/400 [25:59<24:27,  7.16s/it]

✅ [Row 197] GPT Received: {
  "reasoning": "The Anchor story revolves around a conflict between a young man and his stepfather...
🚀 [Row 197] Claude: Sending request...

 49%|████▉     | 195/400 [25:59<24:27,  7.16s/it]

⏳ [Row 198] Gemini: Rate limit (Attempt 2)

 49%|████▉     | 195/400 [26:02<24:27,  7.16s/it]

✅ [Row 196] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of identity, family secrets, and a quest f...
🚀 [Row 196] Claude: Sending request...

 49%|████▉     | 196/400 [26:09<32:46,  9.64s/it]

✅ [Row 193] Claude Received: ```json
{
  "reasoning": "The Anchor depicts an ensemble cast of diverse neighbors in a Berlin apart...
🏁 [Row 193] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 199] Gemini: Sending request...

 49%|████▉     | 197/400 [26:10<24:12,  7.16s/it]

✅ [Row 197] Claude Received: ```json
{
  "reasoning": "Both texts involve conflicts over plantations, but Text B is narratively c...
🏁 [Row 197] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 200] Gemini: Sending request...

 50%|████▉     | 198/400 [26:11<17:25,  5.17s/it]

✅ [Row 196] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a multi-generational mystery of identity and origins...
🏁 [Row 196] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 201] Gemini: Sending request...

 50%|████▉     | 198/400 [26:19<17:25,  5.17s/it]

✅ [Row 201] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a d...
🚀 [Row 201] GPT: Sending request...

 50%|████▉     | 198/400 [26:21<17:25,  5.17s/it]

✅ [Row 199] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist caught in a national war, struggling with ...
🚀 [Row 199] GPT: Sending request...

 50%|████▉     | 198/400 [26:22<17:25,  5.17s/it]

✅ [Row 200] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist's journey of self-discovery, identity cris...
🚀 [Row 200] GPT: Sending request...

 50%|████▉     | 198/400 [26:25<17:25,  5.17s/it]

✅ [Row 201] GPT Received: {
  "reasoning": "The Anchor story involves a conflict between good and evil, represented by an ange...
🚀 [Row 201] Claude: Sending request...

 50%|████▉     | 198/400 [26:26<17:25,  5.17s/it]

✅ [Row 199] GPT Received: {
  "reasoning": "The Anchor story revolves around a young man, Henn Ahas, caught in a conflict betw...
🚀 [Row 199] Claude: Sending request...

 50%|████▉     | 198/400 [26:27<17:25,  5.17s/it]

✅ [Row 200] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of identity, cultural heritage, and persona...
🚀 [Row 200] Claude: Sending request...

 50%|████▉     | 198/400 [26:33<17:25,  5.17s/it]

❌ [Row 198] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 50%|████▉     | 198/400 [26:34<17:25,  5.17s/it]

🚀 [Row 198] GPT: Sending request...

 50%|████▉     | 199/400 [26:35<36:52, 11.01s/it]

✅ [Row 201] Claude Received: ```json
{
  "reasoning": "The Anchor is fundamentally about a couple's love being tested by supernat...
🏁 [Row 201] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 202] Gemini: Sending request...

 50%|█████     | 200/400 [26:39<28:52,  8.66s/it]

✅ [Row 199] Claude Received: ```json
{
  "reasoning": "Text B is narratively closer to the Anchor. Both stories share the same co...
🏁 [Row 199] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 203] Gemini: Sending request...

 50%|█████     | 200/400 [26:39<28:52,  8.66s/it]

✅ [Row 198] GPT Received: {
  "reasoning": "The Anchor story revolves around a gambler who is forced to fix a horse race but u...
🚀 [Row 198] Claude: Sending request...

 50%|█████     | 200/400 [26:46<28:52,  8.66s/it]

✅ [Row 203] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature a protagonist w...
🚀 [Row 203] GPT: Sending request...
✅ [Row 202] Gemini Received: {
  "reasoning": "The Anchor text centers around a literary critic acting as a detective to uncover ...
🚀 [Row 202] GPT: Sending request...

 50%|█████     | 201/400 [26:46<27:50,  8.40s/it]

✅ [Row 200] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a young woman (Neige) struggling with identity issue...
🏁 [Row 200] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 204] Gemini: Sending request...

 50%|█████     | 202/400 [26:49<21:49,  6.62s/it]

✅ [Row 198] Claude Received: ```json
{
  "reasoning": "The Anchor follows a gambler forced to fix a horse race who falls in love ...
🏁 [Row 198] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 205] Gemini: Sending request...

 50%|█████     | 202/400 [26:50<21:49,  6.62s/it]

✅ [Row 203] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a transformation into a creature that lea...
🚀 [Row 203] Claude: Sending request...

 50%|█████     | 202/400 [26:55<21:49,  6.62s/it]

✅ [Row 202] GPT Received: {
  "reasoning": "The Anchor text revolves around a literary mystery involving the investigation of ...
🚀 [Row 202] Claude: Sending request...

 50%|█████     | 202/400 [26:57<21:49,  6.62s/it]

✅ [Row 205] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A are fu...
🚀 [Row 205] GPT: Sending request...

 50%|█████     | 202/400 [27:00<21:49,  6.62s/it]

✅ [Row 204] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B revolve aro...
🚀 [Row 204] GPT: Sending request...

 51%|█████     | 203/400 [27:01<27:27,  8.36s/it]

✅ [Row 203] Claude Received: ```json
{
  "reasoning": "The Anchor follows Peter Cotton, a researcher who is physically transforme...
🏁 [Row 203] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 206] Gemini: Sending request...

 51%|█████     | 203/400 [27:02<27:27,  8.36s/it]

✅ [Row 205] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of martial arts, tradition, and corruption...
🚀 [Row 205] Claude: Sending request...

 51%|█████     | 204/400 [27:05<22:29,  6.88s/it]

✅ [Row 202] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a literary critic investigating the true authorship ...
🏁 [Row 202] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 207] Gemini: Sending request...

 51%|█████     | 204/400 [27:09<22:29,  6.88s/it]

✅ [Row 204] GPT Received: {
  "reasoning": "The Anchor story revolves around a television game show host and his assistant, wi...
🚀 [Row 204] Claude: Sending request...

 51%|█████▏    | 205/400 [27:12<22:41,  6.98s/it]

✅ [Row 205] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on three karate pupils who must decide who deserves the...
🏁 [Row 205] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 208] Gemini: Sending request...

 51%|█████▏    | 205/400 [27:16<22:41,  6.98s/it]

✅ [Row 206] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B focus ...
🚀 [Row 206] GPT: Sending request...

 51%|█████▏    | 205/400 [27:17<22:41,  6.98s/it]

✅ [Row 207] Gemini Received: {
  "reasoning": "The Anchor text is a romantic comedy with political satire, centered around an Ame...
🚀 [Row 207] GPT: Sending request...

 51%|█████▏    | 205/400 [27:23<22:41,  6.98s/it]

✅ [Row 206] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a protagonist who is released from prison...
🚀 [Row 206] Claude: Sending request...

 51%|█████▏    | 205/400 [27:24<22:41,  6.98s/it]

✅ [Row 207] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of political intrigue, deception, and a sh...
🚀 [Row 207] Claude: Sending request...

 51%|█████▏    | 205/400 [27:25<22:41,  6.98s/it]

✅ [Row 208] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A prominently...
🚀 [Row 208] GPT: Sending request...

 51%|█████▏    | 205/400 [27:30<22:41,  6.98s/it]

✅ [Row 208] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve a legal case where the accused is initiall...
🚀 [Row 208] Claude: Sending request...

 52%|█████▏    | 206/400 [27:33<35:45, 11.06s/it]

✅ [Row 204] Claude Received: ```json
{
  "reasoning": "The Anchor follows an ambitious young man (Bastien) working in television ...
🏁 [Row 204] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 209] Gemini: Sending request...

 52%|█████▏    | 207/400 [27:33<25:30,  7.93s/it]

✅ [Row 206] Claude Received: ```json
{
  "reasoning": "Both texts involve ex-convicts struggling to reintegrate into society, but...
🏁 [Row 206] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 210] Gemini: Sending request...

 52%|█████▏    | 208/400 [27:39<23:07,  7.23s/it]

✅ [Row 208] Claude Received: ```json
{
  "reasoning": "Both texts involve criminal cases with questions of guilt and innocence, b...
🏁 [Row 208] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 211] Gemini: Sending request...

 52%|█████▏    | 209/400 [27:40<17:03,  5.36s/it]

✅ [Row 207] Claude Received: ```json
{
  "reasoning": "The Anchor involves deception/hidden identity, ideological conflict, black...
🏁 [Row 207] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 212] Gemini: Sending request...

 52%|█████▏    | 209/400 [27:42<17:03,  5.36s/it]

✅ [Row 209] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature protagonists wh...
🚀 [Row 209] GPT: Sending request...

 52%|█████▏    | 209/400 [27:42<17:03,  5.36s/it]

✅ [Row 210] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A have con ar...
🚀 [Row 210] GPT: Sending request...

 52%|█████▏    | 209/400 [27:46<17:03,  5.36s/it]

✅ [Row 211] Gemini Received: {
  "reasoning": "The Anchor story describes a protagonist who becomes disillusioned with his highly...
🚀 [Row 211] GPT: Sending request...
✅ [Row 209] GPT Received: {
  "reasoning": "The Anchor text 'The Immoralist' revolves around Michel's personal journey and tra...
🚀 [Row 209] Claude: Sending request...

 52%|█████▏    | 209/400 [27:47<17:03,  5.36s/it]

✅ [Row 210] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of con artistry, faith healing, and the ma...
🚀 [Row 210] Claude: Sending request...

 52%|█████▏    | 209/400 [27:48<17:03,  5.36s/it]

✅ [Row 212] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A center on the dire issue of human trafficking and ...
🚀 [Row 212] GPT: Sending request...

 52%|█████▏    | 209/400 [27:51<17:03,  5.36s/it]

✅ [Row 211] GPT Received: {
  "reasoning": "The Anchor text is about a character disillusioned with the advertisement industry...
🚀 [Row 211] Claude: Sending request...

 52%|█████▏    | 209/400 [27:52<17:03,  5.36s/it]

✅ [Row 212] GPT Received: {
  "reasoning": "The Anchor text involves a protagonist who is coerced into a dangerous mission to ...
🚀 [Row 212] Claude: Sending request...

 52%|█████▎    | 210/400 [27:55<25:59,  8.21s/it]

✅ [Row 209] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Michel's personal transformation following illness, ...
🏁 [Row 209] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 213] Gemini: Sending request...

 53%|█████▎    | 211/400 [27:59<22:08,  7.03s/it]

✅ [Row 210] Claude Received: ```json
{
  "reasoning": "The Anchor centers on con artists, faith healing, religious manipulation, ...
🏁 [Row 210] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 214] Gemini: Sending request...

 53%|█████▎    | 212/400 [28:00<16:25,  5.24s/it]

✅ [Row 211] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a protagonist who becomes disillusioned with his sup...
🏁 [Row 211] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 215] Gemini: Sending request...

 53%|█████▎    | 212/400 [28:05<16:25,  5.24s/it]

✅ [Row 213] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a y...
🚀 [Row 213] GPT: Sending request...

 53%|█████▎    | 212/400 [28:07<16:25,  5.24s/it]

✅ [Row 215] Gemini Received: {
  "reasoning": "The Anchor text is about a group of ex-resistance fighters reuniting to uncover a ...
🚀 [Row 215] GPT: Sending request...

 53%|█████▎    | 212/400 [28:09<16:25,  5.24s/it]

✅ [Row 213] GPT Received: {
  "reasoning": "The Anchor story revolves around a young person being drawn into a destructive lif...
🚀 [Row 213] Claude: Sending request...

 53%|█████▎    | 212/400 [28:10<16:25,  5.24s/it]

✅ [Row 214] Gemini Received: {
  "reasoning": "The Anchor text describes the intersecting lives of five families, focusing on var...
🚀 [Row 214] GPT: Sending request...

 53%|█████▎    | 212/400 [28:11<16:25,  5.24s/it]

✅ [Row 215] GPT Received: {
  "reasoning": "The Anchor story revolves around a group of ex-resistance fighters reuniting to un...
🚀 [Row 215] Claude: Sending request...

 53%|█████▎    | 212/400 [28:16<16:25,  5.24s/it]

✅ [Row 214] GPT Received: {
  "reasoning": "The Anchor text revolves around the intersecting lives of multiple families in 195...
🚀 [Row 214] Claude: Sending request...

 53%|█████▎    | 213/400 [28:20<30:16,  9.72s/it]

✅ [Row 213] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a vulnerable young person (Beni, 15) who is se...
🏁 [Row 213] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 216] Gemini: Sending request...

 54%|█████▎    | 214/400 [28:23<23:47,  7.67s/it]

✅ [Row 215] Claude Received: ```json
{
  "reasoning": "The Anchor is centered on a group of ex-resistance fighters reuniting to i...
🏁 [Row 215] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 217] Gemini: Sending request...

 54%|█████▍    | 215/400 [28:27<20:29,  6.65s/it]

✅ [Row 216] Gemini Received: {
  "reasoning": "The Anchor text features a mentally ill man who embarks on a murder spree, includi...
🚀 [Row 216] GPT: Sending request...
✅ [Row 214] Claude Received: ```json
{
  "reasoning": "The Anchor presents an ensemble narrative of five Italian families in the ...
🏁 [Row 214] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 218] Gemini: Sending request...

 54%|█████▍    | 215/400 [28:32<20:29,  6.65s/it]

✅ [Row 216] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a series of murders committed by a centra...
🚀 [Row 216] Claude: Sending request...

 54%|█████▍    | 216/400 [28:33<19:06,  6.23s/it]

✅ [Row 212] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an undercover infiltration mission to dismantle a cr...
🏁 [Row 212] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 219] Gemini: Sending request...

 54%|█████▍    | 216/400 [28:34<19:06,  6.23s/it]

✅ [Row 217] Gemini Received: {
  "reasoning": "The Anchor text describes a love story where the protagonist chooses genuine conne...
🚀 [Row 217] GPT: Sending request...

 54%|█████▍    | 216/400 [28:36<19:06,  6.23s/it]

✅ [Row 218] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share a gra...
🚀 [Row 218] GPT: Sending request...

 54%|█████▍    | 216/400 [28:40<19:06,  6.23s/it]

✅ [Row 217] GPT Received: {
  "reasoning": "The Anchor text is a love story set against the backdrop of East and West Berlin, ...
🚀 [Row 217] Claude: Sending request...

 54%|█████▍    | 216/400 [28:41<19:06,  6.23s/it]

✅ [Row 218] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of political intrigue, the restoration of ...
🚀 [Row 218] Claude: Sending request...

 54%|█████▍    | 217/400 [28:41<21:22,  7.01s/it]

✅ [Row 216] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a mentally ill man who becomes a serial killer targe...
🏁 [Row 216] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 220] Gemini: Sending request...

 54%|█████▍    | 217/400 [28:42<21:22,  7.01s/it]

✅ [Row 219] Gemini Received: {
  "reasoning": "The Anchor text features a comedic war scenario where military objectives are achi...
🚀 [Row 219] GPT: Sending request...

 54%|█████▍    | 217/400 [28:48<21:22,  7.01s/it]

✅ [Row 219] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a military setting during World War II, w...
🚀 [Row 219] Claude: Sending request...

 55%|█████▍    | 218/400 [28:49<22:17,  7.35s/it]

✅ [Row 218] Claude Received: ```json
{
  "reasoning": "Text B is narratively closer to the Anchor. Both share a historical East A...
🏁 [Row 218] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 221] Gemini: Sending request...

 55%|█████▍    | 218/400 [28:50<22:17,  7.35s/it]

✅ [Row 220] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor's core theme revolves aroun...
🚀 [Row 220] GPT: Sending request...

 55%|█████▍    | 219/400 [28:51<16:44,  5.55s/it]

✅ [Row 217] Claude Received: ```json
{
  "reasoning": "The Anchor tells a love story centered on a young East German woman (Uschi...
🏁 [Row 217] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 222] Gemini: Sending request...

 55%|█████▌    | 220/400 [28:56<16:31,  5.51s/it]

✅ [Row 219] Claude Received: ```json
{
  "reasoning": "Both texts involve WWII-era military operations with comedic elements, but...
🏁 [Row 219] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 223] Gemini: Sending request...

 55%|█████▌    | 220/400 [28:57<16:31,  5.51s/it]

✅ [Row 220] GPT Received: {
  "reasoning": "The Anchor text and Text B both deal with themes of family, redemption, and reconc...
🚀 [Row 220] Claude: Sending request...

 55%|█████▌    | 220/400 [28:58<16:31,  5.51s/it]

✅ [Row 221] Gemini Received: {
  "reasoning": "The Anchor text features characters who are 'fugitives from justice' and 'on the l...
🚀 [Row 221] GPT: Sending request...

 55%|█████▌    | 220/400 [29:05<16:31,  5.51s/it]

✅ [Row 223] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share a cor...
🚀 [Row 223] GPT: Sending request...

 55%|█████▌    | 220/400 [29:07<16:31,  5.51s/it]

✅ [Row 221] GPT Received: {
  "reasoning": "The Anchor story revolves around fugitives working in a gold mine under a tyrannic...
🚀 [Row 221] Claude: Sending request...

 55%|█████▌    | 220/400 [29:10<16:31,  5.51s/it]

✅ [Row 223] GPT Received: {
  "reasoning": "The Anchor story involves a photographer and his daughter encountering various dan...
🚀 [Row 223] Claude: Sending request...

 55%|█████▌    | 221/400 [29:15<27:51,  9.34s/it]

✅ [Row 221] Claude Received: ```json
{
  "reasoning": "Both texts involve fugitives from the law, but Text B is narratively close...
🏁 [Row 221] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 224] Gemini: Sending request...

 56%|█████▌    | 222/400 [29:20<24:13,  8.17s/it]

✅ [Row 223] Claude Received: ```json
{
  "reasoning": "Both texts involve dangerous wildlife in exotic settings, but Text B is na...
🏁 [Row 223] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 225] Gemini: Sending request...

 56%|█████▌    | 222/400 [29:21<24:13,  8.17s/it]

❌ [Row 222] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 56%|█████▌    | 222/400 [29:22<24:13,  8.17s/it]

✅ [Row 224] Gemini Received: {
  "reasoning": "The Anchor text describes a narrative of marginalized individuals struggling again...
🚀 [Row 224] GPT: Sending request...

 56%|█████▌    | 222/400 [29:26<24:13,  8.17s/it]

✅ [Row 225] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a c...
🚀 [Row 225] GPT: Sending request...

 56%|█████▌    | 222/400 [29:27<24:13,  8.17s/it]

✅ [Row 224] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve individuals facing systemic challenges an...
🚀 [Row 224] Claude: Sending request...

 56%|█████▌    | 222/400 [29:32<24:13,  8.17s/it]

✅ [Row 225] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of inspiration, sacrifice, and historical ...
🚀 [Row 225] Claude: Sending request...

 56%|█████▌    | 222/400 [29:32<24:13,  8.17s/it]

✅ [Row 222] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature a protagonist w...
🚀 [Row 222] GPT: Sending request...

 56%|█████▌    | 223/400 [29:37<31:58, 10.84s/it]

✅ [Row 224] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a group of marginalized men who commit crimes out of...
🏁 [Row 224] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 226] Gemini: Sending request...

 56%|█████▌    | 224/400 [29:37<22:27,  7.66s/it]

✅ [Row 220] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on the son of a notorious criminal (Pablo Escobar) who ...
🏁 [Row 220] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 227] Gemini: Sending request...
✅ [Row 222] GPT Received: {
  "reasoning": "The Anchor story revolves around Arizona Colt, a gunman who is initially in isolat...
🚀 [Row 222] Claude: Sending request...

 56%|█████▋    | 225/400 [29:41<18:38,  6.39s/it]

✅ [Row 225] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a WWI officer inspired by Joan of Arc's story (trans...
🏁 [Row 225] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 228] Gemini: Sending request...

 56%|█████▋    | 225/400 [29:46<18:38,  6.39s/it]

✅ [Row 226] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 226] GPT: Sending request...

 56%|█████▋    | 226/400 [29:47<18:47,  6.48s/it]

✅ [Row 222] Claude Received: ```json
{
  "reasoning": "The Anchor follows a famed gunman who fakes his death, is drawn back into ...
🏁 [Row 222] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 229] Gemini: Sending request...

 56%|█████▋    | 226/400 [29:48<18:47,  6.48s/it]

✅ [Row 228] Gemini Received: {
  "reasoning": "The Anchor text centers on fighter pilots who vow not to fall in love during warti...
🚀 [Row 228] GPT: Sending request...

 56%|█████▋    | 226/400 [29:50<18:47,  6.48s/it]

✅ [Row 226] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of deception, betrayal, and a mission that...
🚀 [Row 226] Claude: Sending request...

 56%|█████▋    | 226/400 [29:53<18:47,  6.48s/it]

✅ [Row 228] GPT Received: {
  "reasoning": "The Anchor story revolves around fighter pilots during wartime who vow not to fall...
🚀 [Row 228] Claude: Sending request...

 56%|█████▋    | 226/400 [29:54<18:47,  6.48s/it]

✅ [Row 229] Gemini Received: {
  "reasoning": "The Anchor text is about a man going to great lengths to impress his childhood lov...
🚀 [Row 229] GPT: Sending request...

 56%|█████▋    | 226/400 [29:59<18:47,  6.48s/it]

✅ [Row 229] GPT Received: {
  "reasoning": "The Anchor story is about a man trying to impress his childhood lover, facing obst...
🚀 [Row 229] Claude: Sending request...

 57%|█████▋    | 227/400 [29:59<23:10,  8.04s/it]

✅ [Row 226] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a rescue mission with a dramatic reversal: Star...
🏁 [Row 226] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 230] Gemini: Sending request...

 57%|█████▋    | 228/400 [30:02<18:30,  6.46s/it]

✅ [Row 228] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on three fighter pilots who vow not to fall in love dur...
🏁 [Row 228] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 231] Gemini: Sending request...

 57%|█████▋    | 228/400 [30:07<18:30,  6.46s/it]

❌ [Row 227] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 57%|█████▋    | 228/400 [30:10<18:30,  6.46s/it]

✅ [Row 231] Gemini Received: {
  "reasoning": "Text B shares a core narrative theme with the Anchor: an intrusive stranger develo...
🚀 [Row 231] GPT: Sending request...

 57%|█████▋    | 229/400 [30:10<19:50,  6.96s/it]

✅ [Row 229] Claude Received: ```json
{
  "reasoning": "The Anchor story focuses on a man (Recep) who reunites with his childhood ...
🏁 [Row 229] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 232] Gemini: Sending request...

 57%|█████▋    | 229/400 [30:11<19:50,  6.96s/it]

✅ [Row 230] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a d...
🚀 [Row 230] GPT: Sending request...

 57%|█████▋    | 229/400 [30:16<19:50,  6.96s/it]

✅ [Row 230] GPT Received: {
  "reasoning": "The Anchor story involves teenagers discovering a dragon and a powerful pearl, wit...
🚀 [Row 230] Claude: Sending request...

 57%|█████▋    | 229/400 [30:17<19:50,  6.96s/it]

✅ [Row 231] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of unwanted intrusion, obsession, and comp...
🚀 [Row 231] Claude: Sending request...

 57%|█████▋    | 229/400 [30:24<19:50,  6.96s/it]

✅ [Row 232] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 232] GPT: Sending request...

 57%|█████▊    | 230/400 [30:24<25:58,  9.17s/it]

✅ [Row 230] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories share a core cons...
🏁 [Row 230] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 233] Gemini: Sending request...

 58%|█████▊    | 231/400 [30:26<19:50,  7.04s/it]

✅ [Row 231] Claude Received: ```json
{
  "reasoning": "The Anchor centers on obsessive, unhealthy relationships: a stranger stalk...
🏁 [Row 231] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 234] Gemini: Sending request...

 58%|█████▊    | 231/400 [30:28<19:50,  7.04s/it]

✅ [Row 232] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve a protagonist arriving in a new, insular c...
🚀 [Row 232] Claude: Sending request...

 58%|█████▊    | 231/400 [30:31<19:50,  7.04s/it]

✅ [Row 227] Gemini Received: {
  "reasoning": "The Anchor text features a central couple whose engagement is broken due to a riva...
🚀 [Row 227] GPT: Sending request...

 58%|█████▊    | 231/400 [30:34<19:50,  7.04s/it]

✅ [Row 227] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle, misunderstandings, and eventual ...
🚀 [Row 227] Claude: Sending request...

 58%|█████▊    | 231/400 [30:35<19:50,  7.04s/it]

✅ [Row 234] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 234] GPT: Sending request...

 58%|█████▊    | 231/400 [30:39<19:50,  7.04s/it]

✅ [Row 234] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of love, oppression, and revenge set agains...
🚀 [Row 234] Claude: Sending request...

 58%|█████▊    | 232/400 [30:43<27:26,  9.80s/it]

✅ [Row 232] Claude Received: ```json
{
  "reasoning": "The Anchor follows a married couple inheriting cursed family property on a...
🏁 [Row 232] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 235] Gemini: Sending request...

 58%|█████▊    | 232/400 [30:44<27:26,  9.80s/it]

✅ [Row 233] Gemini Received: {
  "reasoning": "The Anchor text's core narrative revolves around a deliberate deception that, thro...
🚀 [Row 233] GPT: Sending request...

 58%|█████▊    | 233/400 [30:45<20:46,  7.46s/it]

✅ [Row 227] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a love triangle where Rose is engaged to Steve...
🏁 [Row 227] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 236] Gemini: Sending request...

 58%|█████▊    | 233/400 [30:48<20:46,  7.46s/it]

✅ [Row 233] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a group or individual trying to deceive o...
🚀 [Row 233] Claude: Sending request...

 58%|█████▊    | 233/400 [30:52<20:46,  7.46s/it]

✅ [Row 236] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature the...
🚀 [Row 236] GPT: Sending request...

 58%|█████▊    | 234/400 [30:55<22:54,  8.28s/it]

✅ [Row 234] Claude Received: ```json
{
  "reasoning": "The Anchor tells a story of personal tragedy (imprisonment, family destroy...
🏁 [Row 234] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 237] Gemini: Sending request...

 59%|█████▉    | 235/400 [30:57<17:56,  6.52s/it]

✅ [Row 233] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a bureaucratic misunderstanding where the crew...
🏁 [Row 233] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 238] Gemini: Sending request...
✅ [Row 236] GPT Received: {
  "reasoning": "The Anchor story revolves around a poor girl, Roopa, who is forced to work by her ...
🚀 [Row 236] Claude: Sending request...

 59%|█████▉    | 235/400 [31:03<17:56,  6.52s/it]

✅ [Row 235] Gemini Received: {
  "reasoning": "The Anchor story features a protagonist who, driven by love and a desire to prove ...
🚀 [Row 235] GPT: Sending request...

 59%|█████▉    | 235/400 [31:06<17:56,  6.52s/it]

✅ [Row 237] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A feature a protagonist (...
🚀 [Row 237] GPT: Sending request...

 59%|█████▉    | 236/400 [31:10<22:37,  8.28s/it]

✅ [Row 236] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic storylines with complications, but Text B is n...
🏁 [Row 236] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 239] Gemini: Sending request...

 59%|█████▉    | 236/400 [31:12<22:37,  8.28s/it]

✅ [Row 237] GPT Received: {
  "reasoning": "The Anchor story revolves around an undercover cop, John, who becomes involved in ...
🚀 [Row 237] Claude: Sending request...
✅ [Row 235] GPT Received: {
  "reasoning": "The Anchor story revolves around Samy, a young man from Senegal who embarks on a c...
🚀 [Row 235] Claude: Sending request...

 59%|█████▉    | 236/400 [31:14<22:37,  8.28s/it]

✅ [Row 238] Gemini Received: {
  "reasoning": "The Anchor story describes Karchy, a naive young emigrant, whose world is complica...
🚀 [Row 238] GPT: Sending request...

 59%|█████▉    | 236/400 [31:19<22:37,  8.28s/it]

✅ [Row 238] GPT Received: {
  "reasoning": "The Anchor story revolves around Karchy, a young immigrant trying to navigate his ...
🚀 [Row 238] Claude: Sending request...

 59%|█████▉    | 237/400 [31:22<26:02,  9.59s/it]

✅ [Row 237] Claude Received: ```json
{
  "reasoning": "The Anchor follows an undercover cop who, after losing his family in a fai...
🏁 [Row 237] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 240] Gemini: Sending request...

 59%|█████▉    | 237/400 [31:29<26:02,  9.59s/it]

✅ [Row 239] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A share the fundamental abstract theme of a child be...
🚀 [Row 239] GPT: Sending request...

 60%|█████▉    | 238/400 [31:29<23:29,  8.70s/it]

✅ [Row 238] Claude Received: ```json
{
  "reasoning": "The Anchor tells a coming-of-age story about a young immigrant (Karchy) wh...
🏁 [Row 238] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 241] Gemini: Sending request...

 60%|█████▉    | 239/400 [31:33<19:30,  7.27s/it]

✅ [Row 235] Claude Received: ```json
{
  "reasoning": "The Anchor follows Samy, an unemployed young man from the suburbs who emba...
🏁 [Row 235] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 242] Gemini: Sending request...

 60%|█████▉    | 239/400 [31:34<19:30,  7.27s/it]

✅ [Row 239] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of abandonment and the temporary care o...
🚀 [Row 239] Claude: Sending request...

 60%|█████▉    | 239/400 [31:34<19:30,  7.27s/it]

✅ [Row 240] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature mal...
🚀 [Row 240] GPT: Sending request...

 60%|█████▉    | 239/400 [31:39<19:30,  7.27s/it]

✅ [Row 240] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, loss, and recovery, with a focus ...
🚀 [Row 240] Claude: Sending request...

 60%|█████▉    | 239/400 [31:43<19:30,  7.27s/it]

✅ [Row 241] Gemini Received: {
  "reasoning": "The Anchor text centers on a woman whose present life and relationships are profou...
🚀 [Row 241] GPT: Sending request...
✅ [Row 242] Gemini Received: {
  "reasoning": "The Anchor story describes an engineer getting caught up in a political conflict a...
🚀 [Row 242] GPT: Sending request...

 60%|██████    | 240/400 [31:46<23:51,  8.95s/it]

✅ [Row 239] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a young abandoned child (Asia) temporarily taken in ...
🏁 [Row 239] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 243] Gemini: Sending request...

 60%|██████    | 240/400 [31:48<23:51,  8.95s/it]

✅ [Row 242] GPT Received: {
  "reasoning": "The Anchor story involves themes of political unrest, love, and adventure, with a ...
🚀 [Row 242] Claude: Sending request...

 60%|██████    | 240/400 [31:49<23:51,  8.95s/it]

✅ [Row 241] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of past relationships, reincarnation, and ...
🚀 [Row 241] Claude: Sending request...

 60%|██████    | 241/400 [31:53<22:36,  8.53s/it]

✅ [Row 240] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a summer romance between two young men (Mathieu and ...
🏁 [Row 240] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 244] Gemini: Sending request...

 60%|██████    | 241/400 [31:56<22:36,  8.53s/it]

✅ [Row 243] Gemini Received: {
  "reasoning": "The Anchor text features two parallel love stories, one overcoming obstacles to a ...
🚀 [Row 243] GPT: Sending request...

 60%|██████    | 242/400 [31:56<18:12,  6.92s/it]

✅ [Row 242] Claude Received: ```json
{
  "reasoning": "The Anchor follows an engineer caught up in a political uprising and love ...
🏁 [Row 242] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 245] Gemini: Sending request...

 60%|██████    | 242/400 [32:01<18:12,  6.92s/it]

✅ [Row 243] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve themes of love and redemption, with charac...
🚀 [Row 243] Claude: Sending request...

 61%|██████    | 243/400 [32:02<17:00,  6.50s/it]

✅ [Row 241] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Louise, a divorcée who begins an affair with a young...
🏁 [Row 241] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 246] Gemini: Sending request...

 61%|██████    | 243/400 [32:03<17:00,  6.50s/it]

✅ [Row 244] Gemini Received: {
  "reasoning": "Text A describes an archaeological adventure focused on discovery, which has very ...
🚀 [Row 244] GPT: Sending request...

 61%|██████    | 243/400 [32:05<17:00,  6.50s/it]

✅ [Row 245] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center on a...
🚀 [Row 245] GPT: Sending request...

 61%|██████    | 243/400 [32:08<17:00,  6.50s/it]

✅ [Row 244] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of deforestation, corporate exploitation, a...
🚀 [Row 244] Claude: Sending request...

 61%|██████    | 244/400 [32:10<18:02,  6.94s/it]

✅ [Row 243] Claude Received: ```json
{
  "reasoning": "The Anchor presents two parallel romantic storylines with contrasting outc...
🏁 [Row 243] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 247] Gemini: Sending request...
✅ [Row 245] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, sacrifice, and the impact of past...
🚀 [Row 245] Claude: Sending request...
✅ [Row 246] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 246] GPT: Sending request...

 61%|██████    | 244/400 [32:14<18:02,  6.94s/it]

✅ [Row 246] GPT Received: {
  "reasoning": "The Anchor story involves a comedic plot where a plumber is involved in high socie...
🚀 [Row 246] Claude: Sending request...

 61%|██████▏   | 245/400 [32:16<17:17,  6.69s/it]

✅ [Row 244] Claude Received: ```json
{
  "reasoning": "Both texts involve crime, investigation, and settings in remote regions. H...
🏁 [Row 244] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 248] Gemini: Sending request...

 61%|██████▏   | 245/400 [32:17<17:17,  6.69s/it]

⏳ [Row 248] Gemini: Rate limit (Attempt 1)

 62%|██████▏   | 246/400 [32:20<15:20,  5.98s/it]

✅ [Row 245] Claude Received: ```json
{
  "reasoning": "The Anchor's core narrative involves a romantic relationship between two p...
🏁 [Row 245] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 249] Gemini: Sending request...

 62%|██████▏   | 247/400 [32:23<13:02,  5.12s/it]

✅ [Row 246] Claude Received: ```json
{
  "reasoning": "Both texts share some comedic military/combat elements with the Anchor, bu...
🏁 [Row 246] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 250] Gemini: Sending request...

 62%|██████▏   | 247/400 [32:25<13:02,  5.12s/it]

⏳ [Row 250] Gemini: Rate limit (Attempt 1)

 62%|██████▏   | 247/400 [32:29<13:02,  5.12s/it]

✅ [Row 248] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both texts feature a large-scale inter...
🚀 [Row 248] GPT: Sending request...

 62%|██████▏   | 247/400 [32:30<13:02,  5.12s/it]

✅ [Row 247] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B focus on pr...
🚀 [Row 247] GPT: Sending request...

 62%|██████▏   | 247/400 [32:32<13:02,  5.12s/it]

✅ [Row 249] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist with amnesia who is investigating a mysteri...
🚀 [Row 249] GPT: Sending request...

 62%|██████▏   | 247/400 [32:34<13:02,  5.12s/it]

✅ [Row 247] GPT Received: {
  "reasoning": "The Anchor story and Text B both revolve around characters who engage in criminal ...
🚀 [Row 247] Claude: Sending request...

 62%|██████▏   | 247/400 [32:35<13:02,  5.12s/it]

✅ [Row 250] Gemini Received: {
  "reasoning": "The Anchor text focuses on the profound impact of a historical civil war on a fami...
🚀 [Row 250] GPT: Sending request...

 62%|██████▏   | 247/400 [32:35<13:02,  5.12s/it]

✅ [Row 248] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve international plots with foreign agents a...
🚀 [Row 248] Claude: Sending request...

 62%|██████▏   | 247/400 [32:36<13:02,  5.12s/it]

✅ [Row 249] GPT Received: {
  "reasoning": "The Anchor story involves a protagonist waking up with amnesia, a dead body, and a...
🚀 [Row 249] Claude: Sending request...

 62%|██████▏   | 247/400 [32:39<13:02,  5.12s/it]

✅ [Row 250] GPT Received: {
  "reasoning": "The Anchor story revolves around a personal quest to solve a mystery from the past...
🚀 [Row 250] Claude: Sending request...

 62%|██████▏   | 248/400 [32:45<25:33, 10.09s/it]

✅ [Row 249] Claude Received: ```json
{
  "reasoning": "Both texts involve protagonists investigating mysteries, but Text A is nar...
🏁 [Row 249] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 251] Gemini: Sending request...

 62%|██████▏   | 249/400 [32:46<18:48,  7.47s/it]

✅ [Row 247] Claude Received: ```json
{
  "reasoning": "Both texts involve protagonists who turn to crime, but Text B is narrative...
🏁 [Row 247] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 252] Gemini: Sending request...

 62%|██████▎   | 250/400 [32:48<14:04,  5.63s/it]

✅ [Row 248] Claude Received: ```json
{
  "reasoning": "Both texts involve foreign/international conspiracies with elaborate techn...
🏁 [Row 248] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 253] Gemini: Sending request...

 63%|██████▎   | 251/400 [32:50<11:25,  4.60s/it]

✅ [Row 250] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a man returning to his homeland to investigate ...
🏁 [Row 250] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 254] Gemini: Sending request...

 63%|██████▎   | 251/400 [32:50<11:25,  4.60s/it]

❌ [Row 254] Gemini Exception: 'candidates'

 63%|██████▎   | 251/400 [32:52<11:25,  4.60s/it]

❌ [Row 254] Gemini Exception: 'candidates'

 63%|██████▎   | 251/400 [32:53<11:25,  4.60s/it]

✅ [Row 251] Gemini Received: {
  "reasoning": "Both the Anchor and Text A deal with a character arriving at profound philosophica...
🚀 [Row 251] GPT: Sending request...

 63%|██████▎   | 251/400 [32:54<11:25,  4.60s/it]

❌ [Row 254] Gemini Exception: 'candidates'

 63%|██████▎   | 251/400 [32:55<11:25,  4.60s/it]

🚀 [Row 254] GPT: Sending request...
✅ [Row 253] Gemini Received: {
  "reasoning": "Both the Anchor text and Text B describe an individual's journey from a state of d...
🚀 [Row 253] GPT: Sending request...

 63%|██████▎   | 251/400 [32:55<11:25,  4.60s/it]

✅ [Row 252] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature an ...
🚀 [Row 252] GPT: Sending request...

 63%|██████▎   | 251/400 [32:56<11:25,  4.60s/it]

✅ [Row 251] GPT Received: {
  "reasoning": "The Anchor text revolves around a prophet discussing various aspects of life and h...
🚀 [Row 251] Claude: Sending request...

 63%|██████▎   | 251/400 [32:59<11:25,  4.60s/it]

✅ [Row 253] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a journey of personal discovery and reali...
🚀 [Row 253] Claude: Sending request...

 63%|██████▎   | 251/400 [33:00<11:25,  4.60s/it]

✅ [Row 254] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of captivity, artistic obsession, and a da...
🚀 [Row 254] Claude: Sending request...

 63%|██████▎   | 251/400 [33:02<11:25,  4.60s/it]

✅ [Row 252] GPT Received: {
  "reasoning": "The Anchor story revolves around a group of friends trying to celebrate a traditio...
🚀 [Row 252] Claude: Sending request...

 63%|██████▎   | 252/400 [33:09<21:48,  8.84s/it]

✅ [Row 253] Claude Received: ```json
{
  "reasoning": "The Anchor is about Siddhartha's spiritual journey from wealth through asc...
🏁 [Row 253] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 255] Gemini: Sending request...

 63%|██████▎   | 253/400 [33:09<15:25,  6.30s/it]

✅ [Row 252] Claude Received: ```json
{
  "reasoning": "Both texts involve isolated settings and interpersonal complications, but ...
🏁 [Row 252] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 256] Gemini: Sending request...

 64%|██████▎   | 254/400 [33:10<11:04,  4.55s/it]

✅ [Row 254] Claude Received: ```json
{
  "reasoning": "The Anchor depicts an artist-captor relationship that evolves into a conse...
🏁 [Row 254] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 257] Gemini: Sending request...

 64%|██████▎   | 254/400 [33:18<11:04,  4.55s/it]

✅ [Row 255] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 255] GPT: Sending request...

 64%|██████▎   | 254/400 [33:18<11:04,  4.55s/it]

✅ [Row 256] Gemini Received: {
  "reasoning": "The Anchor text describes an investigation into a murder that uncovers a vast, sys...
🚀 [Row 256] GPT: Sending request...

 64%|██████▎   | 254/400 [33:20<11:04,  4.55s/it]

✅ [Row 255] GPT Received: {
  "reasoning": "The Anchor story revolves around a brothel, a love story, and a resolution involvi...
🚀 [Row 255] Claude: Sending request...

 64%|██████▎   | 254/400 [33:21<11:04,  4.55s/it]

✅ [Row 257] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor's core theme is a deceased ...
🚀 [Row 257] GPT: Sending request...

 64%|██████▎   | 254/400 [33:22<11:04,  4.55s/it]

✅ [Row 256] GPT Received: {
  "reasoning": "The Anchor text involves a murder investigation that uncovers a larger conspiracy ...
🚀 [Row 256] Claude: Sending request...

 64%|██████▎   | 254/400 [33:27<11:04,  4.55s/it]

✅ [Row 257] GPT Received: {
  "reasoning": "The Anchor story revolves around a ghost who needs his body to be buried in his ho...
🚀 [Row 257] Claude: Sending request...

 64%|██████▍   | 255/400 [33:29<21:28,  8.88s/it]

✅ [Row 255] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a brothel setting where a student arrives to conduct...
🏁 [Row 255] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 258] Gemini: Sending request...

 64%|██████▍   | 256/400 [33:32<17:30,  7.30s/it]

✅ [Row 256] Claude Received: ```json
{
  "reasoning": "The Anchor follows Brunetti investigating a murder that initially appears ...
🏁 [Row 256] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 259] Gemini: Sending request...

 64%|██████▍   | 257/400 [33:37<15:46,  6.62s/it]

✅ [Row 257] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a deceased immigrant whose ghost must communic...
🏁 [Row 257] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 260] Gemini: Sending request...

 64%|██████▍   | 257/400 [33:43<15:46,  6.62s/it]

✅ [Row 259] Gemini Received: {
  "reasoning": "Both Text A and Text B involve a protagonist returning or a long-absent figure ret...
🚀 [Row 259] GPT: Sending request...

 64%|██████▍   | 257/400 [33:47<15:46,  6.62s/it]

✅ [Row 259] GPT Received: {
  "reasoning": "The Anchor story involves themes of returning home, uncovering family secrets, and...
🚀 [Row 259] Claude: Sending request...

 64%|██████▍   | 258/400 [33:52<21:14,  8.98s/it]

✅ [Row 251] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a prophet delivering philosophical discourse on fund...
🏁 [Row 251] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 261] Gemini: Sending request...

 64%|██████▍   | 258/400 [33:54<21:14,  8.98s/it]

⏳ [Row 258] Gemini: Rate limit (Attempt 1)

 65%|██████▍   | 259/400 [33:56<17:56,  7.64s/it]

✅ [Row 259] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve parental secrets and children, but Text B i...
🏁 [Row 259] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 262] Gemini: Sending request...

 65%|██████▍   | 259/400 [33:59<17:56,  7.64s/it]

✅ [Row 260] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 260] GPT: Sending request...

 65%|██████▍   | 259/400 [34:02<17:56,  7.64s/it]

✅ [Row 261] Gemini Received: {
  "reasoning": "The Anchor text is a fable about preferring security to opulence, illustrating a m...
🚀 [Row 261] GPT: Sending request...

 65%|██████▍   | 259/400 [34:02<17:56,  7.64s/it]

⏳ [Row 258] Gemini: Rate limit (Attempt 2)

 65%|██████▍   | 259/400 [34:03<17:56,  7.64s/it]

✅ [Row 260] GPT Received: {
  "reasoning": "The Anchor story involves a music student investigating a composer's unfinished wo...
🚀 [Row 260] Claude: Sending request...

 65%|██████▍   | 259/400 [34:04<17:56,  7.64s/it]

✅ [Row 262] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor describes a young boy, Frit...
🚀 [Row 262] GPT: Sending request...

 65%|██████▍   | 259/400 [34:06<17:56,  7.64s/it]

✅ [Row 261] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a character making a choice between two l...
🚀 [Row 261] Claude: Sending request...

 65%|██████▍   | 259/400 [34:10<17:56,  7.64s/it]

✅ [Row 262] GPT Received: {
  "reasoning": "The Anchor story is set in a rural Danish school in 1969, focusing on a young boy,...
🚀 [Row 262] Claude: Sending request...

 65%|██████▌   | 260/400 [34:13<24:28, 10.49s/it]

✅ [Row 260] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic triangles with elements of obsession and trage...
🏁 [Row 260] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 263] Gemini: Sending request...

 65%|██████▌   | 261/400 [34:15<18:26,  7.96s/it]

✅ [Row 261] Claude Received: ```json
{
  "reasoning": "The Anchor story is fundamentally about a choice between two lifestyles: t...
🏁 [Row 261] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 264] Gemini: Sending request...

 65%|██████▌   | 261/400 [34:21<18:26,  7.96s/it]

⏳ [Row 258] Gemini: Rate limit (Attempt 3)

 65%|██████▌   | 261/400 [34:25<18:26,  7.96s/it]

✅ [Row 264] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature pro...
🚀 [Row 264] GPT: Sending request...

 65%|██████▌   | 261/400 [34:27<18:26,  7.96s/it]

🚀 [Row 258] GPT: Sending request...

 65%|██████▌   | 261/400 [34:29<18:26,  7.96s/it]

✅ [Row 264] GPT Received: {
  "reasoning": "The Anchor story revolves around elderly characters dealing with personal and soci...
🚀 [Row 264] Claude: Sending request...

 65%|██████▌   | 261/400 [34:30<18:26,  7.96s/it]

✅ [Row 263] Gemini Received: {
  "reasoning": "The Anchor text features a couple whose relationship is profoundly shaped by large...
🚀 [Row 263] GPT: Sending request...

 66%|██████▌   | 262/400 [34:30<23:01, 10.01s/it]

✅ [Row 262] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a young boy (Frits) inspired by civil rights movemen...
🏁 [Row 262] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 265] Gemini: Sending request...

 66%|██████▌   | 262/400 [34:31<23:01, 10.01s/it]

✅ [Row 258] GPT Received: {
  "reasoning": "The Anchor story involves a couple in Las Vegas for a divorce who become embroiled...
🚀 [Row 258] Claude: Sending request...

 66%|██████▌   | 262/400 [34:33<23:01, 10.01s/it]

✅ [Row 263] GPT Received: {
  "reasoning": "The Anchor story revolves around two actors, Agnes and Jochen, whose relationship ...
🚀 [Row 263] Claude: Sending request...

 66%|██████▌   | 263/400 [34:37<20:53,  9.15s/it]

✅ [Row 264] Claude Received: ```json
{
  "reasoning": "The Anchor centers on elderly characters dealing with conflicts related to...
🏁 [Row 264] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 266] Gemini: Sending request...

 66%|██████▌   | 263/400 [34:40<20:53,  9.15s/it]

✅ [Row 265] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 265] GPT: Sending request...

 66%|██████▌   | 264/400 [34:44<19:19,  8.53s/it]

✅ [Row 263] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two actors (Agnes and Jochen) whose marriage fractur...
🏁 [Row 263] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 267] Gemini: Sending request...

 66%|██████▌   | 264/400 [34:45<19:19,  8.53s/it]

✅ [Row 265] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a young woman starting a new life in a bi...
🚀 [Row 265] Claude: Sending request...

 66%|██████▋   | 265/400 [34:46<14:46,  6.57s/it]

✅ [Row 266] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A utilize a n...
🚀 [Row 266] GPT: Sending request...
✅ [Row 258] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a couple in Las Vegas for divorce who become ca...
🏁 [Row 258] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 268] Gemini: Sending request...

 66%|██████▋   | 265/400 [34:51<14:46,  6.57s/it]

✅ [Row 266] GPT Received: {
  "reasoning": "The Anchor text revolves around the themes of political ambition, idealism, and th...
🚀 [Row 266] Claude: Sending request...

 66%|██████▋   | 265/400 [34:54<14:46,  6.57s/it]

✅ [Row 267] Gemini Received: {
  "reasoning": "Text A shares several key narrative similarities with the Anchor. Both feature an ...
🚀 [Row 267] GPT: Sending request...

 66%|██████▋   | 266/400 [34:55<16:02,  7.19s/it]

✅ [Row 265] Claude Received: ```json
{
  "reasoning": "Both texts involve young women arriving in new urban environments and find...
🏁 [Row 265] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 269] Gemini: Sending request...

 66%|██████▋   | 266/400 [34:55<16:02,  7.19s/it]

✅ [Row 268] Gemini Received: {
  "reasoning": "The Anchor text describes a film that traces the history of a building, showing ho...
🚀 [Row 268] GPT: Sending request...

 66%|██████▋   | 266/400 [34:59<16:02,  7.19s/it]

✅ [Row 267] GPT Received: {
  "reasoning": "The Anchor story revolves around a timid milkman who inadvertently becomes a boxin...
🚀 [Row 267] Claude: Sending request...

 66%|██████▋   | 266/400 [35:00<16:02,  7.19s/it]

✅ [Row 268] GPT Received: {
  "reasoning": "The Anchor text focuses on the history and transformation of a building in Egypt, ...
🚀 [Row 268] Claude: Sending request...

 66%|██████▋   | 266/400 [35:05<16:02,  7.19s/it]

✅ [Row 269] Gemini Received: {
  "reasoning": "The Anchor text features a princess, a kingdom, usurpation of power by an evil sor...
🚀 [Row 269] GPT: Sending request...

 67%|██████▋   | 267/400 [35:07<19:05,  8.61s/it]

✅ [Row 266] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a politically ambitious man (Fielding) haunted by hi...
🏁 [Row 266] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 270] Gemini: Sending request...

 67%|██████▋   | 268/400 [35:10<15:20,  6.97s/it]

✅ [Row 267] Claude Received: ```json
{
  "reasoning": "The Anchor is fundamentally about a timid person (milkman) who accidentall...
🏁 [Row 267] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 271] Gemini: Sending request...

 67%|██████▋   | 268/400 [35:11<15:20,  6.97s/it]

✅ [Row 269] GPT Received: {
  "reasoning": "The Anchor story involves a princess who is possessed and replaced by an evil clon...
🚀 [Row 269] Claude: Sending request...

 67%|██████▋   | 269/400 [35:13<12:13,  5.60s/it]

✅ [Row 268] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a multi-generational, multi-character narrative centere...
🏁 [Row 268] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 272] Gemini: Sending request...

 67%|██████▋   | 269/400 [35:17<12:13,  5.60s/it]

✅ [Row 270] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a c...
🚀 [Row 270] GPT: Sending request...

 67%|██████▋   | 269/400 [35:18<12:13,  5.60s/it]

✅ [Row 271] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center arou...
🚀 [Row 271] GPT: Sending request...

 68%|██████▊   | 270/400 [35:19<12:26,  5.74s/it]

✅ [Row 269] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a princess whose kingdom is usurped by an evil sorce...
🏁 [Row 269] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 273] Gemini: Sending request...

 68%|██████▊   | 270/400 [35:21<12:26,  5.74s/it]

✅ [Row 270] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of identity, belonging, and the challenges...
🚀 [Row 270] Claude: Sending request...

 68%|██████▊   | 270/400 [35:22<12:26,  5.74s/it]

✅ [Row 271] GPT Received: {
  "reasoning": "The Anchor text 'A Mighty Heart' focuses on the kidnapping of a journalist and the...
🚀 [Row 271] Claude: Sending request...

 68%|██████▊   | 270/400 [35:26<12:26,  5.74s/it]

✅ [Row 272] Gemini Received: {
  "reasoning": "The Anchor text centers on two childhood friends who are pitted against each other...
🚀 [Row 272] GPT: Sending request...

 68%|██████▊   | 270/400 [35:30<12:26,  5.74s/it]

✅ [Row 272] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve former allies who become adversaries due ...
🚀 [Row 272] Claude: Sending request...

 68%|██████▊   | 271/400 [35:31<16:30,  7.67s/it]

✅ [Row 271] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on the real-life kidnapping of journalist Daniel ...
🏁 [Row 271] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 274] Gemini: Sending request...

 68%|██████▊   | 271/400 [35:37<16:30,  7.67s/it]

✅ [Row 273] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist who radically abandons her former life and ...
🚀 [Row 273] GPT: Sending request...

 68%|██████▊   | 272/400 [35:39<16:46,  7.86s/it]

✅ [Row 272] Claude Received: ```json
{
  "reasoning": "The Anchor is about childhood friends Billy and Chuck who become enemies (...
🏁 [Row 272] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 275] Gemini: Sending request...

 68%|██████▊   | 272/400 [35:40<16:46,  7.86s/it]

✅ [Row 273] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a character who experiences a significant...
🚀 [Row 273] Claude: Sending request...

 68%|██████▊   | 272/400 [35:40<16:46,  7.86s/it]

⏳ [Row 275] Gemini: Rate limit (Attempt 1)

 68%|██████▊   | 272/400 [35:49<16:46,  7.86s/it]

✅ [Row 274] Gemini Received: {
  "reasoning": "Both candidate texts deviate significantly from the Anchor in terms of course of a...
🚀 [Row 274] GPT: Sending request...

 68%|██████▊   | 273/400 [35:52<19:45,  9.34s/it]

✅ [Row 273] Claude Received: ```json
{
  "reasoning": "The Anchor follows a young woman who deliberately chooses an unconventiona...
🏁 [Row 273] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 276] Gemini: Sending request...
✅ [Row 275] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a y...
🚀 [Row 275] GPT: Sending request...

 68%|██████▊   | 273/400 [35:53<19:45,  9.34s/it]

⏳ [Row 276] Gemini: Rate limit (Attempt 1)

 68%|██████▊   | 273/400 [35:54<19:45,  9.34s/it]

✅ [Row 274] GPT Received: {
  "reasoning": "The Anchor story involves a teacher and an assistant teaching locals, with a confl...
🚀 [Row 274] Claude: Sending request...

 68%|██████▊   | 274/400 [35:57<16:55,  8.06s/it]

✅ [Row 270] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a boy with hidden identity (not Jewish) who is...
🏁 [Row 270] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 277] Gemini: Sending request...

 68%|██████▊   | 274/400 [35:58<16:55,  8.06s/it]

✅ [Row 275] GPT Received: {
  "reasoning": "The Anchor story revolves around a young girl, Gitty, dealing with family stress a...
🚀 [Row 275] Claude: Sending request...

 68%|██████▊   | 274/400 [36:02<16:55,  8.06s/it]

✅ [Row 276] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 276] GPT: Sending request...

 69%|██████▉   | 275/400 [36:03<15:28,  7.43s/it]

✅ [Row 274] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a teacher/assistant educating locals, particularly B...
🏁 [Row 274] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 278] Gemini: Sending request...

 69%|██████▉   | 276/400 [36:09<14:17,  6.92s/it]

✅ [Row 276] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of sacrifice, professional challenges, and...
🚀 [Row 276] Claude: Sending request...
✅ [Row 275] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a young girl (Gitty) on a family farm facing loss, w...
🏁 [Row 275] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 279] Gemini: Sending request...

 69%|██████▉   | 276/400 [36:12<14:17,  6.92s/it]

✅ [Row 278] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A share the central theme...
🚀 [Row 278] GPT: Sending request...

 69%|██████▉   | 276/400 [36:14<14:17,  6.92s/it]

✅ [Row 277] Gemini Received: {
  "reasoning": "The Anchor text describes an 'odyssey' of refugees escaping their homeland and bei...
🚀 [Row 277] GPT: Sending request...

 69%|██████▉   | 276/400 [36:17<14:17,  6.92s/it]

✅ [Row 279] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor's core story revolves aroun...
🚀 [Row 279] GPT: Sending request...

 69%|██████▉   | 276/400 [36:17<14:17,  6.92s/it]

✅ [Row 278] GPT Received: {
  "reasoning": "The Anchor text revolves around a wrongful conviction and the protagonist's effort...
🚀 [Row 278] Claude: Sending request...

 69%|██████▉   | 276/400 [36:18<14:17,  6.92s/it]

✅ [Row 277] GPT Received: {
  "reasoning": "The Anchor story and Text B both focus on the plight of individuals seeking a bett...
🚀 [Row 277] Claude: Sending request...

 69%|██████▉   | 276/400 [36:21<14:17,  6.92s/it]

✅ [Row 279] GPT Received: {
  "reasoning": "The Anchor story revolves around the search for immortality, forbidden love, and t...
🚀 [Row 279] Claude: Sending request...

 69%|██████▉   | 277/400 [36:27<21:32, 10.51s/it]

✅ [Row 277] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Iranian refugees stuck in Turkey waiting for asylum ...
🏁 [Row 277] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 280] Gemini: Sending request...

 69%|██████▉   | 277/400 [36:35<21:32, 10.51s/it]

✅ [Row 280] Gemini Received: {
  "reasoning": "Text B shares a much closer abstract theme and course of action with the Anchor. B...
🚀 [Row 280] GPT: Sending request...

 70%|██████▉   | 278/400 [36:36<20:17,  9.98s/it]

✅ [Row 278] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Picquart's investigation into wrongful espionage con...
🏁 [Row 278] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 281] Gemini: Sending request...
✅ [Row 279] Claude Received: ```json
{
  "reasoning": "Both texts share core elements with the Anchor: a romantic connection acro...
🏁 [Row 279] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 282] Gemini: Sending request...

 70%|███████   | 280/400 [36:37<10:55,  5.46s/it]

✅ [Row 276] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a nurse who takes blame for another's mistake, reloc...
🏁 [Row 276] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 283] Gemini: Sending request...

 70%|███████   | 280/400 [36:39<10:55,  5.46s/it]

✅ [Row 280] GPT Received: {
  "reasoning": "The Anchor text revolves around a character with a dual identity, dealing with pas...
🚀 [Row 280] Claude: Sending request...

 70%|███████   | 280/400 [36:43<10:55,  5.46s/it]

✅ [Row 282] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A feature a protagonist driven by a profound persona...
🚀 [Row 282] GPT: Sending request...

 70%|███████   | 280/400 [36:47<10:55,  5.46s/it]

✅ [Row 282] GPT Received: {
  "reasoning": "The Anchor story revolves around a personal quest to solve the mystery of a mother...
🚀 [Row 282] Claude: Sending request...

 70%|███████   | 280/400 [36:47<10:55,  5.46s/it]

✅ [Row 281] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A involve the...
🚀 [Row 281] GPT: Sending request...

 70%|███████   | 280/400 [36:47<10:55,  5.46s/it]

✅ [Row 283] Gemini Received: {
  "reasoning": "Both the Anchor text and Text B feature a protagonist who faces a significant barr...
🚀 [Row 283] GPT: Sending request...

 70%|███████   | 281/400 [36:49<14:09,  7.14s/it]

✅ [Row 280] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a medical resident in witness protection who wa...
🏁 [Row 280] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 284] Gemini: Sending request...

 70%|███████   | 281/400 [36:51<14:09,  7.14s/it]

✅ [Row 281] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve a central character who becomes entangled ...
🚀 [Row 281] Claude: Sending request...

 70%|███████   | 281/400 [36:53<14:09,  7.14s/it]

✅ [Row 283] GPT Received: {
  "reasoning": "The Anchor story revolves around a kidnapping plot to manipulate the music industr...
🚀 [Row 283] Claude: Sending request...

 70%|███████   | 282/400 [36:57<14:29,  7.37s/it]

✅ [Row 282] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a man returning to his homeland to investigate ...
🏁 [Row 282] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 285] Gemini: Sending request...

 70%|███████   | 282/400 [36:57<14:29,  7.37s/it]

❌ [Row 285] Gemini Exception: 'candidates'
✅ [Row 284] Gemini Received: {
  "reasoning": "The Anchor text describes a 19-year-old single mother who plans and commits murder...
🚀 [Row 284] GPT: Sending request...

 70%|███████   | 282/400 [36:59<14:29,  7.37s/it]

❌ [Row 285] Gemini Exception: 'candidates'

 70%|███████   | 282/400 [37:01<14:29,  7.37s/it]

❌ [Row 285] Gemini Exception: 'candidates'

 71%|███████   | 283/400 [37:01<12:48,  6.57s/it]

✅ [Row 281] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a detective investigating a murder case involvi...
🏁 [Row 281] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 286] Gemini: Sending request...

 71%|███████   | 283/400 [37:02<12:48,  6.57s/it]

🚀 [Row 285] GPT: Sending request...

 71%|███████   | 284/400 [37:02<09:44,  5.04s/it]

✅ [Row 283] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a deliberate kidnapping scheme orchestrated by ...
🏁 [Row 283] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 287] Gemini: Sending request...

 71%|███████   | 284/400 [37:03<09:44,  5.04s/it]

✅ [Row 284] GPT Received: {
  "reasoning": "The Anchor story revolves around a young woman, Katrina, who is deeply involved in...
🚀 [Row 284] Claude: Sending request...

 71%|███████   | 284/400 [37:04<09:44,  5.04s/it]

⏳ [Row 287] Gemini: Rate limit (Attempt 1)

 71%|███████   | 284/400 [37:07<09:44,  5.04s/it]

✅ [Row 285] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of deception, betrayal, and familial confl...
🚀 [Row 285] Claude: Sending request...

 71%|███████▏  | 285/400 [37:11<11:22,  5.93s/it]

✅ [Row 284] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Katrina, a manipulative young single mother who plot...
🏁 [Row 284] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 288] Gemini: Sending request...
✅ [Row 286] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A are biograp...
🚀 [Row 286] GPT: Sending request...

 71%|███████▏  | 285/400 [37:15<11:22,  5.93s/it]

✅ [Row 287] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 287] GPT: Sending request...

 71%|███████▏  | 285/400 [37:17<11:22,  5.93s/it]

✅ [Row 286] GPT Received: {
  "reasoning": "The Anchor text focuses on Anna Wimschneider's life on a farm in Germany, her stru...
🚀 [Row 286] Claude: Sending request...

 71%|███████▏  | 285/400 [37:19<11:22,  5.93s/it]

✅ [Row 287] GPT Received: {
  "reasoning": "The Anchor story involves themes of espionage, betrayal, and historical military c...
🚀 [Row 287] Claude: Sending request...

 71%|███████▏  | 285/400 [37:22<11:22,  5.93s/it]

✅ [Row 288] Gemini Received: {
  "reasoning": "The Anchor text features a character attempting to avert misfortune by sacrificing...
🚀 [Row 288] GPT: Sending request...

 71%|███████▏  | 285/400 [37:26<11:22,  5.93s/it]

✅ [Row 288] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of fortune, hubris, and the consequences o...
🚀 [Row 288] Claude: Sending request...

 72%|███████▏  | 286/400 [37:32<19:45, 10.40s/it]

✅ [Row 287] Claude Received: ```json
{
  "reasoning": "The Anchor is a Cold War naval story focusing on wartime betrayal revealed...
🏁 [Row 287] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 289] Gemini: Sending request...

 72%|███████▏  | 287/400 [37:35<15:44,  8.36s/it]

✅ [Row 285] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a man who deceives his wife about his identity, dese...
🏁 [Row 285] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 290] Gemini: Sending request...

 72%|███████▏  | 287/400 [37:45<15:44,  8.36s/it]

✅ [Row 289] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B share a cor...
🚀 [Row 289] GPT: Sending request...

 72%|███████▏  | 287/400 [37:49<15:44,  8.36s/it]

✅ [Row 289] GPT Received: {
  "reasoning": "The Anchor story revolves around Ali, an ice cream salesman, dealing with competit...
🚀 [Row 289] Claude: Sending request...

 72%|███████▏  | 288/400 [37:50<19:17, 10.33s/it]

✅ [Row 288] Claude Received: ```json
{
  "reasoning": "Text B is narratively closer to the Anchor. Both share the core abstract t...
🏁 [Row 288] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 291] Gemini: Sending request...

 72%|███████▏  | 289/400 [37:56<16:29,  8.91s/it]

✅ [Row 286] Claude Received: ```json
{
  "reasoning": "The Anchor text follows a woman (Anna) in 1920s rural Bavaria whose mother...
🏁 [Row 286] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 292] Gemini: Sending request...

 72%|███████▏  | 289/400 [37:58<16:29,  8.91s/it]

⏳ [Row 292] Gemini: Rate limit (Attempt 1)

 72%|███████▎  | 290/400 [37:59<13:20,  7.28s/it]

✅ [Row 289] Claude Received: ```json
{
  "reasoning": "The Anchor is about a small ice cream vendor (Ali) who loses his motorbike...
🏁 [Row 289] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 293] Gemini: Sending request...
✅ [Row 291] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 291] GPT: Sending request...

 72%|███████▎  | 290/400 [38:05<13:20,  7.28s/it]

✅ [Row 291] GPT Received: {
  "reasoning": "The Anchor story revolves around a marketing executive from Coca-Cola trying to un...
🚀 [Row 291] Claude: Sending request...

 72%|███████▎  | 290/400 [38:05<13:20,  7.28s/it]

❌ [Row 290] Gemini Exception: HTTPSConnectionPool(host='generativelanguage.googleapis.com', port=443): Read timed out. (read timeout=30)

 72%|███████▎  | 290/400 [38:09<13:20,  7.28s/it]

✅ [Row 293] Gemini Received: {
  "reasoning": "The Anchor text describes a plot where a safety expert investigates a series of my...
🚀 [Row 293] GPT: Sending request...

 72%|███████▎  | 290/400 [38:10<13:20,  7.28s/it]

✅ [Row 292] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a c...
🚀 [Row 292] GPT: Sending request...

 73%|███████▎  | 291/400 [38:13<16:55,  9.31s/it]

✅ [Row 291] Claude Received: ```json
{
  "reasoning": "Both texts share some surface-level similarities with the Anchor (corporat...
🏁 [Row 291] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 294] Gemini: Sending request...

 73%|███████▎  | 291/400 [38:15<16:55,  9.31s/it]

✅ [Row 290] Gemini Received: {
  "reasoning": "The Anchor text features a student moving into an isolating and bizarre domestic s...
🚀 [Row 290] GPT: Sending request...

 73%|███████▎  | 291/400 [38:15<16:55,  9.31s/it]

✅ [Row 292] GPT Received: {
  "reasoning": "The Anchor story involves a criminal who escapes from a sanitarium, goes on a crim...
🚀 [Row 292] Claude: Sending request...

 73%|███████▎  | 291/400 [38:17<16:55,  9.31s/it]

✅ [Row 293] GPT Received: {
  "reasoning": "The Anchor story revolves around a series of mysterious aircraft crashes caused by...
🚀 [Row 293] Claude: Sending request...

 73%|███████▎  | 291/400 [38:20<16:55,  9.31s/it]

✅ [Row 290] GPT Received: {
  "reasoning": "The Anchor story involves a student who rents a room expecting peace but finds him...
🚀 [Row 290] Claude: Sending request...

 73%|███████▎  | 291/400 [38:27<16:55,  9.31s/it]

✅ [Row 294] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A are set in ...
🚀 [Row 294] GPT: Sending request...

 73%|███████▎  | 292/400 [38:28<19:22, 10.77s/it]

✅ [Row 293] Claude Received: ```json
{
  "reasoning": "The Anchor follows a safety expert investigating mysterious aircraft crash...
🏁 [Row 293] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 295] Gemini: Sending request...

 73%|███████▎  | 293/400 [38:29<14:10,  7.95s/it]

✅ [Row 290] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a student who encounters bizarre, delusional l...
🏁 [Row 290] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 296] Gemini: Sending request...

 74%|███████▎  | 294/400 [38:30<10:11,  5.77s/it]

✅ [Row 292] Claude Received: ```json
{
  "reasoning": "The Anchor follows a criminal protagonist (escaped madman/thief) who commi...
🏁 [Row 292] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 297] Gemini: Sending request...

 74%|███████▎  | 294/400 [38:30<10:11,  5.77s/it]

✅ [Row 294] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve space travel and a mysterious, potentiall...
🚀 [Row 294] Claude: Sending request...

 74%|███████▎  | 294/400 [38:36<10:11,  5.77s/it]

✅ [Row 297] Gemini Received: {
  "reasoning": "The Anchor text emphasizes a narrative of a protagonist (Dantès) bringing down ant...
🚀 [Row 297] GPT: Sending request...

 74%|███████▎  | 294/400 [38:38<10:11,  5.77s/it]

✅ [Row 296] Gemini Received: {
  "reasoning": "The Anchor text centers on a court-martial during wartime where an individual's ac...
🚀 [Row 296] GPT: Sending request...

 74%|███████▎  | 294/400 [38:40<10:11,  5.77s/it]

✅ [Row 297] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of revenge and manipulation, with a focus o...
🚀 [Row 297] Claude: Sending request...

 74%|███████▎  | 294/400 [38:41<10:11,  5.77s/it]

✅ [Row 296] GPT Received: {
  "reasoning": "The Anchor story and Text B both revolve around a military trial and the defense o...
🚀 [Row 296] Claude: Sending request...

 74%|███████▍  | 295/400 [38:45<14:56,  8.54s/it]

✅ [Row 294] Claude Received: ```json
{
  "reasoning": "The Anchor is a military survival story set on the moon during a war over ...
🏁 [Row 294] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 298] Gemini: Sending request...

 74%|███████▍  | 296/400 [38:50<13:02,  7.53s/it]

✅ [Row 297] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on revenge, manipulation, courtroom drama, loss of love...
🏁 [Row 297] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 299] Gemini: Sending request...

 74%|███████▍  | 297/400 [38:54<11:17,  6.58s/it]

✅ [Row 296] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a WWI soldier accused of desertion who receive...
🏁 [Row 296] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 300] Gemini: Sending request...

 74%|███████▍  | 297/400 [38:56<11:17,  6.58s/it]

⏳ [Row 298] Gemini: Rate limit (Attempt 1)

 74%|███████▍  | 297/400 [38:58<11:17,  6.58s/it]

✅ [Row 295] Gemini Received: {
  "reasoning": "The Anchor text features a female protagonist, Lisa, who is entangled in a complex...
🚀 [Row 295] GPT: Sending request...

 74%|███████▍  | 297/400 [39:03<11:17,  6.58s/it]

✅ [Row 295] GPT Received: {
  "reasoning": "The Anchor story revolves around a woman, Lisa, dealing with the aftermath of her ...
🚀 [Row 295] Claude: Sending request...

 74%|███████▍  | 297/400 [39:12<11:17,  6.58s/it]

✅ [Row 299] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B focus ...
🚀 [Row 299] GPT: Sending request...

 74%|███████▍  | 298/400 [39:13<17:37, 10.37s/it]

✅ [Row 295] Claude Received: ```json
{
  "reasoning": "Both texts involve a woman whose actions lead to tragedy and violence, but...
🏁 [Row 295] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 301] Gemini: Sending request...

 74%|███████▍  | 298/400 [39:15<17:37, 10.37s/it]

✅ [Row 298] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center on a...
🚀 [Row 298] GPT: Sending request...

 74%|███████▍  | 298/400 [39:18<17:37, 10.37s/it]

✅ [Row 299] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of grief, family relationships, and moving...
🚀 [Row 299] Claude: Sending request...

 74%|███████▍  | 298/400 [39:20<17:37, 10.37s/it]

✅ [Row 298] GPT Received: {
  "reasoning": "The Anchor story revolves around a love triangle involving Sofya, her husband Andr...
🚀 [Row 298] Claude: Sending request...

 74%|███████▍  | 298/400 [39:23<17:37, 10.37s/it]

✅ [Row 300] Gemini Received: {
  "reasoning": "The Anchor text centers on Sonny, an aging 'has-been' producer burdened by a diffi...
🚀 [Row 300] GPT: Sending request...

 74%|███████▍  | 298/400 [39:23<17:37, 10.37s/it]

✅ [Row 301] Gemini Received: {
  "reasoning": "The Anchor text centers on Don, a character implicitly or explicitly on the autism...
🚀 [Row 301] GPT: Sending request...

 75%|███████▍  | 299/400 [39:27<19:17, 11.46s/it]

✅ [Row 299] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a widower (David) struggling with grief over his dec...
🏁 [Row 299] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 302] Gemini: Sending request...

 75%|███████▍  | 299/400 [39:28<19:17, 11.46s/it]

✅ [Row 300] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a central character who is trying to rede...
🚀 [Row 300] Claude: Sending request...

 75%|███████▍  | 299/400 [39:28<19:17, 11.46s/it]

✅ [Row 301] GPT Received: {
  "reasoning": "The Anchor story focuses on a father, Don, trying to help his son, Hudson, who is ...
🚀 [Row 301] Claude: Sending request...

 75%|███████▌  | 300/400 [39:35<17:14, 10.34s/it]

✅ [Row 298] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a woman (Sofya) in a marriage who struggles with des...
🏁 [Row 298] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 303] Gemini: Sending request...

 75%|███████▌  | 301/400 [39:38<13:13,  8.02s/it]

✅ [Row 301] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a father (Don) dealing with his son's difficulties, ...
🏁 [Row 301] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 304] Gemini: Sending request...

 75%|███████▌  | 301/400 [39:40<13:13,  8.02s/it]

✅ [Row 302] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 302] GPT: Sending request...

 76%|███████▌  | 302/400 [39:43<11:48,  7.23s/it]

✅ [Row 300] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on an aging Hollywood producer (Sonny Wexler) desperate...
🏁 [Row 300] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 305] Gemini: Sending request...
✅ [Row 302] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of deception, love, and guilt, with a cour...
🚀 [Row 302] Claude: Sending request...

 76%|███████▌  | 302/400 [39:46<11:48,  7.23s/it]

✅ [Row 304] Gemini Received: {
  "reasoning": "The Anchor text centers on the James brothers being hunted by a Union officer whos...
🚀 [Row 304] GPT: Sending request...

 76%|███████▌  | 302/400 [39:46<11:48,  7.23s/it]

✅ [Row 303] Gemini Received: {
  "reasoning": "The Anchor text is about a violent perpetrator who is given a choice between jail ...
🚀 [Row 303] GPT: Sending request...

 76%|███████▌  | 302/400 [39:51<11:48,  7.23s/it]

✅ [Row 305] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a g...
🚀 [Row 305] GPT: Sending request...

 76%|███████▌  | 302/400 [39:51<11:48,  7.23s/it]

✅ [Row 304] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of betrayal, revenge, and turning to crime ...
🚀 [Row 304] Claude: Sending request...

 76%|███████▌  | 303/400 [39:53<12:52,  7.96s/it]

✅ [Row 302] Claude Received: ```json
{
  "reasoning": "The Anchor follows Julian, who initially plans to con and kill a blind hei...
🏁 [Row 302] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 306] Gemini: Sending request...
✅ [Row 303] GPT Received: {
  "reasoning": "The Anchor story revolves around a youth perpetrator, Victor, who is given a choic...
🚀 [Row 303] Claude: Sending request...

 76%|███████▌  | 303/400 [39:56<12:52,  7.96s/it]

✅ [Row 305] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve a group of young men who are wannabe crimi...
🚀 [Row 305] Claude: Sending request...

 76%|███████▌  | 304/400 [40:01<12:36,  7.89s/it]

✅ [Row 304] Claude Received: ```json
{
  "reasoning": "Both Anchor and Text B center on revenge/justice-seeking in the post-Civil...
🏁 [Row 304] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 307] Gemini: Sending request...
✅ [Row 306] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 306] GPT: Sending request...

 76%|███████▌  | 304/400 [40:02<12:36,  7.89s/it]

⏳ [Row 307] Gemini: Rate limit (Attempt 1)

 76%|███████▋  | 306/400 [40:03<06:54,  4.41s/it]

✅ [Row 303] Claude Received: ```json
{
  "reasoning": "The Anchor's core narrative involves Victor, a violent perpetrator given a...
🏁 [Row 303] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 308] Gemini: Sending request...
✅ [Row 305] Claude Received: ```json
{
  "reasoning": "The Anchor follows three white youths who try to adopt a gangsta rap lifes...
🏁 [Row 305] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 309] Gemini: Sending request...

 76%|███████▋  | 306/400 [40:05<06:54,  4.41s/it]

✅ [Row 306] GPT Received: {
  "reasoning": "The Anchor story revolves around a baseball team with vaudeville connections, roma...
🚀 [Row 306] Claude: Sending request...

 76%|███████▋  | 306/400 [40:11<06:54,  4.41s/it]

✅ [Row 309] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A deal centrally with the...
🚀 [Row 309] GPT: Sending request...

 76%|███████▋  | 306/400 [40:16<06:54,  4.41s/it]

✅ [Row 309] GPT Received: {
  "reasoning": "The Anchor story revolves around the theme of death and the inevitability of morta...
🚀 [Row 309] Claude: Sending request...

 76%|███████▋  | 306/400 [40:16<06:54,  4.41s/it]

✅ [Row 308] Gemini Received: {
  "reasoning": "The Anchor text features Joey, a 'hustler' who manipulates others (using sex for r...
🚀 [Row 308] GPT: Sending request...

 76%|███████▋  | 306/400 [40:21<06:54,  4.41s/it]

✅ [Row 307] Gemini Received: {
  "reasoning": "The Anchor text centers on twin sisters attempting to orchestrate their widower fa...
🚀 [Row 307] GPT: Sending request...

 76%|███████▋  | 306/400 [40:22<06:54,  4.41s/it]

✅ [Row 308] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of failed aspirations, manipulation, and c...
🚀 [Row 308] Claude: Sending request...

 77%|███████▋  | 307/400 [40:22<13:43,  8.86s/it]

✅ [Row 306] Claude Received: ```json
{
  "reasoning": "The Anchor centers on romantic entanglements within a sports/entertainment...
🏁 [Row 306] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 310] Gemini: Sending request...

 77%|███████▋  | 307/400 [40:24<13:43,  8.86s/it]

✅ [Row 307] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve twin sisters who are initially at odds wi...
🚀 [Row 307] Claude: Sending request...

 77%|███████▋  | 308/400 [40:26<11:01,  7.19s/it]

✅ [Row 309] Claude Received: ```json
{
  "reasoning": "The Anchor story is about Death keeping a promise by sending symbolic mess...
🏁 [Row 309] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 311] Gemini: Sending request...

 77%|███████▋  | 309/400 [40:34<11:39,  7.69s/it]

✅ [Row 307] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on twin sisters trying to find their widowed father a g...
🏁 [Row 307] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 312] Gemini: Sending request...

 77%|███████▋  | 309/400 [40:36<11:39,  7.69s/it]

✅ [Row 310] Gemini Received: {
  "reasoning": "The Anchor text features two distinct couples (Tom & Anne, Ellen & John) whose par...
🚀 [Row 310] GPT: Sending request...

 77%|███████▋  | 309/400 [40:37<11:39,  7.69s/it]

⏳ [Row 312] Gemini: Rate limit (Attempt 1)

 77%|███████▋  | 309/400 [40:38<11:39,  7.69s/it]

✅ [Row 311] Gemini Received: {
  "reasoning": "The Anchor text describes a woman's transformation from political ignorance to act...
🚀 [Row 311] GPT: Sending request...

 77%|███████▋  | 309/400 [40:40<11:39,  7.69s/it]

✅ [Row 310] GPT Received: {
  "reasoning": "The Anchor story revolves around two siblings, Tom and Ellen, who are involved in ...
🚀 [Row 310] Claude: Sending request...

 77%|███████▋  | 309/400 [40:43<11:39,  7.69s/it]

✅ [Row 311] GPT Received: {
  "reasoning": "The Anchor text revolves around a woman's struggle with poverty, domestic abuse, a...
🚀 [Row 311] Claude: Sending request...

 78%|███████▊  | 310/400 [40:44<12:35,  8.39s/it]

✅ [Row 308] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a washed-up former child star using sexual manipulat...
🏁 [Row 308] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 313] Gemini: Sending request...

 78%|███████▊  | 311/400 [40:51<11:28,  7.74s/it]

✅ [Row 310] Claude Received: ```json
{
  "reasoning": "The Anchor centers on two siblings (Tom and Ellen) who travel to London fo...
🏁 [Row 310] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 314] Gemini: Sending request...

 78%|███████▊  | 312/400 [40:52<08:23,  5.72s/it]

✅ [Row 311] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a working-class mother (Nilovna) who becomes politic...
🏁 [Row 311] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 315] Gemini: Sending request...

 78%|███████▊  | 312/400 [40:54<08:23,  5.72s/it]

⏳ [Row 315] Gemini: Rate limit (Attempt 1)

 78%|███████▊  | 312/400 [40:58<08:23,  5.72s/it]

✅ [Row 314] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 314] GPT: Sending request...

 78%|███████▊  | 312/400 [40:59<08:23,  5.72s/it]

✅ [Row 312] Gemini Received: {
  "reasoning": "The Anchor text focuses on a character's internal moral and ethical struggles rela...
🚀 [Row 312] GPT: Sending request...

 78%|███████▊  | 312/400 [41:00<08:23,  5.72s/it]

✅ [Row 313] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a s...
🚀 [Row 313] GPT: Sending request...

 78%|███████▊  | 312/400 [41:03<08:23,  5.72s/it]

✅ [Row 314] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a journey in Vietnam that is deeply conne...
🚀 [Row 314] Claude: Sending request...

 78%|███████▊  | 312/400 [41:05<08:23,  5.72s/it]

✅ [Row 312] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of guilt, ethical dilemmas, and family dyn...
🚀 [Row 312] Claude: Sending request...
✅ [Row 313] GPT Received: {
  "reasoning": "The Anchor story involves themes of corruption, framing, and revenge, with a cours...
🚀 [Row 313] Claude: Sending request...

 78%|███████▊  | 312/400 [41:05<08:23,  5.72s/it]

✅ [Row 315] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist who escapes a cruel family situation, finds...
🚀 [Row 315] GPT: Sending request...

 78%|███████▊  | 312/400 [41:12<08:23,  5.72s/it]

✅ [Row 315] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of overcoming adversity, selflessness, and...
🚀 [Row 315] Claude: Sending request...

 78%|███████▊  | 313/400 [41:12<14:40, 10.13s/it]

✅ [Row 314] Claude Received: ```json
{
  "reasoning": "Both texts involve journeys through Vietnam dealing with death and persona...
🏁 [Row 314] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 316] Gemini: Sending request...

 78%|███████▊  | 314/400 [41:13<10:44,  7.49s/it]

✅ [Row 313] Claude Received: ```json
{
  "reasoning": "Both texts share core elements with the Anchor: a law enforcement figure, ...
🏁 [Row 313] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 317] Gemini: Sending request...

 79%|███████▉  | 315/400 [41:16<08:29,  6.00s/it]

✅ [Row 312] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a couple dealing with moral guilt over profiting fro...
🏁 [Row 312] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 318] Gemini: Sending request...

 79%|███████▉  | 315/400 [41:21<08:29,  6.00s/it]

✅ [Row 316] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a c...
🚀 [Row 316] GPT: Sending request...

 79%|███████▉  | 316/400 [41:21<08:10,  5.84s/it]

✅ [Row 315] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a woman (Michèle) who escapes a cruel fate (prostitu...
🏁 [Row 315] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 319] Gemini: Sending request...

 79%|███████▉  | 316/400 [41:24<08:10,  5.84s/it]

✅ [Row 318] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 318] GPT: Sending request...

 79%|███████▉  | 316/400 [41:25<08:10,  5.84s/it]

✅ [Row 317] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A share the s...
🚀 [Row 317] GPT: Sending request...

 79%|███████▉  | 316/400 [41:26<08:10,  5.84s/it]

✅ [Row 316] GPT Received: {
  "reasoning": "The Anchor story involves a brother and sister who are transformed by a malevolent...
🚀 [Row 316] Claude: Sending request...

 79%|███████▉  | 316/400 [41:27<08:10,  5.84s/it]

✅ [Row 318] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a protagonist with a military background ...
🚀 [Row 318] Claude: Sending request...

 79%|███████▉  | 316/400 [41:29<08:10,  5.84s/it]

✅ [Row 317] GPT Received: {
  "reasoning": "The Anchor story revolves around a priest sent to a town controlled by a bandit, w...
🚀 [Row 317] Claude: Sending request...

 79%|███████▉  | 316/400 [41:30<08:10,  5.84s/it]

✅ [Row 319] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a s...
🚀 [Row 319] GPT: Sending request...

 79%|███████▉  | 316/400 [41:34<08:10,  5.84s/it]

✅ [Row 319] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a scientist conducting unconventional res...
🚀 [Row 319] Claude: Sending request...

 79%|███████▉  | 317/400 [41:37<12:08,  8.78s/it]

✅ [Row 316] Claude Received: ```json
{
  "reasoning": "The Anchor story is fundamentally about siblings transformed by a malevole...
🏁 [Row 316] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 320] Gemini: Sending request...

 80%|███████▉  | 318/400 [41:38<08:54,  6.52s/it]

✅ [Row 317] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve conflicts with authority figures and share ...
🏁 [Row 317] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 321] Gemini: Sending request...

 80%|███████▉  | 319/400 [41:44<08:23,  6.22s/it]

✅ [Row 319] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a researcher living with chimpanzees who disappears,...
🏁 [Row 319] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 322] Gemini: Sending request...

 80%|████████  | 320/400 [41:45<06:07,  4.60s/it]

✅ [Row 318] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories share the core na...
🏁 [Row 318] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 323] Gemini: Sending request...

 80%|████████  | 320/400 [41:47<06:07,  4.60s/it]

✅ [Row 320] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A portray rel...
🚀 [Row 320] GPT: Sending request...

 80%|████████  | 320/400 [41:50<06:07,  4.60s/it]

✅ [Row 321] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist facing extreme pressure from an oppressive ...
🚀 [Row 321] GPT: Sending request...

 80%|████████  | 320/400 [41:52<06:07,  4.60s/it]

✅ [Row 320] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, betrayal, and jealousy, with a co...
🚀 [Row 320] Claude: Sending request...

 80%|████████  | 320/400 [41:54<06:07,  4.60s/it]

✅ [Row 322] Gemini Received: {
  "reasoning": "The Anchor text describes a complex, multi-threaded crime narrative set in an urba...
🚀 [Row 322] GPT: Sending request...
✅ [Row 321] GPT Received: {
  "reasoning": "The Anchor text revolves around the theme of love and loyalty in the face of oppre...
🚀 [Row 321] Claude: Sending request...

 80%|████████  | 320/400 [41:58<06:07,  4.60s/it]

✅ [Row 322] GPT Received: {
  "reasoning": "The Anchor story involves a complex web of crime, personal relationships, and a cl...
🚀 [Row 322] Claude: Sending request...
✅ [Row 323] Gemini Received: {
  "reasoning": "The Anchor text centers on a husband realizing his wife has poisoned him and refle...
🚀 [Row 323] GPT: Sending request...

 80%|████████  | 320/400 [42:02<06:07,  4.60s/it]

✅ [Row 323] GPT Received: {
  "reasoning": "The Anchor text revolves around a marriage where the wife poisons the husband, lea...
🚀 [Row 323] Claude: Sending request...

 80%|████████  | 321/400 [42:03<11:27,  8.70s/it]

✅ [Row 321] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a man who refuses to abandon his Jewish wife under N...
🏁 [Row 321] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 324] Gemini: Sending request...

 80%|████████  | 322/400 [42:06<09:05,  6.99s/it]

✅ [Row 320] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a passionate love triangle involving Carmen (a gypsy...
🏁 [Row 320] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 325] Gemini: Sending request...

 81%|████████  | 323/400 [42:12<08:47,  6.85s/it]

✅ [Row 323] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a wealthy man poisoned by his wife, lying in hospita...
🏁 [Row 323] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 326] Gemini: Sending request...

 81%|████████  | 324/400 [42:14<06:31,  5.16s/it]

✅ [Row 322] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a complex, interconnected crime narrative set in a fict...
🏁 [Row 322] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 327] Gemini: Sending request...

 81%|████████  | 324/400 [42:17<06:31,  5.16s/it]

✅ [Row 325] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a m...
🚀 [Row 325] GPT: Sending request...

 81%|████████  | 324/400 [42:19<06:31,  5.16s/it]

✅ [Row 326] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a c...
🚀 [Row 326] GPT: Sending request...

 81%|████████  | 324/400 [42:21<06:31,  5.16s/it]

✅ [Row 324] Gemini Received: {
  "reasoning": "The Anchor text revolves around a protagonist (Khavtshi) burdened by family respon...
🚀 [Row 324] GPT: Sending request...

 81%|████████  | 324/400 [42:22<06:31,  5.16s/it]

✅ [Row 325] GPT Received: {
  "reasoning": "The Anchor story follows Spyros on a journey across Greece, focusing on themes of ...
🚀 [Row 325] Claude: Sending request...

 81%|████████  | 324/400 [42:23<06:31,  5.16s/it]

✅ [Row 327] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a p...
🚀 [Row 327] GPT: Sending request...
✅ [Row 326] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of betrayal, rebuilding one's life, and be...
🚀 [Row 326] Claude: Sending request...

 81%|████████  | 324/400 [42:25<06:31,  5.16s/it]

✅ [Row 324] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a protagonist who is initially constraine...
🚀 [Row 324] Claude: Sending request...

 81%|████████  | 324/400 [42:27<06:31,  5.16s/it]

✅ [Row 327] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a central character who is an outsider to...
🚀 [Row 327] Claude: Sending request...

 81%|████████▏ | 325/400 [42:31<10:56,  8.76s/it]

✅ [Row 325] Claude Received: ```json
{
  "reasoning": "The Anchor follows a solitary journey of an older man (Spyros) traveling t...
🏁 [Row 325] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 328] Gemini: Sending request...

 82%|████████▏ | 326/400 [42:34<08:45,  7.10s/it]

✅ [Row 324] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both stories center on a prota...
🏁 [Row 324] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 329] Gemini: Sending request...

 82%|████████▏ | 327/400 [42:35<06:33,  5.39s/it]

✅ [Row 326] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic betrayal and murder, but Text A is narratively...
🏁 [Row 326] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 330] Gemini: Sending request...

 82%|████████▏ | 327/400 [42:44<06:33,  5.39s/it]

✅ [Row 328] Gemini Received: {
  "reasoning": "Both Text A and Text B are narratively very distant from the Anchor text. However,...
🚀 [Row 328] GPT: Sending request...

 82%|████████▏ | 328/400 [42:45<07:50,  6.53s/it]

✅ [Row 327] Claude Received: ```json
{
  "reasoning": "The Anchor centers on C-Note using property ownership and bribery to force...
🏁 [Row 327] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 331] Gemini: Sending request...

 82%|████████▏ | 328/400 [42:47<07:50,  6.53s/it]

✅ [Row 330] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature eld...
🚀 [Row 330] GPT: Sending request...

 82%|████████▏ | 328/400 [42:49<07:50,  6.53s/it]

✅ [Row 328] GPT Received: {
  "reasoning": "The Anchor story revolves around a group of friends fulfilling a pact to honor a d...
🚀 [Row 328] Claude: Sending request...
✅ [Row 329] Gemini Received: {
  "reasoning": "The Anchor text features an intergroup conflict between rolleys and elves, which a...
🚀 [Row 329] GPT: Sending request...

 82%|████████▏ | 328/400 [42:53<07:50,  6.53s/it]

✅ [Row 330] GPT Received: {
  "reasoning": "The Anchor story revolves around a group of retired gendarmes who reunite to help ...
🚀 [Row 330] Claude: Sending request...

 82%|████████▏ | 328/400 [42:54<07:50,  6.53s/it]

✅ [Row 331] Gemini Received: {
  "reasoning": "The Anchor story is centered on the theme of sacrificial love, where characters gi...
🚀 [Row 331] GPT: Sending request...

 82%|████████▏ | 328/400 [42:55<07:50,  6.53s/it]

✅ [Row 329] GPT Received: {
  "reasoning": "The Anchor story involves a conflict between two groups, the rolleys and the elves...
🚀 [Row 329] Claude: Sending request...

 82%|████████▏ | 329/400 [42:58<10:16,  8.68s/it]

✅ [Row 328] Claude Received: ```json
{
  "reasoning": "The Anchor is about five friends honoring a pact to scatter their deceased...
🏁 [Row 328] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 332] Gemini: Sending request...

 82%|████████▏ | 329/400 [43:01<10:16,  8.68s/it]

✅ [Row 331] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve themes of sacrifice and love, though in d...
🚀 [Row 331] Claude: Sending request...

 82%|████████▎ | 330/400 [43:02<08:28,  7.27s/it]

✅ [Row 330] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on retired gendarmes reuniting to help an amnesiac coll...
🏁 [Row 330] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 333] Gemini: Sending request...

 83%|████████▎ | 331/400 [43:05<06:52,  5.98s/it]

✅ [Row 329] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a conflict between two groups (trolleys and elves) t...
🏁 [Row 329] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 334] Gemini: Sending request...

 83%|████████▎ | 332/400 [43:12<07:06,  6.27s/it]

✅ [Row 331] Claude Received: ```json
{
  "reasoning": "The Anchor story is fundamentally about mutual, loving sacrifice between p...
🏁 [Row 331] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 335] Gemini: Sending request...

 83%|████████▎ | 332/400 [43:15<07:06,  6.27s/it]

✅ [Row 334] Gemini Received: {
  "reasoning": "The Anchor story features a boy who discovers a magical being (a genie) that grant...
🚀 [Row 334] GPT: Sending request...

 83%|████████▎ | 332/400 [43:16<07:06,  6.27s/it]

✅ [Row 332] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature pro...
🚀 [Row 332] GPT: Sending request...

 83%|████████▎ | 332/400 [43:18<07:06,  6.27s/it]

✅ [Row 333] Gemini Received: {
  "reasoning": "The Anchor text features a male protagonist in a competitive setting, dealing with...
🚀 [Row 333] GPT: Sending request...

 83%|████████▎ | 332/400 [43:20<07:06,  6.27s/it]

✅ [Row 332] GPT Received: {
  "reasoning": "The Anchor story focuses on a woman's fight to free her husband from a long prison...
🚀 [Row 332] Claude: Sending request...

 83%|████████▎ | 332/400 [43:21<07:06,  6.27s/it]

✅ [Row 334] GPT Received: {
  "reasoning": "The Anchor story involves a young boy, Volka, who discovers a genie and must navig...
🚀 [Row 334] Claude: Sending request...

 83%|████████▎ | 332/400 [43:21<07:06,  6.27s/it]

✅ [Row 335] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both texts are set in East Germany dur...
🚀 [Row 335] GPT: Sending request...

 83%|████████▎ | 332/400 [43:22<07:06,  6.27s/it]

✅ [Row 333] GPT Received: {
  "reasoning": "The Anchor story is about a young skier, Harkin Banks, who is determined to prove ...
🚀 [Row 333] Claude: Sending request...

 83%|████████▎ | 332/400 [43:24<07:06,  6.27s/it]

✅ [Row 335] GPT Received: {
  "reasoning": "The Anchor text and Text A both deal with themes of disillusionment and personal g...
🚀 [Row 335] Claude: Sending request...

 84%|████████▎ | 334/400 [43:30<07:30,  6.83s/it]

✅ [Row 334] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a boy discovering a magical being (genie) who emerge...
🏁 [Row 334] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 336] Gemini: Sending request...
✅ [Row 332] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a woman's long-term fight to free her imprisoned hus...
🏁 [Row 332] Votes: {'gemini': True, 'gpt': True, 'claude': False}
🚀 [Row 337] Gemini: Sending request...

 84%|████████▍ | 335/400 [43:32<05:41,  5.25s/it]

✅ [Row 333] Claude Received: ```json
{
  "reasoning": "The Anchor is a sports comedy about a young skier competing in a freestyle...
🏁 [Row 333] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 338] Gemini: Sending request...

 84%|████████▍ | 336/400 [43:33<04:30,  4.23s/it]

✅ [Row 335] Claude Received: ```json
{
  "reasoning": "Text A is narratively closer to the Anchor. Both are set in East Germany d...
🏁 [Row 335] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 339] Gemini: Sending request...

 84%|████████▍ | 336/400 [43:38<04:30,  4.23s/it]

✅ [Row 336] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B revolve aro...
🚀 [Row 336] GPT: Sending request...

 84%|████████▍ | 336/400 [43:38<04:30,  4.23s/it]

✅ [Row 337] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center on a...
🚀 [Row 337] GPT: Sending request...

 84%|████████▍ | 336/400 [43:42<04:30,  4.23s/it]

✅ [Row 336] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a medical setting and a character dealing...
🚀 [Row 336] Claude: Sending request...

 84%|████████▍ | 336/400 [43:43<04:30,  4.23s/it]

✅ [Row 337] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve a female protagonist who is dealing with ...
🚀 [Row 337] Claude: Sending request...

 84%|████████▍ | 336/400 [43:45<04:30,  4.23s/it]

✅ [Row 339] Gemini Received: {
  "reasoning": "Text A focuses on a personal crime, escape, and self-reinvention, which bears no s...
🚀 [Row 339] GPT: Sending request...

 84%|████████▍ | 336/400 [43:51<04:30,  4.23s/it]

✅ [Row 339] GPT Received: {
  "reasoning": "The Anchor story revolves around an investigative journalist uncovering a scientif...
🚀 [Row 339] Claude: Sending request...

 84%|████████▍ | 336/400 [43:51<04:30,  4.23s/it]

✅ [Row 338] Gemini Received: {
  "reasoning": "The Anchor text features small-time gangsters who commit a large theft, attempt to...
🚀 [Row 338] GPT: Sending request...

 84%|████████▍ | 337/400 [43:54<09:33,  9.10s/it]

✅ [Row 337] Claude Received: ```json
{
  "reasoning": "The Anchor is about a lonely young girl (Harriet) living in difficult circ...
🏁 [Row 337] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 340] Gemini: Sending request...

 84%|████████▍ | 338/400 [43:54<06:42,  6.49s/it]

✅ [Row 336] Claude Received: ```json
{
  "reasoning": "The Anchor describes a medical professional (Feldsher Kuryatin) attempting...
🏁 [Row 336] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 341] Gemini: Sending request...

 84%|████████▍ | 338/400 [43:56<06:42,  6.49s/it]

✅ [Row 338] GPT Received: {
  "reasoning": "The Anchor story involves small-time gangsters who steal money from a gangster bos...
🚀 [Row 338] Claude: Sending request...

 85%|████████▍ | 339/400 [44:01<06:36,  6.49s/it]

✅ [Row 339] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an investigative journalist and whistleblower exposi...
🏁 [Row 339] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 342] Gemini: Sending request...

 85%|████████▌ | 340/400 [44:06<06:07,  6.13s/it]

✅ [Row 338] Claude Received: ```json
{
  "reasoning": "Both texts involve con artists/criminals, but Text B is narratively closer...
🏁 [Row 338] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 343] Gemini: Sending request...

 85%|████████▌ | 340/400 [44:10<06:07,  6.13s/it]

✅ [Row 340] Gemini Received: {
  "reasoning": "The Anchor story centers on an established author whose life is unexpectedly disru...
🚀 [Row 340] GPT: Sending request...

 85%|████████▌ | 340/400 [44:13<06:07,  6.13s/it]

✅ [Row 341] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B descri...
🚀 [Row 341] GPT: Sending request...

 85%|████████▌ | 340/400 [44:15<06:07,  6.13s/it]

✅ [Row 340] GPT Received: {
  "reasoning": "The Anchor text 'Kokowääh' revolves around the themes of unexpected parenthood, re...
🚀 [Row 340] Claude: Sending request...

 85%|████████▌ | 340/400 [44:17<06:07,  6.13s/it]

✅ [Row 341] GPT Received: {
  "reasoning": "The Anchor text focuses on a small group of soldiers trying to survive and deliver...
🚀 [Row 341] Claude: Sending request...

 85%|████████▌ | 340/400 [44:18<06:07,  6.13s/it]

✅ [Row 343] Gemini Received: {
  "reasoning": "Text A focuses on a man's experience in prison, his false accusation, and his even...
🚀 [Row 343] GPT: Sending request...

 85%|████████▌ | 340/400 [44:21<06:07,  6.13s/it]

✅ [Row 342] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist who is an outlaw, Billy Joe Cudlip, and his...
🚀 [Row 342] GPT: Sending request...

 85%|████████▌ | 340/400 [44:23<06:07,  6.13s/it]

✅ [Row 343] GPT Received: {
  "reasoning": "The Anchor story 'Return Engagement' revolves around a Triad boss who, after being...
🚀 [Row 343] Claude: Sending request...

 85%|████████▌ | 340/400 [44:25<06:07,  6.13s/it]

✅ [Row 342] GPT Received: {
  "reasoning": "The Anchor story revolves around a bandit who becomes a sheriff and faces a moral ...
🚀 [Row 342] Claude: Sending request...

 85%|████████▌ | 341/400 [44:26<10:13, 10.40s/it]

✅ [Row 340] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on Henry, a Berlin-based author dealing with the sudden...
🏁 [Row 340] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 344] Gemini: Sending request...

 86%|████████▌ | 342/400 [44:30<08:04,  8.34s/it]

✅ [Row 341] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B depict WWII military conflicts involving outnumbere...
🏁 [Row 341] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 345] Gemini: Sending request...

 86%|████████▌ | 343/400 [44:30<05:39,  5.95s/it]

✅ [Row 343] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a Triad boss released from prison who travels to Hon...
🏁 [Row 343] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 346] Gemini: Sending request...

 86%|████████▌ | 343/400 [44:38<05:39,  5.95s/it]

✅ [Row 346] Gemini Received: {
  "reasoning": "Text A is closer to the Anchor. Both the Anchor and Text A describe communities fo...
🚀 [Row 346] GPT: Sending request...

 86%|████████▌ | 343/400 [44:41<05:39,  5.95s/it]

✅ [Row 346] GPT Received: {
  "reasoning": "The Anchor text and Text A both involve communities facing economic hardship and c...
🚀 [Row 346] Claude: Sending request...

 86%|████████▌ | 343/400 [44:41<05:39,  5.95s/it]

✅ [Row 345] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist who, having caused a murder (indirectly), o...
🚀 [Row 345] GPT: Sending request...

 86%|████████▌ | 344/400 [44:42<07:10,  7.69s/it]

✅ [Row 342] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a bandit who pretends to reform and becomes sheriff,...
🏁 [Row 342] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 347] Gemini: Sending request...

 86%|████████▌ | 344/400 [44:43<07:10,  7.69s/it]

✅ [Row 344] Gemini Received: {
  "reasoning": "The Anchor text centers around a specific murder plot driven by financial gain (in...
🚀 [Row 344] GPT: Sending request...

 86%|████████▌ | 344/400 [44:46<07:10,  7.69s/it]

✅ [Row 345] GPT Received: {
  "reasoning": "The Anchor story involves a central character, Jay Moore, who is involved in crimi...
🚀 [Row 345] Claude: Sending request...

 86%|████████▌ | 344/400 [44:47<07:10,  7.69s/it]

✅ [Row 344] GPT Received: {
  "reasoning": "The Anchor story revolves around a plot involving inheritance, a murder plot for f...
🚀 [Row 344] Claude: Sending request...

 86%|████████▌ | 344/400 [44:50<07:10,  7.69s/it]

✅ [Row 347] Gemini Received: {
  "reasoning": "The Anchor text features a pregnancy and a child as a central point of conflict, w...
🚀 [Row 347] GPT: Sending request...

 86%|████████▌ | 344/400 [44:53<07:10,  7.69s/it]

✅ [Row 347] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of love, abandonment, and the challenges o...
🚀 [Row 347] Claude: Sending request...

 86%|████████▋ | 345/400 [44:57<08:58,  9.78s/it]

✅ [Row 344] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around an inheritance plot where the store manager (Gr...
🏁 [Row 344] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 348] Gemini: Sending request...

 86%|████████▋ | 346/400 [45:02<07:32,  8.37s/it]

✅ [Row 346] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a religious leader gathering impoverished followers ...
🏁 [Row 346] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 349] Gemini: Sending request...

 87%|████████▋ | 347/400 [45:05<06:01,  6.81s/it]

✅ [Row 347] Claude Received: ```json
{
  "reasoning": "The Anchor involves a central pregnancy plotline where a woman (Callie) is...
🏁 [Row 347] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 350] Gemini: Sending request...

 87%|████████▋ | 348/400 [45:13<06:15,  7.22s/it]

✅ [Row 345] Claude Received: ```json
{
  "reasoning": "Text A involves a murder investigation where a family member (Silvelie) is...
🏁 [Row 345] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 351] Gemini: Sending request...
✅ [Row 348] Gemini Received: {
  "reasoning": "The Anchor text features an elderly woman who takes it upon herself to solve a cri...
🚀 [Row 348] GPT: Sending request...

 87%|████████▋ | 348/400 [45:14<06:15,  7.22s/it]

✅ [Row 350] Gemini Received: {
  "reasoning": "Text A is significantly closer to the Anchor text. Both the Anchor and Text A shar...
🚀 [Row 350] GPT: Sending request...

 87%|████████▋ | 348/400 [45:17<06:15,  7.22s/it]

✅ [Row 348] GPT Received: {
  "reasoning": "The Anchor story revolves around a grandmother who, after being robbed, takes matt...
🚀 [Row 348] Claude: Sending request...

 87%|████████▋ | 348/400 [45:18<06:15,  7.22s/it]

✅ [Row 350] GPT Received: {
  "reasoning": "The Anchor story revolves around a rancher who unexpectedly becomes a king and mus...
🚀 [Row 350] Claude: Sending request...

 87%|████████▋ | 348/400 [45:20<06:15,  7.22s/it]

✅ [Row 349] Gemini Received: {
  "reasoning": "The Anchor text features themes of delusion, obsession with a scandalous past, and...
🚀 [Row 349] GPT: Sending request...

 87%|████████▋ | 348/400 [45:22<06:15,  7.22s/it]

✅ [Row 351] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature mal...
🚀 [Row 351] GPT: Sending request...

 87%|████████▋ | 348/400 [45:25<06:15,  7.22s/it]

✅ [Row 349] GPT Received: {
  "reasoning": "The Anchor text revolves around an elderly woman who believes she is Anita Berber,...
🚀 [Row 349] Claude: Sending request...

 87%|████████▋ | 348/400 [45:26<06:15,  7.22s/it]

✅ [Row 351] GPT Received: {
  "reasoning": "The Anchor story revolves around two men fantasizing about a life as pimps, dreami...
🚀 [Row 351] Claude: Sending request...

 87%|████████▋ | 349/400 [45:28<08:05,  9.53s/it]

✅ [Row 350] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a Montana rancher who unexpectedly inherits a Europe...
🏁 [Row 350] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 352] Gemini: Sending request...

 88%|████████▊ | 350/400 [45:29<05:49,  7.00s/it]

✅ [Row 348] Claude Received: ```json
{
  "reasoning": "Text A shares a stronger narrative similarity with the Anchor. Both storie...
🏁 [Row 348] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 353] Gemini: Sending request...

 88%|████████▊ | 351/400 [45:35<05:30,  6.74s/it]

✅ [Row 351] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on two men fantasizing about running an escort service ...
🏁 [Row 351] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 354] Gemini: Sending request...

 88%|████████▊ | 352/400 [45:36<04:03,  5.06s/it]

✅ [Row 349] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a delusional elderly woman who believes she is a dec...
🏁 [Row 349] Votes: {'gemini': False, 'gpt': True, 'claude': False}
🚀 [Row 355] Gemini: Sending request...

 88%|████████▊ | 352/400 [45:38<04:03,  5.06s/it]

⏳ [Row 354] Gemini: Rate limit (Attempt 1)

 88%|████████▊ | 352/400 [45:41<04:03,  5.06s/it]

✅ [Row 352] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 352] GPT: Sending request...

 88%|████████▊ | 352/400 [45:43<04:03,  5.06s/it]

✅ [Row 353] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A deeply expl...
🚀 [Row 353] GPT: Sending request...

 88%|████████▊ | 352/400 [45:46<04:03,  5.06s/it]

✅ [Row 352] GPT Received: {
  "reasoning": "The Anchor story revolves around a naive young man, Pyarelal, who is wrongfully ac...
🚀 [Row 352] Claude: Sending request...

 88%|████████▊ | 352/400 [45:47<04:03,  5.06s/it]

✅ [Row 355] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A involve the...
🚀 [Row 355] GPT: Sending request...

 88%|████████▊ | 352/400 [45:47<04:03,  5.06s/it]

✅ [Row 353] GPT Received: {
  "reasoning": "The Anchor text and Text A both focus on family dynamics and the struggles that ar...
🚀 [Row 353] Claude: Sending request...

 88%|████████▊ | 352/400 [45:52<04:03,  5.06s/it]

✅ [Row 355] GPT Received: {
  "reasoning": "The Anchor text involves a plot centered around mistaken identities, con-men, and ...
🚀 [Row 355] Claude: Sending request...

 88%|████████▊ | 354/400 [45:56<05:03,  6.60s/it]

✅ [Row 352] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a naive young man who surprisingly confesses to murd...
🏁 [Row 352] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 356] Gemini: Sending request...
✅ [Row 353] Claude Received: ```json
{
  "reasoning": "Both texts involve family dysfunction and moral complexity, but Text A is ...
🏁 [Row 353] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 357] Gemini: Sending request...

 88%|████████▊ | 354/400 [45:59<05:03,  6.60s/it]

✅ [Row 354] Gemini Received: {
  "reasoning": "The Anchor text describes Moomintroll waking into an unfamiliar, harsh world (wint...
🚀 [Row 354] GPT: Sending request...

 89%|████████▉ | 355/400 [46:01<04:31,  6.02s/it]

✅ [Row 355] Claude Received: ```json
{
  "reasoning": "The Anchor is about con-men impersonating scientists, stealing a formula, ...
🏁 [Row 355] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 358] Gemini: Sending request...

 89%|████████▉ | 355/400 [46:05<04:31,  6.02s/it]

✅ [Row 357] Gemini Received: {
  "reasoning": "The Anchor text describes a deliberate scheme of insurance fraud, involving a plan...
🚀 [Row 357] GPT: Sending request...

 89%|████████▉ | 355/400 [46:05<04:31,  6.02s/it]

✅ [Row 354] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve a character who finds themselves in an unf...
🚀 [Row 354] Claude: Sending request...

 89%|████████▉ | 355/400 [46:09<04:31,  6.02s/it]

✅ [Row 357] GPT Received: {
  "reasoning": "The Anchor story revolves around a rich businessman committing insurance fraud by ...
🚀 [Row 357] Claude: Sending request...
✅ [Row 356] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 356] GPT: Sending request...

 89%|████████▉ | 355/400 [46:13<04:31,  6.02s/it]

✅ [Row 356] GPT Received: {
  "reasoning": "The Anchor story involves a plot centered around a hidden identity, a series of mu...
🚀 [Row 356] Claude: Sending request...

 89%|████████▉ | 356/400 [46:15<06:07,  8.36s/it]

✅ [Row 354] Claude Received: ```json
{
  "reasoning": "Both texts share the core narrative of a protagonist who awakens/enters an...
🏁 [Row 354] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 359] Gemini: Sending request...

 89%|████████▉ | 356/400 [46:22<06:07,  8.36s/it]

✅ [Row 358] Gemini Received: {
  "reasoning": "The Anchor text is about a sheltered 28-year-old adult who is forced into independ...
🚀 [Row 358] GPT: Sending request...

 89%|████████▉ | 357/400 [46:23<06:06,  8.51s/it]

✅ [Row 356] Claude Received: ```json
{
  "reasoning": "Both Text A and Text B involve protagonists who uncover criminal activitie...
🏁 [Row 356] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 360] Gemini: Sending request...

 90%|████████▉ | 358/400 [46:26<04:49,  6.88s/it]

✅ [Row 357] Claude Received: ```json
{
  "reasoning": "The Anchor centers on an insurance fraud scheme during the Great Depressio...
🏁 [Row 357] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 361] Gemini: Sending request...

 90%|████████▉ | 358/400 [46:27<04:49,  6.88s/it]

✅ [Row 358] GPT Received: {
  "reasoning": "The Anchor story revolves around John, a sheltered individual who must navigate ad...
🚀 [Row 358] Claude: Sending request...
✅ [Row 359] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B center...

 90%|████████▉ | 358/400 [46:27<04:49,  6.88s/it]

🚀 [Row 359] GPT: Sending request...

 90%|████████▉ | 358/400 [46:31<04:49,  6.88s/it]

✅ [Row 359] GPT Received: {
  "reasoning": "The Anchor story involves a murder investigation with a private investigator, Tom ...
🚀 [Row 359] Claude: Sending request...

 90%|████████▉ | 358/400 [46:32<04:49,  6.88s/it]

✅ [Row 360] Gemini Received: {
  "reasoning": "Both the Anchor text and Text A feature a protagonist whose established life is sh...
🚀 [Row 360] GPT: Sending request...

 90%|████████▉ | 358/400 [46:36<04:49,  6.88s/it]

✅ [Row 360] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve protagonists who are successful in their ...
🚀 [Row 360] Claude: Sending request...

 90%|████████▉ | 359/400 [46:36<05:19,  7.80s/it]

✅ [Row 358] Claude Received: ```json
{
  "reasoning": "Both texts feature protagonists who are sheltered/coddled and must face ne...
🏁 [Row 358] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 362] Gemini: Sending request...

 90%|████████▉ | 359/400 [46:37<05:19,  7.80s/it]

✅ [Row 361] Gemini Received: {
  "reasoning": "The Anchor text features a protagonist (Jan Holman) embarking on a journey for a s...
🚀 [Row 361] GPT: Sending request...

 90%|█████████ | 360/400 [46:38<03:58,  5.96s/it]

✅ [Row 359] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a murder investigation where a private investig...
🏁 [Row 359] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 363] Gemini: Sending request...

 90%|█████████ | 360/400 [46:40<03:58,  5.96s/it]

✅ [Row 361] GPT Received: {
  "reasoning": "The Anchor story involves a documentary filmmaker following a musician on a tour t...
🚀 [Row 361] Claude: Sending request...

 90%|█████████ | 361/400 [46:44<03:53,  5.99s/it]

✅ [Row 360] Claude Received: ```json
{
  "reasoning": "Both texts share the core element of a protagonist fleeing their troubled ...
🏁 [Row 360] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 364] Gemini: Sending request...

 90%|█████████ | 361/400 [46:45<03:53,  5.99s/it]

✅ [Row 362] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B are set in ...
🚀 [Row 362] GPT: Sending request...

 90%|█████████ | 362/400 [46:49<03:30,  5.53s/it]

✅ [Row 361] Claude Received: ```json
{
  "reasoning": "The Anchor follows a documentary filmmaker who travels to make a film and ...
🏁 [Row 361] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 365] Gemini: Sending request...

 90%|█████████ | 362/400 [46:50<03:30,  5.53s/it]

✅ [Row 362] GPT Received: {
  "reasoning": "The Anchor story involves themes of inheritance, deception, and political conspira...
🚀 [Row 362] Claude: Sending request...

 90%|█████████ | 362/400 [46:51<03:30,  5.53s/it]

✅ [Row 363] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text than Text A. Both the Anchor and T...
🚀 [Row 363] GPT: Sending request...

 90%|█████████ | 362/400 [46:56<03:30,  5.53s/it]

✅ [Row 363] GPT Received: {
  "reasoning": "The Anchor story revolves around a young man's tragic love affair with an older wo...
🚀 [Row 363] Claude: Sending request...

 90%|█████████ | 362/400 [46:57<03:30,  5.53s/it]

✅ [Row 364] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A center on t...
🚀 [Row 364] GPT: Sending request...

 91%|█████████ | 363/400 [47:02<04:55,  8.00s/it]

✅ [Row 362] Claude Received: ```json
{
  "reasoning": "Both texts involve Central European settings with innkeepers/establishment...
🏁 [Row 362] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 366] Gemini: Sending request...

 91%|█████████ | 363/400 [47:04<04:55,  8.00s/it]

⏳ [Row 366] Gemini: Rate limit (Attempt 1)
✅ [Row 364] GPT Received: {
  "reasoning": "The Anchor story revolves around two single parents, Brad and Jean, who meet, get ...
🚀 [Row 364] Claude: Sending request...

 91%|█████████ | 363/400 [47:05<04:55,  8.00s/it]

✅ [Row 365] Gemini Received: {
  "reasoning": "The Anchor text features a U.S. cavalry officer who experiences an ambush, is subs...
🚀 [Row 365] GPT: Sending request...

 91%|█████████ | 364/400 [47:06<03:59,  6.65s/it]

✅ [Row 363] Claude Received: ```json
{
  "reasoning": "Both texts involve affairs and tragic consequences, but Text A is narrativ...
🏁 [Row 363] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 367] Gemini: Sending request...

 91%|█████████ | 364/400 [47:08<03:59,  6.65s/it]

✅ [Row 365] GPT Received: {
  "reasoning": "The Anchor story involves a cavalry officer, Hemp Brown, who is ambushed, court-ma...
🚀 [Row 365] Claude: Sending request...

 91%|█████████▏| 365/400 [47:15<04:15,  7.31s/it]

✅ [Row 364] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around two single parents (Brad and Jean) getting enga...
🏁 [Row 364] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 368] Gemini: Sending request...

 91%|█████████▏| 365/400 [47:16<04:15,  7.31s/it]

✅ [Row 366] Gemini Received: {
  "reasoning": "The Anchor text revolves heavily around themes of sexual exploitation, captivity, ...
🚀 [Row 366] GPT: Sending request...

 91%|█████████▏| 365/400 [47:18<04:15,  7.31s/it]

✅ [Row 367] Gemini Received: {
  "reasoning": "The Anchor text centers on Christa's unexpected pregnancy, societal pressure, a fo...
🚀 [Row 367] GPT: Sending request...

 92%|█████████▏| 366/400 [47:19<03:40,  6.49s/it]

✅ [Row 365] Claude Received: ```json
{
  "reasoning": "Both texts share military/cavalry settings with the Anchor, but Text B is ...
🏁 [Row 365] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 369] Gemini: Sending request...

 92%|█████████▏| 366/400 [47:20<03:40,  6.49s/it]

✅ [Row 366] GPT Received: {
  "reasoning": "The Anchor story involves a couple accidentally trespassing and getting involved i...
🚀 [Row 366] Claude: Sending request...

 92%|█████████▏| 366/400 [47:23<03:40,  6.49s/it]

✅ [Row 367] GPT Received: {
  "reasoning": "The Anchor story revolves around a young woman facing an unexpected pregnancy, soc...
🚀 [Row 367] Claude: Sending request...

 92%|█████████▏| 366/400 [47:27<03:40,  6.49s/it]

✅ [Row 368] Gemini Received: {
  "reasoning": "The Anchor text describes a documentary film focused on antibiotic resistance. Bot...
🚀 [Row 368] GPT: Sending request...

 92%|█████████▏| 366/400 [47:27<03:40,  6.49s/it]

✅ [Row 369] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B featur...
🚀 [Row 369] GPT: Sending request...

 92%|█████████▏| 367/400 [47:29<04:07,  7.49s/it]

✅ [Row 366] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a woman (Olga) being held captive in an exploitative...
🏁 [Row 366] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 370] Gemini: Sending request...

 92%|█████████▏| 367/400 [47:31<04:07,  7.49s/it]

⏳ [Row 370] Gemini: Rate limit (Attempt 1)

 92%|█████████▏| 368/400 [47:33<03:23,  6.37s/it]

✅ [Row 367] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a young woman (Christa) facing an unexpected pregnan...
🏁 [Row 367] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 371] Gemini: Sending request...
✅ [Row 368] GPT Received: {
  "reasoning": "The Anchor text is a documentary about antibiotic resistance, focusing on its glob...
🚀 [Row 368] Claude: Sending request...

 92%|█████████▏| 368/400 [47:33<03:23,  6.37s/it]

✅ [Row 369] GPT Received: {
  "reasoning": "The Anchor story revolves around Scheherazade's clever use of storytelling to avoi...
🚀 [Row 369] Claude: Sending request...

 92%|█████████▏| 369/400 [47:43<03:53,  7.52s/it]

✅ [Row 368] Claude Received: ```json
{
  "reasoning": "The Anchor is a documentary about antibiotic resistance as a global health...
🏁 [Row 368] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 372] Gemini: Sending request...

 92%|█████████▏| 369/400 [47:44<03:53,  7.52s/it]

✅ [Row 371] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center on a...
🚀 [Row 371] GPT: Sending request...

 92%|█████████▎| 370/400 [47:45<02:54,  5.83s/it]

✅ [Row 369] Claude Received: ```json
{
  "reasoning": "The Anchor's narrative revolves around a tyrannical ruler executing women,...
🏁 [Row 369] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 373] Gemini: Sending request...

 92%|█████████▎| 370/400 [47:47<02:54,  5.83s/it]

✅ [Row 370] Gemini Received: {
  "reasoning": "The Anchor text describes a narrative where a protagonist (Raymond) and a cultural...
🚀 [Row 370] GPT: Sending request...

 92%|█████████▎| 370/400 [47:49<02:54,  5.83s/it]

✅ [Row 371] GPT Received: {
  "reasoning": "The Anchor text focuses on a young girl's struggle with her passion for poetry and...
🚀 [Row 371] Claude: Sending request...

 92%|█████████▎| 370/400 [47:52<02:54,  5.83s/it]

✅ [Row 370] GPT Received: {
  "reasoning": "The Anchor story 'Wild Style' revolves around the themes of graffiti art, the tens...
🚀 [Row 370] Claude: Sending request...

 92%|█████████▎| 370/400 [47:55<02:54,  5.83s/it]

✅ [Row 373] Gemini Received: {
  "reasoning": "The Anchor text features a community facing significant external threats (bigotry,...
🚀 [Row 373] GPT: Sending request...

 92%|█████████▎| 370/400 [47:56<02:54,  5.83s/it]

✅ [Row 372] Gemini Received: {
  "reasoning": "The Anchor text describes an external force that influences a family to unleash th...
🚀 [Row 372] GPT: Sending request...

 93%|█████████▎| 371/400 [47:59<03:56,  8.16s/it]

✅ [Row 371] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a teenage girl (Xiomara) navigating conflicts with h...
🏁 [Row 371] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 374] Gemini: Sending request...

 93%|█████████▎| 371/400 [48:01<03:56,  8.16s/it]

✅ [Row 373] GPT Received: {
  "reasoning": "The Anchor text revolves around themes of land ownership, racial tension, and mora...
🚀 [Row 373] Claude: Sending request...

 93%|█████████▎| 371/400 [48:01<03:56,  8.16s/it]

✅ [Row 372] GPT Received: {
  "reasoning": "The Anchor story revolves around a family being influenced by a supernatural force...
🚀 [Row 372] Claude: Sending request...

 93%|█████████▎| 372/400 [48:03<03:15,  6.98s/it]

✅ [Row 370] Claude Received: ```json
{
  "reasoning": "The Anchor follows an anonymous graffiti artist who is drawn from undergro...
🏁 [Row 370] Votes: {'gemini': True, 'gpt': False, 'claude': False}
🚀 [Row 375] Gemini: Sending request...

 93%|█████████▎| 372/400 [48:08<03:15,  6.98s/it]

✅ [Row 374] Gemini Received: {
  "reasoning": "The Anchor text features protagonists who inadvertently become involved with the c...
🚀 [Row 374] GPT: Sending request...

 93%|█████████▎| 372/400 [48:09<03:15,  6.98s/it]

✅ [Row 375] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a c...
🚀 [Row 375] GPT: Sending request...

 93%|█████████▎| 373/400 [48:11<03:20,  7.42s/it]

✅ [Row 373] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a land ownership conflict in rural Georgia, where bi...
🏁 [Row 373] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 376] Gemini: Sending request...

 93%|█████████▎| 373/400 [48:13<03:20,  7.42s/it]

✅ [Row 374] GPT Received: {
  "reasoning": "The Anchor story revolves around three bachelors whose lives are turned upside dow...
🚀 [Row 374] Claude: Sending request...

 94%|█████████▎| 374/400 [48:13<02:27,  5.69s/it]

✅ [Row 375] GPT Received: {
  "reasoning": "The Anchor story and Text A both involve rival reporters who are forced to work to...
🚀 [Row 375] Claude: Sending request...
✅ [Row 372] Claude Received: ```json
{
  "reasoning": "The Anchor depicts a family's descent into depravity triggered by a supern...
🏁 [Row 372] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 377] Gemini: Sending request...

 94%|█████████▎| 374/400 [48:15<02:27,  5.69s/it]

⏳ [Row 377] Gemini: Rate limit (Attempt 1)

 94%|█████████▍| 375/400 [48:20<02:31,  6.06s/it]

✅ [Row 375] Claude Received: ```json
{
  "reasoning": "Text A shares the core narrative structure with the Anchor: two rival repo...
🏁 [Row 375] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 378] Gemini: Sending request...

 94%|█████████▍| 375/400 [48:20<02:31,  6.06s/it]

✅ [Row 376] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor text. Both the Anchor and Text A featur...
🚀 [Row 376] GPT: Sending request...

 94%|█████████▍| 376/400 [48:21<01:50,  4.62s/it]

✅ [Row 374] Claude Received: ```json
{
  "reasoning": "Both texts share significant narrative elements with the Anchor. However, ...
🏁 [Row 374] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 379] Gemini: Sending request...

 94%|█████████▍| 376/400 [48:24<01:50,  4.62s/it]

✅ [Row 376] GPT Received: {
  "reasoning": "The Anchor story and Text B both revolve around themes of love, societal disapprov...
🚀 [Row 376] Claude: Sending request...

 94%|█████████▍| 376/400 [48:30<01:50,  4.62s/it]

✅ [Row 379] Gemini Received: {
  "reasoning": "The Anchor story involves a complex web of land disputes, evasion of justice (a mu...
🚀 [Row 379] GPT: Sending request...

 94%|█████████▍| 376/400 [48:32<01:50,  4.62s/it]

✅ [Row 378] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B prominently...
🚀 [Row 378] GPT: Sending request...
✅ [Row 377] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center on a...
🚀 [Row 377] GPT: Sending request...

 94%|█████████▍| 376/400 [48:34<01:50,  4.62s/it]

✅ [Row 379] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of land disputes, family loyalty, and roma...
🚀 [Row 379] Claude: Sending request...

 94%|█████████▍| 377/400 [48:36<02:54,  7.59s/it]

✅ [Row 376] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic relationships between characters from differen...
🏁 [Row 376] Votes: {'gemini': True, 'gpt': False, 'claude': True}
🚀 [Row 380] Gemini: Sending request...

 94%|█████████▍| 377/400 [48:36<02:54,  7.59s/it]

✅ [Row 377] GPT Received: {
  "reasoning": "The Anchor story revolves around a same-sex couple, Ben and George, who face chall...
🚀 [Row 377] Claude: Sending request...

 94%|█████████▍| 377/400 [48:37<02:54,  7.59s/it]

✅ [Row 378] GPT Received: {
  "reasoning": "The Anchor text involves themes of cultural heritage, voodoo, and possession, with...
🚀 [Row 378] Claude: Sending request...

 94%|█████████▍| 378/400 [48:43<02:46,  7.55s/it]

✅ [Row 377] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a long-term same-sex couple (Ben and George, 39 year...
🏁 [Row 377] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 381] Gemini: Sending request...

 95%|█████████▍| 379/400 [48:46<02:10,  6.19s/it]

✅ [Row 379] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a ranching family's land dispute with homesteaders a...
🏁 [Row 379] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 382] Gemini: Sending request...

 95%|█████████▌| 380/400 [48:47<01:32,  4.60s/it]

✅ [Row 378] Claude Received: ```json
{
  "reasoning": "The Anchor involves a supernatural horror narrative centered on voodoo cul...
🏁 [Row 378] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 383] Gemini: Sending request...

 95%|█████████▌| 380/400 [48:48<01:32,  4.60s/it]

✅ [Row 380] Gemini Received: {
  "reasoning": "The Anchor text describes a narrative of divine conflict spilling into the mortal ...
🚀 [Row 380] GPT: Sending request...

 95%|█████████▌| 380/400 [48:49<01:32,  4.60s/it]

✅ [Row 381] Gemini Received: {
  "reasoning": "Text A shares a strong narrative similarity with the Anchor text regarding the cen...
🚀 [Row 381] GPT: Sending request...

 95%|█████████▌| 380/400 [48:53<01:32,  4.60s/it]

✅ [Row 381] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of rekindling past relationships, dealing ...
🚀 [Row 381] Claude: Sending request...

 95%|█████████▌| 380/400 [48:54<01:32,  4.60s/it]

✅ [Row 380] GPT Received: {
  "reasoning": "The Anchor story involves a conflict between gods, with Mars and Venus attempting ...
🚀 [Row 380] Claude: Sending request...

 95%|█████████▌| 380/400 [48:57<01:32,  4.60s/it]

✅ [Row 383] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. While the Anchor features divine ...
🚀 [Row 383] GPT: Sending request...

 95%|█████████▌| 380/400 [48:59<01:32,  4.60s/it]

✅ [Row 382] Gemini Received: {
  "reasoning": "The Anchor text centers on a mafia power struggle, an assassination attempt, betra...
🚀 [Row 382] GPT: Sending request...

 95%|█████████▌| 381/400 [49:00<02:15,  7.12s/it]

✅ [Row 381] Claude Received: ```json
{
  "reasoning": "The Anchor centers on Jake's romantic complications (losing Julia to an en...
🏁 [Row 381] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 384] Gemini: Sending request...

 95%|█████████▌| 381/400 [49:02<02:15,  7.12s/it]

✅ [Row 383] GPT Received: {
  "reasoning": "The Anchor story involves divine beings intervening in human affairs to test the p...
🚀 [Row 383] Claude: Sending request...

 95%|█████████▌| 381/400 [49:06<02:15,  7.12s/it]

✅ [Row 382] GPT Received: {
  "reasoning": "The Anchor story involves a power struggle within a criminal organization, with th...
🚀 [Row 382] Claude: Sending request...

 96%|█████████▌| 382/400 [49:06<02:02,  6.79s/it]

✅ [Row 380] Claude Received: ```json
{
  "reasoning": "The Anchor involves divine beings (Jupiter, Mars, Venus, Vulcan, Etna) in ...
🏁 [Row 380] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 385] Gemini: Sending request...

 96%|█████████▌| 382/400 [49:09<02:02,  6.79s/it]

✅ [Row 384] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature a p...
🚀 [Row 384] GPT: Sending request...

 96%|█████████▌| 382/400 [49:13<02:02,  6.79s/it]

✅ [Row 385] Gemini Received: {
  "reasoning": "The Anchor text features a character (Don Camillo) who uses deception to infiltrat...
🚀 [Row 385] GPT: Sending request...

 96%|█████████▌| 383/400 [49:14<02:01,  7.13s/it]

✅ [Row 383] Claude Received: ```json
{
  "reasoning": "The Anchor centers on divine beings testing whether humanity can be redeem...
🏁 [Row 383] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 386] Gemini: Sending request...

 96%|█████████▌| 383/400 [49:15<02:01,  7.13s/it]

❌ [Row 386] Gemini Exception: 'candidates'

 96%|█████████▌| 383/400 [49:16<02:01,  7.13s/it]

✅ [Row 384] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of transformation, healing, and the restor...
🚀 [Row 384] Claude: Sending request...

 96%|█████████▌| 383/400 [49:16<02:01,  7.13s/it]

❌ [Row 386] Gemini Exception: 'candidates'

 96%|█████████▌| 384/400 [49:17<01:35,  5.99s/it]

✅ [Row 382] Claude Received: ```json
{
  "reasoning": "Both texts involve organized crime, assassination plots, and betrayals amo...
🏁 [Row 382] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 387] Gemini: Sending request...

 96%|█████████▌| 384/400 [49:18<01:35,  5.99s/it]

✅ [Row 385] GPT Received: {
  "reasoning": "The Anchor text revolves around a political theme involving a Communist mayor and ...
🚀 [Row 385] Claude: Sending request...
❌ [Row 386] Gemini Exception: 'candidates'

 96%|█████████▌| 384/400 [49:19<01:35,  5.99s/it]

🚀 [Row 386] GPT: Sending request...

 96%|█████████▌| 384/400 [49:23<01:35,  5.99s/it]

✅ [Row 386] GPT Received: {
  "reasoning": "The Anchor story involves a journey with obstacles, a focus on family, and a confr...
🚀 [Row 386] Claude: Sending request...

 96%|█████████▌| 384/400 [49:25<01:35,  5.99s/it]

✅ [Row 387] Gemini Received: {
  "reasoning": "The Anchor text features a complicated love affair, a central conflict involving a...
🚀 [Row 387] GPT: Sending request...

 96%|█████████▋| 385/400 [49:26<01:41,  6.73s/it]

✅ [Row 384] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a troubled orphan finding healing and transform...
🏁 [Row 384] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 388] Gemini: Sending request...

 96%|█████████▋| 386/400 [49:28<01:15,  5.36s/it]

✅ [Row 385] Claude Received: {
  "reasoning": "The Anchor involves Italian Communists (including a disguised priest) traveling to...
🏁 [Row 385] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 389] Gemini: Sending request...

 96%|█████████▋| 386/400 [49:29<01:15,  5.36s/it]

✅ [Row 387] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a love affair that leads to tragic conseq...
🚀 [Row 387] Claude: Sending request...

 97%|█████████▋| 387/400 [49:34<01:11,  5.54s/it]

✅ [Row 386] Claude Received: ```json
{
  "reasoning": "Both texts involve journeys and challenging circumstances, but Text B is n...
🏁 [Row 386] Votes: {'gemini': None, 'gpt': False, 'claude': False}
🚀 [Row 390] Gemini: Sending request...

 97%|█████████▋| 387/400 [49:34<01:11,  5.54s/it]

✅ [Row 389] Gemini Received: {
  "reasoning": "The Anchor text describes a protagonist who undergoes a significant life change (r...
🚀 [Row 389] GPT: Sending request...

 97%|█████████▋| 388/400 [49:38<01:02,  5.23s/it]

✅ [Row 387] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic triangles and lovers facing obstacles, but Tex...
🏁 [Row 387] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 391] Gemini: Sending request...

 97%|█████████▋| 388/400 [49:40<01:02,  5.23s/it]

✅ [Row 389] GPT Received: {
  "reasoning": "The Anchor story revolves around themes of rediscovery, friendship, and personal g...
🚀 [Row 389] Claude: Sending request...

 97%|█████████▋| 388/400 [49:43<01:02,  5.23s/it]

✅ [Row 388] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B center on a...
🚀 [Row 388] GPT: Sending request...

 97%|█████████▋| 388/400 [49:47<01:02,  5.23s/it]

✅ [Row 391] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B feature a m...
🚀 [Row 391] GPT: Sending request...

 97%|█████████▋| 388/400 [49:48<01:02,  5.23s/it]

✅ [Row 388] GPT Received: {
  "reasoning": "The Anchor story involves a case of mistaken identity where an actor is mistaken f...
🚀 [Row 388] Claude: Sending request...

 97%|█████████▋| 388/400 [49:50<01:02,  5.23s/it]

✅ [Row 390] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. The Anchor features a protagonist (Fur...
🚀 [Row 390] GPT: Sending request...

 97%|█████████▋| 389/400 [49:50<01:19,  7.20s/it]

✅ [Row 389] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a painter who reconnects with his childhood home and...
🏁 [Row 389] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 392] Gemini: Sending request...

 97%|█████████▋| 389/400 [49:52<01:19,  7.20s/it]

✅ [Row 391] GPT Received: {
  "reasoning": "The Anchor story is set in a distant galaxy on a desert planet with a conflict bet...
🚀 [Row 391] Claude: Sending request...

 97%|█████████▋| 389/400 [49:58<01:19,  7.20s/it]

✅ [Row 390] GPT Received: {
  "reasoning": "The Anchor story involves themes of crime, deception, and redemption, with a focus...
🚀 [Row 390] Claude: Sending request...

 98%|█████████▊| 390/400 [49:58<01:14,  7.44s/it]

✅ [Row 388] Claude Received: ```json
{
  "reasoning": "The Anchor revolves around a case of mistaken identity where an unsuccessf...
🏁 [Row 388] Votes: {'gemini': False, 'gpt': True, 'claude': True}
🚀 [Row 393] Gemini: Sending request...

 98%|█████████▊| 390/400 [49:59<01:14,  7.44s/it]

✅ [Row 392] Gemini Received: {
  "reasoning": "Text A is narratively closer to the Anchor. Both the Anchor and Text A feature pro...
🚀 [Row 392] GPT: Sending request...

 98%|█████████▊| 391/400 [50:03<00:59,  6.56s/it]

✅ [Row 391] Claude Received: ```json
{
  "reasoning": "The Anchor story centers on a mercenary who initially seeks personal gain ...
🏁 [Row 391] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 394] Gemini: Sending request...

 98%|█████████▊| 391/400 [50:05<00:59,  6.56s/it]

✅ [Row 392] GPT Received: {
  "reasoning": "The Anchor story revolves around Mohsen, who is from a butcher family but dislikes...
🚀 [Row 392] Claude: Sending request...

 98%|█████████▊| 391/400 [50:06<00:59,  6.56s/it]

✅ [Row 393] Gemini Received: {
  "reasoning": "The Anchor text focuses on an individual's internal struggle with a misdeed, conce...
🚀 [Row 393] GPT: Sending request...

 98%|█████████▊| 392/400 [50:08<00:49,  6.19s/it]

✅ [Row 390] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a gangster (Farrow) who manipulates a gambler (Fury)...
🏁 [Row 390] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 395] Gemini: Sending request...

 98%|█████████▊| 392/400 [50:12<00:49,  6.19s/it]

✅ [Row 394] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor text. Both the Anchor and Text B are se...
🚀 [Row 394] GPT: Sending request...
✅ [Row 393] GPT Received: {
  "reasoning": "The Anchor text revolves around a young boy, Emil Sinclair, who commits a minor th...
🚀 [Row 393] Claude: Sending request...

 98%|█████████▊| 392/400 [50:15<00:49,  6.19s/it]

✅ [Row 395] Gemini Received: {
  "reasoning": "Text A is significantly closer to the Anchor. Both the Anchor and Text A share a c...
🚀 [Row 395] GPT: Sending request...

 98%|█████████▊| 392/400 [50:17<00:49,  6.19s/it]

✅ [Row 394] GPT Received: {
  "reasoning": "The Anchor text and Text B both deal with themes of political struggle and persona...
🚀 [Row 394] Claude: Sending request...

 98%|█████████▊| 393/400 [50:20<00:54,  7.83s/it]

✅ [Row 392] Claude Received: ```json
{
  "reasoning": "Both texts involve deception about identity/background and family business...
🏁 [Row 392] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 396] Gemini: Sending request...
✅ [Row 395] GPT Received: {
  "reasoning": "The Anchor story involves a comedic group of characters who, through a series of m...
🚀 [Row 395] Claude: Sending request...

 98%|█████████▊| 394/400 [50:23<00:38,  6.40s/it]

✅ [Row 393] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a young boy's internal moral struggle after stealing...
🏁 [Row 393] Votes: {'gemini': False, 'gpt': False, 'claude': True}
🚀 [Row 397] Gemini: Sending request...

 99%|█████████▉| 395/400 [50:29<00:31,  6.28s/it]

✅ [Row 394] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on a 13-year-old girl (Molly) in 1960s South Africa who...
🏁 [Row 394] Votes: {'gemini': False, 'gpt': False, 'claude': False}
🚀 [Row 398] Gemini: Sending request...

 99%|█████████▉| 396/400 [50:30<00:19,  4.87s/it]

✅ [Row 395] Claude Received: ```json
{
  "reasoning": "The Anchor is about a comedic group of Turkish characters who take control...
🏁 [Row 395] Votes: {'gemini': True, 'gpt': True, 'claude': True}
🚀 [Row 399] Gemini: Sending request...

 99%|█████████▉| 396/400 [50:36<00:19,  4.87s/it]

✅ [Row 396] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B involve a p...
🚀 [Row 396] GPT: Sending request...

 99%|█████████▉| 396/400 [50:40<00:19,  4.87s/it]

✅ [Row 398] Gemini Received: {
  "reasoning": "Text B is narratively closer to the Anchor. Both the Anchor and Text B explore how...
🚀 [Row 398] GPT: Sending request...

 99%|█████████▉| 396/400 [50:41<00:19,  4.87s/it]

✅ [Row 396] GPT Received: {
  "reasoning": "The Anchor story revolves around a young woman, Merlin, who is dealing with the af...
🚀 [Row 396] Claude: Sending request...

 99%|█████████▉| 396/400 [50:43<00:19,  4.87s/it]

✅ [Row 397] Gemini Received: {
  "reasoning": "The Anchor text describes a series of escalating misfortunes and conflicts (car tr...
🚀 [Row 397] GPT: Sending request...

 99%|█████████▉| 396/400 [50:44<00:19,  4.87s/it]

✅ [Row 398] GPT Received: {
  "reasoning": "The Anchor text and Text B both involve characters reflecting on their pasts and d...
🚀 [Row 398] Claude: Sending request...

 99%|█████████▉| 396/400 [50:47<00:19,  4.87s/it]

✅ [Row 399] Gemini Received: {
  "reasoning": "The Anchor text describes a mysterious, vengeful stranger who emerges from a past ...
🚀 [Row 399] GPT: Sending request...

 99%|█████████▉| 396/400 [50:48<00:19,  4.87s/it]

✅ [Row 397] GPT Received: {
  "reasoning": "The Anchor story and Text B both involve a series of comedic mishaps and misunders...
🚀 [Row 397] Claude: Sending request...

 99%|█████████▉| 396/400 [50:52<00:19,  4.87s/it]

✅ [Row 399] GPT Received: {
  "reasoning": "The Anchor story involves a mysterious stranger seeking vengeance for a past betra...
🚀 [Row 399] Claude: Sending request...

 99%|█████████▉| 397/400 [50:54<00:31, 10.52s/it]

✅ [Row 396] Claude Received: ```json
{
  "reasoning": "Both texts involve romantic relationships and marriage complications, but ...
🏁 [Row 396] Votes: {'gemini': False, 'gpt': False, 'claude': False}

100%|█████████▉| 398/400 [50:55<00:15,  7.55s/it]

✅ [Row 398] Claude Received: ```json
{
  "reasoning": "The Anchor focuses on two traumatized individuals (Mattia and Alice) who m...
🏁 [Row 398] Votes: {'gemini': False, 'gpt': False, 'claude': False}

100%|█████████▉| 399/400 [50:59<00:06,  6.58s/it]

✅ [Row 397] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a comedic outing derailed by repeated automobile tro...
🏁 [Row 397] Votes: {'gemini': True, 'gpt': False, 'claude': False}

100%|██████████| 400/400 [51:03<00:00,  7.66s/it]

✅ [Row 399] Claude Received: ```json
{
  "reasoning": "The Anchor centers on a mysterious stranger who methodically targets multi...
🏁 [Row 399] Votes: {'gemini': True, 'gpt': True, 'claude': True}

--- Done ---

In [ ]:
# חישוב דיוק
if 'text_a_is_closer' in df_test.columns:
    acc = (df_test['text_a_is_closer'] == df_test['prediction']).mean()
    print(f"Final Accuracy: {acc:.4f}")

# בדיקה כמה נכשלו לחלוטין
failed_count = sum(1 for d in details_map.values() if "FAILED_ALL" in d)
print(f"Rows with complete API failure (fallback used): {failed_count}")

# יצירת קובץ להגשה
import zipfile
from google.colab import files

sub_df = df_test[['prediction']].rename(columns={'prediction': 'text_a_is_closer'})
sub_df.to_json('track_a.jsonl', orient='records', lines=True)

with zipfile.ZipFile('submission_robust_test.zip', 'w', zipfile.ZIP_DEFLATED) as z:
    z.write('track_a.jsonl')

print("Created submission_robust test.zip")
files.download('submission_robust_test.zip')

Rows with complete API failure (fallback used): 0
Created submission_robust test.zip

In [ ]:
import ast

def parse_vote_details(detail_str):
    try:
        return ast.literal_eval(detail_str)
    except:
        return {}

logs_df = df_test.copy()

votes_expanded = logs_df['votes_detail'].apply(parse_vote_details).apply(pd.Series)

detailed_logs = pd.concat([
    logs_df[['anchor_text', 'prediction']],
    votes_expanded
], axis=1)

detailed_logs = detailed_logs.rename(columns={
    'gemini': 'Vote_Gemini',
    'gpt': 'Vote_GPT',
    'claude': 'Vote_Claude',
    'prediction': 'Final_Ensemble_Prediction',
})

def has_disagreement(row):
    votes = [row['Vote_Gemini'], row['Vote_GPT'], row['Vote_Claude']]
    valid_votes = [v for v in votes if v is not None]
    if not valid_votes: return False
    return len(set(valid_votes)) > 1

disagreements = detailed_logs[detailed_logs.apply(has_disagreement, axis=1)]

print(f"Total rows with disagreement: {len(disagreements)}")
if not disagreements.empty:
    print("\n--- Sample Disagreements ---")
    display(disagreements[['Vote_Gemini', 'Vote_GPT', 'Vote_Claude', 'Final_Ensemble_Prediction']].head())

# 4. שמירה לקובץ CSV והורדה
log_filename = 'full_model_logs.csv'
detailed_logs.to_csv(log_filename, index=True)

print(f"\nFull logs saved to {log_filename}")
files.download(log_filename)

Total rows with disagreement: 144

--- Sample Disagreements ---

   Vote_Gemini  Vote_GPT  Vote_Claude  Final_Ensemble_Prediction
3        False     False         True                      False
5         True     False         True                       True
6        False      True         True                       True
7         True     False        False                      False
11        True     False        False                      False

Full logs saved to full_model_logs.csv